import { dto,type Resource } from '../../database/resources';
import { one,type Row,type Transaction } from '../../database/database';
import { notFound } from '../../common/problem';

const meta={id:'id',version:'version',createdAt:'created_at',updatedAt:'updated_at'};
export const ticketResource:Resource={table:`(SELECT t.*,s.name AS school_name,u.display_name AS requester_name,a.display_name AS assignee_name FROM platform.support_tickets t JOIN platform.schools s ON s.id=t.school_id JOIN identity.users u ON u.id=t.requester_id LEFT JOIN identity.users a ON a.id=t.assignee_id)`,fields:{...meta,schoolId:'school_id',subject:'subject',description:'description',status:'status',priority:'priority',assigneeId:'assignee_id',schoolName:'school_name',requesterName:'requester_name',assigneeName:'assignee_name'},writeFields:[],search:['subject','description','school_name'],filters:{schoolId:'school_id',status:'status',priority:'priority',assigneeId:'assignee_id'}};
export const messageResource:Resource={table:`(SELECT m.*,t.school_id,coalesce(u.display_name,'Nhân sự hỗ trợ') AS author_label FROM platform.support_messages m JOIN platform.support_tickets t ON t.id=m.ticket_id LEFT JOIN identity.users u ON u.id=m.author_id)`,fields:{id:'id',authorLabel:'author_label',body:'body',createdAt:'created_at',side:'side'},writeFields:[],search:['body'],filters:{ticketId:'ticket_id'}};
export const supportResource:Resource={table:`(SELECT g.*,s.name AS school_name,u.display_name AS operator_name,a.display_name AS approver_name,q.display_name AS requester_name,(g.status='APPROVED' AND g.valid_from<=now() AND g.valid_until>now() AND g.revoked_at IS NULL AND u.status='ACTIVE' AND s.status<>'ARCHIVED' AND EXISTS(SELECT 1 FROM platform.operator_grants op WHERE op.user_id=g.operator_id AND op.action_code='platform.support' AND op.revoked_at IS NULL AND op.valid_from<=now() AND (op.valid_until IS NULL OR op.valid_until>now()))) AS effective FROM platform.support_access g JOIN platform.schools s ON s.id=g.school_id JOIN identity.users u ON u.id=g.operator_id LEFT JOIN identity.users a ON a.id=g.approved_by_user_id LEFT JOIN identity.users q ON q.id=g.requested_by_user_id)`,fields:{...meta,schoolId:'school_id',ticketId:'ticket_id',operatorId:'operator_id',classId:'class_id',allowedActions:'allowed_actions',reason:'reason',status:'status',validFrom:'valid_from',validUntil:'valid_until',requestedById:'requested_by_user_id',approvedById:'approved_by_user_id',operatorName:'operator_name',approverName:'approver_name',requesterName:'requester_name',schoolName:'school_name',effective:'effective',revokedAt:'revoked_at'},writeFields:[],search:['reason','school_name','operator_name'],filters:{schoolId:'school_id',ticketId:'ticket_id',operatorId:'operator_id',status:'status'}};
export const supportActions=['school.read','year.read','dictionary.read','class.read','assignment.read','member.read','role.read','school.settings','import.read'] as const;
export const operatorSql="SELECT DISTINCT u.id,u.display_name FROM identity.users u JOIN platform.operator_grants g ON g.user_id=u.id AND g.action_code='platform.support' AND g.revoked_at IS NULL AND g.valid_from<=now() AND (g.valid_until IS NULL OR g.valid_until>now()) WHERE u.status='ACTIVE'";
export async function supportRow(tx:Transaction,schoolId:string,id:string){const row=await one<Row>(tx,`SELECT * FROM ${supportResource.table} t WHERE t.school_id=$1 AND t.id=$2`,[schoolId,id]);if(!row)notFound();return dto(supportResource,row);}
export function supportText(value:unknown){return typeof value==='string'?value.trim():'';}
