"use client";
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {http} from '@/lib/api/client';
import {useClassroom,ClassHeader} from '@/features/classroom/context';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Modal} from '@/components/ui/dialog';
import {fillMessageTemplate} from './message-template';
interface Progress{id:string;full_name:string;title:string;due_at:string;class_name:string;status:string;file_count:number;last_submission:string|null}
interface Access{id:string;participant_id:string;expires_at:string;revoked_at:string|null;version:number}
const defaultTemplate='Bạn {student} lớp {class}, vui lòng hoàn thành {activity} trước {due}. Tình trạng hiện tại: {status}.';
export function ActivityAccessPage({activityId}:{activityId:string}){
 const {schoolId,classId,base,readOnly}=useClassroom(),params={schoolId,classId};
 const [progress,setProgress]=useState<Progress[]>([]),[accesses,setAccesses]=useState<Access[]>([]),[template,setTemplate]=useState(defaultTemplate),[filter,setFilter]=useState<'ALL'|'MISSING'|'SUBMITTED'|'LATE'>('ALL'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[issued,setIssued]=useState<string|null>(null),[qr,setQr]=useState<string|null>(null),[revoke,setRevoke]=useState<Access|null>(null),[reason,setReason]=useState('');
 const [loading,setLoading]=useState(true);
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const [p,a]=await Promise.all([http('getActivityReminders',{params:{schoolId,classId},query:{activityId},signal}),http('getStudentEvidenceAccesses',{params:{schoolId,classId},query:{activityId},signal})]);if(signal?.aborted)return;setProgress(p.data as unknown as Progress[]);setAccesses(a.data as unknown as Access[]);setError('');}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Chưa tải được tiến độ');}finally{if(!signal?.aborted)setLoading(false);}},[schoolId,classId,activityId]);
 useEffect(()=>{const a=new AbortController();void load(a.signal);return()=>a.abort();},[load]);
 const message=(r:Progress,common=false)=>{const student=common?'các em':r.full_name,due=new Date(r.due_at).toLocaleString('vi-VN'),status=common?`${progress.filter(p=>!p.file_count).length} học sinh chưa nộp; ${progress.filter(p=>p.file_count).length} đã nộp`:r.file_count===0?'Chưa nộp':r.status==='APPROVED'?'Đã chấp nhận':r.status==='NEEDS_REVISION'?'Cần sửa':'Chờ duyệt';return fillMessageTemplate(template,{student,student_name:student,class:r.class_name,class_name:r.class_name,activity:r.title,activity_name:r.title,due,due_at:due,due_date:due,status});};
 const visible=progress.filter(p=>filter==='ALL'||filter==='MISSING'&&p.file_count===0||filter==='SUBMITTED'&&p.file_count>0||filter==='LATE'&&!!p.last_submission&&new Date(p.last_submission)>new Date(p.due_at));
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);}catch{setError('Chưa copy được. Chọn nội dung và copy thủ công.');}};
 const issue=async(participantId:string)=>{setBusy(true);setError('');try{const r=await http('issueStudentEvidenceAccess',{params,body:{participantId,expiresAt:new Date(Date.now()+7*86400000).toISOString()}});setIssued(window.location.origin+String((r.data as Record<string,unknown>).path));setQr(null);await load();}catch(e){setError(e instanceof Error?e.message:'Chưa cấp được mã');}finally{setBusy(false);}};
 return <div className="page"><ClassHeader title="Nộp minh chứng & nhắc hoạt động" subtitle={progress[0]?.title} crumbs={[{label:'Hoạt động',href:base+'/activities'},{label:'Chi tiết',href:base+'/activities/'+activityId}]}/>{error&&<p role="alert" className="text-danger-text">{error} <Button size="sm" onClick={()=>void load()}>Thử lại</Button></p>}{loading&&<p role="status">Đang tải dữ liệu…</p>}<Card className="space-y-3 p-4"><label className="block">Mẫu tin nhắc<textarea className="input mt-1 w-full" value={template} maxLength={2000} onChange={e=>setTemplate(e.target.value)}/></label><p className="text-sm">Biến dùng được: {'{{student_name}}, {{class_name}}, {{activity_name}}, {{due_at}}, {{status}} (cũng nhận biến ngắn {student}, {class}, {activity}, {due}, {status})'}</p><p>{!loading&&!error&&!progress.length?'Chưa có học sinh tham gia hoạt động. ':''}Tổng: {progress.length} học sinh · Đã nộp: {progress.filter(p=>p.file_count>0).length} · Chưa nộp: {progress.filter(p=>p.file_count===0).length}</p><div className="flex flex-wrap gap-3"><Button disabled={!progress.length} onClick={()=>void copy(message(progress[0]!,true))}>Copy tin chung</Button><label>Lọc<select className="input ml-2" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="ALL">Tất cả</option><option value="MISSING">Chưa nộp</option><option value="SUBMITTED">Đã nộp</option><option value="LATE">Nộp muộn</option></select></label><Button disabled={!visible.length} onClick={()=>void copy(visible.map(r=>message(r)).join('\n\n'))}>Copy toàn bộ tin nhắc</Button><Link className="text-primary underline" href={base+'/activities/'+activityId}>Duyệt minh chứng tại chi tiết hoạt động</Link></div></Card><div className="grid gap-3 md:grid-cols-2">{visible.map(p=><Card key={p.id} className="space-y-2 p-4"><h2 className="font-bold">{p.full_name}</h2><p>{p.file_count} tệp · {p.status==='APPROVED'?'Đã chấp nhận':p.status==='NEEDS_REVISION'?'Cần sửa':p.file_count?'Đã nộp':'Chưa nộp'}</p>{p.last_submission&&<p>Nộp gần nhất: {new Date(p.last_submission).toLocaleString('vi-VN')}{new Date(p.last_submission)>new Date(p.due_at)&&' · muộn'}</p>}<p className="rounded-lg bg-surface p-2">{message(p)}</p><div className="flex flex-wrap gap-2"><Button onClick={()=>void copy(message(p))}>Copy tin nhắc</Button><Button disabled={busy||readOnly} onClick={()=>void issue(p.id)}>Cấp / đổi link nộp 7 ngày</Button>{accesses.filter(a=>a.participant_id===p.id&&!a.revoked_at&&new Date(a.expires_at)>new Date()).map(a=><Button key={a.id} disabled={busy||readOnly} onClick={()=>{setRevoke(a);setReason('');}}>Thu hồi link</Button>)}</div></Card>)}</div>
 <Modal open={!!issued} onOpenChange={o=>{if(!o){setIssued(null);setQr(null);}}} title="Link riêng nộp minh chứng" description="Link này chỉ trả một lần; chỉ gửi cho đúng học sinh." footer={<Button onClick={()=>{setIssued(null);setQr(null);}}>Đã lưu, đóng</Button>}>{issued&&<div className="space-y-3"><p className="break-all">{issued}</p><Button onClick={()=>void copy(issued)}>Copy link riêng</Button><Button onClick={()=>void import('qrcode').then(QR=>QR.toDataURL(issued,{width:400,margin:2})).then(setQr).catch(()=>setError('Chưa tạo được QR'))}>Hiện QR để mở link</Button>{qr&&<img src={qr} width={280} height={280} alt="QR link riêng nộp minh chứng"/>}<p>QR mở trang nộp. Máy chủ vẫn kiểm tra mã riêng, thời hạn, học sinh và hoạt động cho từng lần nộp.</p></div>}</Modal>
 <Modal open={!!revoke} onOpenChange={o=>{if(!o)setRevoke(null);}} title="Thu hồi mã nộp minh chứng" busy={busy} footer={<Button variant="primary" disabled={busy||reason.trim().length<5} onClick={()=>{if(!revoke)return;setBusy(true);void http('revokeStudentEvidenceAccess',{params,body:{accessId:revoke.id,expectedVersion:revoke.version,reason}}).then(async()=>{setRevoke(null);await load();}).catch(e=>setError(e instanceof Error?e.message:'Chưa thu hồi được')).finally(()=>setBusy(false));}}>Thu hồi</Button>}><label>Lý do<textarea className="input mt-2 w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label></Modal>
 </div>;
}
