"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {http} from '@/lib/api/client';
import type {ApiRequest,OperationId,ApiSchemas} from '@/lib/api/generated';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Modal} from '@/components/ui/dialog';
import {ROLE_LABEL,STATUS_LABEL,type OfficerWorkspace} from './types';
const errorMessage=(e:unknown)=>e instanceof Error?e.message:'Không thực hiện được thao tác';
type Entry=ApiSchemas['TimetableEntry'];
export function OfficerWorkspacePage({slug}:{slug:string}){
 const [data,setData]=useState<OfficerWorkspace|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[assignment,setAssignment]=useState(''),[pin,setPin]=useState(''),[weekId,setWeekId]=useState(''),[confirm,setConfirm]=useState(false),[tick,setTick]=useState(0);
 const [selected,setSelected]=useState<string[]>([]),[ruleId,setRuleId]=useState(''),[date,setDate]=useState(''),[occurrences,setOccurrences]=useState(1),[delta,setDelta]=useState(''),[note,setNote]=useState(''),[editing,setEditing]=useState<OfficerWorkspace['records'][number]|null>(null);
 const [dutyDate,setDutyDate]=useState(''),[task,setTask]=useState(''),[dutyGroup,setDutyGroup]=useState(''),[dutyEntries,setDutyEntries]=useState<ApiSchemas['DutyCreate']['assignments']>([]),[entries,setEntries]=useState<Entry[]>([]),[teaching,setTeaching]=useState(''),[weekday,setWeekday]=useState(1),[period,setPeriod]=useState(1),[start,setStart]=useState('07:00'),[end,setEnd]=useState('07:45');
 const clockOffset=useRef(0);const params={publicClassSlug:slug};
 const load=useCallback(async(signal?:AbortSignal)=>{try{const r=await http('getClassOfficerWorkspace',{params:{publicClassSlug:slug},query:weekId?{weekId}:{},signal});if(!signal?.aborted){const workspace=r.data as unknown as OfficerWorkspace;clockOffset.current=Date.parse(workspace.serverNow)-Date.now();setData(workspace);setError('');}}catch(e){if(!signal?.aborted){setData(null);setError(errorMessage(e));}}},[slug,weekId]);
 useEffect(()=>{setAssignment(new URLSearchParams(window.location.search).get('assignment')??'');setDate(new Date().toLocaleDateString('en-CA'));const abort=new AbortController();void load(abort.signal);return()=>abort.abort();},[load]);
 useEffect(()=>{if(!data)return;const timer=setInterval(()=>{setTick(t=>t+1);void load();},15000);return()=>clearInterval(timer);},[Boolean(data),load]);
 const command=async<K extends OperationId>(id:K,body:ApiRequest<K>)=>{if(!data||busy)return;setBusy(true);setError('');try{await http(id,{params,body,capabilityCsrf:data.csrfToken});await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const login=async()=>{setBusy(true);setError('');try{await http('loginClassOfficer',{params,body:{assignmentId:assignment.trim(),pin}});setPin('');await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
 const state=data?.submission,now=Date.now()+clockOffset.current+tick*0,until=state?.status==='REOPENED'?state.reopened_until:state?.status==='SUBMITTED'?state.lock_at:null;
 const locked=!!data&&(state?.status==='LOCKED'||!!until&&new Date(until).getTime()<=now||state?.status!=='REOPENED'&&new Date(data.deadlines.submit).getTime()<=now),rule=data?.rules.find(r=>r.id===ruleId),body=data?{weekId:data.weekId,expectedVersion:data.submission.version}:null;
 const saveEntry=async(exclude=false)=>{if(!body||!rule)return;await command('saveClassOfficerEntry',{...body,enrollmentIds:selected,ruleId,occurredOn:date,occurrences,...(rule.value_mode==='MANUAL'?{manualDelta:delta}:{}),note,...(editing?{recordId:editing.id,recordVersion:editing.version,exclude}: {})});setEditing(null);setSelected([]);};
 return <main className="mx-auto max-w-4xl space-y-4 p-4 sm:p-8"><header><p className="text-primary">Sổ chủ nhiệm · Cổng cán bộ lớp</p><h1 className="page-title">{data?`${ROLE_LABEL[data.role]} · ${data.className}`:'Đăng nhập cán bộ lớp'}</h1>{data&&<p>{data.displayName}</p>}</header>{error&&<p role="alert" className="rounded-xl bg-danger-bg p-3 text-danger-text">{error}</p>}
 {!data?<Card className="space-y-4 p-5"><label className="block">Mã phân công<input className="input mt-1 w-full" value={assignment} onChange={e=>setAssignment(e.target.value)} autoComplete="off"/></label><label className="block">PIN riêng<input className="input mt-1 w-full" type="password" minLength={6} value={pin} onChange={e=>setPin(e.target.value)} autoComplete="current-password"/></label><Button variant="primary" disabled={busy||pin.length<6||!assignment} onClick={()=>void login()}>Đăng nhập</Button><p className="text-sm text-muted">Dùng đường dẫn và PIN GVCN cấp. PIN sai nhiều lần sẽ bị khóa tạm thời.</p></Card>:<>
 <Card className="space-y-3 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><label>Tuần<select className="input ml-2" value={data.weekId} onChange={e=>{setWeekId(e.target.value);setSelected([]);setEditing(null);}}>{data.weeks.map(w=><option key={w.id} value={w.id}>Tuần {w.week_number} · {w.starts_on}</option>)}</select></label><Button disabled={busy} onClick={()=>void command('logoutClassOfficer',{}).then(()=>setData(null))}>Đăng xuất</Button></div><b>{locked?'Đã khóa':STATUS_LABEL[state!.status]}</b><p>Hạn nộp: {new Date(data.deadlines.submit).toLocaleString('vi-VN')} · Hạn khóa: {new Date(data.deadlines.lock).toLocaleString('vi-VN')}</p>{until&&<p>{state?.status==='REOPENED'?'Mở lại':'Chỉnh sửa sau nộp'} đến {new Date(until).toLocaleTimeString('vi-VN')} · còn {Math.max(0,Math.ceil((new Date(until).getTime()-now)/60000))} phút</p>}{locked&&<p>Liên hệ GVCN để mở lại tuần có lý do.</p>}</Card>
 {data.role!=='LABOR_VICE'&&<Card className="space-y-3 p-4"><h2 className="text-lg font-bold">{data.role==='GROUP_LEADER'?'Ghi nhận học sinh trong tổ':'Ghi nhận các tổ trưởng'}</h2>{!data.period&&<p>GVCN cần mở tuần rèn luyện trước khi nhập.</p>}<div className="grid gap-3 sm:grid-cols-2"><label>Ngày sự kiện<input className="input mt-1 w-full" type="date" value={date} max={new Date().toLocaleDateString('en-CA')} onChange={e=>setDate(e.target.value)}/></label><label>Nội quy<select className="input mt-1 w-full" value={ruleId} onChange={e=>setRuleId(e.target.value)}><option value="">Chọn nội quy</option>{data.rules.map(r=><option key={r.id} value={r.id}>{r.label} · {r.value_mode==='FIXED'?r.default_delta:`${r.minimum_delta}…${r.maximum_delta}`}</option>)}</select></label><label>Số lần<input className="input mt-1 w-full" type="number" min={1} max={50} value={occurrences} disabled={!!editing} onChange={e=>setOccurrences(Number(e.target.value))}/></label>{rule?.value_mode==='MANUAL'&&<label>Điểm mỗi lần<input className="input mt-1 w-full" type="number" step="0.01" min={rule.minimum_delta??undefined} max={rule.maximum_delta??undefined} value={delta} onChange={e=>setDelta(e.target.value)}/></label>}</div><fieldset className="grid gap-2 sm:grid-cols-2"><legend>Học sinh được phép ghi nhận</legend>{data.targets.map(s=><label className="flex min-h-11 items-center gap-2 rounded-lg border p-2" key={s.enrollment_id}><input type="checkbox" checked={selected.includes(s.enrollment_id)} disabled={locked||!!editing} onChange={e=>setSelected(old=>e.target.checked?[...old,s.enrollment_id]:old.filter(id=>id!==s.enrollment_id))}/>{s.full_name}</label>)}</fieldset><label className="block">Ghi chú / lý do<textarea className="input mt-1 w-full" value={note} maxLength={500} onChange={e=>setNote(e.target.value)}/></label><div className="flex flex-wrap gap-2"><Button variant="primary" disabled={busy||locked||!data.period||!rule||!selected.length||note.trim().length<3} onClick={()=>void saveEntry()}>{editing?'Lưu sửa ghi nhận':'Lưu ghi nhận'}</Button>{editing&&<><Button disabled={busy||locked||note.trim().length<5} onClick={()=>void saveEntry(true)}>Loại ghi nhận có lý do</Button><Button onClick={()=>{setEditing(null);setSelected([]);}}>Hủy sửa</Button></>}</div><p className="text-sm text-muted">{selected.length} học sinh × {occurrences} lần. Các ghi nhận chờ GVCN duyệt.</p></Card>}
 {data.role==='LABOR_VICE'&&<Card className="space-y-3 p-4"><h2 className="font-bold">Lịch trực nhật nháp</h2><label className="block">Ngày trực<input className="input ml-2" type="date" value={dutyDate} onChange={e=>setDutyDate(e.target.value)}/></label><label className="block">Tổ trực<select className="input ml-2" value={dutyGroup} onChange={e=>{setDutyGroup(e.target.value);setSelected(data.targets.filter(t=>t.group_id===e.target.value).map(t=>t.enrollment_id));}}><option value="">Chọn từng học sinh</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><fieldset className="grid gap-2 sm:grid-cols-2"><legend>Thành viên trực</legend>{data.targets.map(s=><label key={s.enrollment_id}><input type="checkbox" checked={selected.includes(s.enrollment_id)} onChange={e=>setSelected(old=>e.target.checked?[...old,s.enrollment_id]:old.filter(id=>id!==s.enrollment_id))}/> {s.full_name}</label>)}</fieldset><label className="block">Nhiệm vụ<input className="input mt-1 w-full" value={task} onChange={e=>setTask(e.target.value)}/></label><Button disabled={locked||!selected.length||!dutyDate||task.trim().length<3} onClick={()=>{setDutyEntries(old=>[...old,...selected.map(enrollmentId=>({enrollmentId,dutyDate,task,status:'ASSIGNED' as const}))]);setSelected([]);}}>Thêm nhiệm vụ</Button>{dutyEntries.map((a,i)=><p key={i}>{a.dutyDate} · {data.targets.find(s=>s.enrollment_id===a.enrollmentId)?.full_name} · {a.task} <button type="button" className="text-danger-text" onClick={()=>setDutyEntries(old=>old.filter((_,n)=>n!==i))}>Bỏ dòng</button></p>)}<div className="flex flex-wrap gap-2"><Button variant="primary" disabled={busy||locked||!dutyEntries.length} onClick={()=>void command('saveClassOfficerDuty',{...body!,assignments:dutyEntries})}>Lưu nháp trực nhật</Button><Button disabled={busy||locked} onClick={()=>void command('saveClassOfficerDuty',{...body!,copyPrevious:true})}>Copy tuần trước</Button></div><p>GVCN kiểm tra và công bố lịch trực nhật.</p></Card>}
 {data.role==='CLASS_LEADER'&&<Card className="space-y-3 p-4"><h2 className="font-bold">Tiến độ các tổ</h2>{data.submissions.map((s,i)=><p key={i}>{s.group_name}: {STATUS_LABEL[s.status??'DRAFT']}</p>)}{data.timetableEnabled&&<><h3 className="font-bold">Thời khóa biểu nháp</h3><div className="grid grid-cols-2 gap-2"><label>Thứ<select className="input w-full" value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{[1,2,3,4,5,6,7].map(d=><option key={d} value={d}>{d===7?'Chủ nhật':'Thứ '+(d+1)}</option>)}</select></label><label>Tiết<input type="number" className="input w-full" min={1} max={12} value={period} onChange={e=>setPeriod(Number(e.target.value))}/></label><label className="col-span-2">Môn / giáo viên<select className="input w-full" value={teaching} onChange={e=>setTeaching(e.target.value)}><option value="">Chọn phân công</option>{data.teaching.map((t,i)=><option key={i} value={String(i)}>{t.subject_name} · {t.teacher_name}</option>)}</select></label><label>Bắt đầu<input type="time" className="input w-full" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Kết thúc<input type="time" className="input w-full" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><Button disabled={locked||!teaching||start>=end} onClick={()=>{const t=data.teaching[Number(teaching)];if(t)setEntries(old=>[...old,{weekday,periodNumber:period,subjectId:t.subject_id,memberId:t.member_id,startsAtLocal:start,endsAtLocal:end}]);}}>Thêm tiết</Button>{entries.map((e,i)=><p key={i}>Thứ {e.weekday+1} · tiết {e.periodNumber} · {e.startsAtLocal}–{e.endsAtLocal} <button type="button" onClick={()=>setEntries(old=>old.filter((_,n)=>n!==i))}>Bỏ dòng</button></p>)}<div className="flex flex-wrap gap-2"><Button variant="primary" disabled={busy||locked||!entries.length} onClick={()=>void command('saveClassOfficerTimetable',{...body!,entries})}>Lưu TKB nháp</Button><Button disabled={busy||locked} onClick={()=>void command('saveClassOfficerTimetable',{...body!,copyPrevious:true})}>Copy TKB tuần trước</Button></div></>}</Card>}
 {data.role!=='LABOR_VICE'&&<Card className="p-4"><h2 className="font-bold">Ghi nhận trong tuần</h2>{data.records.map(r=><div key={r.id} className="border-b py-3"><b>{data.targets.find(s=>s.enrollment_id===r.enrollment_id)?.full_name}</b><p>{r.rule_label_snapshot}: {r.delta_snapshot} · {r.public_reason} · {r.status}</p>{r.status==='DRAFT'&&r.officer_assignment_id===data.assignmentId&&!locked&&<Button disabled={busy} onClick={()=>{setEditing(r);setSelected([r.enrollment_id]);setRuleId(r.rule_id);setOccurrences(1);setDelta(r.delta_snapshot);setNote(r.public_reason);setDate(new Date(r.occurred_at).toLocaleDateString('en-CA'));}}>Sửa ghi nhận</Button>}</div>)}</Card>}
 <Card className="flex flex-wrap items-center justify-between gap-3 p-4"><p>Nộp tuần để GVCN rà soát. Có tối đa 5 phút chỉnh sửa sau nộp.</p><Button variant="primary" disabled={busy||locked||state?.status==='SUBMITTED'} onClick={()=>setConfirm(true)}>Xem trước và nộp tuần</Button></Card>
 <Modal open={confirm} onOpenChange={setConfirm} title="Xác nhận nộp tuần" busy={busy} footer={<Button variant="primary" disabled={busy||locked} onClick={()=>void command('submitClassOfficerWeek',body!).then(()=>setConfirm(false))}>Xác nhận nộp tuần</Button>}><p>{data.records.length} ghi nhận; {data.records.filter(r=>r.status==='DRAFT').length} chờ duyệt.</p><p>Điểm đã ghi: {data.records.filter(r=>r.status!=='EXCLUDED').reduce((s,r)=>s+Number(r.delta_snapshot),0)}.</p><p>{data.targets.filter(s=>!data.records.some(r=>r.enrollment_id===s.enrollment_id&&r.status!=='EXCLUDED')).length} học sinh chưa có ghi nhận trong tuần.</p><p>Sau cửa sổ chỉnh sửa, hệ thống khóa theo thời gian máy chủ.</p></Modal>
 </>}
 </main>;
}
