"use client";
import {useCallback,useEffect,useState} from 'react';
import {http,download} from '@/lib/api/client';
import {useClassroom,ClassHeader} from '@/features/classroom/context';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Modal} from '@/components/ui/dialog';
import type {ApiRequest,OperationId} from '@/lib/api/generated';
import {STATUS_LABEL,type Periodic,type PeriodicResult} from './types';
type Options={year_id:string;version:number;notebook_settings:{periodicClassificationPolicy?:{thresholds:{label:string;minimum_score:string}[];version:number}};terms:{id:string;name:string}[];thresholds:{label:string;minimum_score:string}[]};
export function ClassPeriodicPage(){
 const {schoolId,classId,yearId,can,readOnly}=useClassroom(),params={schoolId,classId};
 const [periods,setPeriods]=useState<Periodic[]>([]),[options,setOptions]=useState<Options|null>(null),[current,setCurrent]=useState(''),[type,setType]=useState<'MONTH'|'TERM'|'YEAR'>('MONTH'),[key,setKey]=useState(()=>new Date().toISOString().slice(0,7)),[aggregation,setAggregation]=useState<'AVERAGE'|'SUM'>('AVERAGE'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<PeriodicResult|null>(null),[final,setFinal]=useState(''),[reason,setReason]=useState(''),[policyOpen,setPolicyOpen]=useState(false),[thresholds,setThresholds]=useState<{label:string;minimum_score:string}[]>([]),[exportJob,setExportJob]=useState<{id:string;status:string}|null>(null);
 const [loading,setLoading]=useState(true);
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const [p,o]=await Promise.all([http('listClassPeriodicConduct',{params:{schoolId,classId},signal}),http('getClassPeriodicOptions',{params:{schoolId,classId},signal})]);if(signal?.aborted)return;setPeriods(p.data as unknown as Periodic[]);setOptions(o.data as unknown as Options);setError('');}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Chưa tải được dữ liệu');}finally{if(!signal?.aborted)setLoading(false);}},[schoolId,classId]);
 useEffect(()=>{const a=new AbortController();void load(a.signal);return()=>a.abort();},[load]);
 useEffect(()=>{if(!options||loading||error)return;if(type==='TERM'&&!options.terms.some(t=>t.id===key))setKey('');if(current&&!periods.some(p=>p.id===current))setCurrent('');},[options,loading,error,type,key,current,periods]);
 const selected=periods.find(p=>p.id===current)??periods[0],labels=selected?.policy_snapshot.thresholds.map(t=>t.label)??[],mutable=!!selected&&['DRAFT','REVIEW'].includes(selected.status);
 const command=async<K extends OperationId>(op:K,body:ApiRequest<K>)=>{setBusy(true);setError('');try{const r=await http(op,{params,body});if(op==='calculateClassPeriodicConduct')setCurrent(String((r.data as Record<string,unknown>).id));await load();return true;}catch(e){setError(e instanceof Error?e.message:'Thao tác chưa hoàn tất');return false;}finally{setBusy(false);}};
 const action=(op:'reviewClassPeriodicConduct'|'finalizeClassPeriodicConduct'|'publishClassPeriodicConduct')=>{if(selected)void command(op,{periodId:selected.id,expectedVersion:selected.version});};
 const exportReport=async(format:'PDF'|'XLSX',studentId?:string)=>{if(!selected)return;setBusy(true);setError('');try{const r=await http('createExport',{params:{schoolId},body:{reportType:'parent-conduct',format,yearId,classId,periodId:selected.id,periodType:selected.period_type,from:selected.starts_on,to:selected.ends_on,dataSource:'PUBLISHED_SNAPSHOT',scope:'CLASS',...(studentId?{studentId}:{})}});setExportJob({id:String(r.data.id),status:r.data.status});}catch(e){setError(e instanceof Error?e.message:'Không tạo được bản xuất');}finally{setBusy(false);}};
 useEffect(()=>{if(!exportJob||['COMPLETED','FAILED','CANCELLED'].includes(exportJob.status))return;const a=new AbortController(),timer=setInterval(()=>{void http('getExport',{params:{schoolId,exportId:exportJob.id},signal:a.signal}).then(r=>{if(!a.signal.aborted)setExportJob({id:exportJob.id,status:r.data.status});}).catch(e=>{if(!a.signal.aborted)setError(e instanceof Error?e.message:'Chưa kiểm tra được bản xuất');});},2000);return()=>{a.abort();clearInterval(timer);};},[exportJob?.id,exportJob?.status,schoolId]);
 const saveDownload=async()=>{if(!exportJob)return;try{const file=await download('downloadExport',{params:{schoolId,exportId:exportJob.id}}),url=URL.createObjectURL(file.blob),a=document.createElement('a');a.href=url;a.download=file.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Không tải được bản xuất');}};
 return <div className="page"><ClassHeader title="Xếp loại định kỳ" subtitle="Tháng, học kỳ và năm · lấy từ các tuần đã khóa và công bố"/>{error&&<p role="alert" className="rounded-xl bg-danger-bg p-3 text-danger-text">{error} <Button size="sm" onClick={()=>void load()}>Thử lại</Button></p>}{loading&&<p role="status">Đang tải dữ liệu…</p>}
 {!readOnly&&can('conduct.review')&&<Card className="space-y-3 p-4"><h2 className="font-bold">Tính gợi ý xếp loại</h2><div className="grid gap-3 sm:grid-cols-3"><label>Loại kỳ<select className="input w-full" value={type} onChange={e=>{const t=e.target.value as typeof type;setType(t);setKey(t==='YEAR'?yearId:t==='TERM'?options?.terms[0]?.id??'':new Date().toISOString().slice(0,7));}}><option value="MONTH">Tháng</option><option value="TERM">Học kỳ</option><option value="YEAR">Năm học</option></select></label><label>Kỳ{type==='MONTH'?<input className="input w-full" type="month" value={key} onChange={e=>setKey(e.target.value)}/>:type==='TERM'?<select className="input w-full" value={key} onChange={e=>setKey(e.target.value)}>{options?.terms.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>:<p>Năm học của lớp</p>}</label><label>Cách tổng hợp<select className="input w-full" value={aggregation} onChange={e=>setAggregation(e.target.value as typeof aggregation)}><option value="AVERAGE">Trung bình điểm tuần</option><option value="SUM">Tổng điểm tuần</option></select></label></div><div className="flex flex-wrap gap-2"><Button variant="primary" disabled={busy||loading||!!error||!options||!key} onClick={()=>{const old=periods.find(p=>p.period_type===type&&p.period_key===key);void command('calculateClassPeriodicConduct',{periodType:type,periodKey:key,aggregation,...(old?{expectedVersion:old.version}:{})});}}>Tính / cập nhật nháp</Button>{can('groups.manage')&&<Button disabled={busy} onClick={()=>{setThresholds(options?.notebook_settings.periodicClassificationPolicy?.thresholds??options?.thresholds??[]);setPolicyOpen(true);}}>Chính sách xếp loại kỳ</Button>}</div><p className="text-sm text-muted">Gợi ý theo chính sách đang áp dụng. Kết quả cuối do GVCN/quản trị có quyền chốt; đổi khác gợi ý phải có lý do.</p></Card>}
 <Card className="space-y-4 p-4"><label>Bản định kỳ<select className="input ml-2 max-w-full" value={selected?.id??''} onChange={e=>setCurrent(e.target.value)}><option value="" disabled>Chọn bản</option>{periods.map(p=><option key={p.id} value={p.id}>{p.period_label} · {STATUS_LABEL[p.status]??p.status}</option>)}</select></label>{loading?<p role="status">Đang tải các bản định kỳ…</p>:error?<p>Chưa xác nhận được dữ liệu; hãy thử lại.</p>:selected?<><p><b>{selected.period_label}</b> · {STATUS_LABEL[selected.status]} · {selected.source_publication_ids.length} bản tuần làm nguồn · {selected.policy_snapshot.aggregation==='AVERAGE'?'Điểm trung bình':'Tổng điểm'}</p><div className="flex flex-wrap gap-2">{selected.status==='DRAFT'&&can('conduct.review')&&<Button disabled={busy||readOnly} onClick={()=>action('reviewClassPeriodicConduct')}>Chuyển rà soát</Button>}{selected.status==='REVIEW'&&can('conduct.lock')&&<Button disabled={busy||readOnly} onClick={()=>action('finalizeClassPeriodicConduct')}>Chốt xếp loại</Button>}{selected.status==='FINALIZED'&&can('conduct.publish')&&<Button variant="primary" disabled={busy||readOnly} onClick={()=>action('publishClassPeriodicConduct')}>Công bố kết quả</Button>}{selected.status==='PUBLISHED'&&can('report.export')&&<><Button disabled={busy} onClick={()=>void exportReport('XLSX')}>Xuất Excel cả lớp</Button><Button disabled={busy} onClick={()=>void exportReport('PDF')}>PDF cả lớp</Button></>}</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr>{['Học sinh','Tuần có dữ liệu','Điểm kỳ','Gợi ý','Xếp loại cuối','Lý do','Thao tác'].map(t=><th className="border-b p-2 text-left" key={t}>{t}</th>)}</tr></thead><tbody>{selected.results.map(r=><tr key={r.studentId}><td className="border-b p-2"><b>{r.fullName}</b><p>{r.studentCode}</p></td><td className="border-b p-2">{r.weekCount}</td><td className="border-b p-2">{r.score}</td><td className="border-b p-2">{r.suggestedClassification??'Chưa có mức phù hợp'}</td><td className="border-b p-2">{r.finalClassification??'Chưa chốt'}</td><td className="border-b p-2">{r.overrideReason??'—'}</td><td className="border-b p-2">{mutable&&can('conduct.review')&&!readOnly&&<Button disabled={busy} onClick={()=>{setEdit(r);setFinal(r.finalClassification??'');setReason(r.overrideReason??'');}}>Điều chỉnh</Button>}{selected.status==='PUBLISHED'&&can('report.export')&&<Button disabled={busy} onClick={()=>void exportReport('PDF',r.studentId)}>PDF cá nhân</Button>}</td></tr>)}</tbody></table></div></>:<p>Chưa có bản xếp loại định kỳ. Hãy tính gợi ý từ các tuần đã công bố.</p>}</Card>
 {exportJob&&<Card className="p-4"><p>Xuất báo cáo: {exportJob.status==='COMPLETED'?'Đã sẵn sàng':exportJob.status==='FAILED'?'Không hoàn tất': 'Đang xử lý'}</p>{exportJob.status==='COMPLETED'&&<Button variant="primary" onClick={()=>void saveDownload()}>Tải bản xuất</Button>}</Card>}
 <Modal open={!!edit} onOpenChange={o=>{if(!o)setEdit(null);}} title="Xếp loại cuối của học sinh" busy={busy} footer={<Button variant="primary" disabled={busy||!final||final!==edit?.suggestedClassification&&reason.trim().length<5} onClick={()=>{if(selected&&edit)void command('overrideClassPeriodicConduct',{periodId:selected.id,expectedVersion:selected.version,studentId:edit.studentId,classification:final,reason}).then(ok=>{if(ok)setEdit(null);});}}>Lưu xếp loại</Button>}>{edit&&<div className="space-y-3"><p>{edit.fullName} · điểm {edit.score} · gợi ý {edit.suggestedClassification}</p><label className="block">Xếp loại cuối<select className="input w-full" value={final} onChange={e=>setFinal(e.target.value)}><option value="">Chọn xếp loại</option>{labels.map(l=><option key={l} value={l}>{l}</option>)}</select></label><label className="block">Lý do điều chỉnh<textarea className="input w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label></div>}</Modal>
 <Modal open={policyOpen} onOpenChange={setPolicyOpen} title="Chính sách xếp loại định kỳ của lớp" busy={busy} footer={<Button variant="primary" disabled={busy||!thresholds.length} onClick={()=>{if(options)void command('saveClassNotebookSettings',{expectedVersion:options.version,settings:{periodicClassificationPolicy:{thresholds}}}).then(ok=>{if(ok)setPolicyOpen(false);});}}>Lưu chính sách</Button>}><p>Nhập điểm tối thiểu và nhãn. Bản đã chốt giữ nguyên chính sách đã ghi.</p>{thresholds.map((t,i)=><div className="my-2 flex gap-2" key={i}><input aria-label={`Nhãn mức ${i+1}`} className="input min-w-0 flex-1" value={t.label} onChange={e=>setThresholds(old=>old.map((v,n)=>n===i?{...v,label:e.target.value}:v))}/><input aria-label={`Điểm tối thiểu mức ${i+1}`} className="input w-24" type="number" step="0.01" value={t.minimum_score} onChange={e=>setThresholds(old=>old.map((v,n)=>n===i?{...v,minimum_score:e.target.value}:v))}/><button type="button" onClick={()=>setThresholds(old=>old.filter((_,n)=>n!==i))}>Bỏ</button></div>)}<Button onClick={()=>setThresholds(old=>[...old,{label:'',minimum_score:'0'}])}>Thêm mức</Button></Modal>
 </div>;
}
