"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {http,download} from '@/lib/api/client';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
interface Workspace{studentName:string;className:string;title:string;description:string;dueAt:string;maxFiles:number;maxBytes:number;csrfToken:string;files:{id:string;file_id:string;caption:string|null;status:string;review_reason:string|null;created_at:string;original_name:string}[]}
export function StudentEvidencePage({slug}:{slug:string}){
 const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null),[caption,setCaption]=useState('');
 const exchange=useRef<{slug:string;promise:Promise<unknown>}|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{const r=await http('getStudentEvidenceWorkspace',{params:{publicClassSlug:slug},signal});if(!signal?.aborted)setData(r.data as unknown as Workspace);},[slug]);
 useEffect(()=>{const a=new AbortController(),token=new URLSearchParams(window.location.hash.slice(1)).get('access');if(token){window.history.replaceState(null,'',window.location.pathname);exchange.current={slug,promise:http('exchangeStudentEvidenceAccess',{params:{publicClassSlug:slug},body:{accessToken:token}})};}void(async()=>{try{if(exchange.current?.slug===slug)await exchange.current.promise;await load(a.signal);}catch(e){if(!a.signal.aborted)setError(e instanceof Error?e.message:'Mã nộp minh chứng không khả dụng');}})();return()=>a.abort();},[load,slug]);
 const submit=async()=>{if(!file||!data)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);if(caption.trim())form.append('caption',caption.trim());await http('uploadStudentEvidence',{params:{publicClassSlug:slug},multipart:form,capabilityCsrf:data.csrfToken});setFile(null);setCaption('');await load();}catch(e){setError(e instanceof Error?e.message:'Chưa nộp được minh chứng');}finally{setBusy(false);}};
 const getFile=async(id:string)=>{try{const r=await download('downloadStudentEvidence',{params:{publicClassSlug:slug,fileId:id}}),url=URL.createObjectURL(r.blob),a=document.createElement('a');a.href=url;a.download=r.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Tệp không khả dụng');}};
 return <main className="mx-auto max-w-2xl space-y-4 p-4 sm:p-8"><h1 className="page-title">Nộp minh chứng hoạt động</h1>{error&&<p role="alert" className="rounded-xl bg-danger-bg p-3 text-danger-text">{error}</p>}{!data&&!error&&<p>Đang kiểm tra mã truy cập…</p>}{data&&<><Card className="space-y-2 p-4"><h2 className="text-lg font-bold">{data.title}</h2><p>{data.studentName} · {data.className}</p><p>{data.description}</p><p>Hạn: {new Date(data.dueAt).toLocaleString('vi-VN')}{new Date(data.dueAt)<new Date()&&' · bài nộp sẽ được đánh dấu muộn'}</p></Card><Card className="space-y-4 p-4"><p>{data.files.length}/{data.maxFiles} tệp đã nộp. Ảnh PNG/JPEG/WebP, tối đa {data.maxBytes/1024/1024} MB/tệp.</p><label className="block">Ảnh minh chứng<input className="input mt-1 w-full" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||data.files.length>=data.maxFiles} onChange={e=>{const f=e.target.files?.[0]??null;if(f&&f.size>data.maxBytes){setError(`Ảnh vượt ${data.maxBytes/1024/1024} MB`);e.target.value='';return;}setFile(f);}}/></label><label className="block">Chú thích<textarea className="input mt-1 w-full" value={caption} maxLength={200} onChange={e=>setCaption(e.target.value)}/></label><Button variant="primary" disabled={busy||!file||data.files.length>=data.maxFiles} onClick={()=>void submit()}>Nộp minh chứng</Button></Card><Card className="p-4"><h2 className="font-bold">Bài của bạn</h2>{data.files.map(f=><div className="space-y-1 border-b py-3" key={f.id}><p>{f.original_name} · {f.status==='APPROVED'?'Đã chấp nhận':f.status==='NEEDS_REVISION'?'Cần sửa':'Chờ duyệt'}</p><p>{f.caption}</p>{f.review_reason&&<p>Nhận xét: {f.review_reason}</p>}<Button onClick={()=>void getFile(f.file_id)}>Tải ảnh của bạn</Button></div>)}</Card></>}</main>;
}
