export type OfficerRole='GROUP_LEADER'|'CLASS_LEADER'|'LABOR_VICE';
export const ROLE_LABEL:Record<OfficerRole,string>={GROUP_LEADER:'Tổ trưởng',CLASS_LEADER:'Lớp trưởng',LABOR_VICE:'Lớp phó Lao động'};
export const STATUS_LABEL:Record<string,string>={DRAFT:'Chưa nộp',SUBMITTED:'Đã nộp · đang chờ khóa',LOCKED:'Đã khóa',REOPENED:'Đang mở lại',REVIEW:'Đang rà soát',FINALIZED:'Đã chốt',PUBLISHED:'Đã công bố'};
export interface Week{id:string;week_number:number;starts_on:string;ends_on:string}
export interface Submission{id:string;officer_assignment_id:string;status:string;version:number;submitted_at:string|null;lock_at:string|null;reopened_until:string|null}
export interface Officer{id:string;version:number;role:OfficerRole;full_name:string;group_id:string|null;group_name:string|null;enrollment_id:string;revoked_at:string|null;valid_from:string;valid_until:string|null;locked_until:string|null}
export interface Student{enrollment_id:string;student_id?:string;full_name:string;student_code?:string;group_id?:string|null}
export interface Position{id:string;version:number;name:string;description:string;weekly_bonus:string;officer_role:OfficerRole|null;group_id:string|null}
export interface NotebookWorkspace{classId:string;yearId:string;className:string;version:number;today:string;settings:{weeklyDeadlineDay?:number;weeklySubmitTime?:string;weeklyLockTime?:string;officerTimetableEnabled?:boolean;reminderTemplate?:string};slug:string|null;weeks:Week[];weekId:string;roster:Student[];groups:{id:string;name:string}[];positions:Position[];officers:Officer[];submissions:Submission[];deadline:{submit_deadline:string;lock_deadline:string;version:number}|null;terms:{id:string;name:string}[];recentAudit:{action:string;reason:string|null;created_at:string}[]}
export interface OfficerWorkspace{assignmentId:string;className:string;displayName:string;role:OfficerRole;csrfToken:string;serverNow:string;weeks:Week[];weekId:string;submission:Submission;deadlines:{submit:string;lock:string};period:{id:string;status:string}|null;targets:Student[];rules:{id:string;label:string;value_mode:string;default_delta:string;minimum_delta:string|null;maximum_delta:string|null;reason_required:boolean}[];records:{id:string;version:number;enrollment_id:string;rule_id:string;rule_label_snapshot:string;delta_snapshot:string;public_reason:string;status:string;officer_assignment_id:string|null;occurred_at:string}[];groups:{id:string;name:string}[];submissions:{group_name:string;status:string|null}[];timetables:{id:string;status:string}[];timetableEnabled:boolean;teaching:{member_id:string;subject_id:string;teacher_name:string;subject_name:string}[]}
export interface PeriodicResult{studentId:string;studentCode:string;fullName:string;weekCount:number;score:string;suggestedClassification:string|null;finalClassification:string|null;overrideReason:string|null;bonusPoints:string;penaltyPoints:string;penaltyCount:number}
export interface Periodic{id:string;version:number;period_type:'MONTH'|'TERM'|'YEAR';period_key:string;period_label:string;status:string;starts_on:string;ends_on:string;finalized_at:string|null;policy_snapshot:{aggregation:string;thresholds:{label:string;minimum_score:string}[]};results:PeriodicResult[];source_publication_ids:string[]}
