"use client";
import {useCallback,useEffect,useState} from 'react';
import {http} from '@/lib/api/client';
import {useClassroom,ClassHeader} from '@/features/classroom/context';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {fillMessageTemplate} from './message-template';
interface Student{studentId:string;studentName:string;guardianName:string|null;phone:string|null;zaloUrl:string|null;period:string;score:string;classification:string|null;bonus:string;penalty:string;attendance:Record<string,number>}
interface Workspace{className:string;version:number;template:string;sources:{id:string;label:string}[];selectedPublicationId:string|null;students:Student[]}
const attendanceLabels:Record<string,string>={PRESENT:'có mặt',LATE:'muộn',EXCUSED:'nghỉ có phép',UNEXCUSED:'nghỉ không phép',UNMARKED:'chưa điểm danh'};
export function ZaloHelperPage(){
 const {schoolId,classId,base,readOnly,can}=useClassroom(),[data,setData]=useState<Workspace|null>(null),[source,setSource]=useState(''),[template,setTemplate]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{try{const r=await http('getClassZaloHelper',{params:{schoolId,classId},query:source?{publicationId:source}:{},signal});if(signal?.aborted)return;const w=r.data as unknown as Workspace;setData(w);setTemplate(w.template);}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Chưa tải được');}},[schoolId,classId,source]);
 useEffect(()=>{const a=new AbortController();void load(a.signal);return()=>a.abort();},[load]);
 const render=(s:Student)=>{const classification=s.classification??'Chưa xếp loại',attendance=Object.entries(s.attendance).map(([k,n])=>`${n} ${attendanceLabels[k]??k}`).join(', ')||'Chưa có bản công bố';return fillMessageTemplate(template,{student:s.studentName,student_name:s.studentName,class:data?.className??'',class_name:data?.className??'',period:s.period,period_label:s.period,score:s.score,classification,bonus:s.bonus,penalty:s.penalty,attendance});};
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);setMessage('Đã copy. Bạn tự gửi cho phụ huynh.');}catch{setError('Chưa copy được; chọn nội dung để copy thủ công.');}};
 const save=async()=>{if(!data)return;setBusy(true);try{await http('saveClassNotebookSettings',{params:{schoolId,classId},body:{expectedVersion:data.version,settings:{zaloTemplate:template}}});await load();setMessage('Đã lưu mẫu tin cho lớp');}catch(e){setError(e instanceof Error?e.message:'Chưa lưu được');}finally{setBusy(false);}};
 return <div className="page"><ClassHeader title="Soạn tin cho phụ huynh qua Zalo" subtitle="Điểm và chuyên cần lấy từ bản đã công bố; bạn tự kiểm tra, copy và gửi." crumbs={[{label:'Báo cáo',href:base+'/reports'}]}/>{error&&<p role="alert" className="text-danger-text">{error}</p>}{message&&<p role="status">{message}</p>}{data&&<><Card className="space-y-3 p-4"><label className="block">Kỳ đã công bố<select className="input mt-1 w-full" value={data.selectedPublicationId??''} onChange={e=>setSource(e.target.value)}>{data.sources.map(p=><option value={p.id} key={p.id}>{p.label}</option>)}</select></label><label className="block">Mẫu tin nhắn<textarea className="input mt-1 w-full" value={template} onChange={e=>setTemplate(e.target.value)} maxLength={2000} rows={4}/></label><p className="text-sm">Biến: {'{{student_name}}, {{class_name}}, {{period_label}}, {{score}}, {{classification}}, {{bonus}}, {{penalty}}, {{attendance}} (hoặc biến ngắn cùng tên)'}</p><div className="flex flex-wrap gap-2">{can('groups.manage')&&<Button disabled={busy||readOnly} onClick={()=>void save()}>Lưu mẫu tin của lớp</Button>}<Button disabled={!data.students.length} onClick={()=>void copy(data.students.map(render).join('\n\n'))}>Copy tất cả</Button></div></Card><div className="grid gap-3 md:grid-cols-2">{data.students.map(s=><Card key={s.studentId} className="space-y-3 p-4"><h2 className="font-bold">{s.studentName}</h2><p>{s.guardianName??'Chưa có người giám hộ đã xác minh'} · {s.phone??'Chưa có số điện thoại'}</p><p className="whitespace-pre-wrap rounded-xl bg-surface p-3">{render(s)}</p><div className="flex flex-wrap gap-2"><Button onClick={()=>void copy(render(s))}>Copy tin nhắn</Button>{s.zaloUrl&&/^https:\/\/zalo\.me\/84[0-9]{9}$/.test(s.zaloUrl)?<a className="btn btn-secondary" href={s.zaloUrl} target="_blank" rel="noopener noreferrer" onClick={()=>void copy(render(s))}>Mở Zalo</a>:<span className="text-sm">Cần số điện thoại hợp lệ để mở Zalo</span>}</div></Card>)}</div>{!data.sources.length&&<p>Chưa có bản rèn luyện đã công bố để soạn tin.</p>}</>}</div>;
}
