import {one,iso,type Row,type Transaction} from '../../database/database';
import {getResource,resource} from '../../database/resources';
import {Permissions,grantAllows} from '../../common/permissions';
import {Problem,notFound} from '../../common/problem';
import {fileDto} from '../files/files.service';
import type {RequestContext} from '../../api.router';

function bounded<T>(rows:T[],limit:number){if(rows.length>limit)throw new Problem(422,'ACTIVITY_WORKSPACE_LIMIT');return rows;}
export async function activityWorkspaceAccess(tx:Transaction,policy:Permissions,c:RequestContext,action='activity.read'){
 const schoolId=c.params.schoolId!,classId=c.params.classId!,yearId=c.params.yearId!,access=await policy.require(tx,c.principal!,action,{schoolId,classId,yearId,allowSubject:action==='activity.read'});
 const cls=await getResource(tx,resource('class'),schoolId,classId);if(cls.year_id!==yearId)notFound();const year=await getResource(tx,resource('year'),schoolId,yearId);
 const can=(permission:string)=>access.grants.some(g=>grantAllows(g,permission,{schoolId,classId,yearId},access.today));
 const readOnly=cls.status==='ARCHIVED'||year.status==='ARCHIVED';if(c.operation.method!=='GET'&&readOnly)throw new Problem(409,'YEAR_ARCHIVED');
 const school=(await one<Row>(tx,'SELECT timezone FROM platform.schools WHERE id=$1',[schoolId]))!;
 return {schoolId,classId,yearId,today:access.today,timezone:String(school.timezone),readOnly,can};
}
export async function activityWorkspace(tx:Transaction,policy:Permissions,c:RequestContext){
 const a=await activityWorkspaceAccess(tx,policy,c),canDraft=a.can('activity.manage'),canReadEvidence=a.can('evidence.read');
 const activities=bounded((await tx.query<Row>(`SELECT a.*,m.work_display_name AS author_name,(a.due_at AT TIME ZONE $5)::date AS due_date,p.id AS publication_id,p.source_version AS published_source_version FROM app.activities a LEFT JOIN app.memberships m ON m.school_id=a.school_id AND m.user_id=a.created_by LEFT JOIN app.publication_revisions p ON p.school_id=a.school_id AND p.activity_id=a.id AND p.status='PUBLISHED' WHERE a.school_id=$1 AND a.class_id=$2 AND a.year_id=$3 AND a.status<>'ARCHIVED' AND ($4::boolean OR a.status<>'DRAFT') ORDER BY a.due_at,a.id LIMIT 1001`,[a.schoolId,a.classId,a.yearId,canDraft,a.timezone])).rows,1000);
 const ids=activities.map(r=>r.id),roster=bounded((await tx.query<Row>(`SELECT e.id AS enrollment_id,s.id,s.full_name,s.student_code,g.id AS group_id,g.name AS group_name FROM app.enrollments e JOIN app.students s ON s.school_id=e.school_id AND s.id=e.student_id LEFT JOIN app.group_memberships gm ON gm.school_id=e.school_id AND gm.enrollment_id=e.id AND gm.cancelled_at IS NULL AND gm.starts_on<=$4 AND (gm.ends_on IS NULL OR gm.ends_on>$4) LEFT JOIN app.class_groups g ON g.school_id=gm.school_id AND g.id=gm.group_id WHERE e.school_id=$1 AND e.class_id=$2 AND e.year_id=$3 AND e.status<>'CANCELLED' AND e.starts_on<=$4 AND (e.ends_on IS NULL OR e.ends_on>$4) ORDER BY s.full_name COLLATE app.vi_names,s.id LIMIT 5001`,[a.schoolId,a.classId,a.yearId,a.today])).rows,5000);
 const groups=bounded((await tx.query<Row>("SELECT id,name FROM app.class_groups WHERE school_id=$1 AND class_id=$2 ORDER BY sort_order,id LIMIT 101",[a.schoolId,a.classId])).rows,100);
 const participants=bounded((await tx.query<Row>(`SELECT p.*,s.id AS student_id,s.full_name,s.student_code FROM app.activity_participants p JOIN app.enrollments e ON e.school_id=p.school_id AND e.id=p.enrollment_id JOIN app.students s ON s.school_id=e.school_id AND s.id=e.student_id WHERE p.school_id=$1 AND p.class_id=$2 AND p.activity_id=ANY($3::uuid[]) AND p.cancelled_at IS NULL ORDER BY s.full_name COLLATE app.vi_names,p.id LIMIT 10001`,[a.schoolId,a.classId,ids])).rows,10000);
 const evidence=canReadEvidence?bounded((await tx.query<Row>(`SELECT ev.*,p.activity_id,e.student_id,m.work_display_name AS author_name,to_jsonb(f) AS file FROM app.evidence ev JOIN app.activity_participants p ON p.school_id=ev.school_id AND p.id=ev.participant_id JOIN app.enrollments e ON e.school_id=p.school_id AND e.id=p.enrollment_id JOIN app.files f ON f.school_id=ev.school_id AND f.id=ev.file_id LEFT JOIN app.memberships m ON m.school_id=ev.school_id AND m.user_id=ev.submitted_by WHERE p.school_id=$1 AND p.class_id=$2 AND p.activity_id=ANY($3::uuid[]) ORDER BY ev.created_at DESC,ev.id LIMIT 10001`,[a.schoolId,a.classId,ids])).rows,10000):null;
 const history=bounded((await tx.query<Row>(`SELECT h.*,m.work_display_name AS actor_name FROM app.audit_events h LEFT JOIN app.memberships m ON m.school_id=h.school_id AND m.user_id=h.actor_user_id WHERE h.school_id=$1 AND (h.target_type='activity' AND h.target_id=ANY($2::uuid[]) OR $4::boolean AND (h.target_type='evidence' AND h.target_id=ANY($3::uuid[]) OR h.target_type='activity-participant' AND (h.redacted_after->>'activityId')=ANY($2::text[]))) ORDER BY h.created_at DESC,h.id LIMIT 2001`,[a.schoolId,ids,evidence?.map(e=>e.id)??[],canReadEvidence])).rows,2000);
 return {schoolId:a.schoolId,yearId:a.yearId,classId:a.classId,today:a.today,timezone:a.timezone,readOnly:a.readOnly,canManage:a.can('activity.manage')&&!a.readOnly,canEvidence:a.can('evidence.manage')&&!a.readOnly,canReview:a.can('evidence.review')&&!a.readOnly,canPublish:a.can('activity.publish')&&!a.readOnly,canReadEvidence,
  students:roster.map(r=>({id:r.id,enrollmentId:r.enrollment_id,fullName:r.full_name,code:r.student_code,groupId:r.group_id??null,groupName:r.group_name??null})),groups:groups.map(g=>({id:g.id,name:g.name,size:roster.filter(r=>r.group_id===g.id).length})),
  activities:activities.map(r=>({id:r.id,version:Number(r.version),dataVersion:Number(r.data_version),createdAt:iso(r.created_at as Date),updatedAt:iso(r.updated_at as Date),classId:r.class_id,yearId:r.year_id,title:r.title,description:r.description,dueAt:iso(r.due_at as Date),dueDate:r.due_date,startsAt:r.starts_at?iso(r.starts_at as Date):null,maxFiles:Number(r.max_files),evidenceRequired:r.evidence_required,status:r.status,illustration:r.illustration,createdBy:r.created_by,createdByName:r.author_name??null,publicationId:r.publication_id??null,publishedSourceVersion:r.published_source_version??null})),
  participants:participants.map(p=>({id:p.id,version:Number(p.version),activityId:p.activity_id,enrollmentId:p.enrollment_id,studentId:p.student_id,fullName:p.full_name,code:p.student_code,status:p.status,reviewNote:canReadEvidence?p.review_note??null:null,updatedAt:iso(p.updated_at as Date),stillEnrolled:roster.some(r=>r.enrollment_id===p.enrollment_id),groupName:roster.find(r=>r.enrollment_id===p.enrollment_id)?.group_name??null})),
  evidence:evidence?.map(e=>({id:e.id,version:Number(e.version),participantId:e.participant_id,activityId:e.activity_id,studentId:e.student_id,fileId:e.file_id,submittedBy:e.submitted_by,uploadedByName:e.author_name??null,createdAt:iso(e.created_at as Date),status:e.status,caption:e.caption??null,reviewReason:e.review_reason??null,shareWithGuardian:e.share_with_guardian,file:fileDto({...e.file as Row,created_at:String((e.file as Row).created_at),updated_at:String((e.file as Row).updated_at)})}))??null,
  history:history.map(h=>({id:h.id,at:iso(h.created_at as Date),action:h.action,actorId:h.actor_user_id,actorName:h.actor_name??(h.actor_kind==='STUDENT'?'Học sinh':null),entityType:h.target_type,entityId:h.target_id,reason:canReadEvidence?h.reason??null:null,activityId:h.target_type==='activity'?h.target_id:(h.redacted_after as Row).activityId??null}))};
}
