"use client";
import {useEffect,useState} from 'react';
import {http} from '@/lib/api/client';
import type {ApiSchemas} from '@/lib/api/generated';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
const attendanceLabels:Record<string,string>={PRESENT:'Có mặt',LATE:'Đi muộn',EXCUSED:'Nghỉ có phép',UNEXCUSED:'Nghỉ không phép',UNMARKED:'Chưa điểm danh'};
export function PublicClassPortal({slug}:{slug:string}){
 const [data,setData]=useState<ApiSchemas['PublicClassPortal']|null>(null),[student,setStudent]=useState<ApiSchemas['PublicClassStudentDetail']|null>(null),[search,setSearch]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();void http('getPublicClassPortal',{params:{publicClassSlug:slug},signal:abort.signal}).then(r=>setData(r.data)).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Cổng lớp không khả dụng');});return()=>abort.abort();},[slug]);
 const select=async(id:string)=>{setError('');try{setStudent((await http('getPublicClassStudent',{params:{publicClassSlug:slug,studentId:id}})).data);}catch(e){setError(e instanceof Error?e.message:'Chưa tải được học sinh');}};
 return <main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-8"><header><p className="text-primary">Cổng lớp công khai · EduManage</p><h1 className="page-title">{data?`Lớp ${data.className}`:'Cổng lớp'}</h1>{data&&<p>{data.schoolName} · {data.yearName} · GVCN: {data.homeroomName??'Chưa phân công'}</p>}</header>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Đang tải…</p>}
 {data&&<><nav className="flex flex-wrap gap-3">{[['students','Học sinh'],['timetable','TKB'],['announcements','Thông báo'],['duties','Trực nhật']].map(([id,title])=><a className="text-primary underline" key={id} href={'#'+id}>{title}</a>)}</nav>
 <section id="students"><Card className="p-4"><h2 className="text-lg font-bold">Danh sách học sinh</h2><input className="input my-3 w-full" aria-label="Tìm học sinh" placeholder="Tìm theo tên, tổ hoặc chức vụ…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.students.filter(s=>[s.fullName,s.groupName,...s.roles].join(' ').toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))).map(s=><button className="rounded-xl border border-line p-3 text-left hover:bg-surface" key={s.id} onClick={()=>void select(s.id)}><b>{s.fullName}</b><p className="text-sm">{s.groupName} {s.roles.join(' · ')}</p></button>)}</div></Card></section>
 {student&&<Card className="p-4"><div className="flex justify-between"><h2 className="font-bold">{student.student.fullName}</h2><Button onClick={()=>setStudent(null)}>Đóng</Button></div><h3>Kết quả thi đua đã công bố</h3>{student.conduct.length?student.conduct.map(c=><p key={c.publicationId}>{c.periodLabel}: {c.finalPoints} điểm · {c.classification??'Chưa xếp loại'}</p>):<p>Chưa có thông tin được công khai.</p>}{data.settings.publicStudentAttendanceEnabled&&<><h3>Chuyên cần</h3>{student.attendance.map((a,i)=><p key={i}>{a.date} {a.slotLabel}: {attendanceLabels[a.status]??a.status}</p>)}</>}{data.settings.publicStudentActivitiesEnabled&&<><h3>Hoạt động</h3>{student.activities.map((a,i)=><p key={i}>{a.title}: {a.studentStatus}</p>)}</>}</Card>}
 <section id="timetable"><Card className="p-4"><h2 className="text-lg font-bold">Thời khóa biểu đã công bố</h2><div className="max-h-96 overflow-auto">{data.timetable.length?data.timetable.map((l,i)=><p className="border-b border-line py-2" key={i}>{l.startsAt?new Date(l.startsAt).toLocaleString('vi-VN'):''} — {l.subjectName} · {l.teacherName}</p>):<p>Chưa có lịch được công bố.</p>}</div></Card></section>
 <section id="announcements"><Card className="p-4"><h2 className="text-lg font-bold">Thông báo công khai</h2>{data.announcements.map(a=><p key={a.id}><a className="text-primary underline" href={a.href}>{a.title}</a></p>)}</Card></section>
 <section id="duties"><Card className="p-4"><h2 className="text-lg font-bold">Trực nhật đã công bố</h2>{data.duties.map((d,i)=><p key={i}>{d.date}: {d.task}</p>)}</Card></section><section id="rules"><Card className="p-4"><h2 className="font-bold">Nội quy đang áp dụng</h2>{data.rules.map((r,i)=><p key={i}>{r.label}: {r.points} điểm</p>)}</Card></section>{data.settings.publicSeatingEnabled&&<Card className="p-4"><h2 className="font-bold">Sơ đồ lớp</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{data.seating.map((s,i)=><div className="rounded-lg border p-2" key={i}>Hàng {s.row+1}, cột {s.column+1}<p>{s.studentName??"Trống"}</p></div>)}</div></Card>}{data.settings.publicRankingEnabled&&<Card className="p-4"><h2 className="font-bold">Xếp hạng tuần đã công bố</h2>{data.ranking.map((s,i)=><p key={s.studentId}>{i+1}. {s.fullName} — {s.finalPoints} ({s.periodLabel})</p>)}</Card>}</>}
 </main>;
}
