import type {Activity,FileAsset,FileShare,ID,SubmissionStatus} from '../../model/types';
import type {Ctx} from '../core';
import type {ApiSchemas} from '../../api/generated';
import {http,captureStaffAccess} from '../../api/client';
import {RepoError} from '../errors';
import {withStaffAccess,displayedVersion,formResult} from './common';
import {dateDays} from '../../api/dates';
import {connectedAnnouncementsRepo} from './announcements';
import {announcementScheduledAt} from './announcement-clock';
type Workspace=ApiSchemas['ClassActivitiesWorkspace'];
type NativeActivity=ApiSchemas['ActivityWorkspaceItem'];
type Source=ApiSchemas['ActivityWorkspaceSource'];
type FileView=FileAsset & {version:number;ownerName:string;studentName?:string};
const invalid=()=>new RepoError('READ_ERROR','API chưa xác nhận đầy đủ dữ liệu hoạt động và tệp lớp.');
const uuid=(value:unknown)=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
const stamp=(value:unknown)=>typeof value==='string'&&Number.isFinite(Date.parse(value));
const text=(value:unknown)=>typeof value==='string';
const count=(value:unknown,min=0)=>typeof value==='number'&&Number.isInteger(value)&&value>=min;
function exact(value:unknown,keys:string[]){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length!==keys.length||keys.some(key=>!Object.hasOwn(value,key)))throw invalid();}
function source(a:{id:string;version:number;dataVersion?:number;publicationId?:string|null}):Source{if(!uuid(a.id)||!count(a.version,1)||!count(a.dataVersion,1)||!(a.publicationId===null||uuid(a.publicationId)))throw new RepoError('CONFLICT','Tải lại hoạt động để xác nhận đúng nguồn trước khi sửa.');return {id:a.id,version:a.version,dataVersion:a.dataVersion!,publicationId:a.publicationId!};}
function file(value:ApiSchemas['File'],schoolId:string,classId:string,share:FileShare='internal',studentId?:string):FileView{
 if(!uuid(value.id)||!uuid(value.uploadedBy)||!count(value.version,1)||!count(value.byteSize)||!text(value.originalName)||!text(value.contentType)||!stamp(value.createdAt)||!['READY','ARCHIVED','QUARANTINED','REJECTED','UPLOADING'].includes(value.status))throw invalid();
 return {id:value.id!,schoolId,classId,studentId,name:value.originalName,mime:value.contentType,size:value.byteSize,source:{kind:'staff_api',schoolId,fileId:value.id!,owner:captureStaffAccess()},ownerId:value.uploadedBy!,share,category:'document',status:value.status==='READY'?'active':value.status==='ARCHIVED'?'archived':value.status==='REJECTED'?'rejected':'processing',createdAt:value.createdAt,version:value.version,ownerName:''};
}
function activity(a:NativeActivity,w:Pick<Workspace,'schoolId'|'yearId'|'classId'|'canPublish'>,participants:Workspace['participants']):Activity{
 exact(a,['id','version','dataVersion','createdAt','updatedAt','classId','yearId','title','description','dueAt','dueDate','evidenceRequired','status','illustration','createdBy','createdByName','publicationId','publishedSourceVersion']);
 if(!uuid(a.id)||!uuid(a.createdBy)||a.classId!==w.classId||a.yearId!==w.yearId||!count(a.version,1)||!count(a.dataVersion,1)||!stamp(a.createdAt)||!stamp(a.dueAt)||!/^\d{4}-\d{2}-\d{2}$/.test(a.dueDate)||!['DRAFT','ASSIGNED','CLOSED'].includes(a.status)||!['trophy','stem','clean','book','heart'].includes(a.illustration)||typeof a.evidenceRequired!=='boolean'||!(a.publicationId===null||uuid(a.publicationId))||!(a.publishedSourceVersion===null||count(a.publishedSourceVersion,1)))throw invalid();
 return {id:a.id,schoolId:w.schoolId,classId:w.classId,title:a.title,description:a.description,illustration:a.illustration,dueDate:a.dueDate,assignedStudentIds:participants.filter(p=>p.activityId===a.id).map(p=>p.studentId),evidenceRequired:a.evidenceRequired,status:a.status==='DRAFT'?'draft':a.status==='CLOSED'?'closed':'active',publishedToParents:a.publicationId!==null,createdBy:a.createdBy,createdAt:a.createdAt,version:a.version,dataVersion:a.dataVersion,publicationId:a.publicationId,canPublish:w.canPublish};
}
const submission:Record<Workspace['participants'][number]['status'],SubmissionStatus>={ASSIGNED:'not_received',SUBMITTED:'pending_review',APPROVED:'approved',NEEDS_REVISION:'needs_supplement',EXCUSED:'received'};
export function nativeActivitiesWorkspace(w:Workspace,schoolId:string,yearId:string,classId:string){
 exact(w,['schoolId','yearId','classId','today','timezone','readOnly','canManage','canEvidence','canReview','canPublish','canReadEvidence','students','groups','activities','participants','evidence','history']);
 if(!w||w.schoolId!==schoolId||w.yearId!==yearId||w.classId!==classId||![schoolId,yearId,classId].every(uuid)||!text(w.timezone)||!/^\d{4}-\d{2}-\d{2}$/.test(w.today)||['readOnly','canManage','canEvidence','canReview','canPublish','canReadEvidence'].some(key=>typeof w[key as keyof Workspace]!=='boolean')||w.readOnly&&(w.canManage||w.canEvidence||w.canReview||w.canPublish)||!Array.isArray(w.activities)||!Array.isArray(w.participants)||!Array.isArray(w.students)||!Array.isArray(w.groups)||!Array.isArray(w.history)||w.canReadEvidence!==(w.evidence!==null))throw invalid();
 for(const [rows,maximum] of [[w.activities,1000],[w.participants,10000],[w.students,5000],[w.groups,100],[w.history,2000],[w.evidence??[],10000]] as const)if(rows.length>maximum||new Set(rows.map(r=>r.id)).size!==rows.length||rows.some(r=>!uuid(r.id)))throw invalid();
 for(const s of w.students){exact(s,['id','enrollmentId','fullName','code','groupId','groupName']);if(!uuid(s.enrollmentId)||!text(s.fullName)||!text(s.code)||!(s.groupId===null&&s.groupName===null||w.groups.some(g=>g.id===s.groupId&&g.name===s.groupName)))throw invalid();}
 for(const g of w.groups){exact(g,['id','name','size']);if(!text(g.name)||!count(g.size))throw invalid();}
 for(const p of w.participants){exact(p,['id','version','activityId','enrollmentId','studentId','fullName','code','status','reviewNote','updatedAt','stillEnrolled','groupName']);if(!w.activities.some(a=>a.id===p.activityId)||!uuid(p.enrollmentId)||!uuid(p.studentId)||!count(p.version,1)||!Object.hasOwn(submission,p.status)||!text(p.fullName)||!text(p.code)||!stamp(p.updatedAt)||typeof p.stillEnrolled!=='boolean'||!w.canReadEvidence&&p.reviewNote!==null)throw invalid();}
 const participants=w.participants.map(p=>({...p,status:submission[p.status],note:p.reviewNote??undefined,groupName:p.groupName??undefined,code:p.code}));
 const activities=w.activities.map(a=>({...activity(a,w,w.participants),createdByName:a.createdByName??'Nhân sự đã kết thúc',publishedSourceVersion:a.publishedSourceVersion}));
 const evidence=(w.evidence??[]).map(e=>{
  exact(e,['id','version','participantId','activityId','studentId','fileId','submittedBy','uploadedByName','createdAt','status','caption','reviewReason','shareWithGuardian','file']);
  const p=w.participants.find(p=>p.id===e.participantId);if(!p||p.activityId!==e.activityId||p.studentId!==e.studentId||!count(e.version,1)||!uuid(e.submittedBy)||!stamp(e.createdAt)||e.fileId!==e.file.id||typeof e.shareWithGuardian!=='boolean'||e.shareWithGuardian&&e.status!=='APPROVED'||!['SUBMITTED','APPROVED','NEEDS_REVISION','REJECTED'].includes(e.status))throw invalid();
  const f=file(e.file,schoolId,classId,e.shareWithGuardian?'student_parent':'internal',e.studentId);f.category='evidence';
  return {id:e.id,version:e.version,schoolId,classId,activityId:e.activityId,studentId:e.studentId,fileId:e.fileId,uploadedBy:e.submittedBy,uploadedAt:e.createdAt,status:({SUBMITTED:'pending',APPROVED:'approved',NEEDS_REVISION:'supplement',REJECTED:'rejected'} as const)[e.status],reviewNote:e.reviewReason??e.caption??undefined,sharedWithParent:e.shareWithGuardian,file:f,studentName:p.fullName,activityTitle:activities.find(a=>a.id===e.activityId)!.title,uploadedByName:e.uploadedByName??'Nhân sự đã kết thúc'};
 });
 const history=w.history.map(h=>{if(!stamp(h.at)||!uuid(h.actorId)||!uuid(h.entityId)||!(h.activityId===null||activities.some(a=>a.id===h.activityId))||!w.canReadEvidence&&(h.entityType!=='activity'||h.reason!==null))throw invalid();return {...h,action:({createActivity:'Tạo hoạt động',updateActivity:'Sửa hoạt động',assignActivity:'Giao hoạt động',publishActivity:'Công bố hoạt động',createEvidence:'Ghi nhận minh chứng',reviewEvidence:'Duyệt minh chứng',setParticipantStatus:'Cập nhật tình trạng học sinh'} as Record<string,string>)[h.action]??h.action,actorName:h.actorName??'Nhân sự đã kết thúc',reason:h.reason??undefined,entityLabel:activities.find(a=>a.id===h.activityId)?.title??'Minh chứng hoạt động'};});
 return {...w,activities,participants,evidence,history};
}
async function read(s:string,y:string,c:string){return nativeActivitiesWorkspace((await http('getClassActivitiesWorkspace',{params:{schoolId:s,yearId:y,classId:c}})).data,s,y,c);}
function progress(w:ReturnType<typeof nativeActivitiesWorkspace>,id:string){const rows=w.participants.filter(p=>p.activityId===id),total=rows.length;return {total,approved:rows.filter(p=>p.status==='approved').length,pending:rows.filter(p=>p.status==='pending_review').length,received:rows.filter(p=>p.status==='received').length,supplement:rows.filter(p=>p.status==='needs_supplement').length,notReceived:rows.filter(p=>p.status==='not_received').length};}
const matches=(q:string,...text:string[])=>text.join(' ').toLocaleLowerCase('vi').includes(q.toLocaleLowerCase('vi'));
function detail(w:ReturnType<typeof nativeActivitiesWorkspace>,id:string){const a=w.activities.find(a=>a.id===id);if(!a)throw new RepoError('NOT_FOUND');return {activity:a,progress:progress(w,id),students:w.participants.filter(p=>p.activityId===id).map(p=>({...p,id:p.studentId,participantId:p.id,evidence:w.evidence.filter(e=>e.studentId===p.studentId&&e.activityId===id)})),groupName:undefined as string|undefined,createdByName:a.createdByName,history:w.history.filter(h=>h.activityId===id),canManage:w.canManage,canEvidence:w.canEvidence&&w.canReview,canReadEvidence:w.canReadEvidence,canPublish:w.canPublish};}
const uploaded=new WeakMap<Blob,{s:string;c:string;purpose:string;id:string;owner:ReturnType<typeof captureStaffAccess>;linkVersion?:number;linked?:boolean}>();
async function upload(s:string,c:string,input:{name:string;type:string;size:number;blob:Blob},purpose:'EVIDENCE'|'CLASS_DOCUMENT'){
 if(input.size!==input.blob.size||!input.size||input.size>5*1024*1024)throw new RepoError('VALIDATION','Tệp rỗng hoặc vượt giới hạn 5 MB.',{fieldErrors:{file:'Kiểm tra dung lượng tệp.'}});
 let state=uploaded.get(input.blob);if(state){state.owner.assertCurrent();if(state.s!==s||state.c!==c||state.purpose!==purpose)throw new RepoError('CONFLICT','Tệp đã được gửi trong phạm vi khác. Chọn lại tệp để xác nhận.');}
 else{const form=new FormData();form.append('purpose',purpose);form.append('classId',c);form.append('file',input.blob,input.name);const value=(await http('uploadFile',{params:{schoolId:s},multipart:form})).data;if(!uuid(value.id))throw invalid();state={s,c,purpose,id:value.id!,owner:captureStaffAccess()};uploaded.set(input.blob,state);}
 for(let attempt=0;attempt<40;attempt++){state.owner.assertCurrent();const value=(await http('getFile',{params:{schoolId:s,fileId:state.id}})).data;if(value.id!==state.id)throw invalid();if(value.status==='READY')return {value,state};if(value.status==='REJECTED')throw new RepoError('VALIDATION',`Máy chủ từ chối tệp (${value.rejectionCode??'FILE_REJECTED'}).`,{fieldErrors:{file:'Tệp không vượt qua kiểm tra định dạng/nội dung.'}});if(!['UPLOADING','QUARANTINED'].includes(value.status))throw new RepoError('CONFLICT','Tệp không còn sẵn sàng để gắn vào hoạt động.');await new Promise(resolve=>setTimeout(resolve,750));}
 throw new RepoError('NETWORK','Tệp đã được tải lên và đang kiểm tra. Giữ tệp đã chọn rồi thử lại; yêu cầu sẽ dùng đúng tệp đã gửi.');
}
function nativeFiles(w:ApiSchemas['ClassFilesWorkspace'],s:string,y:string,c:string){if(w.schoolId!==s||w.yearId!==y||w.classId!==c||typeof w.readOnly!=='boolean'||!Array.isArray(w.files)||new Set(w.files.map(f=>f.id)).size!==w.files.length)throw invalid();return w.files.map(f=>{if(!['internal','class_parents','student_parent'].includes(f.share)||f.share==='student_parent'&&!uuid(f.studentId)||!(f.studentId===null||uuid(f.studentId)))throw invalid();return {...file(f,s,c,f.share,f.studentId??undefined),ownerName:f.ownerName??'Nhân sự đã kết thúc',studentName:f.studentName??undefined};});}
export const connectedActivitiesRepo=withStaffAccess({
 async list(_ctx:Ctx,s:ID,y:ID,c:ID,opts:{status?:string;q?:string}={}){const w=await read(s,y,c),all=w.activities.filter(a=>a.status!=='draft');return {items:w.activities.filter(a=>(!opts.status||a.status===opts.status||opts.status==='due'&&a.status==='active'&&a.dueDate<=w.today)&&matches(opts.q??'',a.title,a.description)).map(a=>({...a,progress:progress(w,a.id),groupName:undefined as string|undefined,dueSoon:a.status==='active'&&a.dueDate>=w.today&&a.dueDate<=dateDays(w.today,7),overdue:a.status==='active'&&a.dueDate<w.today})),totals:all.reduce((sum,a)=>{const p=progress(w,a.id);return {total:sum.total+p.total,approved:sum.approved+p.approved,notReceived:sum.notReceived+p.notReceived};},{total:0,approved:0,notReceived:0}),pendingEvidence:w.evidence.filter(e=>e.status==='pending').length,recent:w.history.slice(0,6),canManage:w.canManage,canEvidence:w.canEvidence&&w.canReview,canReadEvidence:w.canReadEvidence};},
 async detail(_ctx:Ctx,s:ID,y:ID,c:ID,id:ID){return detail(await read(s,y,c),id);},
 async formOptions(_ctx:Ctx,s:ID,y:ID,c:ID){const w=await read(s,y,c);return {students:w.students.map(st=>({...st,groupId:st.groupId??undefined})),groups:w.groups,today:w.today};},
 async save(_ctx:Ctx,s:ID,y:ID,c:ID,input:{id?:ID;title:string;description:string;illustration:Activity['illustration'];dueDate:string;assignedStudentIds:ID[];assignedGroupId?:ID;evidenceRequired:boolean;publish:boolean;version?:number;dataVersion?:number;publicationId?:string|null}){
  const w=await read(s,y,c),selected=input.assignedStudentIds.map(id=>{const student=w.students.find(st=>st.id===id);if(!student)throw new RepoError('VALIDATION','Có học sinh không còn thuộc lớp.',{fieldErrors:{assignedStudentIds:'Tải lại danh sách được giao.'}});return student.enrollmentId;});
  const old=input.id?source({id:input.id,version:displayedVersion(input.version),dataVersion:input.dataVersion,publicationId:input.publicationId}):null;
  const end=await formResult(http('saveActivityWorkspace',{params:{schoolId:s,yearId:y,classId:c},body:{source:old,action:input.publish?'assign':old?'save':'draft',input:{title:input.title.trim(),description:input.description.trim(),illustration:input.illustration,dueAt:announcementScheduledAt(w.timezone,input.dueDate,'23:59'),evidenceRequired:input.evidenceRequired,enrollmentIds:selected}}}),{dueAt:'dueDate',enrollmentIds:'assignedStudentIds'});
  const fresh=await read(s,y,c),a=detail(fresh,end.data.id).activity;return a;
 },
 async setActivityStatus(_ctx:Ctx,s:ID,y:ID,c:ID,id:ID,status:'active'|'closed',expected:Source){const result=await http('saveActivityWorkspace',{params:{schoolId:s,yearId:y,classId:c},body:{source:source(expected),action:status==='closed'?'close':'reopen'}});if(result.data.id!==id)throw invalid();return detail(await read(s,y,c),id).activity;},
 async assign(_ctx:Ctx,s:ID,y:ID,c:ID,a:Activity){const w=await read(s,y,c),selected=w.participants.filter(p=>p.activityId===a.id).map(p=>p.enrollmentId);await http('saveActivityWorkspace',{params:{schoolId:s,yearId:y,classId:c},body:{source:source(a),action:'assign',input:{title:a.title,description:a.description,dueAt:announcementScheduledAt(w.timezone,a.dueDate,'23:59'),illustration:a.illustration,evidenceRequired:a.evidenceRequired,enrollmentIds:selected}}});return detail(await read(s,y,c),a.id).activity;},
 async publish(_ctx:Ctx,s:ID,y:ID,c:ID,a:Activity){await http('saveActivityWorkspace',{params:{schoolId:s,yearId:y,classId:c},body:{source:source(a),action:'publish'}});return detail(await read(s,y,c),a.id).activity;},
 async addEvidence(_ctx:Ctx,s:ID,y:ID,c:ID,input:{activityId:ID;studentId:ID;file:{name:string;type:string;size:number;blob:Blob};note?:string}){const w=await read(s,y,c),p=w.participants.find(p=>p.activityId===input.activityId&&p.studentId===input.studentId);if(!p||!p.stillEnrolled)throw new RepoError('VALIDATION','Học sinh không còn được giao hoạt động này.');const received=await upload(s,c,input.file,'EVIDENCE');return formResult(http('createEvidence',{params:{schoolId:s,classId:c},body:{participantId:p.id,fileId:received.value.id!,caption:input.note,shareWithGuardian:false}}).then(r=>r.data),{caption:'note'});},
 async setSubmission(_ctx:Ctx,s:ID,y:ID,c:ID,input:{activityId:ID;studentIds:ID[];status:SubmissionStatus;note?:string;versions:Record<string,{id:string;version:number}>}){const map:Record<SubmissionStatus,ApiSchemas['ParticipantBatchCommand']['status']>={not_received:'ASSIGNED',received:'EXCUSED',pending_review:'SUBMITTED',approved:'APPROVED',needs_supplement:'NEEDS_REVISION'};const items=input.studentIds.map(id=>{const p=input.versions[id];if(!p||!uuid(p.id))throw new RepoError('CONFLICT','Tải lại tình trạng học sinh trước khi sửa.');return {id:p.id,expectedVersion:displayedVersion(p.version)};});return formResult(http('setActivityParticipantStatuses',{params:{schoolId:s,yearId:y,classId:c},body:{activityId:input.activityId,items,status:map[input.status],reason:input.note?.trim()||'Giáo viên cập nhật tình trạng hoạt động'}}).then(r=>r.data.count),{reason:'note'});},
 async reviewEvidence(_ctx:Ctx,s:ID,y:ID,c:ID,input:{evidenceIds:ID[];decision:'approved'|'rejected'|'supplement';note?:string;shareWithParent:boolean;versions:Record<string,number>}){const items=input.evidenceIds.map(id=>({id,expectedVersion:displayedVersion(input.versions[id])}));return formResult(http('reviewEvidenceBatch',{params:{schoolId:s,yearId:y,classId:c},body:{items,decision:({approved:'APPROVED',rejected:'REJECTED',supplement:'NEEDS_REVISION'} as const)[input.decision],reason:input.note?.trim()||'Giáo viên xác nhận minh chứng hợp lệ',shareWithGuardian:input.decision==='approved'&&input.shareWithParent}}).then(r=>r.data.count),{reason:'note'});},
 async evidence(_ctx:Ctx,s:ID,y:ID,c:ID,opts:{status?:string;activityId?:ID;q?:string}={}){const w=await read(s,y,c);if(!w.canReadEvidence)throw new RepoError('FORBIDDEN');return {items:w.evidence.filter(e=>(!opts.status||e.status===opts.status)&&(!opts.activityId||e.activityId===opts.activityId)&&matches(opts.q??'',e.studentName,e.activityTitle)),activities:w.activities.filter(a=>a.status==='active').map(a=>({id:a.id,title:a.title,assigned:a.assignedStudentIds})),students:w.students.map(s=>({id:s.id,fullName:s.fullName})),canManage:w.canEvidence&&w.canReview};},
 async files(_ctx:Ctx,s:ID,y:ID,c:ID,opts:{share?:string;status?:string;q?:string}={}){const files=nativeFiles((await http('getClassFilesWorkspace',{params:{schoolId:s,yearId:y,classId:c}})).data,s,y,c);return files.filter(f=>(!opts.share||f.share===opts.share)&&(!opts.status||f.status===opts.status)&&matches(opts.q??'',f.name));},
 async fileFormOptions(_ctx:Ctx,s:ID,y:ID,c:ID){const value=(await http('getClassFilesWorkspace',{params:{schoolId:s,yearId:y,classId:c}})).data;nativeFiles(value,s,y,c);if(!Array.isArray(value.students)||new Set(value.students.map(st=>st.id)).size!==value.students.length||value.students.some(st=>!uuid(st.id)||!text(st.fullName)))throw invalid();return {students:value.students};},
 async uploadFile(_ctx:Ctx,s:ID,y:ID,c:ID,input:{file:{name:string;type:string;size:number;blob:Blob};share:FileShare;studentId?:ID}){const received=await upload(s,c,input.file,'CLASS_DOCUMENT');if(received.state.linked){const result=nativeFiles((await http('getClassFilesWorkspace',{params:{schoolId:s,yearId:y,classId:c}})).data,s,y,c).find(f=>f.id===received.state.id);if(!result)throw invalid();return result;}received.state.linkVersion??=received.value.version;const result=await http('updateClassFile',{params:{schoolId:s,yearId:y,classId:c,fileId:received.state.id},body:{expectedVersion:received.state.linkVersion,share:input.share,studentId:input.studentId}});received.state.linked=true;return {...file(result.data,s,c,result.data.share,result.data.studentId??undefined),ownerName:result.data.ownerName??'Nhân sự đã kết thúc',studentName:result.data.studentName??undefined};},
 async updateFile(_ctx:Ctx,s:ID,y:ID,c:ID,id:ID,patch:{share?:FileShare;status?:FileAsset['status'];studentId?:ID;version:number}){if(patch.status&&!['active','archived'].includes(patch.status))throw new RepoError('VALIDATION','Trạng thái tệp không hợp lệ.');const value=(await http('updateClassFile',{params:{schoolId:s,yearId:y,classId:c,fileId:id},body:{expectedVersion:displayedVersion(patch.version),share:patch.share,studentId:patch.studentId,status:patch.status as 'active'|'archived'|undefined}})).data;return {...file(value,s,c,value.share,value.studentId??undefined),ownerName:value.ownerName??'Nhân sự đã kết thúc',studentName:value.studentName??undefined};},
});
export const connectedActivitiesExtraRepo=withStaffAccess({
 async recentFeed(_ctx:Ctx,s:ID,y:ID,c:ID,limit=6){const w=await read(s,y,c);return w.history.slice(0,limit).map(h=>({id:h.id,at:h.at,kind:h.entityType==='evidence'?'evidence' as const:'activity' as const,actor:h.actorName,text:h.action,detail:h.entityLabel,href:h.activityId?`activities/${h.activityId}`:'evidence'}));},
 async announcementsPanel(ctx:Ctx,s:ID,y:ID,c:ID){const w=await read(s,y,c);const list=await connectedAnnouncementsRepo.classList(ctx,s,y,c);const monday=dateDays(w.today,-((new Date(w.today+'T00:00:00Z').getUTCDay()+6)%7)),previous=dateDays(monday,-7);return {thisWeek:list.own.filter(a=>a.status==='published'&&a.publishedAt&&a.publishedAt.slice(0,10)>=monday).length,lastWeek:list.own.filter(a=>a.status==='published'&&a.publishedAt&&a.publishedAt.slice(0,10)>=previous&&a.publishedAt.slice(0,10)<monday).length,upcoming:list.own.filter(a=>a.status==='draft'||a.status==='scheduled').map(a=>({...a,scopeLabel:a.scopeLabel,audienceLabel:a.audienceLabel}))};},
});
