import type {ApiSchemas} from '../../api/generated';
import type {AnnouncementScope,Announcement} from '../../model/types';
import type {Ctx,ListQuery} from '../core';
import {http,captureStaffAccess} from '../../api/client';
import {apiPage} from '../../api/lists';
import {withStaffAccess} from './common';
import {RepoError} from '../errors';
import type {StaffFileSource} from '@/components/ui/file';
type Native=ApiSchemas['AnnouncementWorkspaceItem'];
type Source=ApiSchemas['AnnouncementWorkspaceSource'];
const invalid=()=>new RepoError('READ_ERROR','API chưa xác nhận đầy đủ dữ liệu thông báo.');
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v),num=(v:unknown,min=0)=>typeof v==='number'&&Number.isInteger(v)&&v>=min,text=(v:unknown)=>typeof v==='string',stamp=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const nullable=(v:unknown)=>v===null||text(v);
function exact(v:unknown,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))throw invalid();}
export function announcementSource(v:Source){exact(v,['id','rootId','yearId','classId','version','dataVersion','publicationId']);if(![v.id,v.rootId,v.yearId].every(uuid)||!(v.classId===null||uuid(v.classId))||!num(v.version,1)||!num(v.dataVersion,1)||!(v.publicationId===null||uuid(v.publicationId)))throw invalid();return v;}
function cleanScope(s:AnnouncementScope){if(s.type==='school')return {type:'school' as const};const type=s.type,key=type==='grade'?'gradeIds':type==='class'?'classIds':'studentIds',ids=s[key];if(!['grade','class','student'].includes(type)||!Array.isArray(ids)||!ids.length||!ids.every(uuid)||new Set(ids).size!==ids.length)throw new RepoError('VALIDATION','Chọn người nhận thông báo.',{fieldErrors:{scope:'Chọn ít nhất một đối tượng nhận.'}});return {type,[key]:ids} as ApiSchemas['AnnouncementAudienceInput']['scope'];}
function estimate(v:NonNullable<Native['estimate']>){exact(v,['students','activeLinks','staff']);if(!num(v.students)||!(v.activeLinks===null||num(v.activeLinks))||!num(v.staff))throw invalid();return v;}
export function nativeAnnouncement(v:Native,schoolId:string,yearId?:string,classId?:string){
 exact(v,['schoolId','id','rootId','yearId','yearVersion','classVersion','origin','originClassId','className','title','summary','body','audience','scope','scopeLabel','audienceLabel','isPublic','status','createdAt','updatedAt','createdByName','scheduledAt','publishedAt','withdrawnAt','withdrawReason','internalNote','version','source','canEdit','canPublish','canViewInternal','canWithdraw','canDelete','readOnly','scheduleState','scheduleErrorCode','estimate','attachmentIds','attachments','historyView']);announcementSource(v.source);
 if(v.schoolId!==schoolId||!uuid(schoolId)||v.yearId!==v.source.yearId||v.id!==v.source.id||v.rootId!==v.source.rootId||v.version!==v.source.version||v.originClassId!==v.source.classId||yearId!==undefined&&v.yearId!==yearId||classId!==undefined&&v.originClassId!==null&&v.originClassId!==classId||!num(v.yearVersion,1)||!(v.classVersion===null||num(v.classVersion,1))||(v.origin==='class')!==(v.originClassId!==null)||!['school','class'].includes(v.origin)||!['draft','scheduled','published','withdrawn'].includes(v.status)||!['all','staff','families'].includes(v.audience)||![v.title,v.summary,v.scopeLabel,v.audienceLabel].every(text)||![v.className,v.createdByName,v.withdrawReason,v.internalNote,v.scheduleState,v.scheduleErrorCode].every(nullable)||![v.createdAt,v.updatedAt].every(stamp)||![v.scheduledAt,v.publishedAt,v.withdrawnAt].every(x=>x===null||stamp(x))||['canEdit','canPublish','canViewInternal','canWithdraw','canDelete','readOnly','isPublic'].some(k=>typeof v[k as keyof Native]!=='boolean')||v.readOnly&&(v.canEdit||v.canPublish||v.canDelete||v.canWithdraw))throw invalid();
 if(v.scope.type==='mixed'){exact(v.scope,['type','targets']);if(!Array.isArray(v.scope.targets)||!v.scope.targets.length||v.canEdit)throw invalid();for(const t of v.scope.targets)if(!['SCHOOL','PUBLIC','GRADE','CLASS','STUDENT','STAFF'].includes(t.kind)||!['SCHOOL','PUBLIC'].includes(t.kind)&&!uuid(t.id))throw invalid();}else{const normalized=cleanScope(v.scope);if(JSON.stringify(normalized)!==JSON.stringify(v.scope))throw invalid();}
 if(!Array.isArray(v.body)||!v.body.length||v.body.length>500||!Array.isArray(v.attachments)||v.attachments.length>100||!Array.isArray(v.attachmentIds)||new Set(v.attachmentIds).size!==v.attachmentIds.length||v.attachmentIds.length!==v.attachments.length)throw invalid();for(const b of v.body){exact(b,['type','text']);if(!['p','h','li'].includes(b.type)||!text(b.text)||!b.text.trim()||b.text.length>50000)throw invalid();}
 for(const f of v.attachments){exact(f,['id','version','name','mime','size','canDownload']);if(!uuid(f.id)||!num(f.version,1)||!text(f.name)||!text(f.mime)||!num(f.size)||typeof f.canDownload!=='boolean'||!v.attachmentIds.includes(f.id))throw invalid();}if(new Set(v.attachments.map(f=>f.id)).size!==v.attachments.length)throw invalid();
 if(!v.canViewInternal&&(v.internalNote!==null||v.historyView!==null||v.estimate!==null))throw invalid();if(v.estimate!==null)estimate(v.estimate);if(v.historyView!==null){if(!Array.isArray(v.historyView)||v.historyView.length>2000)throw invalid();for(const h of v.historyView){exact(h,['id','at','action','byName','reason']);if(!uuid(h.id)||!stamp(h.at)||!text(h.action)||!nullable(h.byName)||!nullable(h.reason))throw invalid();}if(new Set(v.historyView.map(h=>h.id)).size!==v.historyView.length)throw invalid();}
 const owner=captureStaffAccess();return {...v,originClassId:v.originClassId??undefined,className:v.className??undefined,createdByName:v.createdByName??undefined,internalNote:v.internalNote??undefined,scheduledAt:v.scheduledAt??undefined,publishedAt:v.publishedAt??undefined,withdrawnAt:v.withdrawnAt??undefined,withdrawReason:v.withdrawReason??undefined,attachments:v.attachments.map(f=>({...f,source:f.canDownload?{kind:'staff_api',schoolId,fileId:f.id,owner} as StaffFileSource:undefined})),historyView:v.historyView?.map(h=>({...h,byName:h.byName??undefined,reason:h.reason??undefined}))??null};
}
export type AnnouncementView=ReturnType<typeof nativeAnnouncement>;
function directory(v:ApiSchemas['AnnouncementDirectory'],s:string,y?:string,c?:string){exact(v,['schoolId','yearId','classId','today','items','counts','canCompose']);exact(v.counts,['draft','scheduled','published','withdrawn']);if(v.schoolId!==s||v.yearId!==(y??null)||v.classId!==(c??null)||!/^\d{4}-\d{2}-\d{2}$/.test(v.today)||!Object.values(v.counts).every(n=>num(n))||typeof v.canCompose!=='boolean'||!Array.isArray(v.items)||v.items.length>100)throw invalid();const items=v.items.map(a=>nativeAnnouncement(a,s,y,c));if(new Set(items.map(a=>a.id)).size!==items.length)throw invalid();return {...v,items};}
function receipt(v:ApiSchemas['AnnouncementWorkspaceReceipt'],source?:Source){exact(v,['id','rootId','status','source']);if(!uuid(v.id)||!uuid(v.rootId)||source&&v.rootId!==source.rootId||!['draft','scheduled','published','withdrawn','discarded'].includes(v.status))throw invalid();if(v.source!==null){announcementSource(v.source);if(v.id!==v.source.id||v.rootId!==v.source.rootId)throw invalid();}else if(!['withdrawn','discarded'].includes(v.status))throw invalid();return v;}
export function announcementEstimateLine(v:Native['estimate'],audience:Native['audience']){if(v===null)return 'Không có quyền xem ước tính người nhận';if(audience==='staff')return `${v.staff.toLocaleString('vi-VN')} nhân sự`;return `${v.students.toLocaleString('vi-VN')} gia đình học sinh${v.activeLinks===null?'':` · ${v.activeLinks.toLocaleString('vi-VN')} link đang hiệu lực`}${v.staff?` · ${v.staff.toLocaleString('vi-VN')} nhân sự`:''}`;}
export const connectedAnnouncementsRepo=withStaffAccess({
 async schoolList(_ctx:Ctx,s:string,q:ListQuery){let meta:ReturnType<typeof directory>|undefined;const result=await apiPage('getAnnouncementDirectory',{params:{schoolId:s},query:{q:q.q,status:q.filters?.status,origin:q.filters?.origin}},q,(v:AnnouncementView)=>v,v=>{meta=directory(v,s);return meta.items;});if(!meta)throw invalid();return {...result,counts:meta.counts,canCompose:meta.canCompose};},
 async classList(_ctx:Ctx,s:string,y:string,c:string){const own:AnnouncementView[]=[],fromSchool:AnnouncementView[]=[],seen=new Set<string>();let cursor:string|undefined,canCompose=false;for(let n=0;n<100;n++){const result=await http('getClassAnnouncementDirectory',{params:{schoolId:s,yearId:y,classId:c},query:{limit:100,cursor}}),value=directory(result.data,s,y,c),p=result.page;if(!p||!num(p.limit,1)||p.limit>100||typeof p.hasMore!=='boolean'||!Array.isArray(value.items)||value.items.length>p.limit||!(p.nextCursor===null||text(p.nextCursor))||p.hasMore!==(p.nextCursor!==null))throw invalid();canCompose=value.canCompose;for(const a of value.items){if(seen.has(a.id)||seen.size>=10000)throw invalid();seen.add(a.id);if(a.originClassId===c)own.push(a);else{if(a.origin!=='school'||a.status!=='published')throw invalid();fromSchool.push(a);}}if(!p.hasMore)return {own,fromSchool,canCompose};if(!p.nextCursor||seen.has(p.nextCursor))throw invalid();cursor=p.nextCursor;}throw invalid();},
 async detail(_ctx:Ctx,s:string,id:string,bound?:{yearId:string;classId:string}){const v=nativeAnnouncement((await http('getAnnouncementWorkspaceDetail',{params:{schoolId:s,announcementId:id},query:bound})).data,s,bound?.yearId,bound?.classId);if(v.id!==id)throw invalid();return v;},
 async composeOptions(_ctx:Ctx,s:string,c?:string,y?:string){const v=(await http('getAnnouncementComposeWorkspace',{params:{schoolId:s},query:{classId:c,yearId:y}})).data;exact(v,['schoolId','yearId','classId','timezone','today','serverNow','yearVersion','classVersion','readOnly','canPublish','canSelectStudents','grades','classes','students','files']);if(v.schoolId!==s||v.classId!==(c??null)||y!==undefined&&v.yearId!==y||!uuid(v.yearId)||!num(v.yearVersion,1)||!(v.classVersion===null||num(v.classVersion,1))||!text(v.timezone)||!v.timezone||!stamp(v.serverNow)||!/^\d{4}-\d{2}-\d{2}$/.test(v.today)||[v.canPublish,v.canSelectStudents,v.readOnly].some(x=>typeof x!=='boolean'))throw invalid();for(const list of [v.grades,v.classes,v.students,v.files])if(!Array.isArray(list)||new Set(list.map(x=>x.id)).size!==list.length||list.some(x=>!uuid(x.id)))throw invalid();for(const f of v.files){exact(f,['id','name','mime','size','version','share']);if(!text(f.name)||!text(f.mime)||!num(f.size)||!num(f.version,1)||!['school_parent','class_parent','student_parent'].includes(f.share))throw invalid();}return v;},
 async estimate(_ctx:Ctx,s:string,scope:AnnouncementScope,audience:Announcement['audience'],options:{yearId:string;classId?:string;isPublic:boolean}){const body={yearId:options.yearId,classId:options.classId??null,scope:cleanScope(scope),audience,isPublic:options.isPublic},v=(await http('estimateAnnouncementAudience',{params:{schoolId:s},body})).data;exact(v,['schoolId','yearId','classId','scope','audience','isPublic','counts']);if(v.schoolId!==s||v.yearId!==body.yearId||v.classId!==body.classId||JSON.stringify(v.scope)!==JSON.stringify(body.scope)||v.audience!==body.audience||v.isPublic!==body.isPublic)throw invalid();return estimate(v.counts);},
 async save(_ctx:Ctx,s:string,input:{source:Source|null;yearId:string;yearVersion:number;classVersion:number|null;origin:'school'|'class';originClassId?:string;title:string;summary:string;body:Announcement['body'];audience:Announcement['audience'];scope:AnnouncementScope;isPublic:boolean;attachmentIds:string[];internalNote?:string;action:'draft'|'publish'|'schedule';scheduledAt?:string}){if(input.source)announcementSource(input.source);const body={source:input.source,yearId:input.yearId,classId:input.origin==='class'?input.originClassId!:null,expectedYearVersion:input.yearVersion,expectedClassVersion:input.classVersion,title:input.title.trim(),summary:input.summary.trim(),body:input.body,audience:input.audience,scope:cleanScope(input.scope),isPublic:input.isPublic,attachmentIds:input.attachmentIds,internalNote:input.internalNote,action:input.action,scheduledAt:input.scheduledAt};return receipt((await http('saveAnnouncementWorkspace',{params:{schoolId:s},body})).data,input.source??undefined);},
 async publish(_ctx:Ctx,s:string,source:Source){announcementSource(source);return receipt((await http('publishAnnouncementWorkspace',{params:{schoolId:s},body:{source}})).data,source);},
 async withdraw(_ctx:Ctx,s:string,source:Source,reason:string){announcementSource(source);return receipt((await http('withdrawAnnouncementWorkspace',{params:{schoolId:s},body:{source,reason}})).data,source);},
 async deleteDraft(_ctx:Ctx,s:string,source:Source){announcementSource(source);return receipt((await http('discardAnnouncementWorkspace',{params:{schoolId:s},body:{source}})).data,source);},
});
