import type {ApiSchemas} from '../../api/generated';
import type {AttendanceStatus} from '../../model/types';
import type {Ctx} from '../core';
import {http} from '../../api/client';
import {withStaffAccess} from './common';
import {RepoError} from '../errors';
import {addDays,mondayOf} from '../../calendar';

const invalid=()=>new RepoError('READ_ERROR','API chưa xác nhận đầy đủ dữ liệu điểm danh trong lớp.');
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const date=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
const text=(v:unknown)=>typeof v==='string'&&!!v.trim(),nullable=(v:unknown)=>v===null||text(v),integer=(v:unknown,min=0)=>typeof v==='number'&&Number.isInteger(v)&&v>=min;
const statuses=['PRESENT','LATE','EXCUSED','UNEXCUSED','UNMARKED'] as const,states=['none','open','published','locked'];
const stamp=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const slotValid=(v:unknown)=>typeof v==='string'&&/^(morning|afternoon|period-[1-9][0-9]*|lesson-[0-9a-fA-F-]{36})$/.test(v);
function exact(v:unknown,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))throw invalid();}
function scope(v:{schoolId:string;yearId:string;classId:string},s:string,y:string,c:string){if(![s,y,c].every(uuid)||v.schoolId!==s||v.yearId!==y||v.classId!==c)throw invalid();}
export function attendanceSource(v:ApiSchemas['ClassAttendanceSource']){
 exact(v,['classVersion','rosterHash','sessionId','version','dataVersion','publicationId']);if(!integer(v.classVersion,1)||!/^[0-9a-f]{64}$/.test(v.rosterHash)||!(v.sessionId===null||uuid(v.sessionId))||!(v.version===null||integer(v.version,1))||!(v.dataVersion===null||integer(v.dataVersion,1))||!(v.publicationId===null||uuid(v.publicationId))||v.sessionId===null&&(v.version!==null||v.dataVersion!==null||v.publicationId!==null)||v.sessionId!==null&&(v.version===null||v.dataVersion===null))throw invalid();return v;
}
function lesson(v:ApiSchemas['ClassAttendanceSheet']['lessons'][number]){exact(v,['id','period','subject','start','end','status']);const time=(s:string)=>/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test(s);if(!uuid(v.id)||!(v.period===null||integer(v.period,1))||!text(v.subject)||!time(v.start)||!time(v.end)||v.end<=v.start||!['SCHEDULED','CANCELLED','REPLACED'].includes(v.status))throw invalid();}
function linked(v:NonNullable<ApiSchemas['ClassAttendanceSheet']['rows'][number]['linkedConduct']>){exact(v,['id','points','status']);if(!uuid(v.id)||typeof v.points!=='number'||!Number.isFinite(v.points)||!['DRAFT','APPROVED','EXCLUDED'].includes(v.status))throw invalid();}
function tally(v:ApiSchemas['ClassAttendanceSheet']['counts']){exact(v,[...statuses]);if(statuses.some(k=>!integer(v[k])))throw invalid();return Object.fromEntries(statuses.map(k=>[k.toLowerCase(),v[k]])) as Record<AttendanceStatus,number>;}
function nativeWeek(v:ApiSchemas['ClassAttendanceSheet']['week']){if(v!==null){exact(v,['id','index']);if(!uuid(v.id)||!integer(v.index,1))throw invalid();}}
export function nativeAttendanceSlots(v:ApiSchemas['ClassAttendanceSlots'],s:string,y:string,c:string,d:string){
 exact(v,['schoolId','yearId','classId','date','slots']);scope(v,s,y,c);if(v.date!==d||!date(v.date)||!Array.isArray(v.slots)||v.slots.length>102)throw invalid();for(const x of v.slots){exact(x,['slot','label','canRecord']);if(!slotValid(x.slot)||!text(x.label)||typeof x.canRecord!=='boolean')throw invalid();}if(new Set(v.slots.map(x=>x.slot)).size!==v.slots.length)throw invalid();return v.slots;
}
export function nativeAttendanceSheet(v:ApiSchemas['ClassAttendanceSheet'],s:string,y:string,c:string,d:string,slot:string){
 exact(v,['schoolId','yearId','classId','date','slot','today','className','source','session','sessionStatus','rows','counts','lessons','lesson','canRecord','canPublish','canLink','holiday','isSunday','updatedByName','week','periodLocked','linkRules']);scope(v,s,y,c);attendanceSource(v.source);
 if(v.date!==d||v.slot!==slot||!date(d)||!slotValid(slot)||!date(v.today)||!text(v.className)||!states.includes(v.sessionStatus)||!Array.isArray(v.rows)||v.rows.length>5000||!Array.isArray(v.lessons)||v.lessons.length>100||!nullable(v.holiday)||!nullable(v.updatedByName)||['canRecord','canPublish','canLink','isSunday','periodLocked'].some(k=>typeof v[k as keyof typeof v]!=='boolean')||v.canRecord&&(d>v.today||v.holiday!==null||v.isSunday)||v.canPublish&&(d>v.today||v.holiday!==null))throw invalid();
 if(v.session!==null){const n=v.session;exact(n,['id','version','dataVersion','updatedAt','publishedAt','locked']);if(n.id!==v.source.sessionId||n.version!==v.source.version||n.dataVersion!==v.source.dataVersion||!stamp(n.updatedAt)||!(n.publishedAt===null||stamp(n.publishedAt))||typeof n.locked!=='boolean'||n.locked!==(v.sessionStatus==='published'||v.sessionStatus==='locked')||(v.sessionStatus==='published')!==(n.publishedAt!==null&&v.source.publicationId!==null))throw invalid();}else if(v.source.sessionId!==null||v.sessionStatus!=='none')throw invalid();
 const counts=tally(v.counts);for(const r of v.rows){exact(r,['studentId','enrollmentId','recordVersion','code','fullName','groupName','status','note','edited','linkedConduct']);if(!uuid(r.studentId)||!uuid(r.enrollmentId)||!(r.recordVersion===null||integer(r.recordVersion,1))||!text(r.code)||!text(r.fullName)||!nullable(r.groupName)||!statuses.includes(r.status)||typeof r.note!=='string'||r.note.length>4000||typeof r.edited!=='boolean'||v.session===null&&(r.recordVersion!==null||r.status!=='UNMARKED'||r.note||r.edited||r.linkedConduct!==null))throw invalid();if(r.linkedConduct!==null)linked(r.linkedConduct);}
 if(new Set(v.rows.map(r=>r.studentId)).size!==v.rows.length||new Set(v.rows.map(r=>r.enrollmentId)).size!==v.rows.length||statuses.some(k=>v.rows.filter(r=>r.status===k).length!==v.counts[k]))throw invalid();
 v.lessons.forEach(lesson);if(new Set(v.lessons.map(l=>l.id)).size!==v.lessons.length)throw invalid();if(v.lesson!==null){lesson(v.lesson);if(!v.lessons.some(l=>JSON.stringify(l)===JSON.stringify(v.lesson)))throw invalid();}if((slot==='morning'||slot==='afternoon')!==(v.lesson===null))throw invalid();nativeWeek(v.week);
 if(!Array.isArray(v.linkRules)||v.linkRules.length>2)throw invalid();for(const r of v.linkRules){exact(r,['link','label','points']);if(!['LATE','UNEXCUSED'].includes(r.link)||!text(r.label)||typeof r.points!=='number'||!Number.isFinite(r.points))throw invalid();}if(new Set(v.linkRules.map(r=>r.link)).size!==v.linkRules.length)throw invalid();
 return {...v,rows:v.rows.map(r=>({...r,avatarTone:'blue' as const,groupName:r.groupName??undefined,status:r.status.toLowerCase() as AttendanceStatus,linkedConduct:r.linkedConduct?{...r.linkedConduct,status:r.linkedConduct.status==='DRAFT'?'pending_review':r.linkedConduct.status==='APPROVED'?'approved':'void'}:null})),counts:{...counts,total:v.rows.length,presentAll:counts.present+counts.late},holiday:v.holiday??undefined,updatedByName:v.updatedByName??undefined,linkRules:v.linkRules.map(r=>({...r,link:r.link.toLowerCase() as 'late'|'unexcused'}))};
}
export function nativeAttendanceWeek(v:ApiSchemas['ClassAttendanceWeek'],s:string,y:string,c:string,m?:string){
 exact(v,['schoolId','yearId','classId','monday','today','week','days','rows']);scope(v,s,y,c);if(!date(v.monday)||m!==undefined&&v.monday!==m||mondayOf(v.monday)!==v.monday||!date(v.today)||!Array.isArray(v.days)||v.days.length!==6||!Array.isArray(v.rows)||v.rows.length>5000)throw invalid();nativeWeek(v.week);
 for(const [i,d]of v.days.entries()){exact(d,['date','sessionStatus','holiday','periodSessions']);if(d.date!==addDays(v.monday,i)||![...states,'future','outside_year'].includes(d.sessionStatus)||!nullable(d.holiday)||!integer(d.periodSessions)||d.sessionStatus==='future'&&d.date<=v.today)throw invalid();}
 for(const r of v.rows){exact(r,['studentId','code','fullName','cells','tally']);if(!uuid(r.studentId)||!text(r.code)||!text(r.fullName)||!Array.isArray(r.cells)||r.cells.length!==6)throw invalid();tally(r.tally);for(const cell of r.cells){exact(cell,['status','note','edited']);if(![...statuses,'holiday','future','not_enrolled'].includes(cell.status)||typeof cell.note!=='string'||cell.note.length>4000||typeof cell.edited!=='boolean'||['holiday','future','not_enrolled'].includes(cell.status)&&(cell.note||cell.edited))throw invalid();}if(statuses.some(k=>r.cells.filter(x=>x.status===k).length!==r.tally[k]))throw invalid();}
 if(new Set(v.rows.map(r=>r.studentId)).size!==v.rows.length)throw invalid();return {...v,rows:v.rows.map(r=>({...r,tally:tally(r.tally),cells:r.cells.map(x=>({...x,status:(statuses.includes(x.status as typeof statuses[number])?x.status.toLowerCase():x.status) as AttendanceStatus|'holiday'|'future'|'not_enrolled'}))}))};
}
export function nativeAttendanceHistory(v:ApiSchemas['ClassAttendanceHistory'],s:string,y:string,c:string,studentId:string,d:string,slot:string){
 exact(v,['schoolId','yearId','classId','studentId','studentName','code','date','slot','status','note','sessionStatus','publishedAt','linkedConduct','history']);scope(v,s,y,c);if(v.studentId!==studentId||!uuid(studentId)||v.date!==d||!date(d)||v.slot!==slot||!slotValid(slot)||!text(v.studentName)||!text(v.code)||!statuses.includes(v.status)||typeof v.note!=='string'||v.note.length>4000||!states.includes(v.sessionStatus)||!(v.publishedAt===null||stamp(v.publishedAt))||!Array.isArray(v.history)||v.history.length>2000||!Array.isArray(v.linkedConduct)||v.linkedConduct.length>1)throw invalid();
 for(const h of v.history){exact(h,['id','at','byName','from','to','reason']);if(!uuid(h.id)||!stamp(h.at)||!nullable(h.byName)||!nullable(h.reason)||!statuses.includes(h.from)||!statuses.includes(h.to))throw invalid();}if(new Set(v.history.map(h=>h.id)).size!==v.history.length||v.history.some((h,i)=>i>0&&h.at>v.history[i-1].at))throw invalid();for(const l of v.linkedConduct){exact(l,['id','points','status','reason']);linked({id:l.id,points:l.points,status:l.status});if(!nullable(l.reason))throw invalid();}
 return {...v,status:v.status.toLowerCase() as AttendanceStatus,publishedAt:v.publishedAt??undefined,history:v.history.map(h=>({...h,byName:h.byName??undefined,reason:h.reason??undefined,from:h.from.toLowerCase() as AttendanceStatus,to:h.to.toLowerCase() as AttendanceStatus})),linkedConduct:v.linkedConduct.map(l=>({...l,status:l.status==='DRAFT'?'pending_review':l.status==='APPROVED'?'approved':'void',reason:l.reason??undefined}))};
}
function receipt(v:ApiSchemas['ClassAttendanceReceipt']){exact(v,['sessionId','changed','linkedCreated','linkedVoided','blockedLinks','source']);attendanceSource(v.source);if(!uuid(v.sessionId)||v.source.sessionId!==v.sessionId||![v.changed,v.linkedCreated,v.linkedVoided].every(n=>integer(n))||!Array.isArray(v.blockedLinks)||v.blockedLinks.length>5000)throw invalid();for(const b of v.blockedLinks){exact(b,['studentId','code']);if(!(b.studentId===null||uuid(b.studentId))||!text(b.code))throw invalid();}return v;}
export async function readAttendanceSlots(s:string,y:string,c:string,d:string){return nativeAttendanceSlots((await http('getClassAttendanceSlots',{params:{schoolId:s,yearId:y,classId:c},query:{date:d}})).data,s,y,c,d);}
export async function readAttendanceHistory(s:string,y:string,c:string,studentId:string,d:string,slot:string){return nativeAttendanceHistory((await http('getClassAttendanceHistory',{params:{schoolId:s,yearId:y,classId:c,studentId},query:{date:d,slot}})).data,s,y,c,studentId,d,slot);}
export const connectedAttendanceRepo=withStaffAccess({
 async sheet(_ctx:Ctx,s:string,y:string,c:string,d:string,slot:string){return nativeAttendanceSheet((await http('getClassAttendanceSheet',{params:{schoolId:s,yearId:y,classId:c},query:{date:d,slot}})).data,s,y,c,d,slot);},
 async weekly(_ctx:Ctx,s:string,y:string,c:string,m?:string){return nativeAttendanceWeek((await http('getClassAttendanceWeek',{params:{schoolId:s,yearId:y,classId:c},query:{weekStart:m}})).data,s,y,c,m);},
 async save(_ctx:Ctx,s:string,y:string,c:string,input:{date:string;slot:string;source:ApiSchemas['ClassAttendanceSource'];entries:{studentId:string;recordVersion:number|null;status:AttendanceStatus;note:string}[];linkConduct:boolean;reason?:string}){attendanceSource(input.source);return receipt((await http('saveClassAttendanceSheet',{params:{schoolId:s,yearId:y,classId:c},body:{...input,entries:input.entries.map(e=>({...e,status:e.status.toUpperCase() as typeof statuses[number]}))}})).data);},
 async publish(_ctx:Ctx,s:string,y:string,c:string,date:string,slot:string,source:ApiSchemas['ClassAttendanceSource']){attendanceSource(source);return receipt((await http('publishClassAttendanceSheet',{params:{schoolId:s,yearId:y,classId:c},body:{date,slot,source}})).data);},
});
