import type {ApiSchemas} from '../../api/generated';
import type {ActionKey,AcademicYear,ClassRoom} from '../../model/types';
import {inclusiveDate} from '../../api/dates';
import {UI_ACTIONS} from '../../api/permissions';
import {RepoError} from '../errors';

const invalid=()=>new RepoError('READ_ERROR','API chưa xác nhận đầy đủ ngữ cảnh và quyền của lớp.');
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const date=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
const text=(v:unknown)=>typeof v==='string'&&!!v.trim();
const nullableText=(v:unknown)=>v===null||text(v);
const count=(v:unknown)=>v===null||Number.isInteger(v)&&Number(v)>=0;
const timestamp=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
function exact(value:object,keys:string[]){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length!==keys.length||keys.some(k=>!Object.hasOwn(value,k)))throw invalid();}
const tabRules=[['overview','Tổng quan','',['class.read']],['students','Học sinh','/students',['student.read']],['attendance','Điểm danh','/attendance',['attendance.read','attendance.record']],['conduct','Thi đua','/conduct',['conduct.read','conduct.record','conduct.review','conduct.adjust.approve']],['timetable','Lịch lớp','/timetable',['schedule.read']],['groups','Tổ & sơ đồ','/groups',['group.manage','seating.manage','duty.read','duty.manage']],['activities','Hoạt động','/activities',['activity.read','activity.manage','evidence.read','evidence.manage']],['announcements','Thông báo','/announcements',['announcement.read','announcement.manage']],['files','Tệp lớp','/files',['file.read','file.manage']],['reports','Báo cáo','/reports',['report.read']]] as const;
/** Exact purpose receipt: no hidden roster, membership identity, or family fields. */
export function nativeClassHeader(row:ApiSchemas['ClassWorkspaceHeader'],schoolId:string,yearId:string,classId:string){
 exact(row,['school','class','year','grade','today','referenceDate','homeroom','studentCount','maleCount','femaleCount','myDuties','viaSchoolRole','workspaceKind','actions','tabs','summary','readOnly']);
 exact(row.school,['id','name','shortName','slug']);exact(row.class,['id','version','yearId','gradeLevelId','name','capacity','status','roomId','motto','createdAt']);exact(row.year,['id','version','code','name','startsOn','endsOn','status']);
 const c=row.class,y=row.year;
 if(row.school.id!==schoolId||!uuid(schoolId)||!uuid(yearId)||!uuid(classId)||!text(row.school.name)||!text(row.school.shortName)||!text(row.school.slug)||c.id!==classId||c.yearId!==yearId||y.id!==yearId||!uuid(c.gradeLevelId)||!Number.isInteger(c.version)||c.version<1||!Number.isInteger(y.version)||y.version<1||!text(c.name)||!Number.isInteger(c.capacity)||c.capacity<0||!['DRAFT','ACTIVE','ARCHIVED'].includes(c.status)||!['DRAFT','ACTIVE','ARCHIVED'].includes(y.status)||!(c.roomId===null||uuid(c.roomId))||!(c.motto===null||typeof c.motto==='string')||!timestamp(c.createdAt)||!text(y.code)||!text(y.name)||!date(y.startsOn)||!date(y.endsOn)||y.endsOn<=y.startsOn||!date(row.today)||!date(row.referenceDate)||row.referenceDate<y.startsOn||row.referenceDate>=y.endsOn||!text(row.grade)||typeof row.viaSchoolRole!=='boolean'||typeof row.readOnly!=='boolean'||row.readOnly!==(y.status==='ARCHIVED'||c.status==='ARCHIVED')||!['TEACHER','SCHOOL','CLASS'].includes(row.workspaceKind)||!Array.isArray(row.myDuties)||row.myDuties.some(d=>!text(d))||new Set(row.myDuties).size!==row.myDuties.length||!Array.isArray(row.actions)||row.actions.some(a=>!text(a)||a.length>100)||new Set(row.actions).size!==row.actions.length||!row.actions.includes('class.read')||!Array.isArray(row.tabs)||!row.tabs.length||row.tabs.length>10)throw invalid();
 if(row.referenceDate!==(row.today<y.startsOn?y.startsOn:row.today>=y.endsOn?inclusiveDate(y.endsOn):row.today)||row.workspaceKind==='TEACHER'&&(!row.myDuties.length||!row.actions.includes('teacher.self'))||row.workspaceKind==='SCHOOL'&&!row.viaSchoolRole)throw invalid();
 for(const t of row.tabs){exact(t,['key','label','path']);const rule=tabRules.find(r=>r[0]===t.key);const path=t.key==='groups'?(row.actions.includes('group.manage')?'/groups':row.actions.includes('seating.manage')?'/seating':'/duties'):rule?.[2];if(!rule||t.label!==rule[1]||t.path!==path||!rule[3].some(a=>row.actions.includes(a)))throw invalid();}
 if(new Set(row.tabs.map(t=>t.key)).size!==row.tabs.length||row.tabs[0].key!=='overview'||JSON.stringify(row.tabs.map(t=>t.key))!==JSON.stringify(tabRules.filter(r=>r[3].some(a=>row.actions.includes(a))).map(r=>r[0])))throw invalid();
 if(!count(row.studentCount)||!count(row.maleCount)||!count(row.femaleCount)||(row.maleCount===null)!==(row.femaleCount===null)||row.studentCount===null&&(row.maleCount!==null||row.femaleCount!==null)||row.studentCount!==null&&row.maleCount!==null&&row.maleCount+row.femaleCount!>row.studentCount||(row.studentCount!==null)!==row.actions.includes('student.read'))throw invalid();
 if(row.homeroom!==null){exact(row.homeroom,['name','contactVisible','workEmail','workPhone']);if(!text(row.homeroom.name)||typeof row.homeroom.contactVisible!=='boolean'||!nullableText(row.homeroom.workEmail)||!nullableText(row.homeroom.workPhone)||!row.homeroom.contactVisible&&(row.homeroom.workEmail!==null||row.homeroom.workPhone!==null))throw invalid();}
 const s=row.summary;exact(s,['weekIndex','weekStatus','pending','links','lastPublishedAt']);
 if(!(s.weekIndex===null||Number.isInteger(s.weekIndex)&&s.weekIndex>0)||s.weekIndex!==null&&!row.actions.includes('year.read')||!(s.weekStatus===null||['OPEN','IN_REVIEW','LOCKED','PUBLISHED'].includes(s.weekStatus))||s.weekStatus!==null&&(!row.actions.includes('conduct.read')||s.weekIndex===null)||!count(s.pending)||!(s.lastPublishedAt===null||timestamp(s.lastPublishedAt))||(s.pending!==null)!==row.actions.includes('conduct.read')||(s.links!==null)!==row.actions.includes('parent_access.manage'))throw invalid();
 if(s.links!==null){exact(s.links,['studentsWithLink','opened']);if(!row.actions.includes('parent_access.manage')||!Number.isInteger(s.links.studentsWithLink)||s.links.studentsWithLink<0||!Number.isInteger(s.links.opened)||s.links.opened<0||s.links.opened>s.links.studentsWithLink||row.studentCount!==null&&s.links.studentsWithLink>row.studentCount)throw invalid();}
 return {school:row.school,class:{id:c.id,schoolId,yearId,gradeId:c.gradeLevelId,name:c.name,capacity:c.capacity,status:c.status.toLowerCase() as ClassRoom['status'],roomId:c.roomId??undefined,motto:c.motto??undefined,createdAt:c.createdAt,version:c.version},
  year:{id:y.id,schoolId,label:y.name,code:y.code,startDate:y.startsOn,endDate:inclusiveDate(y.endsOn),status:y.status.toLowerCase() as AcademicYear['status'],version:y.version},grade:row.grade,
  homeroom:row.homeroom?{name:row.homeroom.name,phone:row.homeroom.workPhone,email:row.homeroom.workEmail,tone:'blue',contactVisible:row.homeroom.contactVisible}:null,
  size:row.studentCount,male:row.maleCount,female:row.femaleCount,myDuties:row.myDuties,viaSchoolRole:row.viaSchoolRole,workspaceKind:row.workspaceKind,
  nativeActions:row.actions,actions:Object.entries(UI_ACTIONS).filter(([,required])=>required.every(a=>row.actions.includes(a))).map(([a])=>a as ActionKey),tabs:row.tabs,summary:{...s,weekStatus:s.weekStatus?.toLowerCase()??null},readOnly:row.readOnly,today:row.today,referenceDate:row.referenceDate};
}
