import {http} from '../../api/client';
import type {ApiSchemas} from '../../api/generated';
import type {Ctx} from '../core';
import {RepoError} from '../errors';
import {withStaffAccess,formResult} from './common';
import {ruleItem} from './conduct';
import {publicationPolicyView} from './conduct-school';

export type ConductSource=ApiSchemas['ConductWorkspaceSource'];
const invalid=()=>new RepoError('READ_ERROR','Phản hồi thi đua không hợp lệ. Hãy tải lại dữ liệu.');
const uuid=(v:unknown):v is string=>typeof v==='string'&&/^[\da-f]{8}-[\da-f]{4}-[1-8][\da-f]{3}-[89ab][\da-f]{3}-[\da-f]{12}$/i.test(v);
const text=(v:unknown):v is string=>typeof v==='string';
const int=(v:unknown,min=0)=>Number.isSafeInteger(v)&&Number(v)>=min;
const decimal=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<100000000&&Math.abs(v*100-Math.round(v*100))<0.00001;
const date=(v:unknown)=>text(v)&&/^\d{4}-\d{2}-\d{2}$/.test(v);
const stamp=(v:unknown)=>text(v)&&/T/.test(v)&&Number.isFinite(Date.parse(v));
const nullable=(v:unknown,test:(v:unknown)=>boolean)=>v===null||test(v);
function exact(v:unknown,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||Object.keys(v).some(k=>!keys.includes(k)))throw invalid();}
function scope(v:{schoolId:string;yearId:string;classId:string},s:string,y:string,c:string){if(v.schoolId!==s||v.yearId!==y||v.classId!==c||![s,y,c].every(uuid))throw invalid();}
export function conductSource(v:ConductSource){exact(v,['weekId','periodId','version','dataVersion','classVersion','schoolVersion','sourceHash','publicationId']);if(!uuid(v.weekId)||!nullable(v.periodId,uuid)||!int(v.version)||!int(v.dataVersion)||!int(v.classVersion,1)||!int(v.schoolVersion,1)||!text(v.sourceHash)||!/^[a-f0-9]{64}$/.test(v.sourceHash)||!nullable(v.publicationId,uuid)||(v.periodId===null)!==(v.version===0&&v.dataVersion===0)||v.periodId===null&&v.publicationId!==null)throw invalid();return v;}
function nativeWeek(v:ApiSchemas['ConductWorkspaceWeek'],id?:string){exact(v,['id','index','startDate','endDate','closeDeadline','status','isCurrent']);if(!uuid(v.id)||id&&id!==v.id||!int(v.index,1)||!date(v.startDate)||!date(v.endDate)||v.startDate>v.endDate||!nullable(v.closeDeadline,date)||!['open','locked','published'].includes(v.status)||typeof v.isCurrent!=='boolean')throw invalid();return v;}
function nativeRecord(v:ApiSchemas['ConductWorkspaceRecord'],s:string,y:string,c:string,w?:string){
 exact(v,['schoolId','yearId','classId','id','studentId','enrollmentId','weekId','date','ruleSetId','ruleId','points','reason','createdBy','createdAt','createdByName','status','reviewNote','version','studentName','studentCode','ruleLabel','category','fromAttendance','linkedAttendanceRecordId','duplicateOf','ruleSetVersion','lessonId','canEdit']);scope(v,s,y,c);
 if(![v.id,v.studentId,v.enrollmentId,v.weekId,v.ruleSetId,v.ruleId,v.createdBy].every(uuid)||w&&v.weekId!==w||!date(v.date)||!decimal(v.points)||!text(v.reason)||!stamp(v.createdAt)||!nullable(v.createdByName,text)||!nullable(v.reviewNote,text)||!['pending_review','approved','rejected','void'].includes(v.status)||!int(v.version,1)||![v.studentName,v.studentCode,v.ruleLabel,v.category].every(text)||!int(v.ruleSetVersion,1)||!nullable(v.lessonId,uuid)||!nullable(v.linkedAttendanceRecordId,uuid)||typeof v.fromAttendance!=='boolean'||v.fromAttendance!==(v.linkedAttendanceRecordId!==null)||typeof v.canEdit!=='boolean'||v.canEdit&&v.status!=='pending_review'||!Array.isArray(v.duplicateOf)||v.duplicateOf.length>10000||!v.duplicateOf.every(uuid)||new Set(v.duplicateOf).size!==v.duplicateOf.length||v.duplicateOf.includes(v.id))throw invalid();
 return {...v,createdByName:v.createdByName??undefined,reviewNote:v.reviewNote??undefined,linkedAttendanceRecordId:v.linkedAttendanceRecordId??undefined};
}
function nativeRows(rows:ApiSchemas['ConductWorkspaceRow'][]){if(!Array.isArray(rows)||rows.length>5000||new Set(rows.map(r=>r.studentId)).size!==rows.length)throw invalid();for(const r of rows){exact(r,['studentId','studentName','studentCode','base','plus','minus','total','grade','items']);if(!uuid(r.studentId)||!text(r.studentName)||!nullable(r.studentCode,text)||!nullable(r.grade,text)||![r.base,r.plus,r.minus,r.total].every(decimal)||r.plus<0||r.minus>0||!Array.isArray(r.items)||r.items.length>10000||new Set(r.items.map(i=>i.recordId)).size!==r.items.length)throw invalid();for(const i of r.items){exact(i,['recordId','date','label','points','shareWithParent']);if(!uuid(i.recordId)||!date(i.date)||!text(i.label)||!decimal(i.points)||typeof i.shareWithParent!=='boolean')throw invalid();}}
 return rows.map(r=>({...r,studentCode:r.studentCode??'—',grade:r.grade??'Chưa xếp loại'}));
}
export function nativeSnapshot(v:ApiSchemas['ConductWorkspaceSnapshot'],s:string,y:string,c:string){
 exact(v,['id','schoolId','yearId','classId','weekId','weekIndex','rowCount','avg','lockedByName','publishedByName','kind','versionNo','ruleSetId','ruleSetVersionNo','ruleSetName','lockedAt','lockedBy','publishedAt','publishedBy','status','rows','detailsAvailable','sourceVersion','publicationVersion','supersedesId','adjustmentNote']);scope(v,s,y,c);
 if(![v.id,v.weekId,v.ruleSetId,v.lockedBy].every(uuid)||v.kind!=='conduct_week'||![v.versionNo,v.ruleSetVersionNo,v.sourceVersion,v.publicationVersion,v.weekIndex].every(n=>int(n,1))||!text(v.ruleSetName)||!stamp(v.lockedAt)||!nullable(v.publishedAt,stamp)||!nullable(v.publishedBy,uuid)||!nullable(v.supersedesId,uuid)||!nullable(v.adjustmentNote,text)||!nullable(v.lockedByName,text)||!nullable(v.publishedByName,text)||!decimal(v.avg)||!int(v.rowCount)||v.rowCount!==v.rows.length||typeof v.detailsAvailable!=='boolean'||!['locked','published','superseded','withdrawn'].includes(v.status)||v.status==='published'&&(v.publishedAt===null||v.publishedBy===null))throw invalid();
 const rows=nativeRows(v.rows);return {...v,rows,publishedAt:v.publishedAt??undefined,publishedBy:v.publishedBy??undefined,supersedesId:v.supersedesId??undefined,adjustmentNote:v.adjustmentNote??undefined,lockedByName:v.lockedByName??undefined,publishedByName:v.publishedByName??undefined};
}
function period(v:ApiSchemas['ConductWorkspaceRecords']['period']){exact(v,['status','lockedAt','lockedByName']);if(!['open','locked','published'].includes(v.status)||!nullable(v.lockedAt,stamp)||!nullable(v.lockedByName,text))throw invalid();return {...v,lockedAt:v.lockedAt??undefined,lockedByName:v.lockedByName??undefined};}
export function conductRecords(v:ApiSchemas['ConductWorkspaceRecords'],s:string,y:string,c:string,w:string){
 exact(v,['schoolId','yearId','classId','today','source','records','roster','ruleSet','week','period','canRecord','isReviewer','lessons']);scope(v,s,y,c);conductSource(v.source);nativeWeek(v.week,w);const p=period(v.period);
 if(!date(v.today)||v.source.weekId!==w||p.status!==v.week.status||typeof v.canRecord!=='boolean'||typeof v.isReviewer!=='boolean'||!Array.isArray(v.records)||v.records.length>10000||new Set(v.records.map(r=>r.id)).size!==v.records.length||!Array.isArray(v.roster)||v.roster.length>5000||!Array.isArray(v.lessons)||v.lessons.length>500)throw invalid();
 const records=v.records.map(r=>nativeRecord(r,s,y,c,w)),roster=v.roster.map(r=>{exact(r,['id','enrollmentId','fullName','code','startsOn','endsOn']);if(!uuid(r.id)||!uuid(r.enrollmentId)||!text(r.fullName)||!text(r.code)||!date(r.startsOn)||!nullable(r.endsOn,date))throw invalid();return {...r,avatarTone:'blue' as const};});if(new Set(roster.map(r=>r.enrollmentId)).size!==roster.length)throw invalid();
 for(const l of v.lessons){exact(l,['id','date','subjectId','subject','start','end','canRecord']);if(!uuid(l.id)||!uuid(l.subjectId)||!date(l.date)||!text(l.subject)||!stamp(l.start)||!stamp(l.end)||l.start>=l.end||typeof l.canRecord!=='boolean')throw invalid();}
 const ruleSet=v.ruleSet===null?null:ruleItem(v.ruleSet,s);if(ruleSet&&records.some(r=>r.ruleSetId!==ruleSet.id)||records.some(r=>!roster.some(e=>e.id===r.studentId&&e.enrollmentId===r.enrollmentId)))throw invalid();return {...v,records,roster,ruleSet,period:p};
}
export function conductSummaryView(v:ApiSchemas['ConductWorkspaceSummary'],s:string,y:string,c:string,w:string){
 exact(v,['schoolId','yearId','classId','today','source','week','period','ruleSet','snapshot','rows','preview','summaryAvailable','checks','perms','policy','approval']);scope(v,s,y,c);conductSource(v.source);nativeWeek(v.week,w);const p=period(v.period),ruleSet=ruleItem(v.ruleSet,s),snapshot=v.snapshot===null?null:nativeSnapshot(v.snapshot,s,y,c);exact(v.checks,['pending','duplicates','blocking','warnings']);exact(v.perms,['lock','publish','review']);exact(v.approval,['required','approvedAt','canApprove']);
 if(!date(v.today)||v.source.weekId!==w||v.week.status!==p.status||typeof v.summaryAvailable!=='boolean'||!int(v.checks.pending)||!int(v.checks.duplicates)||![v.checks.blocking,v.checks.warnings].every(a=>Array.isArray(a)&&a.every(text))||Object.values(v.perms).some(v=>typeof v!=='boolean')||typeof v.approval.required!=='boolean'||typeof v.approval.canApprove!=='boolean'||!nullable(v.approval.approvedAt,stamp)||!v.summaryAvailable&&(v.rows.length||v.preview.length||snapshot||Object.values(v.perms).some(Boolean)))throw invalid();
 const rows=nativeRows(v.rows),preview=nativeRows(v.preview);if(snapshot&&snapshot.weekId!==w||snapshot&&snapshot.ruleSetId!==ruleSet.id)throw invalid();return {...v,ruleSet,snapshot,rows,preview,period:p,policy:publicationPolicyView(v.policy,s)};
}
export function conductReceipt(v:ApiSchemas['ConductWorkspaceReceipt'],s:string,y:string,c:string,w:string){exact(v,['source','changed','status','record','snapshot']);conductSource(v.source);if(v.source.weekId!==w||!int(v.changed)||!['open','locked','published'].includes(v.status))throw invalid();const record=v.record===null?null:nativeRecord(v.record,s,y,c,w),snapshot=v.snapshot===null?null:nativeSnapshot(v.snapshot,s,y,c);if(snapshot&&snapshot.weekId!==w||snapshot&&snapshot.status!==v.status)throw invalid();return {...v,record,snapshot};}
const params=(s:string,y:string,c:string,w?:string)=>({schoolId:s,yearId:y,classId:c,...(w?{weekId:w}:{})});
export const connectedConductWorkspaceRepo=withStaffAccess({
 async weekOptions(_ctx:Ctx,s:string,y:string,c:string){const v=(await http('getConductWorkspaceWeeks',{params:params(s,y,c)})).data;exact(v,['schoolId','yearId','classId','today','weeks']);scope(v,s,y,c);if(!date(v.today)||!Array.isArray(v.weeks)||v.weeks.length>500||new Set(v.weeks.map(w=>w.id)).size!==v.weeks.length)throw invalid();v.weeks.forEach(w=>nativeWeek(w));return v.weeks;},
 async records(_ctx:Ctx,s:string,y:string,c:string,w:string,opts:{studentId?:string}={}){return conductRecords((await http('getConductWorkspaceRecords',{params:params(s,y,c,w),query:opts})).data,s,y,c,w);},
 async weekSummary(_ctx:Ctx,s:string,y:string,c:string,w:string){return conductSummaryView((await http('getConductWorkspaceSummary',{params:params(s,y,c,w)})).data,s,y,c,w);},
 async createRecord(_ctx:Ctx,s:string,y:string,c:string,input:{source:ConductSource;studentId:string;enrollmentId:string;date:string;ruleId:string;reason:string;requestId:string;lessonId?:string;manualDelta?:number;confirmDistinct?:boolean;distinctNote?:string}){conductSource(input.source);const body={...input,lessonId:input.lessonId??null,manualDelta:input.manualDelta??null,confirmDistinct:input.confirmDistinct??false,distinctNote:input.distinctNote??null};const v=conductReceipt((await formResult(http('createConductWorkspaceRecord',{params:params(s,y,c,input.source.weekId),body,idempotencyKey:input.requestId}),{reason:'reason',studentId:'studentId',ruleId:'ruleId'})).data,s,y,c,input.source.weekId);if(!v.record)throw invalid();return {record:v.record,idempotent:false,source:v.source};},
 async updateRecord(_ctx:Ctx,s:string,y:string,c:string,id:string,patch:{source:ConductSource;ruleId:string;reason:string;version:number;manualDelta?:number}){conductSource(patch.source);const v=conductReceipt((await http('updateConductWorkspaceRecord',{params:{...params(s,y,c,patch.source.weekId),recordId:id},body:{...patch,manualDelta:patch.manualDelta??null}})).data,s,y,c,patch.source.weekId);if(!v.record||v.record.id!==id)throw invalid();return v.record;},
 async review(_ctx:Ctx,s:string,y:string,c:string,input:{source:ConductSource;records:{id:string;version:number}[];decision:'approve'|'reject'|'void';note?:string}){conductSource(input.source);return conductReceipt((await http('reviewConductWorkspaceRecords',{params:params(s,y,c,input.source.weekId),body:{...input,note:input.note??null}})).data,s,y,c,input.source.weekId).changed;},
 async lock(_ctx:Ctx,s:string,y:string,c:string,w:string,alsoPublish:boolean,source:ConductSource){conductSource(source);if(source.weekId!==w)throw invalid();const v=conductReceipt((await http('lockConductWorkspaceWeek',{params:params(s,y,c,w),body:{source,alsoPublish}})).data,s,y,c,w);if(!v.snapshot)throw invalid();return v.snapshot;},
 async approvePublication(_ctx:Ctx,s:string,y:string,c:string,w:string,source:ConductSource){conductSource(source);if(source.weekId!==w)throw invalid();return conductReceipt((await http('approveConductWorkspaceWeek',{params:params(s,y,c,w),body:{source}})).data,s,y,c,w);},
 async publish(_ctx:Ctx,s:string,y:string,c:string,w:string,source:ConductSource){conductSource(source);if(source.weekId!==w)throw invalid();const v=conductReceipt((await http('publishConductWorkspaceWeek',{params:params(s,y,c,w),body:{source}})).data,s,y,c,w);if(v.status!=='published'||!v.snapshot)throw invalid();return v.snapshot;},
 async reopen(_ctx:Ctx,s:string,y:string,c:string,w:string,reason:string,source:ConductSource){conductSource(source);if(source.weekId!==w)throw invalid();const v=conductReceipt((await http('reopenConductWorkspaceWeek',{params:params(s,y,c,w),body:{source,reason}})).data,s,y,c,w);if(v.status!=='open'||v.snapshot)throw invalid();return v;},
 async snapshots(_ctx:Ctx,s:string,y:string,c:string){const items:ReturnType<typeof nativeSnapshot>[]=[],ids=new Set<string>(),cursors=new Set<string>();let cursor:string|undefined;for(let n=0;n<100;n++){const response=await http('getConductWorkspaceSnapshots',{params:params(s,y,c),query:{limit:100,cursor}}),v=response.data,p=response.page;exact(v,['schoolId','yearId','classId','items']);scope(v,s,y,c);if(!p||!int(p.limit,1)||p.limit>100||!Array.isArray(v.items)||v.items.length>p.limit||typeof p.hasMore!=='boolean'||!nullable(p.nextCursor,text)||p.hasMore!==(p.nextCursor!==null))throw invalid();for(const item of v.items){const row=nativeSnapshot(item,s,y,c);if(ids.has(row.id))throw invalid();ids.add(row.id);items.push(row);}if(!p.hasMore)return items.sort((a,b)=>b.weekIndex-a.weekIndex||b.versionNo-a.versionNo);if(!p.nextCursor||cursors.has(p.nextCursor))throw invalid();cursors.add(p.nextCursor);cursor=p.nextCursor;}throw invalid();},
 async snapshot(_ctx:Ctx,s:string,y:string,c:string,id:string){const v=(await http('getConductWorkspaceSnapshot',{params:{...params(s,y,c),snapshotId:id}})).data;exact(v,['schoolId','yearId','classId','source','snapshot','ruleSet','week','versions','diff','lockedByName','publishedByName','className','canRequestAdjustment','pendingAdjustments']);scope(v,s,y,c);conductSource(v.source);const snapshot=nativeSnapshot(v.snapshot,s,y,c),ruleSet=v.ruleSet===null?null:ruleItem(v.ruleSet,s);nativeWeek(v.week,snapshot.weekId);if(snapshot.id!==id||!ruleSet||snapshot.ruleSetId!==ruleSet.id||!Array.isArray(v.versions)||v.versions.length>500||new Set(v.versions.map(r=>r.id)).size!==v.versions.length||!Array.isArray(v.diff)||v.diff.length>5000||!nullable(v.lockedByName,text)||!nullable(v.publishedByName,text)||!text(v.className)||typeof v.canRequestAdjustment!=='boolean'||!int(v.pendingAdjustments))throw invalid();for(const r of v.versions){exact(r,['id','versionNo','status','publishedAt','adjustmentNote']);if(!uuid(r.id)||!int(r.versionNo,1)||!['locked','published','superseded','withdrawn'].includes(r.status)||!nullable(r.publishedAt,stamp)||!nullable(r.adjustmentNote,text))throw invalid();}for(const d of v.diff){exact(d,['studentId','studentName','before','after']);if(!uuid(d.studentId)||!text(d.studentName)||!nullable(d.before,decimal)||!decimal(d.after))throw invalid();}return {...v,snapshot,ruleSet,versions:v.versions.map(r=>({...r,publishedAt:r.publishedAt??undefined,adjustmentNote:r.adjustmentNote??undefined})),diff:v.diff.map(r=>({...r,before:r.before??undefined})),lockedByName:v.lockedByName??undefined,publishedByName:v.publishedByName??undefined};},
});
