import {http} from '../../api/client';
import type {ApiSchemas} from '../../api/generated';
import {apiPage} from '../../api/lists';
import type {Ctx,ListQuery} from '../core';
import {withStaffAccess,displayedVersion,requiredId} from './common';
import {RepoError} from '../errors';

type Source=ApiSchemas['TransferSources']['students'][number];
function transfer(v:ApiSchemas['Transfer']){if(!['SUBMITTED','APPLIED','APPROVED','REJECTED'].includes(v.status))throw new RepoError('READ_ERROR','Trạng thái chuyển lớp không hợp lệ.');return {id:requiredId(v.id),version:displayedVersion(v.version),studentId:requiredId(v.studentId),fromEnrollmentId:requiredId(v.fromEnrollmentId),toClassId:v.toClassId,kind:v.toClassId?'transfer' as const:'leave' as const,effectiveDate:v.effectiveOn,reason:v.reason,status:v.status==='SUBMITTED'?'pending' as const:v.status==='REJECTED'?'rejected' as const:'approved' as const};}
export const connectedTransfersRepo=withStaffAccess({
 async studentOptions(_ctx:Ctx,s:string,studentId?:string){const v=(await http('getTransferSources',{params:{schoolId:s},query:{studentId}})).data;if(v.schoolId!==s||new Set(v.students.map(r=>r.enrollmentId)).size!==v.students.length)throw new RepoError('READ_ERROR','Nguồn chuyển lớp không hợp lệ.');return v.students;},
 async transfers(_ctx:Ctx,s:string,q:ListQuery){const statuses:Record<string,string>={pending:'SUBMITTED',approved:'APPLIED',rejected:'REJECTED'},status=q.filters?.status;if(status&&!statuses[status])throw new RepoError('VALIDATION','Bộ lọc chuyển lớp không hợp lệ.');const page=await apiPage('listTransfers',{params:{schoolId:s},query:{q:q.q,status:status?statuses[status]:undefined,sort:'createdAt',dir:'desc'}},q,(v:ApiSchemas['Transfer'])=>{if(!v.studentName||!v.studentCode||!v.fromClassId||!v.fromName||!v.requestedAt)throw new RepoError('READ_ERROR','Biên nhận chuyển lớp thiếu nguồn hiển thị.');return {...transfer(v),schoolId:s,studentName:v.studentName,studentCode:v.studentCode,fromClassId:v.fromClassId,fromName:v.fromName,toName:v.toName??'—',requestedByName:v.requestedByName??'Không còn tên công tác',requestedAt:v.requestedAt,decidedByName:v.decidedByName??undefined,decidedAt:v.decidedAt??undefined};});return {...page,canDecide:true};},
 async requestTransfer(_ctx:Ctx,s:string,input:{studentId:string;kind:'transfer'|'leave';toClassId?:string;effectiveDate:string;reason:string;applyNow?:boolean;source:Pick<Source,'enrollmentId'|'enrollmentVersion'|'id'>}){if(input.source.id!==input.studentId)throw new RepoError('VALIDATION','Chọn lại đúng học sinh trong nguồn chuyển lớp.');return transfer((await http('createTransfer',{params:{schoolId:s},body:{studentId:input.studentId,fromEnrollmentId:requiredId(input.source.enrollmentId),expectedEnrollmentVersion:displayedVersion(input.source.enrollmentVersion),...(input.kind==='transfer'?{toClassId:requiredId(input.toClassId)}:{}),effectiveOn:input.effectiveDate,reason:input.reason,applyNow:input.applyNow===true}})).data);},
 async decideTransfer(_ctx:Ctx,s:string,id:string,approve:boolean,note:string,version:number){return transfer((await http(approve?'approveTransfer':'rejectTransfer',{params:{schoolId:s,transferId:id},body:{expectedVersion:displayedVersion(version),...(!approve?{reason:note}:{})}})).data);},
});
