import fs from 'node:fs';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {test,expect,type BrowserContext,type Page} from '@playwright/test';

test.describe.configure({mode:'default'});
test.setTimeout(120_000);
const baseURL='http://127.0.0.1:18763';
const original=JSON.parse(fs.readFileSync('qa/backend/fast-track-browser-persistence-source.json','utf8')) as {schoolId:string;yearId:string;classId:string;weekId:string;studentId:string};
const schoolId=original.schoolId,yearId=original.yearId;
const retained=process.env.E2E_REUSE_SETUP==='true'?JSON.parse(fs.readFileSync('.secrets/local/run-browser-fixture.json','utf8')):undefined;
const suffix=retained?.pupilCode?.slice(2)??crypto.randomBytes(4).toString('hex').toUpperCase(),className='10RT'+suffix,targetName='10RD'+suffix,pupilName='Học Sinh Browser '+suffix,pupilCode='RT'+suffix,importName='Học Sinh Nhập '+suffix;
let context:BrowserContext,page:Page,classId:string=retained?.classId,targetClassId:string=retained?.targetClassId,studentId:string=retained?.studentId,importId:string=retained?.importId,activityId:string=retained?.activityId;
const errors:string[]=[],receipts:{kind:string;path:string;status:number}[]=[];
async function login(email='admin-a@example.invalid'){
 await page.goto('/login');await page.getByLabel(/^Email công việc/).fill(email);await page.getByLabel(/^Mật khẩu/).fill(fs.readFileSync('.secrets/local/local_test_password','utf8').trim());await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();await page.waitForURL(u=>u.pathname!='/login');
}
async function get(url:string){const r=await context.request.get(url);expect(r.status(),url).toBe(200);return (await r.json()).data;}
async function settled(){await page.waitForLoadState('networkidle');await page.evaluate(()=>document.fonts.ready);await expect(page.locator('[aria-busy="true"]')).toHaveCount(0);}
function saveFixture(){fs.writeFileSync('.secrets/local/run-browser-fixture.json',JSON.stringify({kind:'REAL_BROWSER_HTTP_POSTGRES',schoolId,yearId,classId,targetClassId,studentId,importId,activityId,className,targetName,pupilName,pupilCode,importName},null,2));}
test.beforeAll(async({browser})=>{
 context=await browser.newContext({baseURL,viewport:{width:1440,height:1000},locale:'vi-VN',timezoneId:'Asia/Ho_Chi_Minh'});page=await context.newPage();page.setDefaultTimeout(20_000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/hydration|react error|minified react|uncaught/i.test(m.text()))errors.push(m.text());});
 page.on('response',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/v1/')&&!u.pathname.includes('parent-access'))receipts.push({kind:'HTTP',path:u.pathname,status:r.status()});});await login();
 const ready=await get('/api/v1/health/ready');expect(ready.buildSha).toBe(JSON.parse(fs.readFileSync('.secrets/local/run-source-build.json','utf8')).buildId);
});
test.afterAll(async()=>{saveFixture();fs.writeFileSync('.secrets/local/run-browser-evidence.json',JSON.stringify({kind:'REAL_BROWSER_REAL_HTTP_POSTGRES_NO_INTERCEPTION',errors,receipts},null,2));await context?.close();});

test('connected organization UI creates assigned classes activates them and reloads real persisted rows',async()=>{
 if(classId&&targetClassId){for(const id of [classId,targetClassId])expect((await get(`/api/v1/schools/${schoolId}/classes/${id}`)).status).toBe('ACTIVE');await page.goto(`/school/${schoolId}/classes?year=${yearId}&q=${className}`);await expect(page.getByRole('link',{name:className,exact:true})).toBeVisible();return;}
 const create=async(name:string)=>{
  const members=await get(`/api/v1/schools/${schoolId}/members?purpose=assignment-picker&limit=100`),available=members.find((m:{homeroomOf:string[]})=>m.homeroomOf.length===0);expect(available,'a currently unassigned synthetic staff member is required').toBeTruthy();
  await page.goto(`/school/${schoolId}/classes?year=${yearId}`);await page.getByRole('button',{name:'Tạo lớp',exact:true}).first().click();const dialog=page.getByRole('dialog',{name:'Tạo lớp mới'});await expect(dialog.getByLabel('Tên lớp',{exact:false})).toBeVisible();await dialog.getByLabel('Năm học',{exact:true}).selectOption(yearId);await dialog.getByLabel('Khối',{exact:false}).selectOption({label:'Khối 10'});await dialog.getByLabel('Tên lớp',{exact:false}).fill(name);await dialog.getByLabel('Sức chứa tối đa',{exact:false}).fill('30');await dialog.getByRole('combobox',{name:/Giáo viên chủ nhiệm/}).click();await page.getByRole('option',{name:available.workDisplayName,exact:true}).click();
  const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===`/api/v1/schools/${schoolId}/classes`);await dialog.getByRole('button',{name:'Tạo lớp',exact:true}).click();const r=await response;expect(r.status(),await r.text()).toBe(201);const id=(await r.json()).data.id;if(name===className)classId=id;else targetClassId=id;saveFixture();await expect(dialog).toHaveCount(0);
  await page.getByPlaceholder('Tìm theo tên lớp, GVCN…').fill(name);await page.getByRole('button',{name:`Thao tác với lớp ${name}`}).click();const activate=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===`/api/v1/schools/${schoolId}/classes/${id}/activate`);await page.getByRole('menuitem',{name:/^Kích hoạt lớp/}).click();expect((await activate).status()).toBe(200);await page.reload();await expect(page.getByRole('link',{name,exact:true})).toBeVisible();return id;
 };
 classId=await create(className);targetClassId=await create(targetName);saveFixture();expect(errors).toEqual([]);
});

test('connected student UI saves own guardian data and keeps profile after reload',async()=>{
 if(studentId){await page.goto(`/school/${schoolId}/students/${studentId}`);await expect(page.getByRole('heading',{name:pupilName,exact:true})).toBeVisible();return;}
 await page.goto(`/school/${schoolId}/students/new`);await page.locator('[data-field="fullName"] input').fill(pupilName);await page.locator('[data-field="dob"] input').fill('10/09/2011');await page.getByLabel('Nam',{exact:true}).check();await page.getByLabel(/Mã học sinh/).fill(pupilCode);await page.getByRole('combobox',{name:/^Lớp/}).selectOption(classId);await page.getByLabel('Thêm người giám hộ ngay').check();await page.getByLabel('Họ và tên người giám hộ',{exact:false}).fill('Người Giám Hộ Tổng Hợp');await page.getByLabel('Số điện thoại',{exact:false}).fill('0912345678');
 const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===`/api/v1/schools/${schoolId}/students`);await page.getByRole('button',{name:'Lưu học sinh',exact:true}).click();const r=await response;expect(r.status()).toBe(201);studentId=(await r.json()).data.id;await page.waitForURL(`**/students/${studentId}`);await page.reload();await expect(page.getByRole('heading',{name:pupilName,exact:true})).toBeVisible();saveFixture();expect(errors).toEqual([]);
});

test('connected import UI uploads validates previews commits and reloads PostgreSQL result',async()=>{
 if(importId){expect((await get(`/api/v1/schools/${schoolId}/imports/${importId}`)).status).toBe('COMPLETED');await page.goto(`/school/${schoolId}/imports/${importId}`);await expect(page.getByRole('heading',{name:'Kết quả nhập',exact:true})).toBeVisible();return;}
 await page.goto(`/school/${schoolId}/imports/new`);await page.getByLabel('Lớp nhận',{exact:false}).selectOption(classId);await page.locator('input[type="file"]').setInputFiles({name:`run-${suffix}.csv`,mimeType:'text/csv',buffer:Buffer.from(`studentCode,fullName\nIM${suffix},${importName}\n`)});await page.getByRole('button',{name:'Tải và phân tích tệp',exact:true}).click();await page.waitForURL(/\/imports\/[0-9a-f-]{36}$/);importId=new URL(page.url()).pathname.split('/').at(-1)!;
 await expect(page.getByRole('button',{name:'Kiểm tra trên máy chủ',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Kiểm tra trên máy chủ',exact:true}).click();await expect(page.getByRole('button',{name:'Xác nhận nhập dữ liệu',exact:true})).toBeEnabled({timeout:60_000});await page.getByRole('button',{name:'Xác nhận nhập dữ liệu',exact:true}).click();await expect(page.getByText('Lô đã hoàn tất và dữ liệu đã được lưu.',{exact:true})).toBeVisible({timeout:60_000});await page.reload();await expect(page.getByRole('heading',{name:'Kết quả nhập',exact:true})).toBeVisible();const job=await get(`/api/v1/schools/${schoolId}/imports/${importId}`);expect(job.status).toBe('COMPLETED');expect(job.summary.added).toBe(1);saveFixture();expect(errors).toEqual([]);
});

test('connected attendance UI saves all shown students and publishes the exact retained sheet',async()=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/attendance`);
 await settled();
 if(retained&&await page.getByRole('button',{name:'Đã công bố cho phụ huynh',exact:true}).count()){for(const name of [pupilName,importName])await expect(page.getByRole('radiogroup',{name:`Trạng thái điểm danh của ${name}`,exact:true}).getByRole('radio',{name:/Có mặt/})).toBeChecked();await page.reload();await expect(page.getByRole('button',{name:'Đã công bố cho phụ huynh',exact:true})).toBeVisible();return;}
 for(const name of [pupilName,importName])await page.getByRole('radiogroup',{name:`Trạng thái điểm danh của ${name}`,exact:true}).getByRole('radio',{name:/Có mặt/}).click();
 await page.getByRole('button',{name:/^Lưu điểm danh/}).last().click();await expect(page.getByRole('button',{name:'Công bố cho phụ huynh',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Công bố cho phụ huynh',exact:true}).click();await page.getByRole('dialog',{name:'Công bố chuyên cần cho phụ huynh'}).getByRole('button',{name:'Công bố',exact:true}).click();await expect(page.getByRole('button',{name:'Đã công bố cho phụ huynh',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Đã công bố cho phụ huynh',exact:true})).toBeVisible();expect(errors).toEqual([]);
});

test('connected activity UI retains draft assignment and separate family publication with actual participants',async()=>{
 const root=`/classroom/${schoolId}/${yearId}/${classId}`,title='Hoạt động tổng hợp '+suffix;
 await page.goto(root+'/activities/new');await page.locator('[data-field="title"] input').fill(title);await page.locator('[data-field="description"] textarea').fill('Sản phẩm tổng hợp kiểm thử lưu thật và phân quyền.');await page.locator('[data-field="dueDate"] input').fill('09/10/2026');await page.locator('[data-field="dueDate"] input').press('Tab');await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await page.waitForURL(/\/activities\/[0-9a-f-]{36}$/);activityId=new URL(page.url()).pathname.split('/').at(-1)!;saveFixture();
 expect((await get(`/api/v1/schools/${schoolId}/classes/${classId}/activities/${activityId}`)).status).toBe('DRAFT');await page.getByRole('button',{name:'Giao hoạt động',exact:true}).click();await page.getByRole('dialog',{name:'Giao hoạt động',exact:true}).getByRole('button',{name:'Giao hoạt động',exact:true}).click();await expect(page.getByRole('button',{name:'Công bố',exact:true})).toBeVisible();
 expect((await get(`/api/v1/schools/${schoolId}/classes/${classId}/activities/${activityId}`)).status).toBe('ASSIGNED');expect(await get(`/api/v1/schools/${schoolId}/classes/${classId}/activities/${activityId}/participants`)).toHaveLength(2);await page.getByRole('button',{name:'Công bố',exact:true}).click();await expect(page.getByRole('button',{name:'Công bố lại',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Công bố lại',exact:true})).toBeVisible();expect(errors).toEqual([]);
});

test('connected class file UI uploads downloads real bytes and preserves archive restore after reload',async()=>{
 const filename='tai-lieu-'+suffix+'-'+crypto.randomBytes(3).toString('hex')+'.csv',bytes=Buffer.from('name,note\nTong hop,Tai lieu rieng kiem thu\n');
 await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/files`);await page.getByRole('button',{name:'Tải tệp lên',exact:true}).click();const modal=page.getByRole('dialog',{name:'Tải tệp lên',exact:true});await modal.locator('input[type="file"]').setInputFiles({name:filename,mimeType:'text/csv',buffer:bytes});await modal.getByRole('button',{name:'Tải lên',exact:true}).click();await expect(modal).toHaveCount(0,{timeout:60_000});await expect(page.getByRole('button',{name:filename,exact:true})).toBeVisible();await page.reload();
 await page.getByRole('button',{name:'Thao tác cho '+filename,exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('menuitem',{name:'Tải xuống',exact:true}).click();const file=await pending;const downloaded='.secrets/local/'+filename;await file.saveAs(downloaded);expect(fs.readFileSync(downloaded).equals(bytes)).toBe(true);
 await page.getByRole('button',{name:'Thao tác cho '+filename,exact:true}).click();await page.getByRole('menuitem',{name:'Lưu trữ',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Lưu trữ',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Thao tác cho '+filename,exact:true}).click();await page.getByRole('menuitem',{name:'Khôi phục',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Khôi phục',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Thao tác cho '+filename,exact:true}).click();await expect(page.getByRole('menuitem',{name:'Tải xuống',exact:true})).toBeEnabled();await page.keyboard.press('Escape');expect(errors).toEqual([]);
});

test('connected report UI creates polls and downloads server CSV with the persisted attendance rows',async()=>{
 await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/reports/attendance`);await expect(page.getByRole('button',{name:'Tải CSV',exact:true})).toBeVisible();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Tải CSV',exact:true}).click();const file=await pending;const target='.secrets/local/run-report-'+suffix+'.csv';await file.saveAs(target);const csv=fs.readFileSync(target,'utf8');expect(csv).toContain(pupilName);expect(csv).toContain(importName);
 const jobs=await get(`/api/v1/schools/${schoolId}/exports?classId=${classId}&limit=100`);expect(jobs.some((j:{status:string;rowCount:number})=>j.status==='COMPLETED'&&j.rowCount===2)).toBe(true);await page.goto(`/school/${schoolId}/exports`);await settled();expect(errors).toEqual([]);
});

test('connected newly wired core pages retain real receipts at 390 768 1440 with no body overflow or hydration errors',async()=>{
 const urls=[`/teacher/${schoolId}`,`/teacher/${schoolId}/tasks`,`/teacher/${schoolId}/schedule`,`/school/${schoolId}/publications`,`/school/${schoolId}/timetable`,`/school/${schoolId}/imports`,`/school/${schoolId}/imports/${importId}`,`/school/${schoolId}/transfers`,`/school/${schoolId}/reports`,`/school/${schoolId}/exports`,`/classroom/${schoolId}/${yearId}/${classId}/activities`,`/classroom/${schoolId}/${yearId}/${classId}/evidence`,`/classroom/${schoolId}/${yearId}/${classId}/files`,`/classroom/${schoolId}/${yearId}/${classId}/reports`,`/classroom/${schoolId}/${yearId}/${classId}/timetable`,`/classroom/${schoolId}/${yearId}/${classId}/conduct`,`/classroom/${schoolId}/${yearId}/${classId}/conduct/weekly`,`/classroom/${schoolId}/${yearId}/${classId}/conduct/review`];
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:1000});for(const url of urls){const response=await page.goto(url);expect(response?.status(),url).toBe(200);await settled();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),`${width} ${url}`).toBeLessThanOrEqual(1);await expect(page.locator('body')).not.toContainText('Trang chưa hiển thị được');await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toHaveCount(0);if(/\/conduct(?:\/weekly|\/review)?$/.test(url))await expect(page.getByText('Chưa có nội quy ban hành cho tuần này',{exact:true})).toBeVisible();}}
 expect(errors).toEqual([]);
});

test('connected evidence UI uploads actual private image reviews and republishes the selected student evidence',async()=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/evidence?activity=${activityId}`);await settled();await page.getByRole('button',{name:'Ghi nhận minh chứng',exact:true}).first().click();const modal=page.getByRole('dialog',{name:'Ghi nhận minh chứng',exact:true});await modal.getByRole('combobox',{name:/^Học sinh/}).click();await page.getByRole('option',{name:pupilName,exact:true}).click();await modal.locator('input[type="file"]').setInputFiles({name:`minh-chung-${suffix}.png`,mimeType:'image/png',buffer:fs.readFileSync('.secrets/local/run-evidence.png')});await modal.getByLabel('Ghi chú của giáo viên',{exact:false}).fill('Minh chứng tổng hợp riêng cho đúng học sinh.');await modal.getByRole('button',{name:'Ghi nhận',exact:true}).click();await expect(modal).toHaveCount(0,{timeout:60_000});await page.reload();await settled();
 const card=page.locator('li').filter({has:page.getByRole('button',{name:`Xem minh chứng của ${pupilName}`,exact:true})}).filter({has:page.getByRole('button',{name:'Duyệt',exact:true})}).last();await card.getByRole('button',{name:'Duyệt',exact:true}).click();const review=page.getByRole('dialog',{name:'Duyệt minh chứng',exact:true});await review.getByRole('switch',{name:/^Chia sẻ với phụ huynh của em này/}).check();await review.getByRole('button',{name:'Duyệt',exact:true}).click();await expect(review).toHaveCount(0);await page.reload();await expect(page.getByText('Đã chia sẻ phụ huynh',{exact:true}).last()).toBeVisible();const evidence=await get(`/api/v1/schools/${schoolId}/classes/${classId}/evidence?activityId=${activityId}`);const participants=await get(`/api/v1/schools/${schoolId}/classes/${classId}/activities/${activityId}/participants`);const student=await get(`/api/v1/schools/${schoolId}/students/${studentId}/details`);const participant=participants.find((p:{enrollmentId:string})=>p.enrollmentId===student.selectedEnrollment.id);expect(participant).toBeTruthy();expect(evidence.some((e:{participantId:string;status:string;shareWithGuardian:boolean})=>e.participantId===participant.id&&e.status==='APPROVED'&&e.shareWithGuardian)).toBe(true);
 await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/activities/${activityId}`);await page.getByRole('button',{name:'Công bố lại',exact:true}).click();await settled();expect(errors).toEqual([]);
});

test('connected announcement UI saves a rich draft publishes and keeps internal notes out of the family preview',async()=>{
 await page.setViewportSize({width:1440,height:1000});const root=`/classroom/${schoolId}/${yearId}/${classId}/announcements`,title='Thông báo nghiệm thu '+suffix;await page.goto(root+'/new');await page.locator('[data-field="title"] input').fill(title);await page.locator('[data-field="summary"] textarea').fill('Thông tin tổng hợp đã công bố cho gia đình.');await page.getByLabel('Đoạn văn 1',{exact:true}).fill('Nội dung thông báo tổng hợp kiểm tra lưu thật và tải lại.');await page.getByLabel('Ghi chú nội bộ',{exact:false}).fill('Ghi chú nội bộ nghiệm thu '+suffix);await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await page.waitForURL(/\/announcements\/[0-9a-f-]{36}$/);await page.reload();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(page.getByText('Nháp',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Công bố ngay',exact:true}).click();await page.getByRole('dialog',{name:/^Công bố thông báo/}).getByRole('button',{name:'Công bố',exact:true}).click();await page.reload();await expect(page.getByText('Đã công bố',{exact:true}).first()).toBeVisible();await expect(page.getByText('Nội dung thông báo tổng hợp kiểm tra lưu thật và tải lại.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Xem như phụ huynh',exact:true}).click();const preview=page.getByRole('dialog',{name:/^Xem trước/});await expect(preview).toContainText(title);await expect(preview).not.toContainText('Ghi chú nội bộ nghiệm thu');await preview.getByRole('button',{name:'Đóng',exact:true}).last().click();expect(errors).toEqual([]);
});

test('connected parent UI verifies guardian issues private link reads own publication and revokes an open browser session',async({browser})=>{
 await page.setViewportSize({width:1440,height:1000});const profile=`/school/${schoolId}/students/${studentId}`;await page.goto(profile);await settled();const details=await get(`/api/v1/schools/${schoolId}/students/${studentId}/details`),relation=details.relationships[0];expect(relation).toBeTruthy();
 if(relation.status!=='VERIFIED'){await page.getByRole('button',{name:`Thao tác với ${relation.guardian.fullName}`,exact:true}).click();await page.getByRole('menuitem',{name:'Xác minh quan hệ',exact:true}).click();const verify=page.getByRole('dialog',{name:'Xác minh quan hệ giám hộ',exact:true});await verify.getByRole('radio',{name:'Được nhận thông tin',exact:true}).check();await verify.getByLabel(/^Căn cứ xác minh/).fill('Đối chiếu hồ sơ tổng hợp kiểm thử, không dùng thông tin học sinh thật.');await verify.getByRole('button',{name:'Xác minh',exact:true}).click();await expect(verify).toHaveCount(0);await page.reload();}
 await page.getByRole('button',{name:'Cấp link mới',exact:true}).first().click();const issue=page.getByRole('dialog',{name:'Cấp đường dẫn riêng cho phụ huynh',exact:true});await issue.locator('input[name="issue-rel"]').check();await expect(issue.getByRole('button',{name:'Cấp link',exact:true})).toBeEnabled();await issue.getByRole('checkbox',{name:/^Hoạt động/}).check();await issue.getByRole('checkbox',{name:/^Tài liệu/}).check();await issue.getByRole('checkbox',{name:/^Cho phép tải tài liệu/}).check();await issue.getByRole('button',{name:'Cấp link',exact:true}).click();const receipt=page.getByRole('dialog',{name:'Đã cấp link tra cứu',exact:true});await expect(receipt).toBeVisible();const link=await receipt.getByRole('link',{name:'Mở link tra cứu',exact:true}).getAttribute('href');expect(link).toBeTruthy();const detailHref=await receipt.getByRole('link',{name:'Xem chi tiết quyền',exact:true}).getAttribute('href');await receipt.getByRole('button',{name:'Xong',exact:true}).click();
 const family=await browser.newContext({baseURL,viewport:{width:390,height:900}});try{const familyPage=await family.newPage();familyPage.on('pageerror',e=>errors.push(e.message));await familyPage.goto(link!);await familyPage.waitForURL(u=>!u.hash&&!u.pathname.endsWith('/access'));await expect(familyPage.getByText(pupilName,{exact:true}).first()).toBeVisible();const parentView=await familyPage.evaluate(()=>JSON.parse(sessionStorage.getItem('edu-parent-view')!)) as {slug:string;viewId:string};const read=async(path:string)=>family.request.get(`/api/v1/parent/${parentView.slug}/${path}`,{headers:{'X-Parent-View':parentView.viewId}});const contextResponse=await read('context');expect(contextResponse.status()).toBe(200);expect((await contextResponse.json()).data.student.displayName).toBe(pupilName);
 await familyPage.goto(`/p/${parentView.slug}/activities`);await expect(familyPage.getByText('Hoạt động tổng hợp '+suffix,{exact:true}).first()).toBeVisible();const docsResponse=await read('document-directory');expect(docsResponse.status()).toBe(200);const directory=(await docsResponse.json()).data;const docs=directory.files;expect(docs.some((d:{title:string})=>d.title===`minh-chung-${suffix}.png`)).toBe(true);expect(JSON.stringify(directory)).not.toContain(importName);expect(JSON.stringify(directory)).not.toContain('Minh chứng tổng hợp riêng');const forged=await read(`overview?studentId=${crypto.randomUUID()}`);expect(forged.status()).toBe(200);const forgedData=(await forged.json()).data;expect(forgedData.context.student.displayName).toBe(pupilName);expect(JSON.stringify(forgedData)).not.toContain(importName);expect((await family.request.get(`/api/v1/schools/${schoolId}/students/${studentId}/details`)).status()).toBe(401);
 await page.goto(detailHref!);await page.getByRole('button',{name:'Thu hồi',exact:true}).click();const revoke=page.getByRole('dialog',{name:'Thu hồi link tra cứu',exact:true});await revoke.getByLabel(/^Lý do thu hồi/).fill('Kết thúc phiên kiểm thử link riêng và kiểm tra thu hồi tức thời.');await revoke.getByRole('button',{name:'Thu hồi link',exact:true}).click();await expect(revoke).toHaveCount(0);expect((await read('context')).status()).toBe(401);await familyPage.reload();await familyPage.waitForURL(/access-unavailable/);await expect(familyPage.locator('body')).not.toContainText(importName);expect(errors).toEqual([]);
 }finally{await family.close();}
});

test('connected transfer UI creates shown-version request rejects it and approves a future move preserving past attendance',async()=>{
 if(retained){const existing=await get(`/api/v1/schools/${schoolId}/students/${studentId}/details`);if(existing.history.some((h:{classId:string;startsOn:string})=>h.classId===targetClassId&&h.startsOn==='2026-10-03')){expect(existing.history.some((h:{classId:string;endsOn:string})=>h.classId===classId&&h.endsOn==='2026-10-03')).toBe(true);await page.goto(`/school/${schoolId}/transfers`);await page.getByRole('searchbox').fill(pupilName);await settled();await expect(page.getByRole('row').filter({hasText:pupilName}).filter({hasText:'Từ chối'})).toHaveCount(1);await expect(page.getByRole('row').filter({hasText:pupilName}).filter({hasText:'Đã duyệt'})).toHaveCount(1);await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/attendance?date=2026-10-02`);await expect(page.getByRole('radiogroup',{name:`Trạng thái điểm danh của ${pupilName}`,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Đã công bố cho phụ huynh',exact:true})).toBeVisible();return;}}
 await page.setViewportSize({width:1440,height:1000});const root=`/school/${schoolId}/transfers`,reason='Chuyển lớp tổng hợp '+suffix;const create=async()=>{await page.goto(root);await page.getByRole('button',{name:'Tạo yêu cầu',exact:true}).click();const modal=page.getByRole('dialog',{name:'Chuyển lớp / ngừng theo học',exact:true});await modal.getByRole('combobox',{name:/^Học sinh/}).click();await page.getByRole('option',{name:new RegExp('^'+pupilName+' \\(')}).click();await modal.locator('[data-field="toClassId"] select').selectOption(targetClassId);await modal.locator('[data-field="effectiveDate"] input').fill('03/10/2026');await modal.locator('[data-field="effectiveDate"] input').press('Tab');await modal.getByLabel(/^Lý do/).fill(reason);await modal.getByRole('button',{name:'Gửi đề nghị',exact:true}).click();await expect(modal).toHaveCount(0);await page.reload();await page.getByRole('searchbox').fill(pupilName);await settled();};
 await create();let row=page.getByRole('row').filter({hasText:pupilName}).filter({has:page.getByRole('button',{name:'Từ chối',exact:true})});await row.getByRole('button',{name:'Từ chối',exact:true}).click();let decide=page.getByRole('dialog',{name:'Từ chối yêu cầu',exact:true});await decide.getByLabel(/^Lý do từ chối/).fill('Từ chối yêu cầu tổng hợp để kiểm tra lịch sử quyết định.');await decide.getByRole('button',{name:'Từ chối',exact:true}).click();await expect(decide).toHaveCount(0);await page.reload();await expect(page.getByRole('row').filter({hasText:pupilName}).filter({hasText:'Từ chối'})).toHaveCount(1);
 await create();row=page.getByRole('row').filter({hasText:pupilName}).filter({has:page.getByRole('button',{name:'Duyệt',exact:true})});await row.getByRole('button',{name:'Duyệt',exact:true}).click();decide=page.getByRole('dialog',{name:'Duyệt yêu cầu',exact:true});await decide.getByRole('button',{name:'Duyệt',exact:true}).click();await expect(decide).toHaveCount(0);await page.reload();const d=await get(`/api/v1/schools/${schoolId}/students/${studentId}/details`);expect(d.history.some((h:{classId:string;startsOn:string})=>h.classId===targetClassId&&h.startsOn==='2026-10-03')).toBe(true);expect(d.history.some((h:{classId:string;endsOn:string})=>h.classId===classId&&h.endsOn==='2026-10-03')).toBe(true);await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/attendance?date=2026-10-02`);await expect(page.getByRole('radiogroup',{name:`Trạng thái điểm danh của ${pupilName}`,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Đã công bố cho phụ huynh',exact:true})).toBeVisible();expect(errors).toEqual([]);
});

test('connected assignment and schedule UI validate publish discard drafts and publish a dated lesson cancellation',async()=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto(`/school/${schoolId}/assignments`);await page.getByRole('searchbox',{name:'Tìm lớp hoặc giáo viên',exact:true}).fill(targetName);const matrix=await get(`/api/v1/schools/${schoolId}/assignment-matrix?yearId=${yearId}`),matrixRow=matrix.rows.find((r:{classId:string})=>r.classId===targetClassId);expect(matrixRow).toBeTruthy();const subject=matrix.subjects[0],subjectId=subject.id,subjectName=subject.name;let teacherName:string;let drawer=page.getByRole('dialog',{name:'Gán phân công',exact:true});
 if(matrixRow.bySubject[subjectId]){const assignment=matrixRow.bySubject[subjectId];expect(assignment.accessActive).toBe(true);teacherName=assignment.name;}else{await page.getByRole('button',{name:/^Phân công/}).first().click();await drawer.getByRole('combobox',{name:/^Giáo viên/}).click();const chosen=page.getByRole('listbox').getByRole('option').first();teacherName=(await chosen.locator('span.text-ink').textContent())!;await chosen.click();await drawer.locator('[data-field="subjectId"] select').selectOption(subjectId);await drawer.getByRole('button',{name:'Xem trước quyền',exact:true}).click();drawer=page.getByRole('dialog',{name:'Xem thay đổi quyền',exact:true});await drawer.getByRole('button',{name:'Xác nhận phân công',exact:true}).click();await expect(drawer).toHaveCount(0);await page.reload();await page.getByRole('searchbox',{name:'Tìm lớp hoặc giáo viên',exact:true}).fill(targetName);}await expect(page.getByRole('row').filter({hasText:targetName})).toContainText(teacherName);
 const timetable=`/classroom/${schoolId}/${yearId}/${targetClassId}/timetable?week=2026-10-05`;await page.goto(timetable);await settled();const obsolete=page.getByRole('row').filter({has:page.getByRole('button',{name:'Xóa nháp',exact:true})});expect(await obsolete.count()).toBeLessThanOrEqual(1);if(await obsolete.count()){await obsolete.getByRole('button',{name:'Xóa nháp',exact:true}).click();const discardOld=page.getByRole('dialog',{name:'Xóa bản nháp đổi tiết',exact:true});await discardOld.getByRole('button',{name:'Xóa nháp',exact:true}).click();await expect(discardOld).toHaveCount(0);}await page.getByRole('button',{name:'Soạn thời khóa biểu',exact:true}).click();drawer=page.getByRole('dialog',{name:'Soạn thời khóa biểu',exact:true});await drawer.getByLabel(/^Áp dụng từ ngày/).fill('05/10/2026');await drawer.getByLabel(/^Áp dụng từ ngày/).press('Tab');await drawer.getByLabel(/^Áp dụng đến hết ngày/).fill('09/10/2026');await drawer.getByLabel(/^Áp dụng đến hết ngày/).press('Tab');await drawer.getByRole('button',{name:'Thêm tiết học',exact:true}).click();await drawer.getByLabel('Môn học',{exact:true}).selectOption(subjectId);await drawer.getByLabel('Giáo viên',{exact:true}).selectOption({label:teacherName});await drawer.getByLabel('Bắt đầu',{exact:true}).fill('10:00');await drawer.getByLabel('Kết thúc',{exact:true}).fill('10:45');await drawer.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(drawer.getByRole('button',{name:'Kiểm tra trùng giờ',exact:true})).toBeEnabled();await drawer.getByRole('button',{name:'Kiểm tra trùng giờ',exact:true}).click();await expect(drawer.getByText('Lịch hợp lệ để công bố',{exact:true})).toBeVisible();await drawer.getByRole('button',{name:'Công bố',exact:true}).click();await page.getByRole('dialog',{name:'Công bố thời khóa biểu',exact:true}).getByRole('button',{name:'Công bố',exact:true}).click();await expect(drawer).toHaveCount(0);await page.reload();const lessonButton=page.getByRole('button',{name:/^Đổi tiết 1/});await expect(lessonButton).toContainText(subjectName);await expect(lessonButton).toContainText(teacherName);
 await page.getByRole('button',{name:'Soạn thời khóa biểu',exact:true}).click();drawer=page.getByRole('dialog',{name:'Soạn thời khóa biểu',exact:true});await drawer.getByRole('button',{name:/^Chép lịch #/}).first().click();await drawer.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(drawer.getByRole('button',{name:'Hủy bản nháp',exact:true})).toBeVisible();await drawer.getByRole('button',{name:'Hủy bản nháp',exact:true}).click();await page.getByRole('dialog',{name:'Hủy bản nháp thời khóa biểu',exact:true}).getByRole('button',{name:'Hủy bản nháp',exact:true}).click();await expect(drawer.getByRole('button',{name:'Hủy bản nháp',exact:true})).toHaveCount(0);await drawer.getByRole('button',{name:'Đóng',exact:true}).last().click();await page.reload();await expect(lessonButton).toContainText(subjectName);
 await lessonButton.click();drawer=page.getByRole('dialog',{name:'Đổi tiết',exact:true});await drawer.getByRole('radio',{name:'Nghỉ tiết (hủy)',exact:true}).check();await drawer.getByLabel(/^Lý do/).fill('Lịch nghỉ tiết tổng hợp '+suffix);await drawer.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(drawer).toHaveCount(0);await page.goto(`/school/${schoolId}/timetable`);await page.getByRole('button',{name:'Tuần sau',exact:true}).click();const change=page.locator('li').filter({hasText:'Lịch nghỉ tiết tổng hợp '+suffix}).filter({has:page.getByRole('button',{name:'Công bố',exact:true})});await change.getByRole('button',{name:'Công bố',exact:true}).click();const publishChange=page.getByRole('dialog',{name:'Công bố đổi tiết',exact:true});await publishChange.getByRole('button',{name:'Công bố',exact:true}).click();await expect(publishChange).toHaveCount(0);await page.goto(timetable);await expect(lessonButton).toContainText('Nghỉ: Lịch nghỉ tiết tổng hợp '+suffix);const versions=await get(`/api/v1/schools/${schoolId}/classes/${targetClassId}/timetables?limit=100`);expect(versions.some((v:{status:string})=>v.status==='PUBLISHED')).toBe(true);expect(versions.some((v:{status:string})=>v.status==='ARCHIVED')).toBe(true);expect(errors).toEqual([]);
});

test('connected cross-school browser cannot read profiles classes private export bytes or school screens',async({browser})=>{
 const exports=await get(`/api/v1/schools/${schoolId}/exports?classId=${classId}&limit=100`),exportId=exports.find((j:{status:string})=>j.status==='COMPLETED')?.id;expect(exportId).toBeTruthy();const other=await browser.newContext({baseURL});try{const otherPage=await other.newPage();await otherPage.goto('/login');await otherPage.getByLabel(/^Email công việc/).fill('admin-b@example.invalid');await otherPage.getByLabel(/^Mật khẩu/).fill(fs.readFileSync('.secrets/local/local_test_password','utf8').trim());await otherPage.getByRole('button',{name:'Đăng nhập',exact:true}).click();await otherPage.waitForURL(u=>u.pathname!='/login');const own=await other.request.get('/api/v1/me/context');expect(own.status()).toBe(200);expect((await own.json()).data.memberships.some((m:{schoolId:string})=>m.schoolId===schoolId)).toBe(false);
  for(const path of [`students/${studentId}/details`,`classes/${classId}`,`exports/${exportId}/download`]){const response=await other.request.get(`/api/v1/schools/${schoolId}/${path}`);expect([403,404]).toContain(response.status());expect(await response.text()).not.toContain(pupilName);}
  await otherPage.goto(`/school/${schoolId}/students`);await otherPage.waitForLoadState('networkidle');await expect(otherPage.getByText('Không tìm thấy',{exact:true}).or(otherPage.getByText('Bạn không có quyền xem mục này',{exact:true})).or(otherPage.getByText('Quyền truy cập đã thay đổi',{exact:true}))).toBeVisible();await expect(otherPage.locator('body')).not.toContainText(pupilName);expect(errors).toEqual([]);
 }finally{await other.close();}
});

test('connected common query error recovers after a real API restart without losing the retained activity',async()=>{
 const dc=['compose','--project-directory','D:/Edu/edu','--env-file','.env.local-docker','-f','deploy/compose.local.yml','-p','edumanage_local'];await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/activities/${activityId}`);await settled();try{execFileSync('docker',[...dc,'stop','-t','15','api'],{stdio:'pipe',timeout:30_000});await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/evidence`);await expect(page.getByText(/^Không tải được dữ liệu/).first()).toBeVisible();}finally{execFileSync('docker',[...dc,'up','-d','--wait','--wait-timeout','60','--no-deps','api'],{stdio:'pipe',timeout:75_000});}
 await page.getByRole('button',{name:'Thử lại',exact:true}).first().click();await settled();await expect(page.getByText(/^Không tải được dữ liệu/)).toHaveCount(0);await page.goto(`/classroom/${schoolId}/${yearId}/${classId}/activities/${activityId}`);await expect(page.getByRole('heading',{name:'Hoạt động tổng hợp '+suffix,exact:true})).toBeVisible();expect((await get(`/api/v1/schools/${schoolId}/classes/${classId}/activities/${activityId}`)).status).toBe('ASSIGNED');expect(errors).toEqual([]);
});

test('connected conduct ADD adjustment UI preserves the old publication until approval and explicit republication',async()=>{
 await page.setViewportSize({width:1440,height:1000});const c=original.classId,root=`/classroom/${schoolId}/${yearId}/${c}`,api=`/api/v1/schools/${schoolId}/years/${yearId}/classes/${c}/conduct-workspace`;
 const workspace=await get(api+'/adjustments'),baseline=workspace.snapshots.find((s:{status:string;weekId:string})=>s.status==='published'&&s.weekId===original.weekId);expect(baseline).toBeTruthy();const detail=await get(api+'/snapshots/'+baseline.id),student=baseline.rows.find((r:{studentId:string})=>r.studentId===original.studentId);expect(student).toBeTruthy();const rule=detail.ruleSet.rules.find((r:{attendanceLink:boolean;valueMode:string;points:number})=>!r.attendanceLink&&r.valueMode==='FIXED'&&r.points<0);expect(rule).toBeTruthy();const reason='Bổ sung ghi nhận kiểm thử tổng hợp '+crypto.randomBytes(4).toString('hex');
 await page.goto(root+'/adjustments');await page.getByRole('button',{name:'Đề nghị điều chỉnh',exact:true}).click();let modal=page.getByRole('dialog',{name:'Đề nghị điều chỉnh sau chốt',exact:true});await modal.locator('[data-field="snapshotId"] select').selectOption(baseline.id);await modal.getByRole('combobox',{name:/^Học sinh/}).click();await page.getByRole('option',{name:new RegExp('^'+student.studentName)}).click();await modal.getByRole('radio',{name:'Bổ sung ghi nhận',exact:true}).check();await modal.locator('[data-field="ruleId"] select').selectOption(rule.id);await modal.locator('[data-field="date"] input').fill('2026-10-02');await modal.locator('[data-field="reason"] textarea').fill(reason);await modal.getByRole('button',{name:'Gửi đề nghị',exact:true}).click();await expect(modal).toHaveCount(0);await page.reload();const requested=(await get(api+'/adjustments')).items.find((a:{reason:string})=>a.reason===reason);expect(requested.kind).toBe('add_record');expect(requested.status).toBe('pending');expect((await get(api+'/snapshots/'+baseline.id)).snapshot).toEqual(detail.snapshot);
 let item=page.getByTestId('adj-list').locator('li').filter({hasText:reason});await item.getByRole('button',{name:'Duyệt',exact:true}).click();modal=page.getByRole('dialog',{name:'Duyệt điều chỉnh',exact:true});await modal.getByRole('button',{name:'Duyệt và tạo bản mới',exact:true}).click();await expect(modal).toHaveCount(0);await page.reload();const approved=(await get(api+'/adjustments')).items.find((a:{id:string})=>a.id===requested.id);expect(approved.status).toBe('approved');expect((await get(api+'/snapshots/'+baseline.id)).snapshot).toEqual(detail.snapshot);await item.getByRole('button',{name:'Công bố lại',exact:true}).click();modal=page.getByRole('dialog',{name:'Công bố lại sau điều chỉnh',exact:true});await modal.getByRole('button',{name:'Công bố lại',exact:true}).click();await expect(modal).toHaveCount(0);await page.reload();const published=(await get(api+'/adjustments')).items.find((a:{id:string})=>a.id===requested.id);expect(published.status).toBe('published');expect(published.resultSnapshotId).toBeTruthy();const next=await get(api+'/snapshots/'+published.resultSnapshotId),old=await get(api+'/snapshots/'+baseline.id);expect(next.snapshot.status).toBe('published');expect(old.snapshot.status).toBe('superseded');expect(old.snapshot.rows).toEqual(detail.snapshot.rows);const after=next.snapshot.rows.find((r:{studentId:string})=>r.studentId===student.studentId);expect(after.total).toBe(published.afterTotal);expect(after.items).toHaveLength(student.items.length+1);expect(after.items.some((i:{label:string;points:number})=>i.label===rule.label&&i.points===rule.points)).toBe(true);expect(errors).toEqual([]);
});

test('connected school policy UI saves reloads restores the setting and preserves published conduct rows',async()=>{
 const api=`/api/v1/schools/${schoolId}`,snapApi=`${api}/years/${yearId}/classes/${original.classId}/conduct-workspace`,current=(await get(snapApi+'/adjustments')).snapshots.find((s:{status:string;weekId:string})=>s.status==='published'&&s.weekId===original.weekId);expect(current).toBeTruthy();const before=await get(snapApi+'/snapshots/'+current.id),policy=(await get(api+'/publication-policy')).policy;
 const saveDay=async(day:string)=>{await page.goto(`/school/${schoolId}/publication-policy`);await page.getByRole('group',{name:'Hạn chốt tuần',exact:true}).getByRole('radio',{name:day==='sunday'?'Chủ nhật cùng tuần':'Thứ Hai tuần sau',exact:true}).check();await page.getByRole('button',{name:'Lưu quy trình',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Lưu quy trình chốt và công bố',exact:true});await dialog.getByRole('button',{name:'Lưu',exact:true}).click();await expect(dialog).toHaveCount(0);await page.reload();await expect(page.getByRole('group',{name:'Hạn chốt tuần',exact:true}).getByRole('radio',{name:day==='sunday'?'Chủ nhật cùng tuần':'Thứ Hai tuần sau',exact:true})).toBeChecked();expect((await get(api+'/publication-policy')).policy.weekCloseDay).toBe(day);};
 try{await saveDay(policy.weekCloseDay==='sunday'?'monday':'sunday');expect((await get(snapApi+'/snapshots/'+current.id)).snapshot).toEqual(before.snapshot);}finally{const now=(await get(api+'/publication-policy')).policy;if(now.weekCloseDay!==policy.weekCloseDay)await saveDay(policy.weekCloseDay);}
 const after=(await get(api+'/publication-policy')).policy;expect({...after,version:policy.version}).toEqual(policy);expect(after.version).toBe(policy.version+2);expect(errors).toEqual([]);
});

test('connected rules UI copies edits reloads and issues a future version without changing the old conduct snapshot',async()=>{
 const ruleDates=(await get(`/api/v1/schools/${schoolId}/rule-workspace`)).items.map((r:{effectiveFrom:string})=>Date.parse(r.effectiveFrom)).filter(Number.isFinite);const effective=new Date(Math.max(Date.parse('2026-11-16'),...ruleDates)+7*24*60*60*1000).toISOString().slice(0,10);
 const api=`/api/v1/schools/${schoolId}`,snapApi=`${api}/years/${yearId}/classes/${original.classId}/conduct-workspace`,directory=await get(api+'/rule-workspace'),draft=directory.items.find((r:{status:string})=>r.status==='draft');expect(!draft||draft.name.startsWith('Nội quy tổng hợp '),'preserve any draft outside this synthetic browser test namespace').toBe(true);const current=(await get(snapApi+'/adjustments')).snapshots.find((s:{status:string;weekId:string})=>s.status==='published'&&s.weekId===original.weekId),before=await get(snapApi+'/snapshots/'+current.id),name='Nội quy tổng hợp '+crypto.randomBytes(4).toString('hex');
 let id=draft?.id;let modal=page.getByRole('dialog',{name:'Tạo bản nội quy mới',exact:true});if(id){await page.goto(`/school/${schoolId}/conduct-rules/${id}`);}else{await page.goto(`/school/${schoolId}/conduct-rules`);await page.getByRole('button',{name:'Tạo bản mới',exact:true}).click();await modal.getByRole('button',{name:'Tạo bản nháp',exact:true}).click();await page.waitForURL(/\/conduct-rules\/[0-9a-f-]{36}$/);id=new URL(page.url()).pathname.split('/').at(-1)!;}fs.writeFileSync('.secrets/local/run-rules-fixture.json',JSON.stringify({id,name,source:'synthetic real browser draft'}));await page.locator('[data-field="name"] input').fill(name);await page.locator('[data-field="effectiveFrom"] input').fill(effective.split('-').reverse().join('/'));await page.locator('[data-field="effectiveFrom"] input').press('Tab');await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.getByText('Đã lưu bản nháp nội quy',{exact:true})).toBeVisible();await page.reload();await expect(page.locator('[data-field="name"] input')).toHaveValue(name);await page.getByRole('button',{name:'Ban hành',exact:true}).click();modal=page.getByRole('dialog',{name:'Ban hành nội quy',exact:true});await modal.getByRole('button',{name:'Ban hành',exact:true}).click();await expect(modal).toHaveCount(0);await page.reload();const next=await get(api+'/rule-workspace/'+id);expect(next.ruleSet.status).toBe('published');expect(next.ruleSet.effectiveFrom).toBe(effective);expect(next.ruleSet.name).toBe(name);const old=await get(snapApi+'/snapshots/'+current.id);expect(old.snapshot).toEqual(before.snapshot);expect(old.ruleSet).toEqual(before.ruleSet);expect(errors).toEqual([]);
});
