import 'reflect-metadata';
import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import {Pool} from 'pg';
import {migrate} from '../../dist/database/migrate.js';
import {seedLocal,seedId} from '../../dist/modules/identity/seed.js';
import {Database} from '../../dist/database/database.js';
import {databaseConfig} from '../../dist/common/config.js';
import {hashPassword} from '../../dist/common/security.js';
import {createApplication} from '../../dist/main.js';
import {WorkerRunner} from '../../dist/workers/runner.js';
const prefix=crypto.randomUUID(),tsvCode='PASTE-'+prefix;
const password='Aa1-'+crypto.randomBytes(24).toString('base64url'),school=seedId('school:A'),other=seedId('school:B'),year=seedId('year:A'),cls=seedId('class:A:10A1'),admin=seedId('user:admin-a'),contract=JSON.parse(await fs.readFile('src/generated/contract.json','utf8')),jar=new Map();
let db,raw,app,server,csrf,today,worker,draft,role,teacherEmail,teacherId;
function route(op,params={}){return contract.operations.find(o=>o.id===op).path.replace(/\{([^}]+)\}/g,(_,k)=>({schoolId:school,yearId:year,classId:cls,...params})[k]);}
async function req(op,body,params={}){const method=contract.operations.find(o=>o.id===op).method,r=await server.inject({method,url:route(op,params),headers:{origin:process.env.APP_URL,cookie:[...jar].map(([k,v])=>`${k}=${v}`).join('; '),...(method==='GET'?{}:{'x-csrf-token':csrf,'idempotency-key':crypto.randomUUID()})},...(body===undefined?{}:{payload:body})});for(const c of r.cookies)jar.set(c.name,c.value);return r;}
async function good(op,body,params={}){const r=await req(op,body,params);assert.ok(r.statusCode>=200&&r.statusCode<300,r.body);return r.json().data;}
async function login(email='admin-a@example.invalid'){jar.clear();const bootstrap=await server.inject({method:'GET',url:'/api/v1/auth/csrf'});for(const c of bootstrap.cookies)jar.set(c.name,c.value);const r=await server.inject({method:'POST',url:'/api/v1/auth/login',headers:{origin:process.env.APP_URL,cookie:[...jar].map(([k,v])=>`${k}=${v}`).join('; '),'x-csrf-token':bootstrap.json().data.csrfToken},payload:{email,password}});assert.equal(r.statusCode,200,r.body);for(const c of r.cookies)jar.set(c.name,c.value);csrf=r.json().data.csrfToken;}
const scoped=fn=>db.transaction(fn,{schoolId:school,userId:admin});
async function drain(){for(let i=0;i<100;i++){const event=await worker.claim(school);if(!event)return;await worker.run(event);}assert.fail('Queue did not drain');}
async function settle(id,target){for(let i=0;i<30;i++){await drain();const j=await good('getImport',undefined,{importId:id});if(j.status===target)return j;assert.notEqual(j.status,'FAILED');}assert.fail('Worker did not settle');}
async function paste(rows,classId=draft.id){const j=await good('createStudentPasteImport',{yearId:year,classId,startsOn:today,rows});return settle(j.id,'READY');}
async function commit(j){await good('commitImport',{expectedVersion:j.version,previewHash:j.previewHash},{importId:j.id});return settle(j.id,'COMPLETED');}
before(async()=>{assert.equal(process.env.APP_ENV,'test');assert.equal(process.env.DB_NAME,'edumanage_test_local');await migrate();await seedLocal(password,true);raw=new Pool(databaseConfig('migrator'));db=new Database();await raw.query('UPDATE identity.users SET password_hash=$1,must_change_password=false',[await hashPassword(password)]);app=await createApplication();server=app.getHttpAdapter().getInstance();await server.ready();worker=new WorkerRunner();await login();today=(await good('getClassNotebookWorkspace')).today;role=(await good('getStaffInvitationOptions')).roles.find(r=>r.code==='TEACHER');const grade=await good('createDictionary',{code:'UQA-'+prefix,name:'Khối QA usability',gradeLevel:11},{dictionary:'grades'});draft=await good('createClass',{code:'UQA-'+prefix,name:'UQA-'+prefix,yearId:year,gradeLevelId:grade.id,capacity:100});});
after(async()=>{if(process.env.USABILITY_EVIDENCE_DIR){await fs.mkdir(process.env.USABILITY_EVIDENCE_DIR,{recursive:true});await fs.writeFile(process.env.USABILITY_EVIDENCE_DIR+'/fixture.json',JSON.stringify({fixture:'USABILITY_QA',databaseName:'edumanage_test_local',schoolId:school,otherSchoolId:other,yearId:year,classId:cls,draftClassId:draft?.id,today,adminEmail:'admin-a@example.invalid',teacherEmail,password}));}await worker?.close();await app?.close();await db?.onApplicationShutdown();await raw?.end();});
test('Direct Staff creates without SMTP, on DRAFT homeroom and active subject; explicit identity assignment preserves password',async()=>{
 const subject=await good('createDictionary',{code:'SU-'+prefix,name:'Môn QA usability'},{dictionary:'subjects'}),common={displayName:'Giáo viên usability QA',roleId:role.id,password,mustChangePassword:false};
 for(const kind of ['NONE','HOMEROOM','SUBJECT']){const email=`${kind}-${crypto.randomUUID()}@example.invalid`,staff=await good('createSchoolStaffAccount',{...common,email,...(kind==='NONE'?{}:{assignment:{kind,classId:draft.id,startsOn:today,...(kind==='SUBJECT'?{subjectId:subject.id}:{})}})});assert.equal(staff.status,'ACTIVE');if(kind==='HOMEROOM'){teacherEmail=email;teacherId=staff.id;}assert.equal((await req('createSchoolStaffAccount',{...common,email})).statusCode,409);}
 const current=await good('getClass',undefined,{classId:draft.id});assert.equal(current.status,'DRAFT');assert.equal((await scoped(tx=>tx.query("SELECT id FROM app.teaching_assignments WHERE class_id=$1 AND kind='HOMEROOM' AND revoked_at IS NULL",[draft.id]))).rowCount,1);
 assert.equal((await req('createSchoolStaffAccount',{...common,email:`bad-${crypto.randomUUID()}@example.invalid`,assignment:{kind:'SUBJECT',classId:draft.id,subjectId:subject.id,startsOn:'1900-01-01'}})).statusCode,422);
 await login('admin-b@example.invalid');const bRole=(await good('getStaffInvitationOptions',undefined,{schoolId:other})).roles.find(r=>r.code==='TEACHER'),email=`existing-${crypto.randomUUID()}@example.invalid`;const existing=await good('createSchoolStaffAccount',{...common,email,roleId:bRole.id},{schoolId:other}),before=(await raw.query('SELECT password_hash FROM identity.users WHERE id=$1',[existing.userId])).rows[0].password_hash;
 await login();await good('assignExistingSchoolStaffAccount',{displayName:common.displayName,email,roleId:role.id});assert.equal((await raw.query('SELECT password_hash FROM identity.users WHERE id=$1',[existing.userId])).rows[0].password_hash,before);
 assert.equal((await scoped(tx=>tx.query('SELECT id FROM app.staff_invitations WHERE school_id=$1',[school]))).rowCount,0);assert.equal((await raw.query('SELECT id FROM identity.mail_outbox')).rowCount,0);
});
test('paste names generates ten unique atomic codes, preserves duplicate-name identities and import receipts/history',async()=>{
 const rows=Array.from({length:10},(_,i)=>({fullName:i<2?'Nguyễn Văn An usability':`Học sinh usability ${i}`}));let j=await paste(rows);assert.equal(j.source,'PASTE');assert.equal(j.summary.added,10);assert.equal(j.summary.invalid,0);const preview=await good('listImportRows',undefined,{importId:j.id});assert.ok(preview[0].warnings.length);assert.ok(preview[1].warnings.length);
 const saved=await commit(j);assert.equal(saved.summary.added,10);assert.equal(saved.summary.processed,10);const data=(await scoped(tx=>tx.query('SELECT s.* FROM app.students s JOIN app.import_rows r ON r.school_id=s.school_id AND r.result_id=s.id WHERE r.import_id=$1',[j.id]))).rows;assert.equal(new Set(data.map(s=>s.student_code)).size,10);assert.ok(data.every(s=>/^HS\d+$/.test(s.student_code)&&s.date_of_birth===null&&s.gender===null));assert.equal(data.filter(s=>s.full_name==='Nguyễn Văn An usability').length,2);
 assert.equal((await good('getImport',undefined,{importId:j.id})).status,'COMPLETED');assert.equal((await req('commitImport',{expectedVersion:j.version,previewHash:j.previewHash},{importId:j.id})).statusCode,409);
 // The same file reimport still requires explicit student codes in FILE mode.
 const legacy=await good('createImport',{kind:'STUDENTS',fileId:j.fileId,yearId:year,classId:draft.id});await drain();const parsed=await good('getImport',undefined,{importId:legacy.id});await good('validateImport',{expectedVersion:parsed.version,mode:'ADD_ONLY',mapping:[{sourceColumn:'fullName',targetField:'fullName'}]},{importId:legacy.id});const checked=await settle(legacy.id,'READY');assert.equal(checked.summary.invalid,10);assert.equal((await req('commitImport',{expectedVersion:checked.version,previewHash:checked.previewHash},{importId:legacy.id})).statusCode,422);
});
test('paste partial results reject code/DOB errors, retain guardians unverified, enforce tenant and current class authority',async()=>{
 let j=await paste([{studentCode:tsvCode,fullName:'Học sinh TSV Nam',dateOfBirth:'01/02/2010',gender:'Nam',guardianName:'Phụ huynh QA',guardianPhone:'0977123456',relationshipLabel:'Cha'},{studentCode:tsvCode,fullName:'Mã trùng'},{fullName:'Ngày sai',dateOfBirth:'31/02/2010'},{fullName:'Học sinh TSV Nữ',dateOfBirth:'03/04/2010',gender:'Nữ'}]);assert.equal(j.summary.added,2);assert.equal(j.summary.invalid,2);const preview=await good('listImportRows',undefined,{importId:j.id});assert.ok(preview[1].errors.some(e=>e.field==='studentCode'));j=await commit(j);assert.equal(j.summary.added,2);assert.equal(j.summary.invalid,2);assert.equal(j.summary.processed,2);const rel=(await scoped(tx=>tx.query("SELECT r.status,r.can_receive_info FROM app.guardian_relationships r JOIN app.students s ON s.school_id=r.school_id AND s.id=r.student_id WHERE s.student_code=$1",[tsvCode]))).rows[0];assert.equal(rel.status,'UNVERIFIED');assert.equal(rel.can_receive_info,false);
 const existing=await paste([{studentCode:tsvCode,fullName:'Không ghi đè'}]);assert.equal(existing.summary.invalid,1);assert.equal((await req('commitImport',{expectedVersion:existing.version,previewHash:existing.previewHash},{importId:existing.id})).statusCode,422);
 assert.ok([403,404].includes((await req('getImport',undefined,{schoolId:other,importId:j.id})).statusCode));
 const writeRole=await good('createRole',{code:'PASTE_'+prefix,label:'Thêm học sinh đúng lớp QA',permissions:[{action:'student.manage',scopes:['CLASS']}]});await good('createGrant',{memberId:teacherId,roleId:writeRole.id,scopeType:'CLASS',classId:draft.id,validFrom:new Date().toISOString()});
 await login(teacherEmail);const options=await good('getStudentCreateOptions');assert.ok(options.classes.some(c=>c.id===draft.id));let own=await paste([{fullName:'Học sinh do GVCN được cấp quyền thêm'}]);assert.equal(own.summary.added,1);own=await commit(own);assert.equal(own.summary.added,1);assert.ok([403,404].includes((await req('createStudentPasteImport',{yearId:year,classId:cls,startsOn:today,rows:[{fullName:'Sai quyền lớp'}]})).statusCode));await login();
});
