import { Module } from '@nestjs/common';
import { Database } from './database/database';
import { IdentityService } from './modules/identity/identity.service';
import { Permissions } from './common/permissions';
import { Commands } from './common/commands';
import { OrganizationService } from './modules/academics/organization.service';
import { StudentsService } from './modules/students/students.service';
import { InvitationsService } from './modules/identity/invitations.service';
import { StaffService } from './modules/staff/staff.service';
import { TransitionsService } from './modules/students/transitions.service';
import { FilesService } from './modules/files/files.service';
import { ImportsService } from './modules/imports/imports.service';
import { PublicationsService } from './modules/publications/publications.service';
import { AttendanceService } from './modules/attendance/attendance.service';
import { RulesService } from './modules/conduct/rules.service';
import { ConductService } from './modules/conduct/conduct.service';
import { AdjustmentsService } from './modules/conduct/adjustments.service';
import { ParentService } from './modules/parents/parent.service';
import { ParentAccessService } from './modules/parents/access.service';
import { ClassroomService } from './modules/classroom/classroom.service';
import { ScheduleService } from './modules/schedule/schedule.service';
import { ActivitiesService } from './modules/activities/activities.service';
import { AnnouncementsService } from './modules/announcements/announcements.service';
import { SettingsService } from './modules/settings/settings.service';
import { NotificationsService } from './modules/notifications/notifications.service';
import { DashboardsService } from './modules/dashboards/dashboards.service';
import { PlatformService } from './modules/platform/platform.service';
import { SupportService } from './modules/support/support.service';
const services=[Database,IdentityService,Permissions,Commands,OrganizationService,StudentsService,InvitationsService,StaffService,TransitionsService,FilesService,ImportsService,PublicationsService,AttendanceService,RulesService,ConductService,AdjustmentsService,ParentService,ParentAccessService,ClassroomService,ScheduleService,ActivitiesService,AnnouncementsService,SettingsService,NotificationsService,DashboardsService,PlatformService,SupportService];
@Module({providers:services,exports:services})
export class AppModule {}
