import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter,type NestFastifyApplication } from '@nestjs/platform-fastify';
import cookie from '@fastify/cookie';
import multipart from '@fastify/multipart';
import { AppModule } from './app.module';
import { Database } from './database/database';
import { IdentityService } from './modules/identity/identity.service';
import { Permissions } from './common/permissions';
import { installRoutes,registerHandlers } from './api.router';
import { OrganizationService } from './modules/academics/organization.service';
import { StudentsService } from './modules/students/students.service';
import { InvitationsService } from './modules/identity/invitations.service';
import { StaffService } from './modules/staff/staff.service';
import { TransitionsService } from './modules/students/transitions.service';
import { FilesService } from './modules/files/files.service';
import { ImportsService } from './modules/imports/imports.service';
import { PublicationsService } from './modules/publications/publications.service';
import { AttendanceService } from './modules/attendance/attendance.service';
import { RulesService } from './modules/conduct/rules.service';
import { ConductService } from './modules/conduct/conduct.service';
import { AdjustmentsService } from './modules/conduct/adjustments.service';
import { runtimeConfig } from './common/config';

export async function createApplication() {
  runtimeConfig();
  const adapter=new FastifyAdapter({logger:false,bodyLimit:1024*1024,trustProxy:false});
  const app=await NestFactory.create<NestFastifyApplication>(AppModule,adapter,{logger:false});
  const server=adapter.getInstance();
  await server.register(cookie);
  await server.register(multipart,{limits:{files:1,fields:2,parts:3,fileSize:25*1024*1024,fieldSize:256,fieldNameSize:32,headerPairs:100}});
  installRoutes(server,app.get(Database),app.get(IdentityService),app.get(Permissions));
  registerHandlers(server,app.get(OrganizationService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(StudentsService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(InvitationsService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(StaffService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(TransitionsService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(FilesService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(ImportsService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(PublicationsService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(AttendanceService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(RulesService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(ConductService).handlers(),app.get(IdentityService));
  registerHandlers(server,app.get(AdjustmentsService).handlers(),app.get(IdentityService));
  app.enableShutdownHooks();
  await app.init();
  return app;
}
if(require.main===module)createApplication().then(async app=>{
  await app.listen(Number(process.env.PORT??3001),'0.0.0.0');
  process.stdout.write(JSON.stringify({event:'api_ready_to_listen',buildSha:runtimeConfig().buildSha})+'\n');
}).catch(()=>{process.stderr.write('{"event":"startup_failed"}\n');process.exitCode=1;});
