"use client";
import {useMemo,useState} from 'react';
import {http} from '@/lib/api/client';
import type {ApiSchemas} from '@/lib/api/generated';
import {useRepo} from '@/lib/query/hooks';
import {parseTimetableSheet,resolveTimetableRows,normalizeAlias,SUPPORTED_TIMETABLE_EXTENSIONS,type SpreadsheetSheet,type ImportSettings} from '@/lib/domain/timetable-import';
import {Button} from '@/components/ui/button';
import {Modal} from '@/components/ui/dialog';
import {SelectField,TextField} from '@/components/ui/form';
type Draft={classId:string;className:string;source:ApiSchemas['Timetable'];canPublish:boolean;validation:ApiSchemas['ScheduleConflicts'];published:boolean};
function readFile(file:File){return new Promise<SpreadsheetSheet[]>(async(resolve,reject)=>{
 if(!SUPPORTED_TIMETABLE_EXTENSIONS.some(ext=>file.name.toLowerCase().endsWith('.'+ext))||file.size>5*1024*1024){reject(new Error('Chọn XLSX/XLS/XLSM/CSV/ODS, tối đa 5 MB'));return;}
 const worker=new Worker(new URL('../../lib/domain/timetable-file-worker.ts',import.meta.url)),timer=setTimeout(()=>{worker.terminate();reject(new Error('Workbook mất quá nhiều thời gian xử lý'));},15000);
 worker.onmessage=e=>{clearTimeout(timer);worker.terminate();e.data.error?reject(new Error(e.data.error)):resolve(e.data.sheets);};worker.onerror=()=>{clearTimeout(timer);worker.terminate();reject(new Error('Không đọc được workbook'));};
 try{const buffer=await file.arrayBuffer();worker.postMessage(buffer,[buffer]);}catch(e){clearTimeout(timer);worker.terminate();reject(e);}
});}
export function TimetableImportDialog({schoolId,classId,yearId,onSaved}:{schoolId:string;classId:string;yearId:string;onSaved:()=>void}){
 const [ignored,setIgnored]=useState<string[]>([]),[open,setOpen]=useState(false),[sheets,setSheets]=useState<SpreadsheetSheet[]>([]),[sheetIndex,setSheetIndex]=useState(0),[settings,setSettings]=useState<ImportSettings|null>(null),[classes,setClasses]=useState<Record<string,string>>({}),[from,setFrom]=useState(''),[to,setTo]=useState(''),[all,setAll]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drafts,setDrafts]=useState<Draft[]>([]);
 const [manual,setManual]=useState(false),[headerRow,setHeaderRow]=useState(1),[columns,setColumns]=useState({classColumn:0,dayColumn:1,periodColumn:2,subjectColumn:3,teacherColumn:4,roomColumn:5});
 const q=useRepo(['timetable-import-options',schoolId,classId,open],async()=>{const [workspace,config]=await Promise.all([http('getScheduleWorkspace',{params:{schoolId},query:{yearId}}),http('getScheduleImportSettings',{params:{schoolId}})]);return {workspace:workspace.data,config:config.data};},{enabled:open});
 const config=settings??q.data?.config,parsed=useMemo(()=>sheets[sheetIndex]?parseTimetableSheet(sheets[sheetIndex]!,manual?{...columns,headerRow:headerRow-1}:undefined):null,[sheets,sheetIndex,manual,columns,headerRow]);
 const rows=useMemo(()=>parsed&&q.data&&config?resolveTimetableRows(parsed.rows.map(r=>({...r,ignored:r.ignored||ignored.includes(r.key)})),{...q.data.workspace.options,classes:q.data.workspace.options.classes.filter(c=>c.canEdit)},config,classes):[],[parsed,q.data,config,classes,ignored]);
 const pick=async(file?:File)=>{if(!file)return;setBusy(true);setError('');setDrafts([]);setIgnored([]);try{const result=await readFile(file);setSheets(result);const first=result.findIndex(s=>parseTimetableSheet(s).headerRows.length>0),index=Math.max(0,first);setSheetIndex(index);const date=parseTimetableSheet(result[index]!).effectiveDate;setFrom(date??'');setClasses({});setManual(false);}catch(e){setError(e instanceof Error?e.message:'Lỗi đọc tệp');}finally{setBusy(false);}};
 const saveSettings=async()=>{if(!config)return;setBusy(true);setError('');try{const {version,...body}=config;setSettings((await http('saveScheduleImportSettings',{params:{schoolId},body:{...body,expectedVersion:version}})).data);}catch(e){setError(e instanceof Error?e.message:'Chưa lưu cấu hình');}finally{setBusy(false);}};
 const saveDrafts=async()=>{if(!q.data||!from||!to||from>=to){setError('Chọn ngày bắt đầu và ngày kết thúc thuộc năm học');return;}setBusy(true);setError('');const results:Draft[]=[],errors:string[]=[];
  for(const cls of q.data.workspace.options.classes.filter(c=>c.canEdit&&(all||c.id===classId))){const own=rows.filter(r=>r.classId===cls.id&&r.status!=='IGNORED');if(!own.length)continue;if(own.some(r=>r.status!=='MATCHED')){errors.push(`${cls.name}: còn dòng chưa ánh xạ hoặc lỗi`);continue;}
   try{const source=(await http('createTimetable',{params:{schoolId,classId:cls.id},body:{startsOn:from,endsOn:to,entries:own.map(r=>r.entry)}})).data;
    const params={schoolId,classId:cls.id,timetableId:source.id!},validation=(await http('validateTimetable',{params,body:{expectedVersion:source.version}})).data,current=(await http('getTimetable',{params})).data;results.push({classId:cls.id,className:cls.name,source:current,canPublish:cls.canPublish,validation,published:false});
   }catch(e){errors.push(`${cls.name}: ${e instanceof Error?e.message:'Chưa lưu được'}`);}
  }setDrafts(results);setError(errors.join('\n')||(!results.length?'Không có lớp hợp lệ để lưu':''));setBusy(false);onSaved();
 };
 const publish=async(draft:Draft)=>{setBusy(true);setError('');try{const ws=(await http('getScheduleWorkspace',{params:{schoolId},query:{classId:draft.classId}})).data;await http('publishTimetable',{params:{schoolId,classId:draft.classId,timetableId:draft.source.id!},body:{expectedSourceVersion:draft.source.dataVersion!,expectedPublicationId:ws.publicationId}});setDrafts(current=>current.map(d=>d===draft?{...d,published:true}:d));onSaved();}catch(e){setError(e instanceof Error?e.message:'Chưa công bố được');}finally{setBusy(false);}};
 const selectOptions=(list:{id:string;name:string}[])=>[{value:'',label:'Chọn ánh xạ'},...list.map(x=>({value:x.id,label:x.name}))];
 return <><Button onClick={()=>setOpen(true)}>Nhập từ file Excel/Spreadsheet</Button><Modal open={open} onOpenChange={setOpen} title="Nhập thời khóa biểu" size="xl" busy={busy} footer={<Button variant="primary" loading={busy} disabled={!rows.length||drafts.length>0} onClick={()=>void saveDrafts()}>Lưu bản nháp và kiểm tra xung đột</Button>}>
 <div className="space-y-4"><div className="rounded-xl border-2 border-dashed border-line p-5" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void pick(e.dataTransfer.files[0]);}}><label className="font-bold">Chọn hoặc kéo thả file<input className="block w-full pt-2" type="file" accept=".xlsx,.xls,.xlsm,.csv,.ods" onChange={e=>void pick(e.target.files?.[0])}/></label><p>XLSX · XLS · XLSM · CSV · ODS — tối đa 5 MB, 20 sheet; không chạy macro hoặc công thức.</p></div>
 {error&&<p role="alert" className="whitespace-pre-line text-danger">{error}</p>}{q.error&&<p role="alert">Không tải được cấu hình nhập TKB.</p>}
 {!!sheets.length&&<><SelectField label="Sheet" value={String(sheetIndex)} onChange={e=>{const i=Number(e.target.value);setSheetIndex(i);setFrom(parseTimetableSheet(sheets[i]!).effectiveDate??'');setDrafts([]);}} options={sheets.map((s,i)=>({value:String(i),label:s.name}))}/><p>Nhận diện: {parsed?.mode} · {rows.length} tiết · buổi sáng / chiều được giữ theo từng khối.</p>
 <Button onClick={()=>setManual(v=>!v)}>Ánh xạ cột thủ công khi không nhận diện</Button>{manual&&<div className="grid grid-cols-2 gap-2"><TextField label="Dòng tiêu đề (từ 1)" type="number" min={1} value={headerRow} onChange={e=>setHeaderRow(Number(e.target.value))}/>{Object.entries(columns).map(([key,n])=><TextField key={key} label={`${key} (cột từ 1)`} type="number" min={1} value={n+1} onChange={e=>setColumns({...columns,[key]:Number(e.target.value)-1})}/>)}</div>}
 <div className="grid gap-2 sm:grid-cols-3"><TextField label="Có hiệu lực từ" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><TextField label="Kết thúc (ngày loại trừ)" type="date" value={to} onChange={e=>setTo(e.target.value)}/><SelectField label="Phạm vi nhập" value={all?'all':'class'} onChange={e=>setAll(e.target.value==='all')} options={[{value:'class',label:'Lớp đang mở'},{value:'all',label:'Tất cả lớp hợp lệ có quyền sửa'}]}/></div>
 {q.data&&config&&<><details open><summary className="font-bold">Ánh xạ lớp, môn, giáo viên</summary><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[...new Set(rows.map(r=>r.classLabel))].map(label=><SelectField key={'c'+label} label={`Lớp: ${label}`} value={classes[label]??rows.find(r=>r.classLabel===label)?.classId??''} onChange={e=>setClasses({...classes,[label]:e.target.value})} options={[...selectOptions(q.data!.workspace.options.classes.filter(c=>c.canEdit)),{value:'IGNORE',label:'Bỏ qua lớp này'}]}/>)}{(['subjects','teachers'] as const).map(kind=>[...new Set(rows.filter(r=>!r.ignored).map(r=>kind==='subjects'?r.subjectAlias:r.teacherAlias))].map(alias=><SelectField key={kind+alias} label={`${kind==='subjects'?'Môn':'Giáo viên'}: ${alias||'(trống)'}`} value={config.aliases[kind][normalizeAlias(alias)]??''} onChange={e=>setSettings({...config,aliases:{...config.aliases,[kind]:{...config.aliases[kind],[normalizeAlias(alias)]:e.target.value}}})} options={selectOptions(q.data!.workspace.options[kind])}/>))}</div></details>
 <details><summary className="font-bold">Giờ tiết theo cấu hình trường</summary><p>Phải điền giờ thực tế. Tiết chiều 1–5 lưu thành tiết 6–10.</p><div className="grid gap-2 sm:grid-cols-2">{[...new Set(rows.map(r=>`${r.session}:${r.period}`))].sort().map(key=><div className="flex items-center gap-2" key={key}><span>{key}</span>{(['start','end'] as const).map(field=><input className="input min-w-0" aria-label={`${key} ${field}`} type="time" key={field} value={config.periodTimes[key]?.[field]??''} onChange={e=>setSettings({...config,periodTimes:{...config.periodTimes,[key]:{start:config.periodTimes[key]?.start??'',end:config.periodTimes[key]?.end??'',[field]:e.target.value}}})}/>)}</div>)}</div></details>
 {q.data.workspace.canManage&&<Button disabled={busy} onClick={()=>void saveSettings()}>Lưu ánh xạ và giờ tiết cho trường</Button>}
 </>}
 <div className="max-h-80 overflow-auto"><table className="w-full text-sm"><thead><tr>{['Bỏ qua','Lớp','Thứ','Tiết / buổi','Ô gốc','Môn / giáo viên','Trạng thái'].map(t=><th className="p-2 text-left" key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t border-line" key={r.key}><td><input type="checkbox" aria-label={`Bỏ qua ${r.raw} ${r.classLabel} thứ ${r.weekday+1} tiết ${r.period}`} checked={r.ignored} onChange={e=>setIgnored(v=>e.target.checked?[...v,r.key]:v.filter(k=>k!==r.key))}/></td><td className="p-2">{r.classLabel}</td><td>{r.weekday+1}</td><td>{r.period} / {r.session}</td><td>{r.raw}</td><td>{q.data?.workspace.options.subjects.find(s=>s.id===r.entry.subjectId)?.name??r.subjectAlias} / {q.data?.workspace.options.teachers.find(t=>t.id===r.entry.memberId)?.name??r.teacherAlias}</td><td>{r.status}</td></tr>)}</tbody></table></div></>}
 {drafts.map(d=><div className="rounded-xl border border-line p-3" key={d.classId}><b>{d.className}: {d.published?'Đã công bố':d.validation.valid?'Bản nháp hợp lệ':'Bản nháp có xung đột'}</b>{!d.validation.valid&&<p className="text-sm text-danger">Có {d.validation.conflicts.length} xung đột lớp, giáo viên, phòng, phân công hoặc ngày nghỉ. Chỉnh bản nháp tại Nhập tay rồi kiểm tra lại trước khi công bố.</p>}{d.validation.valid&&d.canPublish&&!d.published&&<Button disabled={busy} onClick={()=>void publish(d)}>Công bố {d.className}</Button>}</div>)}
 </div></Modal></>;
}
