import {test,expect,type Page,type Route} from '@playwright/test';
const id=(n:number)=>`6b000000-0000-4000-8000-${String(n).padStart(12,'0')}`,schoolId=id(1),yearId=id(2),classId=id(3),root=`/api/v1/schools/${schoolId}`,purpose=`${root}/academic-years/${yearId}/classes/${classId}`,base=`/classroom/${schoolId}/${yearId}/${classId}`,date='2026-10-02',stamp=date+'T01:00:00Z',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-announcements';
type State={mode:'ready'|'read'|'outage'|'conflict';saved:boolean;published:boolean;requests:{path:string;method:string;body:unknown}[];unexpected:string[]};
const state=():State=>({mode:'ready',saved:false,published:false,requests:[],unexpected:[]});
const reply=(r:Route,data:unknown)=>r.fulfill({status:200,json:{data,requestId:'announcement-browser'}});
const actions=(s:State)=>['class.read','announcement.read',...(s.mode==='read'?[]:['announcement.manage','announcement.publish'])];
const source=(s:State)=>({id:id(4),rootId:id(4),yearId,classId,version:s.published?2:1,dataVersion:1,publicationId:s.published?id(10):null});
function item(s:State){return {schoolId,id:id(4),rootId:id(4),yearId,yearVersion:1,classVersion:3,origin:'class',originClassId:classId,className:'6A thông báo API',title:'Thông báo theo nguồn API',summary:'Tóm tắt thông báo theo lớp hiện tại',body:[{type:'p',text:'Nội dung tiếng Việt từ API'}],audience:'families',scope:{type:'class',classIds:[classId]},scopeLabel:'Lớp 6A thông báo API',audienceLabel:'Gia đình học sinh',isPublic:false,status:s.published?'published':'draft',createdAt:stamp,updatedAt:stamp,createdByName:null,scheduledAt:null,publishedAt:s.published?stamp:null,withdrawnAt:null,withdrawReason:null,internalNote:null,version:s.published?2:1,source:source(s),canEdit:s.mode!=='read',canPublish:s.mode!=='read',canViewInternal:s.mode!=='read',canWithdraw:s.mode!=='read'&&s.published,canDelete:s.mode!=='read'&&!s.published,readOnly:false,scheduleState:null,scheduleErrorCode:null,estimate:s.mode==='read'?null:{students:1,activeLinks:null,staff:0},attachmentIds:[],attachments:[],historyView:s.mode==='read'?null:[{id:id(11),at:stamp,action:'Lưu bản nháp',byName:null,reason:null}]};}
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname,body=request.method()==='GET'?null:request.postDataJSON();s.requests.push({path,method:request.method(),body});
 if(path==='/api/v1/me/context')return reply(route,{user:{id:id(9),version:1,displayName:'Nhân sự thông báo API',email:'announcements@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'announcement-browser-csrf',mode:'connected',serverNow:stamp,memberships:[{memberId:id(8),schoolId,schoolName:'Trường thông báo API',schoolSlug:'announcement-api',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:date,department:null,schoolWorkspace:false,teacherWorkspace:false,duties:[],grants:[{id:id(7),version:1,roleId:id(6),roleCode:'ANNOUNCEMENT_SCOPE',roleLabel:'Phạm vi thông báo lớp',scopeType:'CLASS',classId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions:actions(s)}]}]});
 if(path==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'announcement-notifications'}});
 if(path===purpose+'/workspace-header')return reply(route,{school:{id:schoolId,name:'Trường thông báo API',shortName:'API',slug:'announcement-api'},class:{id:classId,yearId,gradeLevelId:id(20),name:'6A thông báo API',capacity:40,status:'ACTIVE',version:3,roomId:null,motto:null,createdAt:stamp},year:{id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:'ACTIVE'},grade:'Khối6',today:date,referenceDate:date,homeroom:null,studentCount:null,maleCount:null,femaleCount:null,myDuties:[],viaSchoolRole:false,workspaceKind:'CLASS',actions:actions(s),tabs:[{key:'overview',label:'Tổng quan',path:''},{key:'announcements',label:'Thông báo',path:'/announcements'}],summary:{weekIndex:null,weekStatus:null,pending:null,links:null,lastPublishedAt:null},readOnly:false});
 if(path===purpose+'/announcement-workspace'){if(s.mode==='outage')return route.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE'}});return route.fulfill({status:200,json:{data:{schoolId,yearId,classId,today:date,items:[item(s)],counts:{draft:s.published?0:1,scheduled:0,published:s.published?1:0,withdrawn:0},canCompose:s.mode!=='read'},page:{total:1,limit:100,hasMore:false,nextCursor:null},requestId:'announcement-directory'}});}
 if(path===root+'/announcement-workspace/'+id(4))return reply(route,item(s));
 if(path===root+'/announcement-compose')return reply(route,{schoolId,yearId,classId,timezone:'Asia/Ho_Chi_Minh',today:date,serverNow:stamp,yearVersion:1,classVersion:3,readOnly:false,canPublish:true,canSelectStudents:false,grades:[],classes:[{id:classId,name:'6A thông báo API',gradeId:id(20)}],students:[],files:[]});
 if(path===root+'/announcement-estimate')return reply(route,{schoolId,...body,counts:{students:1,activeLinks:null,staff:0}});
 if(path===root+'/announcement-save'){if(s.mode==='conflict')return route.fulfill({status:409,json:{code:'ANNOUNCEMENT_SOURCE_CHANGED'}});s.saved=true;return reply(route,{id:id(4),rootId:id(4),status:'draft',source:source(s)});}
 if(path===root+'/announcement-publish'){s.published=true;return reply(route,{id:id(4),rootId:id(4),status:'published',source:source(s)});}
 s.unexpected.push(path);return route.fulfill({status:503,json:{code:'UNEXPECTED_BROWSER_CONTRACT_REQUEST'}});
 });}
test('class list and detail use exact source and publication POST while history retains real identifiers',async({page})=>{const s=state();await routes(page,s);await page.goto(base+'/announcements');await expect(page.getByText('Thông báo theo nguồn API',{exact:true})).toBeVisible();await page.goto(base+'/announcements/'+id(4));await expect(page.getByText('Nội dung tiếng Việt từ API')).toBeVisible();await page.getByRole('button',{name:'Công bố ngay',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Công bố',exact:true}).click();await expect(page.getByRole('button',{name:'Thu hồi',exact:true})).toBeVisible();expect(s.requests.filter(r=>r.path===root+'/announcement-publish')).toEqual([{path:root+'/announcement-publish',method:'POST',body:{source:{...source(s),version:1,publicationId:null}}}]);await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('read-only class announcement access hides edit publish compose private history and estimate on mobile',async({page})=>{const s=state();s.mode='read';s.published=true;await page.setViewportSize({width:390,height:844});await routes(page,s);await page.goto(base+'/announcements');await expect(page.getByText('Thông báo theo nguồn API',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Soạn thông báo',exact:true})).toHaveCount(0);await page.goto(base+'/announcements/'+id(4));await expect(page.getByText('Nội dung tiếng Việt từ API')).toBeVisible();await expect(page.getByRole('button',{name:'Công bố ngay',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Lịch sử',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Ghi chú nội bộ',exact:true})).toHaveCount(0);await expect(page.getByText('Không có quyền xem ước tính người nhận')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('composer retains plaintext and displayed year/class versions through conflict without a blind retry',async({page})=>{const s=state();s.mode='conflict';await routes(page,s);await page.goto(base+'/announcements/new');await page.getByRole('textbox',{name:'Tiêu đề (bắt buộc)',exact:true}).fill('Thông báo giữ nguồn trước lỗi');await page.getByRole('textbox',{name:'Tóm tắt (bắt buộc)',exact:true}).fill('Tóm tắt đủ thông tin giữ nguyên');await page.getByRole('textbox',{name:'Đoạn văn 1',exact:true}).fill('Nội dung <script> là văn bản');await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();const calls=s.requests.filter(r=>r.path===root+'/announcement-save');expect(calls).toHaveLength(1);expect(calls[0].body).toMatchObject({source:null,yearId,classId,expectedYearVersion:1,expectedClassVersion:3,body:[{type:'p',text:'Nội dung <script> là văn bản'}]});expect(s.saved).toBe(false);expect(s.unexpected).toEqual([]);});
test('class list outage shows retry and hides compose instead of returning an empty announcement list',async({page})=>{const s=state();s.mode='outage';await routes(page,s);await page.goto(base+'/announcements');await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByRole('link',{name:'Soạn thông báo',exact:true})).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại'}).click();await expect(page.getByText('Thông báo theo nguồn API',{exact:true})).toBeVisible();expect(s.unexpected).toEqual([]);});
