import {test,expect,type Page,type Route} from '@playwright/test';
const id=(n:number)=>`7f000000-0000-4000-8000-${String(n).padStart(12,'0')}`,schoolId=id(1),yearId=id(2),classId=id(3),studentId=id(4),enrollmentId=id(5),root=`/api/v1/schools/${schoolId}`,purpose=`${root}/academic-years/${yearId}/classes/${classId}`,att=purpose+'/attendance-workspace',base=`/classroom/${schoolId}/${yearId}/${classId}`,date='2026-10-02',stamp=date+'T01:00:00Z',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-attendance';
type State={mode:'ready'|'outage'|'malformed'|'slotsoutage'|'subject'|'conflict';saved:boolean;published:boolean;requests:{path:string;method:string;body:unknown}[];unexpected:string[]};
const state=():State=>({mode:'ready',saved:false,published:false,requests:[],unexpected:[]});
const reply=(r:Route,data:unknown)=>r.fulfill({status:200,json:{data,requestId:'attendance-browser'}});
const actions=(s:State)=>['class.read','student.read','attendance.read','attendance.record',...(s.mode==='subject'?[]:['attendance.publish','attendance.reopen'])];
const source=(s:State)=>({classVersion:3,rosterHash:'a'.repeat(64),sessionId:s.saved?id(10):null,version:s.saved?(s.published?3:2):null,dataVersion:s.saved?2:null,publicationId:s.published?id(11):null});
function sheet(s:State){const subject=s.mode==='subject';return {schoolId,yearId,classId,date,slot:subject?'period-2':'morning',today:date,className:'6A điểm danh API',source:source(s),session:s.saved?{id:id(10),version:s.published?3:2,dataVersion:2,updatedAt:stamp,publishedAt:s.published?stamp:null,locked:s.published}:null,sessionStatus:s.published?'published':s.saved?'open':'none',rows:[{studentId,enrollmentId,recordVersion:s.saved?2:null,code:'ATTEND01',fullName:'Học sinh điểm danh API',groupName:null,status:s.saved?'LATE':'UNMARKED',note:s.saved?'Ghi chú điểm danh công khai':'',edited:s.saved,linkedConduct:null}],counts:{PRESENT:0,LATE:s.saved?1:0,EXCUSED:0,UNEXCUSED:0,UNMARKED:s.saved?0:1},lessons:subject?[{id:id(12),period:2,subject:'Môn bộ môn API',start:'08:00',end:'09:00',status:'SCHEDULED'}]:[],lesson:subject?{id:id(12),period:2,subject:'Môn bộ môn API',start:'08:00',end:'09:00',status:'SCHEDULED'}:null,canRecord:true,canPublish:!subject,canLink:false,holiday:null,isSunday:false,updatedByName:s.saved?'Giáo viên điểm danh API':null,week:null,periodLocked:false,linkRules:[]};}
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{const request=route.request(),url=new URL(request.url()),path=url.pathname,body=request.method()==='GET'?null:request.postDataJSON();s.requests.push({path,method:request.method(),body});
 if(path==='/api/v1/me/context')return reply(route,{user:{id:id(9),version:1,displayName:'Nhân sự điểm danh API',email:'attendance@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'attendance-browser-csrf',mode:'connected',serverNow:stamp,memberships:[{memberId:id(8),schoolId,schoolName:'Trường điểm danh API',schoolSlug:'attendance-api',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:date,department:null,schoolWorkspace:false,teacherWorkspace:false,duties:[],grants:[{id:id(7),version:1,roleId:id(6),roleCode:'ATTENDANCE_SCOPE',roleLabel:'Phạm vi lớp',scopeType:s.mode==='subject'?'SUBJECT':'CLASS',classId,...(s.mode==='subject'?{subjectId:id(13)}:{}),validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions:actions(s)}]}]});
 if(path==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'attendance-notifications'}});
 if(path===purpose+'/workspace-header')return reply(route,{school:{id:schoolId,name:'Trường điểm danh API',shortName:'API',slug:'attendance-api'},class:{id:classId,yearId,gradeLevelId:id(20),name:'6A điểm danh API',capacity:40,status:'ACTIVE',version:3,roomId:null,motto:null,createdAt:stamp},year:{id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:'ACTIVE'},grade:'Khối6',today:date,referenceDate:date,homeroom:null,studentCount:1,maleCount:null,femaleCount:null,myDuties:[],viaSchoolRole:false,workspaceKind:'CLASS',actions:actions(s),tabs:[{key:'overview',label:'Tổng quan',path:''},{key:'students',label:'Học sinh',path:'/students'},{key:'attendance',label:'Điểm danh',path:'/attendance'}],summary:{weekIndex:null,weekStatus:null,pending:null,links:null,lastPublishedAt:null},readOnly:false});
 if(path===att+'/slots'){if(s.mode==='slotsoutage')return route.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE'}});return reply(route,{schoolId,yearId,classId,date,slots:[{slot:s.mode==='subject'?'period-2':'morning',label:s.mode==='subject'?'Tiết 2 – Môn bộ môn API':'Buổi sáng (cả buổi)',canRecord:true}]});}
 if(path===att+'/sheet'){if(s.mode==='outage')return route.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE'}});const v=sheet(s);return reply(route,s.mode==='malformed'?{...v,yearId:id(21),internalNote:'PRIVATE'}:v);}
 if(path===att+'/save'){if(s.mode==='conflict')return route.fulfill({status:409,json:{code:'ATTENDANCE_SOURCE_CHANGED'}});s.saved=true;return reply(route,{sessionId:id(10),changed:1,linkedCreated:0,linkedVoided:0,blockedLinks:[],source:source(s)});}
 if(path===att+'/publish'){s.published=true;return reply(route,{sessionId:id(10),changed:0,linkedCreated:0,linkedVoided:0,blockedLinks:[],source:source(s)});}
 if(path===att+`/students/${studentId}/history`)return reply(route,{schoolId,yearId,classId,studentId,studentName:'Học sinh điểm danh API',code:'ATTEND01',date,slot:'morning',status:'LATE',note:'Ghi chú điểm danh công khai',sessionStatus:s.published?'published':'open',publishedAt:s.published?stamp:null,linkedConduct:[],history:[{id:id(30),at:stamp,byName:'Giáo viên điểm danh API',from:'UNMARKED',to:'LATE',reason:'Lý do nguồn thật'}]});
 if(path===att+'/week')return reply(route,{schoolId,yearId,classId,monday:'2026-09-28',today:date,week:null,days:['2026-09-28','2026-09-29','2026-09-30','2026-10-01',date,'2026-10-03'].map(d=>({date:d,sessionStatus:d>date?'future':'none',holiday:null,periodSessions:0})),rows:[{studentId,code:'ATTEND01',fullName:'Học sinh điểm danh API',cells:['not_enrolled','not_enrolled','holiday','UNMARKED','LATE','future'].map(status=>({status,note:'',edited:false})),tally:{PRESENT:0,LATE:1,EXCUSED:0,UNEXCUSED:0,UNMARKED:1}}]});
 s.unexpected.push(path);return route.fulfill({status:503,json:{code:'UNEXPECTED_BROWSER_CONTRACT_REQUEST'}});
 });}
async function open(page:Page,s:State){await routes(page,s);await page.goto(base+`/attendance?date=${date}`);await expect(page.getByRole('heading',{name:'Điểm danh',exact:true})).toBeVisible();}
test('attendance saves only changed displayed pupils and source then publishes and opens real own history',async({page})=>{const s=state();await open(page,s);await expect(page.getByText('Học sinh điểm danh API',{exact:true}).first()).toBeVisible();await expect(page.getByText(/Sĩ số 1 = 0 có mặt/)).toBeVisible();await page.getByRole('radio',{name:'Đi muộn',exact:true}).first().click();await page.getByRole('textbox',{name:'Ghi chú cho Học sinh điểm danh API'}).first().fill('Ghi chú điểm danh công khai');await page.getByRole('button',{name:'Lưu điểm danh',exact:true}).first().click();await expect(page.getByRole('button',{name:'Lịch sử',exact:true}).first()).toBeVisible();const saved=s.requests.find(r=>r.path===att+'/save')!;expect(saved.body).toMatchObject({source:{sessionId:null,version:null,rosterHash:'a'.repeat(64)},entries:[{studentId,recordVersion:null,status:'LATE',note:'Ghi chú điểm danh công khai'}],linkConduct:false});expect(s.requests.filter(r=>r.path===att+'/save')).toHaveLength(1);await page.getByRole('button',{name:'Công bố cho phụ huynh',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Công bố',exact:true}).click();await expect(page.getByRole('button',{name:'Đã công bố cho phụ huynh',exact:true})).toBeVisible();await page.getByRole('button',{name:'Lịch sử',exact:true}).first().click();await expect(page.getByText('Lý do: Lý do nguồn thật')).toBeVisible();await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('attendance API failure retries and malformed foreign source hides roster and all save actions',async({page})=>{const s=state();s.mode='outage';await open(page,s);await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByText('Học sinh điểm danh API',{exact:true})).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại'}).click();await expect(page.getByText('Học sinh điểm danh API',{exact:true}).first()).toBeVisible();s.mode='malformed';await page.reload();await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByRole('button',{name:'Lưu điểm danh',exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);});
test('subject attendance chooses actual own lesson and hides class publication and conduct actions on mobile',async({page})=>{const s=state();s.mode='subject';await page.setViewportSize({width:390,height:844});await open(page,s);await expect(page.getByText('1. Học sinh điểm danh API',{exact:true})).toBeVisible();await expect(page.getByRole('combobox',{name:'Buổi / tiết'})).toHaveValue('period-2');await expect(page.getByRole('button',{name:'Công bố cho phụ huynh',exact:true})).toHaveCount(0);await expect(page.getByRole('checkbox',{name:/Tạo ghi nhận thi đua/})).toBeDisabled();expect(s.requests.filter(r=>r.path===att+'/sheet').every(r=>r.method==='GET')).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('slot failure does not request a default morning sheet and weekly uses native exceptions and own cell history',async({page})=>{const s=state();s.mode='slotsoutage';await open(page,s);await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();expect(s.requests.some(r=>r.path===att+'/sheet')).toBe(false);s.mode='ready';await page.goto(base+'/attendance/weekly?week=2026-09-28');await expect(page.getByText('Học sinh điểm danh API',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'Ma trận chuyên cần'})).toBeVisible();await page.getByRole('button',{name:/Học sinh điểm danh API.*02\/10.*Đi muộn/}).click();await expect(page.getByText('Lý do: Lý do nguồn thật')).toBeVisible();expect(s.unexpected).toEqual([]);});
test('save conflict retains the entered draft and asks for reload without a second blind write',async({page})=>{const s=state();s.mode='conflict';await open(page,s);await page.getByRole('radio',{name:'Đi muộn',exact:true}).first().click();await page.getByRole('button',{name:'Lưu điểm danh',exact:true}).first().click();await expect(page.getByRole('dialog')).toBeVisible();expect(s.requests.filter(r=>r.path===att+'/save')).toHaveLength(1);expect(s.saved).toBe(false);expect(s.unexpected).toEqual([]);});
