import {test,expect,type Page,type Route} from '@playwright/test';
import type {ApiSchemas} from '../../src/lib/api/generated';
const schoolId='7b000000-0000-4000-8000-000000000001',yearId='7b000000-0000-4000-8000-000000000002',classId='7b000000-0000-4000-8000-000000000003',studentId='7b000000-0000-4000-8000-000000000004',enrollmentId='7b000000-0000-4000-8000-000000000005',groupId='7b000000-0000-4000-8000-000000000006',otherId='7b000000-0000-4000-8000-000000000007',targetId='7b000000-0000-4000-8000-000000000008';
const root=`/api/v1/schools/${schoolId}`,purpose=`${root}/academic-years/${yearId}/classes/${classId}`,base=`/classroom/${schoolId}/${yearId}/${classId}`,prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-class-roster';
const year={id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:'ACTIVE'};
type State={mode:'ready'|'subject'|'outage'|'malformed'|'conflict'|'choiceoutage';requests:{path:string;method:string;query:string;body:Record<string,unknown>|null;key:string|null}[];unexpected:string[]};
const state=():State=>({mode:'ready',requests:[],unexpected:[]});
const reply=(route:Route,data:unknown,status=200)=>route.fulfill({status,json:{data,requestId:'roster-controlled-browser'}});
const actions=(s:State)=>['class.read','student.read',...(s.mode==='subject'?[]:['guardian.read','parent_access.issue','student.transfer.request'])];
function roster(s:State,url:URL):ApiSchemas['ClassRosterWorkspace']{
 const full=s.mode!=='subject',rows:ApiSchemas['ClassRosterRow'][]=[{id:studentId,studentCode:'ROSTER001',fullName:'Học sinh roster API',gender:null,enrollmentId,enrollmentVersion:5,startsOn:'2026-09-01',ordinal:1,groupId,groupName:'Tổ roster API',positions:['Lớp trưởng'],transferredIn:false,currentEnrollment:true,guardian:full?{name:'Giám hộ roster riêng API',relation:'Mẹ',verification:'VERIFIED'}:null,linkStatus:full?'opened':null},{id:otherId,studentCode:'ROSTER002',fullName:'Bạn thứ hai roster API',gender:'Nữ',enrollmentId:otherId,enrollmentVersion:2,startsOn:'2026-09-01',ordinal:2,groupId:null,groupName:null,positions:[],transferredIn:true,currentEnrollment:true,guardian:null,linkStatus:full?'none':null}];
 const q=url.searchParams.get('q')?.toLowerCase(),group=url.searchParams.get('groupId'),link=url.searchParams.get('linkStatus');
 return {schoolId,yearId,classId,today:'2026-10-01',referenceDate:'2026-10-01',classVersion:3,readOnly:false,seeGuardians:full,seeLinks:full,canAdd:false,canTransfer:full,canGroups:false,canReadGroups:false,canSeating:false,groups:[{id:groupId,name:'Tổ roster API'}],total:2,rows:rows.filter(r=>(!q||r.fullName.toLowerCase().includes(q)||r.studentCode.toLowerCase().includes(q))&&(!group||(group==='none'?r.groupId===null:r.groupId===group))&&(!link||r.linkStatus===link)),leftRecently:[{id:targetId,enrollmentId:targetId,fullName:'Học sinh đã rời roster API',studentCode:'ROSTER003',endsOn:'2026-09-30',reason:'Chuyển lớp đã được duyệt'}],linkSummary:full?{total:2,withLink:1,opened:1}:null};
}
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{
 const req=route.request(),url=new URL(req.url()),path=url.pathname,body=req.method()==='POST'?req.postDataJSON() as Record<string,unknown>:null;s.requests.push({path,method:req.method(),query:url.search,body,key:req.headers()['idempotency-key']??null});
 if(path==='/api/v1/me/context')return reply(route,{user:{id:targetId,version:1,displayName:'Nhân sự roster API',email:'roster@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'roster-browser-csrf',mode:'connected',serverNow:'2026-10-01T01:00:00Z',memberships:[{memberId:enrollmentId,schoolId,schoolName:'Trường roster API',schoolSlug:'class-roster',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-01',department:null,schoolWorkspace:false,teacherWorkspace:false,duties:[],grants:[{id:groupId,version:1,roleId:otherId,roleCode:'CLASS_ROSTER',roleLabel:'Phạm vi trong lớp',scopeType:'CLASS',classId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions:actions(s)}]}]});
 if(path==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'roster-notifications'}});
 if(path===purpose+'/workspace-header')return reply(route,{school:{id:schoolId,name:'Trường roster API',shortName:'API',slug:'class-roster'},class:{id:classId,yearId,gradeLevelId:groupId,name:'6A roster API',capacity:40,status:'ACTIVE',version:3,roomId:null,motto:null,createdAt:'2026-09-01T00:00:00Z'},year,grade:'Khối6',today:'2026-10-01',referenceDate:'2026-10-01',homeroom:null,studentCount:2,maleCount:0,femaleCount:1,myDuties:[],viaSchoolRole:false,workspaceKind:'CLASS',actions:actions(s),tabs:[{key:'overview',label:'Tổng quan',path:''},{key:'students',label:'Học sinh',path:'/students'}],summary:{weekIndex:null,weekStatus:null,pending:null,links:null,lastPublishedAt:null},readOnly:false});
 if(path===purpose+'/roster-workspace'){if(s.mode==='outage')return route.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE',requestId:'roster-outage'}});const v=roster(s,url);return reply(route,s.mode==='malformed'?{...v,rows:v.rows.map(r=>({...r,guardianPhone:'PRIVATE-UNEXPECTED'}))}:v);}
 if(path===purpose+'/transfer-options'){if(s.mode==='choiceoutage')return route.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE',requestId:'roster-choices-outage'}});return reply(route,{schoolId,yearId,classId,today:'2026-10-01',referenceDate:url.searchParams.get('onDate')??'2026-10-01',startsOn:'2026-09-01',endsOn:'2027-06-01',students:[{id:studentId,fullName:'Học sinh roster API',studentCode:'ROSTER001',enrollmentId,enrollmentVersion:5,startsOn:'2026-09-01',endsOn:null},{id:otherId,fullName:'Bạn thứ hai roster API',studentCode:'ROSTER002',enrollmentId:otherId,enrollmentVersion:2,startsOn:'2026-09-01',endsOn:null}],targets:[{id:targetId,name:'Lớp nhận roster API',size:8,capacity:45}]});}
 if(path===root+'/transfers'&&body){if(s.mode==='conflict')return route.fulfill({status:409,json:{code:'VERSION_CONFLICT',currentVersion:6,requestId:'roster-conflict'}});return reply(route,{id:targetId,version:1,createdAt:'2026-10-01T01:00:00Z',updatedAt:'2026-10-01T01:00:00Z',studentId:body.studentId,fromEnrollmentId:body.fromEnrollmentId,toClassId:body.toClassId??null,effectiveOn:body.effectiveOn,reason:body.reason,status:'SUBMITTED'},201);}
 s.unexpected.push(path);return route.fulfill({status:503,json:{code:'UNEXPECTED_BROWSER_CONTRACT_REQUEST',requestId:'roster-unexpected'}});
 });}
async function open(page:Page,s:State){await routes(page,s);await page.goto(base+'/students');await expect(page.getByRole('heading',{name:'Danh sách học sinh (2)'})).toBeVisible();}
test('class roster preserves server filters stable ordinals historical rows and one displayed versioned transfer request',async({page})=>{
 const s=state();await open(page,s);await expect(page.getByText('Giám hộ roster riêng API',{exact:true}).first()).toBeVisible();await expect(page.getByText('Học sinh đã rời roster API',{exact:false})).toBeVisible();
 await page.getByLabel('Lọc theo tổ').selectOption('none');await expect(page.getByText('Bạn thứ hai roster API',{exact:true}).first()).toBeVisible();await expect(page.getByText('Học sinh roster API',{exact:true})).toHaveCount(0);await page.getByLabel('Lọc theo tổ').selectOption('');
 await page.getByPlaceholder('Tìm học sinh theo họ tên, mã…').fill('ROSTER001');await expect(page.getByText('Bạn thứ hai roster API',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Xóa lọc',exact:true}).click();
 await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});await page.getByRole('button',{name:'Chuyển lớp',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Học sinh',{exact:false}).selectOption(studentId);await dialog.getByLabel('Lớp đích (cùng năm học)').selectOption(targetId);await dialog.getByLabel('Lý do').fill('Đề nghị roster giữ lịch sử');await expect(dialog.getByRole('button',{name:'Gửi đề nghị'})).toBeEnabled();await dialog.getByRole('button',{name:'Gửi đề nghị'}).click();await expect(dialog).toHaveCount(0);
 const posts=s.requests.filter(r=>r.method==='POST');expect(posts).toHaveLength(1);expect(posts[0].body).toEqual({studentId,fromEnrollmentId:enrollmentId,expectedEnrollmentVersion:5,toClassId:targetId,effectiveOn:'2026-10-01',reason:'Đề nghị roster giữ lịch sử'});expect(posts[0].key).toBeTruthy();await expect(page.getByRole('heading',{name:'Danh sách học sinh (2)'})).toBeVisible();expect(s.unexpected).toEqual([]);expect(s.requests.some(r=>r.path===root+'/students')).toBe(false);
});
test('subject roster hides family link transfer and unauthorized organization sources on a390px viewport',async({page})=>{
 const s=state();s.mode='subject';await page.setViewportSize({width:390,height:844});await open(page,s);await expect(page.getByText('Giám hộ roster riêng API',{exact:true})).toHaveCount(0);await expect(page.getByLabel('Trạng thái link')).toHaveCount(0);await expect(page.getByRole('button',{name:'Chuyển lớp',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Sơ đồ lớp'})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Tổ & Chức vụ'})).toHaveCount(0);expect(s.requests.some(r=>/group-workspace|seating-workspace|transfer-options/.test(r.path))).toBe(false);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);
});
test('filtered roster outages and malformed private receipts remove pupil actions rather than showing the cached unfiltered list',async({page})=>{
 const s=state();await open(page,s);s.mode='outage';await page.getByPlaceholder('Tìm học sinh theo họ tên, mã…').fill('Không có nguồn');await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByRole('button',{name:'Chuyển lớp',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Danh sách học sinh (2)'})).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại'}).click();await expect(page.getByText('Không có học sinh khớp bộ lọc',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Xóa bộ lọc'}).first().click();s.mode='malformed';await page.reload();await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByRole('button',{name:'Chuyển lớp',exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);
});
test('transfer choice outages block submission and version conflicts retain the unsaved request fields',async({page})=>{
 const s=state();await open(page,s);s.mode='choiceoutage';await page.getByRole('button',{name:'Chuyển lớp',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(dialog.getByRole('button',{name:'Gửi đề nghị'})).toBeDisabled();expect(s.requests.filter(r=>r.method==='POST')).toHaveLength(0);s.mode='ready';await dialog.getByRole('button',{name:'Thử lại'}).click();await expect(dialog.getByRole('button',{name:'Gửi đề nghị'})).toBeEnabled();await dialog.getByLabel('Học sinh',{exact:false}).selectOption(studentId);await dialog.getByLabel('Lớp đích (cùng năm học)').selectOption(targetId);await dialog.getByLabel('Lý do').fill('Nội dung phải giữ khi xung đột');s.mode='conflict';await dialog.getByRole('button',{name:'Gửi đề nghị'}).click();await expect(dialog.getByLabel('Lý do')).toHaveValue('Nội dung phải giữ khi xung đột');await expect(dialog).toBeVisible();expect(s.requests.filter(r=>r.method==='POST')).toHaveLength(1);expect(s.unexpected).toEqual([]);
});
