import {test,expect,type Page,type Route} from '@playwright/test';
import type {ApiSchemas} from '../../src/lib/api/generated';
const schoolId='79000000-0000-4000-8000-000000000001',yearId='79000000-0000-4000-8000-000000000002',classId='79000000-0000-4000-8000-000000000003',studentId='79000000-0000-4000-8000-000000000004',otherId='79000000-0000-4000-8000-000000000005',enrollmentId='79000000-0000-4000-8000-000000000006',otherEnrollment='79000000-0000-4000-8000-000000000007',groupId='79000000-0000-4000-8000-000000000008',actorId='79000000-0000-4000-8000-000000000009';
const base=`/classroom/${schoolId}/${yearId}/${classId}`,purpose=`/api/v1/schools/${schoolId}/academic-years/${yearId}/classes/${classId}`,prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-class-duties';
const names=new Map([[studentId,'Học sinh trực nhật API'],[otherId,'Bạn khác trực nhật API']]);
const year={id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:'ACTIVE'};
type Task=ApiSchemas['ClassDutyTask'];
type State={mode:'ready'|'limited'|'readonly'|'outage'|'denied'|'malformed'|'conflict';tasks:Task[];publicationId:string|null;sequence:number;failOnce:boolean;receipts:Map<string,{sourceId:string|null;status:string}>;requests:{path:string;method:string;body:Record<string,unknown>|null;key:string|null}[];unexpected:string[]};
const state=():State=>({mode:'ready',tasks:[],publicationId:null,sequence:20,failOnce:false,receipts:new Map(),requests:[],unexpected:[]});
const id=(s:State)=>`79000000-0000-4000-8000-${String(++s.sequence).padStart(12,'0')}`;
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'class-duty-controlled-browser'}});
function actions(s:State){return ['class.read','duty.read',...(s.mode==='readonly'?[]:['duty.manage']),...(['limited','readonly'].includes(s.mode)?[]:['duty.publish','parent_access.preview'])];}
function workspace(s:State,url:URL):ApiSchemas['ClassDutyWorkspace']{
 const date=url.searchParams.get('onDate')??'2026-10-01',monday=url.searchParams.get('weekStart')??'2026-09-28',canEdit=s.mode!=='readonly',canPublish=canEdit&&s.mode!=='limited',canPreview=canPublish;
 const tasks=s.tasks.filter(t=>t.date>=monday&&t.date<new Date(Date.parse(monday+'T00:00:00Z')+7*86400000).toISOString().slice(0,10)&&(!canEdit?t.status!=='DRAFT':true)).map(t=>({...t,canEdit:canEdit&&(t.status==='DRAFT'||canPublish)}));
 return {schoolId,yearId,classId,today:'2026-10-01',monday,referenceDate:date,startsOn:year.startsOn,endsOn:year.endsOn,readOnly:false,canEdit,canPublish,canPreview,publicationId:s.publicationId,tasks,students:canEdit?[{id:studentId,enrollmentId,fullName:names.get(studentId)!},{id:otherId,enrollmentId:otherEnrollment,fullName:names.get(otherId)!}]:[],groups:canEdit?[{id:groupId,name:'Tổ trực API',studentIds:[studentId,otherId]}]:[],previewStudents:canPreview?[{id:studentId,fullName:names.get(studentId)!},{id:otherId,fullName:names.get(otherId)!}]:[],preview:canPreview?tasks.filter(t=>t.status==='PUBLISHED').flatMap(t=>t.studentIds.map(studentId=>({studentId,date:t.date,task:t.task,status:'ASSIGNED' as const,publishedAt:'2026-10-01T01:00:00Z'}))):null};
}
function task(s:State,body:Record<string,unknown>):Task{const students=body.studentIds as string[],group=typeof body.groupId==='string'?body.groupId:null,gp=group?id(s):null,assignments=body.publish===true||!gp?students.map(()=>id(s)):[];return {id:gp??assignments[0],scheduleId:id(s),version:2,dataVersion:4,date:String(body.date),task:String(body.task),groupId:group,groupName:group?'Tổ trực API':null,groupPlanId:gp,assignmentIds:assignments,studentIds:students,studentNames:students.map(id=>names.get(id)!),unavailableTargets:0,status:body.publish===true?'PUBLISHED':'DRAFT',canEdit:true};}
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname,body=req.method()==='POST'?req.postDataJSON() as Record<string,unknown>:null,key=req.headers()['idempotency-key']??null;s.requests.push({path,method:req.method(),body,key});
 if(path==='/api/v1/me/context')return reply(route,{user:{id:actorId,version:1,displayName:'Nhân sự trực nhật API',email:'class-duty@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'class-duty-browser-csrf',mode:'connected',serverNow:'2026-10-01T01:00:00Z',memberships:[{memberId:enrollmentId,schoolId,schoolName:'Trường trực nhật API',schoolSlug:'class-duties',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-01',department:null,schoolWorkspace:false,teacherWorkspace:false,duties:[],grants:[{id:groupId,version:1,roleId:otherEnrollment,roleCode:'CLASS_DUTY',roleLabel:'Trực nhật trong lớp',scopeType:'CLASS',classId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions:actions(s)}]}]});
 if(path==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'class-duty-notifications'}});
 if(path===purpose+'/workspace-header')return reply(route,{school:{id:schoolId,name:'Trường trực nhật API',shortName:'API',slug:'class-duties'},class:{id:classId,yearId,gradeLevelId:groupId,name:'6A trực nhật API',capacity:40,status:'ACTIVE',version:1,roomId:null,motto:null,createdAt:'2026-09-01T00:00:00Z'},year,grade:'Khối 6',today:'2026-10-01',referenceDate:'2026-10-01',homeroom:null,studentCount:null,maleCount:null,femaleCount:null,myDuties:[],viaSchoolRole:false,workspaceKind:'CLASS',actions:actions(s),tabs:[{key:'overview',label:'Tổng quan',path:''},{key:'groups',label:'Tổ & sơ đồ',path:'/duties'}],summary:{weekIndex:null,weekStatus:null,pending:null,links:null,lastPublishedAt:null},readOnly:false});
 if(path===purpose+'/duty-workspace'){if(s.mode==='outage'||s.mode==='denied')return route.fulfill({status:s.mode==='outage'?503:404,json:{code:s.mode==='outage'?'DEPENDENCY_UNAVAILABLE':'RESOURCE_NOT_FOUND',requestId:'class-duty-source-error'}});const data=workspace(s,url);return reply(route,s.mode==='malformed'?{...data,guardianPhone:'PRIVATE-UNEXPECTED'}:data);}
 if((path===purpose+'/duty-tasks'||path===purpose+'/duty-tasks/remove')&&body){
  if(s.mode==='conflict')return route.fulfill({status:409,json:{code:'PUBLICATION_CONFLICT',requestId:'class-duty-conflict'}});
  if(key&&s.receipts.has(key))return reply(route,s.receipts.get(key));
  const source=body.source as ApiSchemas['ClassDutyTaskSource']|null;if(source)s.tasks=s.tasks.filter(t=>t.scheduleId!==source.scheduleId);let result:{sourceId:string|null;status:string};
  if(path.endsWith('/remove')){s.publicationId=id(s);result={sourceId:null,status:'REMOVED'};}else{const t=task(s,body);s.tasks.push(t);if(body.publish===true)s.publicationId=id(s);result={sourceId:t.scheduleId,status:t.status};}
  if(key)s.receipts.set(key,result);if(s.failOnce){s.failOnce=false;return route.abort('failed');}return reply(route,result);
 }
 s.unexpected.push(path);return route.fulfill({status:503,json:{code:'UNEXPECTED_CLASS_DUTY_OPERATION',requestId:'class-duty-unexpected'}});
 });}
async function newTask(page:Page,label:string){await page.getByRole('button',{name:'Phân công',exact:true}).click();await page.getByLabel('Nhiệm vụ',{exact:false}).fill(label);await expect(page.getByRole('button',{name:'Lưu nháp',exact:true})).toBeEnabled();}
test('class duties preserve selected group members displayed sources draft publication move and removal with own parent preview',async({page})=>{
 const s=state();await routes(page,s);await page.goto(base+'/duties');await newTask(page,'Trực nhật chọn một thành viên');await page.getByLabel('Tổ trực (tuỳ chọn)',{exact:true}).selectOption(groupId);await page.getByRole('button',{name:names.get(otherId)!,exact:true}).click();await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.getByText('Trực nhật chọn một thành viên',{exact:true})).toBeVisible();const original=structuredClone(s.tasks[0]);expect(original.studentIds).toEqual([studentId]);await page.getByLabel('Chọn học sinh',{exact:true}).selectOption(studentId);await expect(page.getByText('Không có lịch trực đã công bố.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Sửa',exact:true}).click();await expect(page.getByRole('button',{name:'Công bố',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Công bố',exact:true}).click();await expect(page.getByText('Đã công bố',{exact:true})).toBeVisible();const publish=s.requests.filter(r=>r.method==='POST')[1];expect(publish.body?.source).toMatchObject({scheduleId:original.scheduleId,expectedVersion:2,expectedDataVersion:4,assignmentIds:[],groupPlanId:original.groupPlanId});
 await page.getByRole('button',{name:'Sửa',exact:true}).click();await page.getByLabel('Ngày trực',{exact:false}).fill('03/10/2026');await page.getByLabel('Nhiệm vụ',{exact:false}).click();await expect(page.getByRole('button',{name:'Công bố',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Công bố',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(s.tasks[0].date).toBe('2026-10-03');await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});
 await page.getByRole('button',{name:'Xóa',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Xóa',exact:true}).click();await expect(page.getByText('Trực nhật chọn một thành viên',{exact:true})).toHaveCount(0);expect(s.tasks).toHaveLength(0);expect(s.requests.filter(r=>r.method==='POST')).toHaveLength(4);expect(s.unexpected).toEqual([]);expect(s.requests.some(r=>r.path.includes('/frontend/'))).toBe(false);
});
test('class duties keep management publication and parent preview controls separate and hide draft sources from a read-only actor',async({page})=>{
 const s=state();s.mode='limited';await routes(page,s);await page.goto(base+'/duties');await expect(page.getByText('Bạn chưa được cấp quyền xem trước phần của phụ huynh.',{exact:true})).toBeVisible();await newTask(page,'Chỉ được lưu nháp nguồn API');await expect(page.getByRole('button',{name:'Công bố',exact:true})).toBeDisabled();await page.getByRole('button',{name:names.get(studentId)!,exact:true}).click();await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.getByText('Chỉ được lưu nháp nguồn API',{exact:true})).toBeVisible();s.mode='readonly';await page.reload();await expect(page.getByRole('button',{name:'Phân công',exact:true})).toHaveCount(0);await expect(page.getByText('Chỉ được lưu nháp nguồn API',{exact:true})).toHaveCount(0);await expect(page.getByLabel('Chọn học sinh',{exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);
});
test('class duties retain unsaved fields on publication conflict and retry an uncertain command with one intent key',async({page})=>{
 const s=state();await routes(page,s);await page.goto(base+'/duties');await newTask(page,'Giữ ý định trực chưa lưu');await page.getByRole('button',{name:names.get(studentId)!,exact:true}).click();s.mode='conflict';await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('Nhiệm vụ',{exact:false})).toHaveValue('Giữ ý định trực chưa lưu');expect(s.tasks).toHaveLength(0);s.mode='ready';s.failOnce=true;await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.getByRole('button',{name:'Lưu nháp',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Lưu nháp',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(s.tasks).toHaveLength(1);const writes=s.requests.filter(r=>r.method==='POST');expect(writes.at(-2)?.body).toEqual(writes.at(-1)?.body);expect(writes.at(-2)?.key).toBeTruthy();expect(writes.at(-2)?.key).toBe(writes.at(-1)?.key);expect(s.unexpected).toEqual([]);
});
test('class duty outages malformed receipts and denied scope cannot become an empty board with pupil actions',async({page})=>{
 const s=state();s.mode='outage';await routes(page,s);await page.goto(base+'/duties');await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Phân công',exact:true})).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByRole('button',{name:'Phân công',exact:true})).toBeVisible();s.mode='malformed';await page.reload();await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByLabel('Chọn học sinh',{exact:true})).toHaveCount(0);s.mode='denied';await page.reload();await expect(page.getByText('Không tìm thấy',{exact:true})).toBeVisible();expect(s.unexpected).toEqual([]);
});
test('class duties remain readable on a390px viewport with a minimal own published preview and safe duty navigation',async({page})=>{
 await page.setViewportSize({width:390,height:844});const s=state();s.publicationId=id(s);s.tasks.push(task(s,{date:'2026-10-02',task:'Nhiệm vụ có nguồn công bố API',studentIds:[studentId,otherId],groupId:null,publish:true}));await routes(page,s);await page.goto(base+'/duties');await page.getByLabel('Chọn học sinh',{exact:true}).selectOption(studentId);await expect(page.getByText('Lịch trực của Học sinh trực nhật API tuần này',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Tổ & chức vụ',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Sơ đồ lớp',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);
});
