import {test,expect,type Page,type Route} from '@playwright/test';
const schoolId='77000000-0000-4000-8000-000000000001',yearId='77000000-0000-4000-8000-000000000002',classId='77000000-0000-4000-8000-000000000003',studentId='77000000-0000-4000-8000-000000000004',enrollmentId='77000000-0000-4000-8000-000000000005',groupId='77000000-0000-4000-8000-000000000006',positionId='77000000-0000-4000-8000-000000000007',assignmentId='77000000-0000-4000-8000-000000000008',planId='77000000-0000-4000-8000-000000000009',newId='77000000-0000-4000-8000-000000000010';
const base=`/classroom/${schoolId}/${yearId}/${classId}`,root=`/api/v1/schools/${schoolId}`,purpose=`${root}/academic-years/${yearId}/classes/${classId}`,prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-class-organization';
const year={id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:'ACTIVE'};
const groupSource=()=>({schoolId,yearId,classId,today:'2026-10-01',referenceDate:'2026-10-01',classVersion:3,readOnly:false,canEdit:true,groupsVisible:true,students:[{id:studentId,enrollmentId,studentCode:'P1',fullName:'Học sinh tổ chức API',groupId}],groups:[{id:groupId,version:1,name:'Tổ tổ chức API',sortOrder:1}],positionDefinitions:[{id:positionId,version:1,code:'configured',name:'Chức vụ nguồn API',singleHolder:true,groupId:null as string|null}],holders:[] as {id:string;version:number;positionId:string;enrollmentId:string;startsOn:string;endsOn:string}[]});
const seatSource=()=>({schoolId,yearId,classId,today:'2026-10-01',referenceDate:'2026-10-01',classVersion:3,readOnly:false,canEdit:true,groupsVisible:false,students:[{id:studentId,enrollmentId,studentCode:'P1',fullName:'Học sinh tổ chức API',groupId:null}],groupNames:null,latestRevision:1,plan:{id:planId,version:2,revision:1,effectiveOn:'2026-10-01',endsOn:'2027-06-01',rows:1 as number|null,cols:2 as number|null,note:null as string|null,seats:[{key:'Actual-source-seat',row:0,column:0,enrollmentId:enrollmentId as string|null},{key:'Empty-source-seat',row:0,column:1,enrollmentId:null as string|null}]},history:[{id:planId,version:2,revision:1,effectiveOn:'2026-10-01',endsOn:'2027-06-01',status:'ACTIVE',createdAt:'2026-10-01T01:00:00Z',createdByName:null}]});
type State={groups:ReturnType<typeof groupSource>;seating:ReturnType<typeof seatSource>;mode:'ready'|'outage'|'malformed'|'denied'|'conflict';positionFailOnce:boolean;seatOnly:boolean;requests:{path:string;method:string;body:Record<string,unknown>|null;key:string|null}[];unexpected:string[]};
const state=():State=>({groups:groupSource(),seating:seatSource(),mode:'ready',positionFailOnce:false,seatOnly:false,requests:[],unexpected:[]});
const reply=(route:Route,data:unknown,status=200)=>route.fulfill({status,json:{data,requestId:'organization-controlled-browser'}});
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{const request=route.request(),url=new URL(request.url()),p=url.pathname,body=request.method()==='POST'?request.postDataJSON() as Record<string,unknown>:null;s.requests.push({path:p,method:request.method(),body,key:request.headers()['idempotency-key']??null});const meta={createdAt:'2026-10-01T01:00:00Z',updatedAt:'2026-10-01T01:00:00Z'},actions=s.seatOnly?['class.read','seating.manage']:['class.read','group.manage','seating.manage'];
 if(p==='/api/v1/me/context')return reply(route,{user:{id:studentId,version:1,displayName:'Người quản lý tổ chức API',email:'organization@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'organization-csrf',mode:'connected',serverNow:'2026-10-01T01:00:00Z',memberships:[{memberId:enrollmentId,schoolId,schoolName:'Trường tổ chức API',schoolSlug:'organization-api',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-01',department:null,schoolWorkspace:false,teacherWorkspace:false,duties:[],grants:[{id:assignmentId,version:1,roleId:positionId,roleCode:'ORGANIZATION_CLASS',roleLabel:'Quản lý tổ chức lớp',scopeType:'CLASS',classId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions}]}]});
 if(p==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'organization-notifications'}});
 if(p===purpose+'/workspace-header')return reply(route,{school:{id:schoolId,name:'Trường tổ chức API',shortName:'API',slug:'organization-api'},class:{id:classId,yearId,gradeLevelId:groupId,name:'6A tổ chức API',capacity:40,status:'ACTIVE',version:s.groups.classVersion,roomId:null,motto:null,createdAt:'2026-09-01T00:00:00Z'},year,grade:'Khối 6',today:'2026-10-01',referenceDate:'2026-10-01',homeroom:null,studentCount:null,maleCount:null,femaleCount:null,myDuties:[],viaSchoolRole:false,workspaceKind:'CLASS',actions,tabs:[{key:'overview',label:'Tổng quan',path:''},{key:'groups',label:'Tổ & sơ đồ',path:s.seatOnly?'/seating':'/groups'}],summary:{weekIndex:null,weekStatus:null,pending:null,links:null,lastPublishedAt:null},readOnly:false});
 if(p===purpose+'/group-workspace'||p===purpose+'/seating-workspace'){
  if(s.mode==='outage'||s.mode==='denied')return route.fulfill({status:s.mode==='outage'?503:404,json:{code:s.mode==='outage'?'DEPENDENCY_UNAVAILABLE':'RESOURCE_NOT_FOUND',requestId:'organization-error'}});
  const data=p.endsWith('/group-workspace')?structuredClone(s.groups):structuredClone(s.seating);data.referenceDate=url.searchParams.get('onDate')??data.referenceDate;if(s.mode==='malformed')Object.assign(data,{guardianPhone:'PRIVATE-UNEXPECTED'});return reply(route,data);
 }
 if(p===`${root}/classes/${classId}/groups`&&body){s.groups.groups.push({id:newId,version:1,name:String(body.name),sortOrder:Number(body.sortOrder)});return reply(route,{...s.groups.groups.at(-1),...meta,classId},201);}
 if(p===`${root}/classes/${classId}/positions`&&body){let definition=s.groups.positionDefinitions.find(d=>d.code===body.code);if(!definition){definition={id:newId,version:1,name:String(body.name),code:String(body.code),singleHolder:Boolean(body.singleHolder),groupId:typeof body.groupId==='string'?body.groupId:null};s.groups.positionDefinitions.push(definition);}if(s.positionFailOnce){s.positionFailOnce=false;return route.abort('failed');}const {groupId:definedGroup,...position}=definition;return reply(route,{...position,...meta,classId,...(definedGroup===null?{}:{groupId:definedGroup})},201);}
 if(p===`${root}/classes/${classId}/groups/assign`&&body){s.groups.students[0].groupId=body.groupId as string;s.groups.classVersion++;return reply(route,{id:classId,status:'APPLIED',version:s.groups.classVersion});}
 if(p===`${root}/classes/${classId}/positions/assign`&&body){const holder={id:assignmentId,version:1,positionId:String(body.positionId),enrollmentId:String(body.enrollmentId),startsOn:String(body.startsOn),endsOn:'2027-06-01'};s.groups.holders=[holder];return reply(route,{...holder,...meta},201);}
 if(p===`${root}/classes/${classId}/position-assignments/${assignmentId}/end`&&body){const prior=s.groups.holders[0];s.groups.holders=[];return reply(route,{...prior,...meta,version:2,cancelledAt:meta.updatedAt});}
 if(p===purpose+'/seating-revisions'&&body){if(s.mode==='conflict')return route.fulfill({status:409,json:{code:'SEATING_REVISION_CONFLICT',currentVersion:3,requestId:'organization-conflict'}});s.seating.history[0].status='ARCHIVED';s.seating.history[0].version++;s.seating.latestRevision++;const savedSeats=body.seats as typeof s.seating.plan.seats;s.seating.plan={...s.seating.plan,rows:savedSeats.length?Math.max(...savedSeats.map(seat=>seat.row))+1:null,cols:savedSeats.length?Math.max(...savedSeats.map(seat=>seat.column))+1:null,id:newId,version:2,revision:s.seating.latestRevision,note:String(body.note??''),seats:savedSeats};s.seating.history.unshift({id:newId,version:2,revision:s.seating.latestRevision,effectiveOn:String(body.effectiveOn),endsOn:'2027-06-01',status:'ACTIVE',createdAt:'2026-10-01T01:00:00Z',createdByName:null});const {id,version,revision,effectiveOn,endsOn,seats}=s.seating.plan;return reply(route,{id,version,revision,effectiveOn,endsOn,seats,...meta,classId,status:'ACTIVE'},201);}
 s.unexpected.push(p);return route.fulfill({status:503,json:{code:'UNEXPECTED_ORGANIZATION_OPERATION',requestId:'organization-unexpected'}});
 });}
test('organization groups create actual setup move pupils and assign or end configured positions with displayed versions',async({page})=>{
 const s=state();await routes(page,s);await page.goto(base+'/groups');await expect(page.getByText('Chức vụ nguồn API',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Thêm tổ',exact:true}).click();await page.getByLabel('Tên tổ',{exact:false}).fill('Tổ vừa tạo API');await page.getByRole('button',{name:'Lưu',exact:true}).click();await expect(page.getByRole('region',{name:/Tổ vừa tạo API/})).toBeVisible();
 await page.getByLabel('Chọn học sinh',{exact:true}).selectOption(studentId);await page.getByLabel('Chuyển sang tổ',{exact:true}).selectOption(newId);await page.getByRole('button',{name:'Chuyển',exact:true}).click();await expect(page.getByRole('region',{name:/Tổ vừa tạo API, 1 học sinh/})).toBeVisible();
 await page.getByLabel('Chọn học sinh cho Chức vụ nguồn API',{exact:true}).selectOption(studentId);await page.getByRole('button',{name:'Giao chức vụ',exact:true}).click();await expect(page.getByRole('button',{name:'Bỏ chức vụ',exact:true})).toBeVisible();await page.getByRole('button',{name:'Bỏ chức vụ',exact:true}).click();await expect(page.getByRole('button',{name:'Giao chức vụ',exact:true})).toBeVisible();
 const move=s.requests.find(r=>r.path.endsWith('/groups/assign'))!,end=s.requests.find(r=>r.path.endsWith('/end'))!;expect(move.body).toMatchObject({enrollmentIds:[enrollmentId],expectedClassVersion:3});expect(end.body).toMatchObject({expectedVersion:1,endsOn:'2026-10-01'});expect(s.requests.some(r=>r.path.includes('/frontend/')||r.path.includes('/student-directory'))).toBe(false);expect(s.unexpected).toEqual([]);await page.screenshot({path:`qa/backend/${prefix}-groups-desktop.png`,fullPage:true});
});
test('organization seating saves actual coordinates note and revision atomically then reloads the returned version',async({page})=>{
 const s=state();await routes(page,s);await page.goto(base+'/seating');await page.getByRole('button',{name:'Xếp dạng danh sách',exact:true}).click();await page.getByLabel('Ghế của Học sinh tổ chức API',{exact:true}).selectOption('r1c2');await page.getByLabel('Ghi chú phiên bản',{exact:true}).fill('Đổi chỗ nguồn API');await page.getByRole('button',{name:'Lưu phiên bản 2',exact:true}).click();await expect(page.getByRole('button',{name:'Lưu phiên bản 3',exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Phiên bản 2 · áp dụng từ 01/10/2026',{exact:true})).toBeVisible();expect(s.requests.filter(r=>r.method==='POST')).toHaveLength(1);expect(s.requests.find(r=>r.path.endsWith('/seating-revisions'))?.body).toMatchObject({expectedRevision:1,note:'Đổi chỗ nguồn API',seats:[{key:'r1c1',row:0,column:0,enrollmentId:null},{key:'r1c2',row:0,column:1,enrollmentId}]});expect(s.unexpected).toEqual([]);await page.screenshot({path:`qa/backend/${prefix}-seating-desktop.png`,fullPage:true});
});
test('organization seating keeps an unsaved change visible when the displayed revision conflicts',async({page})=>{
 const s=state();await routes(page,s);await page.goto(base+'/seating');await page.getByLabel('Ghi chú phiên bản',{exact:true}).fill('Giữ bản đang chỉnh');s.mode='conflict';await page.getByRole('button',{name:'Lưu phiên bản 2',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('Ghi chú phiên bản',{exact:true})).toHaveValue('Giữ bản đang chỉnh');expect(s.seating.latestRevision).toBe(1);expect(s.unexpected).toEqual([]);
});
test('organization empty seating revision accepts drag and resized coordinates then persists its new grid',async({page})=>{
 const s=state();s.seating.plan={...s.seating.plan,rows:null,cols:null,seats:[]};await routes(page,s);await page.goto(base+'/seating');await expect(page.locator('[data-seat]')).toHaveCount(36);
 await page.getByLabel('Số hàng',{exact:true}).fill('2');await page.getByLabel('Ghế mỗi hàng',{exact:true}).fill('2');await expect(page.locator('[data-seat]')).toHaveCount(4);
 await page.getByRole('button',{name:'Học sinh tổ chức API (P1)',exact:true}).dragTo(page.locator('[data-seat="r2c2"]'));await expect(page.locator('[data-seat="r2c2"]')).toHaveAttribute('aria-label','Hàng 2, ghế 2: Học sinh tổ chức API');
 await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click();await expect(page.getByRole('button',{name:'Lưu phiên bản 3',exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('Số hàng',{exact:true})).toHaveValue('2');await expect(page.getByLabel('Ghế mỗi hàng',{exact:true})).toHaveValue('2');await expect(page.locator('[data-seat="r2c2"]')).toContainText('chức API');
 const write=s.requests.find(r=>r.path.endsWith('/seating-revisions'))!;expect(write.body).toMatchObject({expectedRevision:1,seats:[{key:'r1c1',row:0,column:0,enrollmentId:null},{key:'r1c2',row:0,column:1,enrollmentId:null},{key:'r2c1',row:1,column:0,enrollmentId:null},{key:'r2c2',row:1,column:1,enrollmentId}]});expect(s.unexpected).toEqual([]);
});
test('organization source failures do not become an empty group or seating source and malformed or denied receipts remove all pupil controls',async({page})=>{
 const s=state();s.mode='outage';await routes(page,s);await page.goto(base+'/seating');await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Lưu phiên bản 1',exact:true})).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByRole('button',{name:'Lưu phiên bản 2',exact:true})).toBeVisible();s.mode='malformed';await page.reload();await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByText('Học sinh tổ chức API',{exact:true})).toHaveCount(0);s.mode='denied';await page.goto(base+'/groups');await expect(page.getByText('Không tìm thấy',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Thêm tổ',exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);
});
test('organization group and seating keep the existing layout readable at390px without page overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844});const s=state();await routes(page,s);await page.goto(base+'/groups');await expect(page.getByText('Chức vụ nguồn API',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-groups-mobile.png`,fullPage:true});await page.goto(base+'/seating');await expect(page.getByRole('button',{name:'Lưu phiên bản 2',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(s.unexpected).toEqual([]);await page.screenshot({path:`qa/backend/${prefix}-seating-mobile.png`,fullPage:true});
});
test('organization position setup retries an uncertain write with the same configured code and idempotency key',async({page})=>{
 const s=state();s.positionFailOnce=true;await routes(page,s);await page.goto(base+'/groups');await page.getByRole('button',{name:'Thêm chức vụ',exact:true}).click();await page.getByLabel('Tên chức vụ',{exact:false}).fill('Chức vụ mới nguồn API');await page.getByRole('button',{name:'Lưu',exact:true}).click();await expect(page.getByRole('button',{name:'Lưu',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Lưu',exact:true}).click();await expect(page.getByText('Chức vụ mới nguồn API',{exact:true})).toBeVisible();const writes=s.requests.filter(r=>r.path===`${root}/classes/${classId}/positions`);expect(writes).toHaveLength(2);expect(writes[0].body).toEqual(writes[1].body);expect(writes[0].key).toBeTruthy();expect(writes[0].key).toBe(writes[1].key);expect(s.groups.positionDefinitions.filter(d=>d.name==='Chức vụ mới nguồn API')).toHaveLength(1);expect(s.unexpected).toEqual([]);
});
test('organization seating-only authority navigates directly to the permitted source and exposes no group or duty links',async({page})=>{
 const s=state();s.seatOnly=true;await routes(page,s);await page.goto(base+'/seating');await expect(page.getByRole('button',{name:'Lưu phiên bản 2',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Tổ & sơ đồ',exact:true}).first()).toHaveAttribute('href',base+'/seating');await expect(page.getByRole('link',{name:'Tổ & chức vụ',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Trực nhật',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Xếp dạng danh sách',exact:true}).click();await expect(page.getByText('Không có quyền xem tổ',{exact:false})).toBeVisible();expect(s.requests.some(r=>r.path.endsWith('/group-workspace'))).toBe(false);expect(s.unexpected).toEqual([]);
});
