import {expect,test,type Page,type Route} from '@playwright/test';
const schoolId='73000000-0000-4000-8000-000000000001',yearId='73000000-0000-4000-8000-000000000002',classId='73000000-0000-4000-8000-000000000003',userId='73000000-0000-4000-8000-000000000004',memberId='73000000-0000-4000-8000-000000000005',gradeId='73000000-0000-4000-8000-000000000006';
const base=`/classroom/${schoolId}/${yearId}/${classId}`,purpose=`/api/v1/schools/${schoolId}/academic-years/${yearId}/classes/${classId}/workspace-header`,prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-class-header';
type State={kind:'CLASS'|'SCHOOL'|'TEACHER';mode:'ready'|'outage'|'denied'|'malformed';unexpected:string[];directoryReads:number};
const state=():State=>({kind:'CLASS',mode:'ready',unexpected:[],directoryReads:0});
const year={id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:'ACTIVE'};
function header(s:State){const teacher=s.kind==='TEACHER';return {school:{id:schoolId,name:'Trường đầu trang API',shortName:'API',slug:'class-header'},class:{id:classId,yearId,gradeLevelId:gradeId,name:'6A API',capacity:40,status:'ACTIVE',version:2,roomId:null,motto:null,createdAt:'2026-09-01T00:00:00Z'},year,grade:'Khối 6',today:'2026-10-01',referenceDate:'2026-10-01',homeroom:{name:'Chủ nhiệm công tác API',contactVisible:teacher,workEmail:teacher?'work-header@example.invalid':null,workPhone:teacher?'0901234567':null},studentCount:teacher?2:null,maleCount:teacher?1:null,femaleCount:teacher?1:null,myDuties:teacher?['Chủ nhiệm']:[],viaSchoolRole:s.kind==='SCHOOL',workspaceKind:s.kind,actions:teacher?['class.read','teacher.self','year.read','student.read','conduct.read','parent_access.manage']:['class.read','parent_access.manage'],tabs:teacher?[{key:'overview',label:'Tổng quan',path:''},{key:'students',label:'Học sinh',path:'/students'},{key:'conduct',label:'Thi đua',path:'/conduct'}]:[{key:'overview',label:'Tổng quan',path:''}],summary:{weekIndex:teacher?5:null,weekStatus:teacher?'PUBLISHED':null,pending:teacher?0:null,links:{studentsWithLink:1,opened:0},lastPublishedAt:teacher?'2026-10-01T01:00:00Z':null},readOnly:false};}
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'class-header-controlled-browser'}});
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{
 const url=new URL(route.request().url()),p=url.pathname;
 if(p==='/api/v1/me/context')return reply(route,{user:{id:userId,version:1,displayName:'Người đọc đầu trang API',email:'header@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'header-csrf',mode:'connected',serverNow:'2026-10-01T01:00:00Z',memberships:[{memberId,schoolId,schoolName:'Trường đầu trang API',schoolSlug:'class-header',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-01',department:null,schoolWorkspace:s.kind==='SCHOOL',teacherWorkspace:s.kind==='TEACHER',duties:s.kind==='TEACHER'?[{id:memberId,classId,className:'6A API',kind:'HOMEROOM',subjectId:null,subjectName:null,startsOn:'2026-09-01',endsOn:'2027-06-01'}]:[],grants:[{id:memberId,version:1,roleId:gradeId,roleCode:s.kind==='TEACHER'?'HOMEROOM':'HEADER_READER',roleLabel:'Đọc lớp',scopeType:s.kind==='SCHOOL'?'SCHOOL':'CLASS',...(s.kind!=='SCHOOL'?{classId}:{}),validFrom:'2026-09-01T00:00:00Z',validUntil:null,...(s.kind==='TEACHER'?{assignmentStartsOn:'2026-09-01',assignmentEndsOn:'2027-06-01'}:{}),actions:s.kind==='SCHOOL'?['class.read','year.read']:s.kind==='TEACHER'?['class.read','teacher.self','year.read','student.read','conduct.read','parent_access.manage']:['class.read','parent_access.manage']}]}]});
 if(p==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'header-notifications'}});
 if(p===purpose){if(s.mode==='outage'||s.mode==='denied')return route.fulfill({status:s.mode==='outage'?503:404,json:{code:s.mode==='outage'?'DEPENDENCY_UNAVAILABLE':'RESOURCE_NOT_FOUND',requestId:'header-read-error'}});const value=header(s);if(s.mode==='malformed')Object.assign(value.homeroom,{userId});return reply(route,value);}
 if(p===`/api/v1/schools/${schoolId}/academic-years`)return route.fulfill({status:200,json:{data:[{...year,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'}],page:{total:1,limit:100,hasMore:false,nextCursor:null},requestId:'header-years'}});
 if(p===`/api/v1/schools/${schoolId}/me/class-directory`){s.directoryReads++;if(s.kind!=='TEACHER'){s.unexpected.push(p);return route.fulfill({status:403,json:{code:'FORBIDDEN',requestId:'no-self-reader'}});}return route.fulfill({status:200,json:{data:[{id:classId,schoolId,yearId,name:'6A API',yearLabel:'2026–2027',status:'ACTIVE',today:'2026-10-01',referenceDate:'2026-10-01',live:true,motto:null,studentCount:2,roomLabel:null,homeroomName:'Chủ nhiệm công tác API',assignments:[{id:memberId,kind:'HOMEROOM',subjectName:null,startsOn:'2026-09-01',endsOn:'2027-06-01',live:true,status:'ACTIVE'}],actions:['class.read','student.read'],nextLesson:null}],page:{total:1,limit:100,hasMore:false,nextCursor:null},requestId:'header-teacher-directory'}});}
 s.unexpected.push(p);return route.fulfill({status:503,json:{code:'UNEXPECTED_HEADER_OPERATION',requestId:'header-unexpected'}});
 });}
test('class header keeps exact delegated CLASS without teacher self and nullable independent panels',async({page})=>{
 const s=state();await routes(page,s);await page.goto(base);await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toBeVisible();await expect(page.getByText('Chưa có kỳ hoặc không có quyền xem',{exact:true})).toBeVisible();await expect(page.getByText('Không có quyền xem',{exact:true})).toBeVisible();await expect(page.getByText('work-header@example.invalid',{exact:true})).toHaveCount(0);await expect(page.getByRole('navigation',{name:'Mục của lớp 6A API'}).getByRole('link')).toHaveCount(1);await expect(page.getByRole('progressbar',{name:'Tỉ lệ học sinh có link tra cứu'})).toHaveCount(0);expect(s.directoryReads).toBe(0);expect(s.unexpected).toEqual([]);
 // CL01 content remains explicitly unavailable in this header-only checkpoint.
 await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-class-header-class-desktop.png`,fullPage:true});
});
test('class header fits mobile while denying absent roster denominator and invented period state',async({page})=>{
 await page.setViewportSize({width:390,height:844});const s=state();await routes(page,s);await page.goto(base);await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.getByText('Chưa có kỳ hoặc không có quyền xem',{exact:true})).toBeVisible();await page.screenshot({path:`qa/backend/${prefix}-class-header-class-mobile.png`,fullPage:true});expect(s.directoryReads).toBe(0);expect(s.unexpected).toEqual([]);
});
test('class header uses actual school authority without fetching a denied teacher directory',async({page})=>{
 const s=state();s.kind='SCHOOL';await routes(page,s);await page.goto(base);await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toBeVisible();await expect(page.getByText('Xem theo quyền nhà trường',{exact:true})).toBeVisible();expect(s.directoryReads).toBe(0);expect(s.unexpected).toEqual([]);await page.screenshot({path:`qa/backend/${prefix}-class-header-school-desktop.png`,fullPage:true});
});
test('class header preserves teacher full cards and actual current contact counters and published status',async({page})=>{
 const s=state();s.kind='TEACHER';await routes(page,s);await page.goto(base);await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toBeVisible();await expect(page.getByText('work-header@example.invalid',{exact:true})).toBeVisible();await expect(page.getByText('1 nam · 1 nữ',{exact:true})).toBeVisible();await expect(page.getByText('Đã công bố',{exact:true})).toBeVisible();await expect(page.getByRole('progressbar',{name:'Tỉ lệ học sinh có link tra cứu'})).toBeVisible();await expect(page.getByRole('navigation',{name:'Mục của lớp 6A API'}).getByRole('link')).toHaveCount(3);expect(s.directoryReads).toBeGreaterThan(0);expect(s.unexpected).toEqual([]);await page.screenshot({path:`qa/backend/${prefix}-class-header-teacher-desktop.png`,fullPage:true});
});
test('class header errors remove private panels and outage retry confirms a fresh exact receipt',async({page})=>{
 const s=state();s.mode='outage';await routes(page,s);await page.goto(base);await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toBeVisible();s.mode='malformed';await page.reload();await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByText('Chủ nhiệm công tác API',{exact:true})).toHaveCount(0);s.mode='denied';await page.reload();await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);
});
