import {test,expect,type Page,type Route} from '@playwright/test';
const schoolId='7d000000-0000-4000-8000-000000000001',yearId='7d000000-0000-4000-8000-000000000002',classId='7d000000-0000-4000-8000-000000000003',studentId='7d000000-0000-4000-8000-000000000004',enrollmentId='7d000000-0000-4000-8000-000000000005',guardianId='7d000000-0000-4000-8000-000000000006',relationshipId='7d000000-0000-4000-8000-000000000007';
const root=`/api/v1/schools/${schoolId}`,purpose=`${root}/academic-years/${yearId}/classes/${classId}`,base=`/classroom/${schoolId}/${yearId}/${classId}`,prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-class-student',stamp='2026-10-02T01:00:00Z';
const year={id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:'ACTIVE'},meta={version:3,createdAt:stamp,updatedAt:stamp};
type State={mode:'ready'|'subject'|'outage'|'malformed'|'profileoutage'|'foreignprofile';requests:{path:string;method:string;query:string}[];unexpected:string[]};
const state=():State=>({mode:'ready',requests:[],unexpected:[]});const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'class-student-controlled'}});
const actions=(s:State)=>['class.read','student.read','attendance.read',...(s.mode==='subject'?[]:['guardian.read','parent_access.manage','student.transfer.request'])];
function profile(s:State){const full=s.mode!=='subject',selected={...meta,id:enrollmentId,studentId,classId,yearId,startsOn:'2026-09-01',endsOn:null,status:'ACTIVE',className:'6A hồ sơ API',yearName:year.name,yearStatus:'ACTIVE',referenceDate:'2026-10-02',inEffect:true,homeroomName:'GVCN hồ sơ API'};
 return {student:{...meta,id:studentId,studentCode:'PROFILE001',fullName:'Học sinh hồ sơ API',dateOfBirth:full?'2011-09-30':null,gender:full?'Nữ':null,status:'ACTIVE',preferredName:null},level:full?'FULL':'SUBJECT_MINIMAL',today:'2026-10-02',year,referenceDate:'2026-10-02',selectedEnrollment:selected,history:[selected],group:null,positions:full?[]:null,relationships:full?[{...meta,id:relationshipId,studentId,guardianId,relationshipLabel:'Mẹ',isPrimary:true,canReceiveInfo:true,status:'VERIFIED',verifiedAt:stamp,revokedAt:null,guardian:{...meta,id:guardianId,fullName:'Giám hộ hồ sơ riêng API',phone:'0912345678',email:null,status:'ACTIVE'}}]:null,links:full?[]:null,accessLog:full?[]:null,accessLogHasMore:full?false:null,internalNote:full?'Ghi chú chỉ dành cho nhân sự API':null,perms:{edit:false,transfer:full,seeGuardians:full,editGuardians:false,verifyGuardians:false,manageLinks:full,issueLinks:false,revokeLinks:false,seeInternalNote:full,seeBirthDate:full}};
}
const attendance=()=>({schoolId,yearId,classId,studentId,today:'2026-10-02',referenceDate:'2026-10-02',className:'6A hồ sơ API',sessions:3,published:1,tally:{PRESENT:1,LATE:1,EXCUSED:0,UNEXCUSED:0,UNMARKED:1},notable:[{date:'2026-10-02',status:'UNMARKED',note:null,published:false},{date:'2026-10-01',status:'LATE',note:'Ghi chú công khai riêng API',published:true}]});
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname;s.requests.push({path,method:req.method(),query:url.search});
 if(path==='/api/v1/me/context')return reply(route,{user:{id:guardianId,version:1,displayName:'Nhân sự hồ sơ API',email:'class-student@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'class-student-browser-csrf',mode:'connected',serverNow:stamp,memberships:[{memberId:enrollmentId,schoolId,schoolName:'Trường hồ sơ API',schoolSlug:'class-student',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-02',department:null,schoolWorkspace:false,teacherWorkspace:false,duties:[],grants:[{id:relationshipId,version:1,roleId:guardianId,roleCode:'CLASS_PROFILE',roleLabel:'Phạm vi lớp',scopeType:'CLASS',classId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions:actions(s)}]}]});
 if(path==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'class-student-notifications'}});
 if(path===purpose+'/workspace-header')return reply(route,{school:{id:schoolId,name:'Trường hồ sơ API',shortName:'API',slug:'class-student'},class:{id:classId,yearId,gradeLevelId:guardianId,name:'6A hồ sơ API',capacity:40,status:'ACTIVE',version:3,roomId:null,motto:null,createdAt:stamp},year,grade:'Khối6',today:'2026-10-02',referenceDate:'2026-10-02',homeroom:null,studentCount:1,maleCount:0,femaleCount:1,myDuties:[],viaSchoolRole:false,workspaceKind:'CLASS',actions:actions(s),tabs:[{key:'overview',label:'Tổng quan',path:''},{key:'students',label:'Học sinh',path:'/students'},{key:'attendance',label:'Điểm danh',path:'/attendance'}],summary:{weekIndex:null,weekStatus:null,pending:null,links:s.mode==='subject'?null:{studentsWithLink:0,opened:0},lastPublishedAt:null},readOnly:false});
 if(path===root+`/students/${studentId}/details`){if(s.mode==='profileoutage')return route.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE',requestId:'profile-outage'}});const v=profile(s);return reply(route,s.mode==='foreignprofile'?{...v,selectedEnrollment:{...v.selectedEnrollment,yearId:guardianId}}:v);}
 if(path===purpose+`/students/${studentId}/attendance`){if(['subject','outage'].includes(s.mode))return route.fulfill({status:s.mode==='subject'?404:503,json:{code:s.mode==='subject'?'RESOURCE_NOT_FOUND':'DEPENDENCY_UNAVAILABLE',requestId:'class-student-attendance-error'}});const v=attendance();return reply(route,s.mode==='malformed'?{...v,studentId:guardianId,internalNote:'PRIVATE-UNEXPECTED'}:v);}
 s.unexpected.push(path);return route.fulfill({status:503,json:{code:'UNEXPECTED_BROWSER_CONTRACT_REQUEST',requestId:'class-student-unexpected'}});
 });}
async function open(page:Page,s:State){await routes(page,s);await page.goto(base+`/students/${studentId}`);await expect(page.getByRole('heading',{name:'Hồ sơ học sinh',exact:true})).toBeVisible();}
test('class student profile shows actual own attendance current scoped family history and independent transfer authority',async({page})=>{const s=state();await open(page,s);await expect(page.getByText('3 buổi đã lưu · 1 buổi đã công bố cho phụ huynh.')).toBeVisible();await expect(page.getByText('Ghi chú công khai riêng API',{exact:true})).toBeVisible();await expect(page.getByText('Giám hộ hồ sơ riêng API',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Đề nghị chuyển lớp',exact:true})).toBeVisible();await expect(page.getByText('Đổi tổ / chức vụ ở trang Tổ & chức vụ',{exact:true})).toHaveCount(0);await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});expect(s.unexpected).toEqual([]);const details=s.requests.find(r=>r.path.endsWith('/details'))!;expect(new URLSearchParams(details.query).get('classId')).toBe(classId);expect(new URLSearchParams(details.query).get('yearId')).toBe(yearId);expect(s.requests.some(r=>r.path===root+'/students')).toBe(false);});
test('subject class profile keeps the native minimal pupil and denies daily summary without exposing family birth date links or zero counts on mobile',async({page})=>{const s=state();s.mode='subject';await page.setViewportSize({width:390,height:844});await open(page,s);await expect(page.getByText('Hồ sơ rút gọn theo phạm vi giáo viên bộ môn',{exact:true})).toBeVisible();await expect(page.getByText('Giám hộ hồ sơ riêng API',{exact:true})).toHaveCount(0);await expect(page.getByText('Ghi chú chỉ dành cho nhân sự API',{exact:false})).toHaveCount(0);await expect(page.getByRole('heading',{name:'Link tra cứu phụ huynh'})).toHaveCount(0);await expect(page.getByText(/buổi đã lưu/)).toHaveCount(0);await expect(page.getByRole('button',{name:'Đề nghị chuyển lớp',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('class profile attendance outages retry without zero fallback and foreign or malformed summary receipts hide counts',async({page})=>{const s=state();s.mode='outage';await open(page,s);await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByText(/buổi đã lưu/)).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại'}).click();await expect(page.getByText('3 buổi đã lưu · 1 buổi đã công bố cho phụ huynh.')).toBeVisible();s.mode='malformed';await page.reload();await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByText(/buổi đã lưu/)).toHaveCount(0);expect(s.unexpected).toEqual([]);});
test('a failed or foreign year profile cannot display pupil family or launch the subordinate attendance purpose',async({page})=>{const s=state();s.mode='profileoutage';await routes(page,s);await page.goto(base+`/students/${studentId}`);await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByText('Giám hộ hồ sơ riêng API',{exact:true})).toHaveCount(0);expect(s.requests.some(r=>r.path.endsWith(`/${studentId}/attendance`))).toBe(false);s.mode='foreignprofile';await page.getByRole('button',{name:'Thử lại'}).click();await expect(page.getByRole('button',{name:'Thử lại'})).toBeVisible();await expect(page.getByRole('heading',{name:'Hồ sơ học sinh',exact:true})).toHaveCount(0);expect(s.requests.some(r=>r.path.endsWith(`/${studentId}/attendance`))).toBe(false);expect(s.unexpected).toEqual([]);});
