import {expect,test,type Page,type Route} from '@playwright/test';
const schoolId='74000000-0000-4000-8000-000000000001',yearId='74000000-0000-4000-8000-000000000002',classId='74000000-0000-4000-8000-000000000003',userId='74000000-0000-4000-8000-000000000004',memberId='74000000-0000-4000-8000-000000000005',gradeId='74000000-0000-4000-8000-000000000006',lessonId='74000000-0000-4000-8000-000000000007',activityId='74000000-0000-4000-8000-000000000008';
const base=`/classroom/${schoolId}/${yearId}/${classId}`,purpose=`/api/v1/schools/${schoolId}/academic-years/${yearId}/classes/${classId}`,prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-class-overview';
type State={mode:'full'|'minimal'|'holiday'|'archived'|'outage'|'malformed'|'denied';unexpected:string[];requests:string[]};
const state=(mode:State['mode']='full'):State=>({mode,unexpected:[],requests:[]});
const actions=(s:State)=>s.mode==='minimal'?['class.read']:s.mode==='archived'?['class.read','report.read']:['class.read','attendance.read','attendance.record','schedule.read','group.manage','activity.read','report.read'];
const year=(s:State)=>({id:yearId,version:1,code:'Y26',name:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01',status:s.mode==='archived'?'ARCHIVED':'ACTIVE'});
function header(s:State){const a=actions(s),tabs=[{key:'overview',label:'Tổng quan',path:''},...(a.includes('attendance.read')?[{key:'attendance',label:'Điểm danh',path:'/attendance'}]:[]),...(a.includes('schedule.read')?[{key:'timetable',label:'Lịch lớp',path:'/timetable'}]:[]),...(a.includes('group.manage')?[{key:'groups',label:'Tổ & sơ đồ',path:'/groups'}]:[]),...(a.includes('activity.read')?[{key:'activities',label:'Hoạt động',path:'/activities'}]:[]),...(a.includes('report.read')?[{key:'reports',label:'Báo cáo',path:'/reports'}]:[])];return {school:{id:schoolId,name:'Trường tổng quan API',shortName:'API',slug:'class-overview'},class:{id:classId,yearId,gradeLevelId:gradeId,name:'6A nguồn thật',capacity:40,status:'ACTIVE',version:2,roomId:null,motto:null,createdAt:'2026-09-01T00:00:00Z'},year:year(s),grade:'Khối 6',today:'2026-10-01',referenceDate:'2026-10-01',homeroom:null,studentCount:null,maleCount:null,femaleCount:null,myDuties:[],viaSchoolRole:false,workspaceKind:'CLASS',actions:a,tabs,summary:{weekIndex:null,weekStatus:null,pending:null,links:null,lastPublishedAt:null},readOnly:s.mode==='archived'};}
function overview(s:State){const minimal=s.mode==='minimal'||s.mode==='archived',holiday=s.mode==='holiday';return {schoolId,yearId,classId,today:'2026-10-01',referenceDate:'2026-10-01',asOf:'2026-10-01T01:00:00Z',isCurrent:s.mode!=='archived',readOnly:s.mode==='archived',permissions:{attendance:!minimal,schedule:!minimal,groups:!minimal,activities:!minimal},canRecordMorning:!minimal&&!holiday,allowedTaskKinds:minimal?[]:['attendance','groups'],tasks:minimal?null:holiday?[{kind:'groups',count:1}]:[{kind:'attendance',count:2},{kind:'groups',count:1}],attendance:minimal?null:{calendarState:holiday?'HOLIDAY':'WITHIN_YEAR',session:null,counts:holiday?null:{total:2,present:0,late:0,excused:0,unexcused:0,unmarked:2}},lessons:minimal?null:holiday?[]:[{id:lessonId,version:1,periodNumber:null,startsAtLocal:'08:00',endsAtLocal:'08:30',subjectName:'Môn chưa ghi tiết API',teacherName:null,roomName:null,status:'SCHEDULED',changeReason:null},{id:gradeId,version:2,periodNumber:2,startsAtLocal:'09:00',endsAtLocal:'09:30',subjectName:'Tiết hủy API',teacherName:'Tên công tác API',roomName:'Phòng nguồn API',status:'CANCELLED',changeReason:'Được thay bằng lịch mới'}],groups:minimal?null:{items:[{id:memberId,name:'Tổ nguồn API',size:1}],totalStudents:2,noGroup:1},activities:minimal?null:{items:Array.from({length:6},(_,i)=>({id:activityId.slice(0,-1)+(i+1),version:1,title:`Hoạt động nguồn API ${i+1}`,dueAt:'2026-10-03T17:30:00Z',dueDate:'2026-10-04',total:2,done:i===0?1:0})),total:8,hasMore:true},navigation:s.mode==='archived'?['reports']:minimal?[]:['reports','attendance/weekly','timetable','groups','activities']};}
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'class-overview-controlled-browser'}});
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async route=>{const p=new URL(route.request().url()).pathname;s.requests.push(p);
 if(p==='/api/v1/me/context')return reply(route,{user:{id:userId,version:1,displayName:'Người đọc tổng quan API',email:'overview@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'overview-csrf',mode:'connected',serverNow:'2026-10-01T01:00:00Z',memberships:[{memberId,schoolId,schoolName:'Trường tổng quan API',schoolSlug:'class-overview',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-01',department:null,schoolWorkspace:false,teacherWorkspace:false,duties:[],grants:[{id:memberId,version:1,roleId:gradeId,roleCode:'OVERVIEW_READER',roleLabel:'Đọc lớp được cấp',scopeType:'CLASS',classId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions:actions(s)}]}]});
 if(p==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'overview-notifications'}});
 if(p===purpose+'/workspace-header')return reply(route,header(s));
 if(p===purpose+'/workspace-overview'){if(s.mode==='outage'||s.mode==='denied')return route.fulfill({status:s.mode==='outage'?503:404,json:{code:s.mode==='outage'?'DEPENDENCY_UNAVAILABLE':'RESOURCE_NOT_FOUND',requestId:'overview-error'}});const d=overview(s);if(s.mode==='malformed')Object.assign(d,{studentId:userId});return reply(route,d);}
 s.unexpected.push(p);return route.fulfill({status:503,json:{code:'UNEXPECTED_OVERVIEW_OPERATION',requestId:'overview-unexpected'}});
 });}
test('class overview renders native morning source tasks cancelled nullable lessons groups and bounded activity progress on desktop',async({page})=>{
 const s=state();await routes(page,s);await page.goto(base);await expect(page.getByTestId('class-overview-attendance').getByText('0/2',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-attendance').getByText('Chưa tạo buổi điểm danh',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-tasks').getByText('2 học sinh chưa có buổi điểm danh',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-lessons').getByText('Chưa ghi số tiết',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-lessons').getByText('Đã hủy',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-groups').getByText('1 học sinh chưa phân tổ',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-activities').getByText('Hiển thị 6/8 hoạt động.',{exact:false})).toBeVisible();expect(s.unexpected).toEqual([]);expect(s.requests.filter(p=>p.includes('/frontend/'))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-class-overview-desktop.png`,fullPage:true});
});
test('class overview keeps the existing cards readable at390px and scrolls its actual schedule inside the table',async({page})=>{
 await page.setViewportSize({width:390,height:844});const s=state();await routes(page,s);await page.goto(base);await expect(page.getByTestId('class-overview-activities')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-class-overview-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);
});
test('class overview distinguishes denied panels from zero sources and does not borrow student or teacher directories',async({page})=>{
 const s=state('minimal');await routes(page,s);await page.goto(base);for(const suffix of ['tasks','attendance','lessons','groups','activities'])await expect(page.getByTestId('class-overview-'+suffix).getByText('Không có quyền xem phần này.',{exact:true})).toBeVisible();await expect(page.getByText('Chưa tạo tổ cho lớp.',{exact:true})).toHaveCount(0);await expect(page.getByText('Chưa có hoạt động đang giao trong phạm vi được cấp.',{exact:true})).toHaveCount(0);expect(s.requests.some(p=>p.includes('/student-directory')||p.includes('/class-directory'))).toBe(false);expect(s.unexpected).toEqual([]);await page.screenshot({path:`qa/backend/${prefix}-class-overview-denied.png`,fullPage:true});
});
test('class overview represents actual holiday absence without fabricated attendance denominator or create action',async({page})=>{
 const s=state('holiday');await routes(page,s);await page.goto(base);await expect(page.getByTestId('class-overview-attendance').getByText('Ngày nghỉ theo lịch trường',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-attendance').getByRole('link',{name:'Mở điểm danh'})).toHaveCount(0);await expect(page.getByTestId('class-overview-attendance').getByRole('progressbar')).toHaveCount(0);await expect(page.getByTestId('class-overview-tasks').getByText('Điểm danh buổi sáng',{exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);
});
test('class overview suppresses current sources for archived scope and independently gates historical links',async({page})=>{
 const s=state('archived');await routes(page,s);await page.goto(base);await expect(page.getByRole('heading',{name:'Năm học hoặc lớp đã lưu trữ',exact:true})).toBeVisible();for(const suffix of ['tasks','attendance','lessons'])await expect(page.getByTestId('class-overview-'+suffix)).toHaveCount(0);await expect(page.getByRole('link',{name:'Báo cáo lớp',exact:true}).first()).toBeVisible();await expect(page.getByRole('link',{name:'Điểm danh theo tuần',exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);await page.screenshot({path:`qa/backend/${prefix}-class-overview-archived.png`,fullPage:true});
});
test('class overview retries outages and removes every private content panel on malformed or denied purpose receipts',async({page})=>{
 const s=state('outage');await routes(page,s);await page.goto(base);await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();s.mode='full';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByTestId('class-overview-groups')).toBeVisible();s.mode='malformed';await page.reload();await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByTestId('class-overview-groups')).toHaveCount(0);s.mode='denied';await page.reload();await expect(page.getByTestId('class-overview-activities')).toHaveCount(0);await expect(page.getByText('Hoạt động nguồn API 1',{exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);
});
