import {test,expect,type Page,type Route} from '@playwright/test';
const id=(n:number)=>`6f100000-0000-4000-8000-${String(n).padStart(12,'0')}`,schoolId=id(1),rsId=id(2),root=`/api/v1/schools/${schoolId}`,web=`/school/${schoolId}/conduct-rules`,date='2026-10-02',stamp=date+'T01:00:00Z',hash='a'.repeat(64),prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-conduct-rules';
type State={mode:'ready'|'read'|'issue'|'outage'|'conflict';created:boolean;version:number;issued:boolean;title:string;calls:{path:string;body:Record<string,unknown>}[];unexpected:string[]};
const state=():State=>({mode:'ready',created:false,version:1,issued:false,title:'Nội quy từ API',calls:[],unexpected:[]});
const source=(s:State)=>({id:rsId,version:s.version,applicationHash:hash});
const item=(s:State)=>({schoolId,id:rsId,name:s.title,versionNo:1,status:s.issued?'published':'draft',effectiveFrom:'2026-10-09',effectiveTo:null,baseScore:100,cap:105,floor:0,rules:[{id:id(3),code:'QD01',label:'Ghi nhận trong API',points:-0.10,category:'Nề nếp',icon:'alert',shareWithParent:false,attendanceLink:null,valueMode:'FIXED',minimumDelta:null,maximumDelta:null,reasonRequired:true,maxOccurrencesPerDay:null}],bands:[{min:0,label:'Đạt',tone:'success'}],entryDeadlineDays:7,createdBy:id(8),createdByName:'Người tạo API',publishedAt:s.issued?stamp:null,version:s.version,source:source(s),isCurrent:false,usedBySnapshots:0,canManage:s.mode!=='read'&&s.mode!=='issue'&&!s.issued,canIssue:s.mode!=='read'&&!s.issued});
const reply=(r:Route,data:unknown,status=200,page?:unknown)=>r.fulfill({status,json:{data,...(page?{page}:{}),requestId:'rule-browser'}});
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async r=>{const request=r.request(),path=new URL(request.url()).pathname,body=request.method()==='GET'?null:request.postDataJSON();
 if(path==='/api/v1/me/context')return reply(r,{user:{id:id(8),version:1,displayName:'Nhân sự nội quy API',email:'rules@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'rule-browser-csrf',mode:'connected',serverNow:stamp,memberships:[{memberId:id(9),schoolId,schoolName:'Trường nội quy API',schoolSlug:'rule-api',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:date,schoolWorkspace:true,teacherWorkspace:false,duties:[],grants:[{id:id(6),version:1,roleId:id(7),roleCode:'CUSTOM',roleLabel:'Quyền nội quy API',scopeType:'SCHOOL',validFrom:'2026-09-01T00:00:00Z',validUntil:null,actions:['school.read','rules.read',...(s.mode==='read'?[]:s.mode==='issue'?['rules.issue','rules.apply']:['rules.manage','rules.issue','rules.apply'])]}]}]});
 if(path==='/api/v1/me/notifications')return reply(r,[],200,{limit:25,hasMore:false,nextCursor:null,total:0});
 if(path===root+'/profile')return reply(r,{id:schoolId,version:1,code:'RULE',name:'Trường nội quy API',slug:'rule-api',shortName:'API',province:'TP.HCM',level:null,accentColor:'#2876bc',motto:'Học tập an toàn',publicIntro:'Trường kiểm thử nội quy',publicContactEmail:null,publicContactPhone:null,publicAddress:null,website:null,status:'ACTIVE',createdAt:stamp});
 if(path===root+'/rule-workspace'&&request.method()==='GET'){if(s.mode==='outage')return r.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE'}});return reply(r,{schoolId,today:date,items:s.created?[item(s)]:[],canManage:s.mode!=='read',applicationHash:hash},200,{limit:100,hasMore:false,nextCursor:null,total:s.created?1:0});}
 if(path===root+'/rule-workspace/'+rsId&&request.method()==='GET')return reply(r,{ruleSet:item(s),previous:null,usedBySnapshots:0,canManage:item(s).canManage,earliestEffective:date});
 if(request.method()==='POST'&&path.startsWith(root+'/rule-workspace/')){s.calls.push({path,body});if(s.mode==='conflict')return r.fulfill({status:409,json:{code:'VERSION_CONFLICT',currentVersion:9}});
  if(path.endsWith('/create')){expect(body).toEqual({applicationHash:hash});s.created=true;return reply(r,item(s),201);}
  if(path.endsWith('/save')){expect(body.source).toEqual(source(s));expect(body.rules[0].shareWithParent).toBe(false);s.version++;s.title=body.name;return reply(r,item(s));}
  if(path.endsWith('/issue')){expect(body.source).toEqual(source(s));s.version++;s.issued=true;return reply(r,item(s));}
 }
 s.unexpected.push(path);return r.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND'}});
});}
test('native rule list creates the first real draft and dirty issue sends the acknowledged saved source',async({page})=>{const s=state();await routes(page,s);await page.goto(web);await expect(page.getByText('Chưa có bộ nội quy',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Tạo bản mới',exact:true}).click();await page.getByRole('button',{name:'Tạo bản nháp',exact:true}).click();await expect(page.getByLabel(/^Tên bộ nội quy/)).toHaveValue('Nội quy từ API');await page.getByLabel(/^Tên bộ nội quy/).fill('Nội quy đã sửa từ giao diện');await page.getByRole('button',{name:'Ban hành',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Ban hành',exact:true}).click();await expect(page.getByText('Phiên bản này không sửa trực tiếp',{exact:true})).toBeVisible();expect(s.calls.map(c=>c.path.split('/').at(-1))).toEqual(['create','save','issue']);expect((s.calls[2].body.source as {version:number}).version).toBe(2);expect(s.issued).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('read-only native rules preserve decimal example and hide write controls on mobile',async({page})=>{const s=state();s.mode='read';s.created=true;s.issued=true;await page.setViewportSize({width:390,height:844});await routes(page,s);await page.goto(web+'/'+rsId);await expect(page.getByRole('heading',{name:'Nội quy từ API',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Lưu nháp',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Ban hành',exact:true})).toHaveCount(0);await expect(page.getByText('Chi tiết',{exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.calls).toHaveLength(0);expect(s.unexpected).toEqual([]);});
test('native rule outage retries real directory and version conflicts keep the draft without issuing it',async({page})=>{const s=state();s.mode='outage';await routes(page,s);await page.goto(web);await expect(page.getByRole('button',{name:'Thử lại',exact:true})).toBeVisible();s.mode='ready';s.created=true;await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Nội quy từ API',{exact:true}).first()).toBeVisible();await page.goto(web+'/'+rsId);await page.getByLabel(/^Tên bộ nội quy/).fill('Bản nháp giữ sau xung đột');s.mode='conflict';await page.getByRole('button',{name:'Ban hành',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Ban hành',exact:true}).click();await expect(page.getByRole('heading',{name:'Dữ liệu đã thay đổi',exact:true})).toBeVisible();expect(s.calls).toHaveLength(1);expect(s.calls[0].path).toMatch(/\/save$/);expect(s.issued).toBe(false);expect(s.unexpected).toEqual([]);});
test('independent issue permission allows a displayed draft to be issued without exposing edit or delete controls',async({page})=>{const s=state();s.mode='issue';s.created=true;await routes(page,s);await page.goto(web+'/'+rsId);await expect(page.getByRole('heading',{name:'Nội quy từ API',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Lưu nháp',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Xóa bản nháp',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Ban hành',exact:true}).first().click();await page.getByRole('dialog').getByRole('button',{name:'Ban hành',exact:true}).click();await expect(page.getByText('Đã ban hành',{exact:true})).toBeVisible();expect(s.calls).toEqual([{path:root+'/rule-workspace/'+rsId+'/issue',body:{source:{id:rsId,version:1,applicationHash:hash}}}]);expect(s.issued).toBe(true);expect(s.unexpected).toEqual([]);});
