import {expect,test,type Page,type Route} from '@playwright/test';
const slug='parent-shared-browser',viewId='6e000000-0000-4000-8000-000000000001',activityId='6e000000-0000-4000-8000-000000000002',announcementId='6e000000-0000-4000-8000-000000000003',documentId='6e000000-0000-4000-8000-000000000004',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-parent-shared';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jVZkAAAAASUVORK5CYII=','base64');
const context=()=>({viewId,school:{name:'Trường nội dung API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con nội dung API',classLabel:'6A',schoolYearLabel:'2026–2027'},allowedSections:['activities','announcements','documents'],allowDownload:false,csrfToken:'shared-browser-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const file=()=>({id:documentId,title:'Minh chứng riêng đã công bố',contentType:'image/png',byteSize:png.length,publishedAt:'2026-10-01T01:00:00Z',viewAllowed:true,downloadAllowed:false});
const activity=()=>({id:activityId,title:'Hoạt động chỉ của con API',description:'Nội dung hoạt động đã công bố',dueAt:'2026-10-03T17:30:00Z',studentStatus:'EXCUSED',publicReviewNote:'Được miễn theo xác nhận đã công bố',documents:[file()],publishedAt:'2026-10-01T01:00:00Z',activityStatus:'ASSIGNED',illustration:'stem',updatedAt:'2026-10-01T00:00:00Z',timezone:'Asia/Ho_Chi_Minh',dueOn:'2026-10-04'});
const announcement=()=>({id:announcementId,title:'Thông báo đã công bố từ API',summary:'Tóm tắt giữ nguyên từ công bố',sanitizedHtml:'<h2>Nội dung họp gia đình</h2><p><strong>Xin mang sổ liên lạc</strong></p><ul><li>Gặp giáo viên tại lớp</li></ul><p>&lt;img src=x onerror=alert(1)&gt;</p>',publishedAt:'2026-10-01T01:00:00Z',senderLabel:'Lớp nguồn API',documents:[file()],scopeKinds:['STUDENT']});
type State={mode:'ready'|'bad'|'withdrawn'|'invalid';views:number};
const ready=():State=>({mode:'ready',views:0}),reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'shared-controlled-browser'}});
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const req=route.request(),path=new URL(req.url()).pathname;
 if(path==='/api/v1/me/context')return route.fulfill({status:401,json:{code:'UNAUTHENTICATED',requestId:'shared-anonymous'}});
 if(path==='/api/v1/auth/csrf')return reply(route,{csrfToken:'shared-bootstrap'});
 if(path===`/api/v1/public/schools/${slug}`)return reply(route,{name:'Trường nội dung API',slug,announcements:[]});
 if(path.endsWith('/access/exchange'))return reply(route,context());
 expect(req.headers()['x-parent-view']).toBe(viewId);
 if(state.mode==='invalid')return route.fulfill({status:401,json:{code:'PARENT_ACCESS_INVALID',requestId:'shared-invalid'}});
 if(path.endsWith('/context'))return reply(route,context());
 if(path.includes('/activities/')){if(path===`/api/v1/parent/${slug}/activities/published`)return reply(route,{items:state.mode==='withdrawn'?[]:[activity()]});if(path.endsWith(`/${activityId}/published`))return state.mode==='withdrawn'?route.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND',requestId:'shared-withdrawn'}}):reply(route,activity());}
 if(path.includes('/announcements/')){const a=announcement();if(state.mode==='bad')a.sanitizedHtml='<p onclick="alert(1)">Không được hiện</p><script>alert(1)</script>';if(path===`/api/v1/parent/${slug}/announcements/published`)return reply(route,{items:state.mode==='withdrawn'?[]:[a]});if(path.endsWith(`/${announcementId}/published`))return state.mode==='withdrawn'?route.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND',requestId:'shared-withdrawn'}}):reply(route,a);}
 if(path===`/api/v1/parent/${slug}/documents/${documentId}`)return reply(route,file());
 if(path===`/api/v1/parent/${slug}/documents/${documentId}/view`){state.views++;return route.fulfill({status:200,contentType:'image/png',headers:{'Cache-Control':'no-store'},body:png});}
 return route.fulfill({status:503,json:{code:'UNEXPECTED_SHARED_OPERATION',requestId:'shared-unexpected'}});
});}
async function open(page:Page){await page.goto(`/p/${slug}/access#token=${'H'.repeat(43)}`);await expect(page).toHaveURL(new RegExp(`/p/${slug}/activities$`));}

test('Parent activity list and detail keep the card design and actual own-child exempt status, school date and view-only evidence',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await expect(page.getByRole('heading',{name:'Hoạt động của con',exact:true})).toBeVisible();await expect(page.getByText('Được miễn',{exact:true})).toBeVisible();await expect(page.getByText('Hạn 04/10/2026',{exact:true})).toBeVisible();await page.screenshot({path:`qa/backend/${prefix}-parent-activities-desktop.png`,fullPage:true});await page.getByRole('link',{name:/Hoạt động chỉ của con API/}).click();await expect(page).toHaveURL(new RegExp(`/activities/${activityId}$`));await expect(page.getByText('Được miễn theo xác nhận đã công bố',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Tải Minh chứng riêng đã công bố',exact:true})).toHaveCount(0);await page.screenshot({path:`qa/backend/${prefix}-parent-activity-detail.png`,fullPage:true});await page.getByRole('button',{name:'Xem: Minh chứng riêng đã công bố',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('img',{name:'Xem trước: Minh chứng riêng đã công bố',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Tải xuống',exact:true})).toHaveCount(0);expect(state.views).toBe(1);
});
test('Parent announcements preserve search, actual audience labels and safe rich formatting without recipients or an active entity payload',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await page.goto(`/p/${slug}/announcements`);await expect(page.getByText('Học sinh được chọn',{exact:true})).toBeVisible();await expect(page.getByText('Riêng gia đình',{exact:true})).toHaveCount(0);await page.getByRole('searchbox').fill('không có khớp');await expect(page.getByText('Không có thông báo khớp từ khóa',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Xóa tìm kiếm',exact:true}).click();await expect(page.getByText('Thông báo đã công bố từ API',{exact:true})).toBeVisible();await page.screenshot({path:`qa/backend/${prefix}-parent-announcements-desktop.png`,fullPage:true});await page.getByRole('link',{name:/Thông báo đã công bố từ API/}).click();await expect(page.getByRole('heading',{name:'Nội dung họp gia đình',exact:true})).toBeVisible();await expect(page.locator('article strong')).toHaveText('Xin mang sổ liên lạc');await expect(page.locator('article li')).toHaveText('Gặp giáo viên tại lớp');await expect(page.locator('article')).toContainText('<img src=x onerror=alert(1)>');await expect(page.locator('article img, article script')).toHaveCount(0);await expect(page.getByRole('button',{name:'Tải Minh chứng riêng đã công bố',exact:true})).toHaveCount(0);await page.screenshot({path:`qa/backend/${prefix}-parent-announcement-detail.png`,fullPage:true});
});
test('Parent shared mobile layout stays within viewport and withdrawing detail removes previously displayed published content',async({page})=>{
 const state=ready();await routes(page,state);await page.setViewportSize({width:390,height:844});await open(page);await expect(page.getByText('Hoạt động chỉ của con API',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`qa/backend/${prefix}-parent-activities-mobile.png`,fullPage:true});await page.goto(`/p/${slug}/announcements`);await expect(page.getByText('Thông báo đã công bố từ API',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`qa/backend/${prefix}-parent-announcements-mobile.png`,fullPage:true});await page.getByRole('link',{name:/Thông báo đã công bố từ API/}).click();await expect(page.getByRole('heading',{name:'Nội dung họp gia đình',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);state.mode='withdrawn';await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));await expect(page.getByText('Không tìm thấy nội dung',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Nội dung họp gia đình',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Xem: Minh chứng riêng đã công bố',exact:true})).toHaveCount(0);
});
test('Parent malformed publication HTML stays hidden; retry restores safe content and terminal revocation clears the view',async({page})=>{
 const state=ready();await routes(page,state);await open(page);state.mode='bad';await page.goto(`/p/${slug}/announcements/${announcementId}`);await expect(page.getByText('API chưa xác nhận nội dung thông báo an toàn.',{exact:true})).toBeVisible();await expect(page.locator('article')).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByRole('heading',{name:'Nội dung họp gia đình',exact:true})).toBeVisible();state.mode='invalid';await page.reload();await expect(page).toHaveURL(/access-unavailable\?reason=invalid$/);expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBeNull();
});
