import {expect,test,type Page,type Route} from '@playwright/test';
const slug='parent-teacher-browser',viewId='67000000-0000-4000-8000-000000000001',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-parent-teachers';
const context=()=>({viewId,school:{name:'Trường giáo viên API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con giáo viên API',classLabel:'6A',schoolYearLabel:'2026–2027'},allowedSections:['teachers'],allowDownload:false,csrfToken:'synthetic-teacher-browser-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const directory=()=>({today:'2026-10-05',classLabel:'6A' as string|null,contactHours:null,teachers:[{kind:'HOMEROOM',displayName:'Chủ nhiệm công tác API',subjectName:null,workEmail:null as string|null,workPhone:null as string|null,weekdays:[]},{kind:'SUBJECT',displayName:'Bộ môn công tác API',subjectName:'Toán',workEmail:'teacher-work@example.invalid' as string|null,workPhone:null as string|null,weekdays:[1,3,7]}]});
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'parent-teacher-controlled-browser'}});
type State={mode:'ready'|'bad'|'masked'|'empty'|'invalid'|'denied';calls:number};
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const request=route.request(),path=new URL(request.url()).pathname;
 if(path==='/api/v1/me/context')return route.fulfill({status:401,json:{code:'UNAUTHENTICATED',requestId:'teacher-browser-anonymous'}});
 if(path==='/api/v1/auth/csrf')return reply(route,{csrfToken:'teacher-browser-bootstrap'});
 if(path===`/api/v1/parent/${slug}/access/exchange`||path===`/api/v1/parent/${slug}/context`)return reply(route,context());
 if(path===`/api/v1/public/schools/${slug}`)return reply(route,{name:'Trường giáo viên API',slug,announcements:[]});
 if(path===`/api/v1/parent/${slug}/teacher-directory`){state.calls++;expect(request.headers()['x-parent-view']).toBe(viewId);if(state.mode==='invalid'||state.mode==='denied')return route.fulfill({status:state.mode==='invalid'?401:403,json:{code:state.mode==='invalid'?'PARENT_ACCESS_INVALID':'PARENT_SECTION_DENIED',requestId:'teacher-browser-denied'}});const data=directory();if(state.mode==='bad')data.teachers[1].weekdays=[1,1];if(state.mode==='masked')data.teachers[1].workEmail=null;if(state.mode==='empty'){data.teachers=[];data.classLabel=null;}return reply(route,data);}
 return route.fulfill({status:503,json:{code:'UNEXPECTED_TEACHER_OPERATION',requestId:'teacher-browser-unexpected'}});
});}
async function open(page:Page){await page.goto(`/p/${slug}/access#token=${'D'.repeat(43)}`);await expect(page).toHaveURL(new RegExp(`/p/${slug}/teachers$`));}
const ready=():State=>({mode:'ready',calls:0});
test('Parent teacher cards use work-only shared contacts, actual published weekdays and nullable school/contact hours',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await expect(page.getByRole('heading',{name:'Giáo viên phụ trách',exact:true})).toBeVisible();await expect(page.getByText('Chủ nhiệm công tác API',{exact:true})).toBeVisible();await expect(page.locator('table').getByText('Thứ 2, Thứ 4, CN',{exact:true})).toBeVisible();await expect(page.locator('table').getByRole('link',{name:'teacher-work@example.invalid',exact:true})).toHaveAttribute('href','mailto:teacher-work@example.invalid');await expect(page.getByText('Thời gian liên hệ:',{exact:false})).toHaveCount(0);await expect(page.getByRole('link',{name:'Xem thời khóa biểu của lớp'})).toHaveCount(0);expect(await page.evaluate(()=>({...sessionStorage}))).toEqual({'edu-parent-view':JSON.stringify({slug,viewId})});await page.screenshot({path:`qa/backend/${prefix}-parent-teachers-desktop.png`,fullPage:true});
});
test('Parent teacher mobile keeps current teacher work cards and explicit empty assignments without horizontal overflow',async({page})=>{
 const state=ready();await routes(page,state);await page.setViewportSize({width:390,height:844});await open(page);await expect(page.locator('li').getByText('Bộ môn công tác API',{exact:false})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`qa/backend/${prefix}-parent-teachers-mobile.png`,fullPage:true});state.mode='empty';await page.reload();await expect(page.getByText('Chưa có giáo viên chủ nhiệm đang phụ trách con',{exact:true})).toBeVisible();await expect(page.getByText('Chưa có phân công giáo viên bộ môn',{exact:true})).toBeVisible();await expect(page.getByText('teacher-work@example.invalid',{exact:true})).toHaveCount(0);
});
test('Parent malformed teacher data stays hidden; focus revalidation suppresses changed work contacts and terminal revoke removes ownership',async({page})=>{
 const state=ready();state.mode='bad';await routes(page,state);await open(page);await expect(page.getByText('API chưa xác nhận đầy đủ giáo viên phụ trách của con.',{exact:true})).toBeVisible();await expect(page.getByText('teacher-work@example.invalid',{exact:true})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.locator('table').getByRole('link',{name:'teacher-work@example.invalid',exact:true})).toBeVisible();state.mode='masked';await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));await expect(page.getByText('teacher-work@example.invalid',{exact:true})).toHaveCount(0);state.mode='denied';await page.reload();await expect(page.getByText('Mục này chưa được nhà trường chia sẻ qua link của bạn',{exact:true})).toBeVisible();expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBe(JSON.stringify({slug,viewId}));state.mode='invalid';await page.reload();await expect(page).toHaveURL(/access-unavailable\?reason=invalid$/);expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBeNull();
});
