import {expect,test,type Page,type Route} from '@playwright/test';
const slug='parent-duty-browser',viewId='69000000-0000-4000-8000-000000000001',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-parent-duties';
const context=()=>({viewId,school:{name:'Trường trực nhật API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con trực nhật API',classLabel:'6A',schoolYearLabel:'2026–2027'},allowedSections:['duties'],allowDownload:false,csrfToken:'synthetic-duty-browser-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const schedule=()=>({today:'2026-10-05',year:{startsOn:'2026-09-01',endsOn:'2027-06-01'},items:[{date:'2026-10-04',task:'Nhiệm vụ đã qua vẫn được giao',status:'ASSIGNED',publishedAt:'2026-10-01T01:00:00Z'},{date:'2026-10-05',task:'Nhiệm vụ hôm nay hoàn thành',status:'DONE',publishedAt:'2026-10-01T01:00:00Z'},{date:'2026-10-06',task:'Nhiệm vụ ngày mai đã hủy',status:'CANCELLED',publishedAt:'2026-10-01T01:00:00Z'},{date:'2026-10-06',task:'Nhiệm vụ thứ hai cùng ngày',status:'ASSIGNED',publishedAt:'2026-10-01T01:00:00Z'}]});
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'parent-duty-controlled-browser'}});
type State={mode:'ready'|'bad'|'empty'|'invalid'|'denied';calls:number};
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const request=route.request(),path=new URL(request.url()).pathname;
 if(path==='/api/v1/me/context')return route.fulfill({status:401,json:{code:'UNAUTHENTICATED',requestId:'duty-browser-anonymous'}});
 if(path==='/api/v1/auth/csrf')return reply(route,{csrfToken:'duty-browser-bootstrap'});
 if(path===`/api/v1/parent/${slug}/access/exchange`||path===`/api/v1/parent/${slug}/context`)return reply(route,context());
 if(path===`/api/v1/public/schools/${slug}`)return reply(route,{name:'Trường trực nhật API',slug,announcements:[]});
 if(path===`/api/v1/parent/${slug}/duty-schedule`){state.calls++;expect(request.headers()['x-parent-view']).toBe(viewId);if(state.mode==='invalid'||state.mode==='denied')return route.fulfill({status:state.mode==='invalid'?401:403,json:{code:state.mode==='invalid'?'PARENT_ACCESS_INVALID':'PARENT_SECTION_DENIED',requestId:'duty-browser-denied'}});const data=schedule();if(state.mode==='bad')data.items[0].date='2027-02-30';if(state.mode==='empty')data.items=[];return reply(route,data);}
 return route.fulfill({status:503,json:{code:'UNEXPECTED_DUTY_OPERATION',requestId:'duty-browser-unexpected'}});
});}
async function open(page:Page){await page.goto(`/p/${slug}/access#token=${'F'.repeat(43)}`);await expect(page).toHaveURL(new RegExp(`/p/${slug}/duties$`));}
const ready=():State=>({mode:'ready',calls:0});
test('Parent duty cards preserve actual publication status and school date without assuming completed past tasks',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await expect(page.getByText('3 nhiệm vụ',{exact:true})).toBeVisible();await expect(page.getByText('1 nhiệm vụ',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Nhiệm vụ trực nhật của con',exact:true})).toBeVisible();await expect(page.locator('li').filter({hasText:'Nhiệm vụ đã qua vẫn được giao'}).getByText('Đã qua',{exact:true})).toBeVisible();await expect(page.locator('li').filter({hasText:'Nhiệm vụ hôm nay hoàn thành'}).getByText('Hoàn thành',{exact:true})).toBeVisible();await expect(page.locator('li').filter({hasText:'Nhiệm vụ ngày mai đã hủy'}).getByText('Đã hủy',{exact:true})).toBeVisible();expect(await page.evaluate(()=>({...sessionStorage}))).toEqual({'edu-parent-view':JSON.stringify({slug,viewId})});await page.screenshot({path:`qa/backend/${prefix}-parent-duties-desktop.png`,fullPage:true});
});
test('Parent duty mobile retains readable upcoming/past cards and refreshes withdrawn publications to truthful empty states',async({page})=>{
 const state=ready();await routes(page,state);await page.setViewportSize({width:390,height:844});await open(page);await expect(page.getByText('Nhiệm vụ hôm nay hoàn thành',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`qa/backend/${prefix}-parent-duties-mobile.png`,fullPage:true});state.mode='empty';await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));await expect(page.getByText('Chưa có lịch trực nhật sắp tới',{exact:true})).toBeVisible();await expect(page.getByText('Chưa có buổi trực nhật đã qua',{exact:true})).toBeVisible();await expect(page.getByText('Nhiệm vụ hôm nay hoàn thành',{exact:true})).toHaveCount(0);
});
test('Parent malformed duties stay hidden until retry; section denial keeps ownership and terminal revocation clears it',async({page})=>{
 const state=ready();state.mode='bad';await routes(page,state);await open(page);await expect(page.getByText('API chưa xác nhận đầy đủ lịch trực nhật của con.',{exact:true})).toBeVisible();await expect(page.getByText('Nhiệm vụ hôm nay hoàn thành',{exact:true})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Nhiệm vụ hôm nay hoàn thành',{exact:true})).toBeVisible();state.mode='denied';await page.reload();await expect(page.getByText('Mục này chưa được nhà trường chia sẻ qua link của bạn',{exact:true})).toBeVisible();expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBe(JSON.stringify({slug,viewId}));state.mode='invalid';await page.reload();await expect(page).toHaveURL(/access-unavailable\?reason=invalid$/);expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBeNull();
});
