import {expect,test,type Page,type Route} from '@playwright/test';
const slug='parent-document-browser',viewId='6c000000-0000-4000-8000-000000000001',ids=['6c000000-0000-4000-8000-000000000002','6c000000-0000-4000-8000-000000000003','6c000000-0000-4000-8000-000000000004'],prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-parent-documents';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jVZkAAAAASUVORK5CYII=','base64');
const context=()=>({viewId,school:{name:'Trường tài liệu API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con tài liệu API',classLabel:'6A',schoolYearLabel:'2026–2027'},allowedSections:['documents','conduct'],allowDownload:true,csrfToken:'document-browser-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const directory=()=>({files:[{id:ids[0],title:'Tài liệu chỉ được xem',contentType:'image/png',byteSize:png.length,downloadAllowed:false,viewAllowed:true,publishedAt:'2026-10-01T01:00:00Z'},{id:ids[1],title:'Tài liệu được tải',contentType:'image/png',byteSize:png.length,downloadAllowed:true,viewAllowed:true,publishedAt:'2026-10-01T01:00:00Z'},{id:ids[2],title:'Tệp không xem trước',contentType:'text/csv',byteSize:3,downloadAllowed:true,viewAllowed:false,publishedAt:'2026-10-01T01:00:00Z'}],reports:[{periodId:ids[2],title:'Kết quả thi đua Tuần 5',publishedAt:'2026-10-01T01:00:00Z',total:'80.10',grade:null,revision:1}]});
type State={mode:'ready'|'bad'|'empty'|'revoked'|'invalid';views:number;downloads:number};
const ready=():State=>({mode:'ready',views:0,downloads:0});
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'document-controlled-browser'}});
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const req=route.request(),path=new URL(req.url()).pathname;
 if(path==='/api/v1/me/context')return route.fulfill({status:401,json:{code:'UNAUTHENTICATED',requestId:'document-anonymous'}});
 if(path==='/api/v1/auth/csrf')return reply(route,{csrfToken:'document-bootstrap'});
 if(path===`/api/v1/public/schools/${slug}`)return reply(route,{name:'Trường tài liệu API',slug,announcements:[]});
 if(path===`/api/v1/parent/${slug}/access/exchange`||path===`/api/v1/parent/${slug}/context`)return reply(route,context());
 expect(req.headers()['x-parent-view']).toBe(viewId);
 if(state.mode==='invalid')return route.fulfill({status:401,json:{code:'PARENT_ACCESS_INVALID',requestId:'document-invalid'}});
 if(path.endsWith('/document-directory')){const data=directory();if(state.mode==='empty')return reply(route,{files:[],reports:[]});if(state.mode==='bad')Object.assign(data.files[0],{objectKey:'private/not-exposed'});return reply(route,data);}
 const match=/\/documents\/([^/]+)(?:\/(view|download))?$/.exec(path);if(match){
  const file=directory().files.find(file=>file.id===match[1]);if(!file||state.mode==='revoked')return route.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND',requestId:'document-revoked'}});
  if(!match[2])return reply(route,file);
  if(match[2]==='download'){state.downloads++;expect(file.downloadAllowed).toBe(true);}else{state.views++;expect(file.viewAllowed).toBe(true);}
  return route.fulfill({status:200,contentType:match[2]==='download'?file.contentType+'; charset=utf-8':file.contentType,headers:{'Cache-Control':'no-store','Content-Disposition':"attachment;filename*=UTF-8''tai-lieu-thuc.png"},body:png});
 }
 return route.fulfill({status:503,json:{code:'UNEXPECTED_DOCUMENT_OPERATION',requestId:'document-unexpected'}});
});}
async function open(page:Page){await page.goto(`/p/${slug}/access#token=${'G'.repeat(43)}`);await expect(page).toHaveURL(new RegExp(`/p/${slug}/documents$`));}
test('Parent documents show real capabilities and reports, view only uses private bytes and permitted download makes a new API call',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await expect(page.getByRole('heading',{name:'Tài liệu và báo cáo được chia sẻ',exact:true})).toBeVisible();await expect(page.getByText('Kết quả thi đua Tuần 5',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Tải Tài liệu chỉ được xem',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Xem: Tệp không xem trước',exact:true})).toHaveCount(0);await expect(page.getByText('Dữ liệu trong bản demo là dữ liệu giả.',{exact:false})).toHaveCount(0);await page.screenshot({path:`qa/backend/${prefix}-parent-documents-desktop.png`,fullPage:true});
 await page.getByRole('button',{name:'Xem: Tài liệu chỉ được xem',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('img',{name:'Xem trước: Tài liệu chỉ được xem',exact:true})).toBeVisible();await expect.poll(()=>dialog.locator('img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBe(1);await expect(dialog.getByRole('button',{name:'Tải xuống',exact:true})).toHaveCount(0);expect(state.views).toBe(1);expect(state.downloads).toBe(0);await page.screenshot({path:`qa/backend/${prefix}-parent-document-view.png`,fullPage:true});await dialog.getByRole('button',{name:'Đóng',exact:true}).last().click();
 const received=page.waitForEvent('download');await page.getByRole('button',{name:'Tải Tài liệu được tải',exact:true}).click();expect((await received).suggestedFilename()).toBe('tai-lieu-thuc.png');expect(state.downloads).toBe(1);expect(await page.evaluate(()=>({...sessionStorage}))).toEqual({'edu-parent-view':JSON.stringify({slug,viewId})});
});
test('Parent document mobile keeps the existing card layout and focus removes a revoked preview instead of retaining bytes',async({page})=>{
 const state=ready();await routes(page,state);await page.setViewportSize({width:390,height:844});await open(page);await expect(page.getByText('Tài liệu chỉ được xem',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`qa/backend/${prefix}-parent-documents-mobile.png`,fullPage:true});await page.getByRole('button',{name:'Xem: Tài liệu chỉ được xem',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.locator('img')).toBeVisible();state.mode='revoked';await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));await expect(dialog.getByText('Tệp đã bị thu hồi',{exact:true})).toBeVisible();await expect(dialog.locator('img')).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Tải xuống',exact:true})).toHaveCount(0);expect(state.downloads).toBe(0);
});
test('Parent document malformed/private metadata stays hidden; withdrawal becomes empty and terminal revocation clears the view',async({page})=>{
 const state=ready();state.mode='bad';await routes(page,state);await open(page);await expect(page.getByText('API chưa xác nhận đầy đủ tài liệu được chia sẻ cho con.',{exact:true})).toBeVisible();await expect(page.getByText('Tài liệu chỉ được xem',{exact:true})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Tài liệu chỉ được xem',{exact:true})).toBeVisible();state.mode='empty';await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));await expect(page.getByText('Chưa có tệp được chia sẻ',{exact:true})).toBeVisible();await expect(page.getByText('Chưa có báo cáo công bố',{exact:true})).toBeVisible();state.mode='invalid';await page.reload();await expect(page).toHaveURL(/access-unavailable\?reason=invalid$/);expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBeNull();
});
