import {expect,test,type Page,type Route} from '@playwright/test';
const slug='parent-conduct-browser',viewId='6f000000-0000-4000-8000-000000000001',periodId='6f000000-0000-4000-8000-000000000002',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-parent-conduct';
const context=()=>({viewId,school:{name:'Trường thi đua API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con thi đua API',classLabel:'Lớp hiện tại khác công bố',schoolYearLabel:'2026–2027'},allowedSections:['conduct'],allowDownload:false,csrfToken:'conduct-browser-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const conduct=()=>({periodId,periodLabel:'Tuần nguồn 5',revision:2,basePoints:'80.10',bonusPoints:'0.20',penaltyPoints:'-1.25',finalPoints:'79.05',classification:'Xếp loại nguồn' as string|null,lines:[{label:'Ghi nhận được chia sẻ',delta:'-1.25',occurredAt:'2026-09-29T17:30:00Z',reason:'Lý do công khai của con',date:'2026-09-30'}],publishedAt:'2026-10-01T01:00:00Z',adjusted:true,weekNumber:5 as number|null,startsOn:'2026-09-28' as string|null,endsOn:'2026-10-05' as string|null,classLabel:'6A lúc công bố' as string|null,ruleSetName:'Quy chế lúc công bố' as string|null,ruleSetRevision:3 as number|null,minimumPoints:'0.00' as string|null,maximumPoints:'100.00' as string|null,timezone:'Asia/Ho_Chi_Minh',history:[{revision:1,publishedAt:'2026-09-30T01:00:00Z',total:'80.30',classification:'Xếp loại nguồn' as string|null,current:false},{revision:2,publishedAt:'2026-10-01T01:00:00Z',total:'79.05',classification:'Xếp loại nguồn' as string|null,current:true}]});
type State={mode:'ready'|'capped'|'null'|'bad'|'withdrawn'|'invalid'|'denied';calls:number};
const ready=():State=>({mode:'ready',calls:0}),reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'conduct-controlled-browser'}});
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const req=route.request(),path=new URL(req.url()).pathname;
 if(path==='/api/v1/me/context')return route.fulfill({status:401,json:{code:'UNAUTHENTICATED',requestId:'conduct-anonymous'}});
 if(path==='/api/v1/auth/csrf')return reply(route,{csrfToken:'conduct-bootstrap'});
 if(path===`/api/v1/public/schools/${slug}`)return reply(route,{name:'Trường thi đua API',slug,announcements:[]});
 if(path.endsWith('/access/exchange'))return reply(route,context());
 expect(req.headers()['x-parent-view']).toBe(viewId);
 if(state.mode==='invalid')return route.fulfill({status:401,json:{code:'PARENT_ACCESS_INVALID',requestId:'conduct-invalid'}});
 if(path.endsWith('/context'))return reply(route,context());
 if(path===`/api/v1/parent/${slug}/conduct/published`||path===`/api/v1/parent/${slug}/conduct/${periodId}/published`){
  state.calls++;if(state.mode==='denied')return route.fulfill({status:403,json:{code:'PARENT_SECTION_DENIED',requestId:'conduct-denied'}});
  const list=path.endsWith('/conduct/published');if(state.mode==='withdrawn')return list?reply(route,{items:[]}):route.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND',requestId:'conduct-withdrawn'}});
  const data=conduct();if(state.mode==='capped'){data.bonusPoints='30.00';data.penaltyPoints='0.00';data.finalPoints='100.00';data.history[1].total='100.00';}if(state.mode==='bad')data.history[1].total='0.00';if(state.mode==='null'){data.weekNumber=null;data.startsOn=null;data.endsOn=null;data.classLabel=null;data.ruleSetName=null;data.ruleSetRevision=null;data.minimumPoints=null;data.maximumPoints=null;data.classification=null;data.history[1].classification=null;}
  return reply(route,list?{items:[data]}:data);
 }
 return route.fulfill({status:503,json:{code:'UNEXPECTED_CONDUCT_OPERATION',requestId:'conduct-unexpected'}});
});}
async function open(page:Page){await page.goto(`/p/${slug}/access#token=${'I'.repeat(43)}`);await expect(page).toHaveURL(new RegExp(`/p/${slug}/conduct$`));}
async function detail(page:Page){await page.getByRole('link',{name:/Tuần nguồn 5/}).click();await expect(page).toHaveURL(new RegExp(`/conduct/${periodId}$`));await expect(page.getByRole('heading',{name:'Kết quả thi đua · Tuần nguồn 5',exact:true})).toBeVisible();}

test('Parent conduct list, detail and print use official decimals, pinned class and rule, local line date and own actual revision history',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await expect(page.getByText('28/09/2026 – 04/10/2026',{exact:true})).toBeVisible();await page.screenshot({path:`qa/backend/${prefix}-parent-conduct-desktop.png`,fullPage:true});await detail(page);await expect(page.getByText('Quy chế: Quy chế lúc công bố (phiên bản 3)',{exact:true})).toBeVisible();await expect(page.locator('tfoot')).toContainText('79.05');await expect(page.getByRole('row').filter({hasText:'Tổng cộng điểm đã chốt'})).toContainText('0.20');await expect(page.getByRole('row').filter({hasText:'Tổng trừ điểm đã chốt'})).toContainText('-1.25');await expect(page.getByText('Các dòng trên là ghi nhận được nhà trường chia sẻ.',{exact:false})).toContainText('Điểm tối đa: 100.00.');await expect(page.locator('tbody')).toContainText('80.10');await expect(page.locator('tbody')).toContainText('30/09/2026');await expect(page.getByText('Lý do công khai của con',{exact:true})).toBeVisible();await expect(page.getByText('Bản 1: 80.30 → Bản 2: 79.05',{exact:true})).toBeVisible();await expect(page.getByText('Hiện hành',{exact:true})).toBeVisible();await expect(page.locator('.page-subtitle')).toContainText('6A lúc công bố');await expect(page.locator('.page-subtitle')).not.toContainText('Lớp hiện tại khác công bố');await page.screenshot({path:`qa/backend/${prefix}-parent-conduct-detail.png`,fullPage:true});await page.evaluate(()=>{window.print=()=>{document.documentElement.dataset.conductPrint='requested';};});await page.getByRole('button',{name:'In / lưu PDF',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-conduct-print','requested');await page.emulateMedia({media:'print'});await expect(page.locator('.print-only')).toContainText('Con thi đua API');await expect(page.locator('.print-only')).toContainText('6A lúc công bố');await page.screenshot({path:`qa/backend/${prefix}-parent-conduct-print.png`,fullPage:true});expect(await page.evaluate(()=>({...sessionStorage}))).toEqual({'edu-parent-view':JSON.stringify({slug,viewId})});await page.emulateMedia({media:'screen'});state.mode='capped';await page.reload();await expect(page.getByRole('row').filter({hasText:'Tổng cộng điểm đã chốt'})).toContainText('30.00');await expect(page.getByRole('row').filter({hasText:'Tổng điểm chính thức đã công bố'})).toContainText('100.00');
});
test('Parent conduct mobile retains actual decimals without overflow and historical missing labels stay absent',async({page})=>{
 const state=ready();await routes(page,state);await page.setViewportSize({width:390,height:844});await open(page);await detail(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`qa/backend/${prefix}-parent-conduct-mobile.png`,fullPage:true});state.mode='null';await page.reload();await expect(page.locator('tfoot')).toContainText('79.05');await expect(page.getByText('Quy chế: Quy chế lúc công bố (phiên bản 3)',{exact:true})).toHaveCount(0);await expect(page.locator('.page-subtitle')).toHaveCount(0);await expect(page.getByText('Xếp loại nguồn',{exact:true})).toHaveCount(0);
});
test('Parent conduct inconsistent history remains an error; withdrawal hides the score and terminal revocation clears the private view',async({page})=>{
 const state=ready();state.mode='bad';await routes(page,state);await open(page);await expect(page.getByText('API chưa xác nhận đầy đủ kết quả thi đua đã công bố cho con.',{exact:true})).toBeVisible();await expect(page.getByText('Tuần nguồn 5',{exact:true})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await detail(page);state.mode='withdrawn';await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));await expect(page.getByText('Không tìm thấy nội dung',{exact:true})).toBeVisible();await expect(page.locator('tfoot')).toHaveCount(0);await page.goto(`/p/${slug}/conduct`);await expect(page.getByText('Chưa có kết quả công bố',{exact:true})).toBeVisible();state.mode='denied';await page.reload();await expect(page.getByText('Mục này chưa được nhà trường chia sẻ qua link của bạn',{exact:true})).toBeVisible();expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBe(JSON.stringify({slug,viewId}));state.mode='invalid';await page.reload();await expect(page).toHaveURL(/access-unavailable\?reason=invalid$/);expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBeNull();
});
