import {expect,test,type Page,type Route} from '@playwright/test';
const slug='parent-week-browser',viewId='6b000000-0000-4000-8000-000000000001',baseWeek='2026-10-05',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-parent-week';
const dateDays=(date:string,days:number)=>{const value=new Date(date+'T00:00:00Z');value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);};
const context=()=>({viewId,school:{name:'Trường lịch API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con lịch API',classLabel:'6A',schoolYearLabel:'2026–2027'},allowedSections:['timetable'],allowDownload:false,csrfToken:'synthetic-week-browser-csrf',expiresAt:'2026-10-05T08:00:00Z',today:baseWeek,year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const lesson=(date:string,periodNumber:number,subjectName:string,status:string,changeNote:string|null)=>({date,startsAt:date+'T01:00:00Z',endsAt:date+'T01:45:00Z',startsAtLocal:'08:00',endsAtLocal:'08:45',periodNumber,subjectName,teacherName:'Giáo viên công tác API',roomName:null,status,changeNote});
const timetable=(week:string)=>({weekStart:week,today:baseWeek,timezone:'Asia/Ho_Chi_Minh',year:{startsOn:'2026-09-01',endsOn:'2027-06-01'},weekNumber:week===baseWeek?6:null,days:Array.from({length:7},(_,i)=>({date:dateDays(week,i),holidayNames:week===baseWeek&&i===6?['Ngày nghỉ Chủ nhật API']:[],lessons:week!==baseWeek?[]:i===0?[lesson(week,3,'Toán đã công bố','SCHEDULED',null)]:i===2?[lesson(dateDays(week,i),2,'Tiết hủy đã công bố','CANCELLED','Đổi lịch kiểm soát')]:i===6?[lesson(dateDays(week,i),5,'Tiết Chủ nhật đã công bố','SCHEDULED',null)]:[]}))});
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'parent-week-controlled-browser'}});
type State={mode:'ready'|'bad'|'empty'|'invalid'|'denied';weeks:string[]};
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const request=route.request(),url=new URL(request.url()),path=url.pathname;
 if(path==='/api/v1/me/context')return route.fulfill({status:401,json:{code:'UNAUTHENTICATED',requestId:'week-browser-anonymous'}});
 if(path==='/api/v1/auth/csrf')return reply(route,{csrfToken:'week-browser-bootstrap'});
 if(path===`/api/v1/parent/${slug}/access/exchange`||path===`/api/v1/parent/${slug}/context`)return reply(route,context());
 if(path===`/api/v1/public/schools/${slug}`)return reply(route,{name:'Trường lịch API',slug,announcements:[]});
 if(path===`/api/v1/parent/${slug}/timetable-week`){const week=url.searchParams.get('week')!;state.weeks.push(week);expect(request.headers()['x-parent-view']).toBe(viewId);if(state.mode==='invalid'||state.mode==='denied')return route.fulfill({status:state.mode==='invalid'?401:403,json:{code:state.mode==='invalid'?'PARENT_ACCESS_INVALID':'PARENT_SECTION_DENIED',requestId:'week-browser-denied'}});const data=timetable(week);if(state.mode==='bad')data.days[0].lessons[0].startsAtLocal='09:00';if(state.mode==='empty')for(const day of data.days)day.lessons=[];return reply(route,data);}
 return route.fulfill({status:503,json:{code:'UNEXPECTED_WEEK_OPERATION',requestId:'week-browser-unexpected'}});
});}
async function open(page:Page){await page.goto(`/p/${slug}/access#token=${'G'.repeat(43)}`);await expect(page).toHaveURL(new RegExp(`/p/${slug}/timetable$`));}
const ready=():State=>({mode:'ready',weeks:[]});
test('Parent weekly timetable keeps school clock, pinned periods/cancellation and all Sunday facts while navigation reads the selected week',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await expect(page.getByRole('heading',{name:'Lịch học của con',exact:true})).toBeVisible();await expect(page.getByText('Tiết 3',{exact:true})).toBeVisible();await expect(page.getByText('Hôm nay',{exact:true})).toBeVisible();await expect(page.getByText('08:00 – 08:45 · Giáo viên công tác API',{exact:true})).toHaveCount(3);await expect(page.getByText('Nghỉ: Ngày nghỉ Chủ nhật API',{exact:true})).toBeVisible();await expect(page.getByText('Tiết Chủ nhật đã công bố',{exact:true})).toBeVisible();await expect(page.locator('section').filter({hasText:'Tiết hủy đã công bố'}).getByText('Tiết nghỉ: Đổi lịch kiểm soát',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.body.innerText)).not.toContain('undefined');await page.screenshot({path:`qa/backend/${prefix}-parent-timetable-desktop.png`,fullPage:true});
 await page.getByRole('button',{name:'Tuần sau',exact:true}).click();await expect(page.getByText('Chưa có tiết học được công bố.',{exact:true})).toHaveCount(7);expect(state.weeks).toContain('2026-10-12');await expect(page.getByText('Toán đã công bố',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Tuần này',exact:true}).click();await expect(page.getByText('Toán đã công bố',{exact:true})).toBeVisible();expect(state.weeks[0]).toBe(baseWeek);
});
test('Parent timetable mobile retains all day cards without overflow and removes withdrawn lessons on current focus revalidation',async({page})=>{
 const state=ready();await routes(page,state);await page.setViewportSize({width:390,height:844});await open(page);await expect(page.getByText('Tiết Chủ nhật đã công bố',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:`qa/backend/${prefix}-parent-timetable-mobile.png`,fullPage:true});state.mode='empty';await page.evaluate(()=>window.dispatchEvent(new Event('visibilitychange')));await expect(page.getByText('Chưa có tiết học được công bố.',{exact:true})).toHaveCount(7);await expect(page.getByText('Toán đã công bố',{exact:true})).toHaveCount(0);await expect(page.getByText('Nghỉ: Ngày nghỉ Chủ nhật API',{exact:true})).toBeVisible();
});
test('Parent malformed clock labels stay hidden until retry; denied module keeps the view and terminal revoke clears it',async({page})=>{
 const state=ready();state.mode='bad';await routes(page,state);await open(page);await expect(page.getByText('API chưa xác nhận đầy đủ thời khóa biểu của con.',{exact:true})).toBeVisible();await expect(page.getByText('Toán đã công bố',{exact:true})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Toán đã công bố',{exact:true})).toBeVisible();state.mode='denied';await page.reload();await expect(page.getByText('Mục này chưa được nhà trường chia sẻ qua link của bạn',{exact:true})).toBeVisible();expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBe(JSON.stringify({slug,viewId}));state.mode='invalid';await page.reload();await expect(page).toHaveURL(/access-unavailable\?reason=invalid$/);expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBeNull();
});
