import {expect,test,type Page,type Route} from '@playwright/test';
const slug='parent-month-browser',viewId='65000000-0000-4000-8000-000000000001',token='C'.repeat(43),prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-parent-attendance';
const context=()=>({viewId,school:{name:'Trường chuyên cần API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con chuyên cần API',classLabel:'6A',schoolYearLabel:'2026–2027'},allowedSections:['attendance'],allowDownload:false,csrfToken:'synthetic-month-browser-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const month=(selected:string)=>{const first=selected+'-01',next=new Date(first+'T00:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);const count=(next.getTime()-Date.parse(first))/86400000,marked=selected==='2026-10';return {granularity:'DAILY',month:selected,yearStart:'2026-09',yearEnd:'2027-05',today:'2026-10-05',totals:{present:marked?1:0,late:marked?1:0,excused:0,unexcused:0,unmarked:marked?1:0,published:marked?3:0,marked:marked?2:0},days:Array.from({length:count},(_,i)=>{const date=`${selected}-${String(i+1).padStart(2,'0')}`,sessions=marked&&i===1?[{date,slotLabel:'Sáng',status:'PRESENT',publicNote:'Buổi sáng đã công bố',publishedAt:'2026-10-03T00:00:00Z'},{date,slotLabel:'Chiều',status:'LATE',publishedAt:'2026-10-03T00:00:00Z'}]:marked&&i===2?[{date,slotLabel:'Sáng',status:'UNMARKED',publishedAt:'2026-10-03T00:00:00Z'}]:[];return {date,weekday:(new Date(date+'T00:00:00Z').getUTCDay()+6)%7+1,holidayNames:marked&&i===0?['Ngày nghỉ được công bố']:[],sessions,status:sessions.length?i===1?'mixed':'unmarked':date>'2026-10-05'?'future':marked&&i===0?'holiday':'not_published'};})};};
const reply=(r:Route,data:unknown)=>r.fulfill({status:200,json:{data,requestId:'parent-month-browser-controlled'}});
type State={mode:'ready'|'malformed'|'denied'|'invalid'|'lesson';monthlyCalls:number};
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const req=route.request(),url=new URL(req.url()),path=url.pathname;
 if(path==='/api/v1/me/context')return route.fulfill({status:401,json:{code:'UNAUTHENTICATED',requestId:'anonymous-month-browser'}});
 if(path==='/api/v1/auth/csrf')return reply(route,{csrfToken:'month-bootstrap'});
 if(path===`/api/v1/parent/${slug}/access/exchange`||path===`/api/v1/parent/${slug}/context`)return reply(route,context());
 if(path===`/api/v1/public/schools/${slug}`)return reply(route,{name:'Trường chuyên cần API',slug,announcements:[]});
 if(path===`/api/v1/parent/${slug}/attendance-month`){state.monthlyCalls++;expect(req.headers()['x-parent-view']).toBe(viewId);if(state.mode==='denied'||state.mode==='invalid')return route.fulfill({status:state.mode==='denied'?403:401,json:{code:state.mode==='denied'?'PARENT_SECTION_DENIED':'PARENT_ACCESS_INVALID',requestId:'month-denial'}});const data=month(url.searchParams.get('month')!);if(state.mode==='malformed')data.totals.marked=999;if(state.mode==='lesson')data.granularity='LESSON';return reply(route,data);}
 return route.fulfill({status:503,json:{code:'UNEXPECTED_MONTH_OPERATION',requestId:'unexpected-month'}});
});}
async function open(page:Page){await page.goto(`/p/${slug}/access#token=${token}`);await expect(page).toHaveURL(new RegExp(`/p/${slug}/attendance$`));}
const ready=():State=>({mode:'ready',monthlyCalls:0});
test('Parent actual month keeps both sessions, excludes unmarked from the ratio and does not turn Sunday into a holiday',async({page})=>{
 const state=ready();await routes(page,state);await open(page);await expect(page.getByText('Con có mặt 2/2 buổi đã được đánh dấu và công bố (tính cả đi muộn).',{exact:true})).toBeVisible();await expect(page.getByText('Sáng: Có mặt · Buổi sáng đã công bố',{exact:true})).toBeVisible();await expect(page.getByText('Chiều: Đi muộn',{exact:true})).toBeVisible();await expect(page.getByText('1 buổi đã công bố nhưng chưa đánh dấu; không tính là có mặt, vắng hay đưa vào tỷ lệ.',{exact:true})).toBeVisible();const sunday=page.getByRole('group',{name:'Lịch chuyên cần tháng 10/2026'}).getByText('4',{exact:true}).locator('..');await expect(sunday).toHaveAttribute('title',/Chưa công bố/);await expect(page.getByRole('button',{name:'Tháng sau',exact:true})).toBeDisabled();await page.screenshot({path:`qa/backend/${prefix}-parent-attendance-desktop.png`,fullPage:true});
});
test('Parent month handles explicit previous-month emptiness and a mobile calendar without persisting private rows',async({page})=>{
 const state=ready();await routes(page,state);await page.setViewportSize({width:390,height:844});await open(page);await expect(page.getByText('Con có mặt 2/2 buổi đã được đánh dấu và công bố (tính cả đi muộn).',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);expect(await page.evaluate(()=>({...sessionStorage}))).toEqual({'edu-parent-view':JSON.stringify({slug,viewId})});await page.screenshot({path:`qa/backend/${prefix}-parent-attendance-mobile.png`,fullPage:true});await page.getByRole('button',{name:'Tháng trước',exact:true}).click();await expect(page.getByText('Tháng này chưa có buổi điểm danh nào được công bố.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Tháng trước',exact:true})).toBeDisabled();await expect(page.getByText('Buổi sáng đã công bố',{exact:false})).toHaveCount(0);
});
test('Parent forged aggregate receipt stays hidden until an explicit retry returns verified actual counts',async({page})=>{
 const state=ready();state.mode='malformed';await routes(page,state);await open(page);await expect(page.getByText('API chưa xác nhận đầy đủ tháng chuyên cần của con.',{exact:true})).toBeVisible();await expect(page.getByText('Buổi sáng đã công bố',{exact:false})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Con có mặt 2/2 buổi đã được đánh dấu và công bố (tính cả đi muộn).',{exact:true})).toBeVisible();expect(state.monthlyCalls).toBe(2);
});
test('Parent section denial keeps its view, while invalid session removes all private month display',async({page})=>{
 const state=ready();state.mode='denied';await routes(page,state);await open(page);await expect(page.getByText('Mục này chưa được nhà trường chia sẻ qua link của bạn',{exact:true})).toBeVisible();expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBe(JSON.stringify({slug,viewId}));state.mode='invalid';await page.reload();await expect(page).toHaveURL(/\/access-unavailable\?reason=invalid$/);await expect(page.getByRole('heading',{name:'Đường dẫn không sử dụng được'})).toBeVisible();await expect(page.getByText('Buổi sáng đã công bố',{exact:false})).toHaveCount(0);expect(await page.evaluate(()=>sessionStorage.getItem('edu-parent-view'))).toBeNull();
});

test('Parent monthly attendance refuses a lesson-granularity receipt instead of mixing its denominator with daily attendance',async({page})=>{
 const state=ready();state.mode='lesson';await routes(page,state);await open(page);await expect(page.getByText('API chưa xác nhận đầy đủ tháng chuyên cần của con.',{exact:true})).toBeVisible();await expect(page.getByText('Buổi sáng đã công bố',{exact:false})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Con có mặt 2/2 buổi đã được đánh dấu và công bố (tính cả đi muộn).',{exact:true})).toBeVisible();expect(state.monthlyCalls).toBe(2);
});
