import {test,expect,type Page,type Route} from '@playwright/test';
const id=(n:number)=>`6f000000-0000-4000-8000-${String(n).padStart(12,'0')}`,slug='truong-cong-khai-api',at='2026-10-02T01:00:00Z',root=`/api/v1/public/schools/${slug}`,web=`/schools/${slug}`,prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-public-announcements';
type State={mode:'ready'|'outage'|'suspended'|'withdrawn';downloads:string[];unexpected:string[]};
const state=():State=>({mode:'ready',downloads:[],unexpected:[]});
const school=(s:State)=>({name:'Trường công khai từ API',shortName:'Trường API',slug,address:'12 Đường kiểm thử',publicPhone:'0900000101',publicEmail:'official@example.invalid',website:'https://school.example.invalid',motto:'Học tập an toàn',publicIntro:'Giới thiệu chính thức từ máy chủ',accentColor:'#2876bc',status:s.mode==='suspended'?'suspended':'active',level:'Trung học'});
const news={id:id(1),title:'Tin đã công bố từ API',summary:'Tóm tắt công khai đã xác nhận',publishedAt:at};
const reply=(r:Route,data:unknown)=>r.fulfill({status:200,json:{data,requestId:'public-announcements-browser'}});
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async r=>{const path=new URL(r.request().url()).pathname;
 if(path==='/api/v1/me/context')return r.fulfill({status:401,json:{code:'AUTHENTICATION_REQUIRED'}});
 if(path===root+'/workspace'){if(s.mode==='outage')return r.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE'}});return r.fulfill({status:200,json:{data:{school:school(s),news:s.mode==='suspended'?[]:[news]},page:{total:s.mode==='suspended'?0:1,limit:100,hasMore:false,nextCursor:null},requestId:'public-school-workspace'}});}
 if(path===root+`/announcements/${id(1)}/workspace`){if(s.mode==='withdrawn')return r.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND'}});return reply(r,{school:{name:school(s).name,slug},news:{...news,body:[{type:'h',text:'Nội dung công bố'},{type:'p',text:'Nội dung tiếng Việt giữ nguyên thiết kế'},{type:'li',text:'Chỉ tin công khai'}],source:{rootId:id(1),publicationId:id(2)},attachments:[{id:id(3),name:'Tài liệu công khai.pdf',mime:'application/pdf',size:3}]}});}
 if(path===root+`/announcements/${id(1)}/revisions/${id(2)}/files/${id(3)}`){s.downloads.push(path);if(s.mode==='withdrawn')return r.fulfill({status:404,json:{code:'RESOURCE_NOT_FOUND'}});return r.fulfill({status:200,headers:{'content-type':'application/pdf','content-disposition':"attachment; filename*=UTF-8''Tai-lieu.pdf",'cache-control':'no-store'},body:'PDF'});}
 s.unexpected.push(path);return r.fulfill({status:503,json:{code:'UNEXPECTED_PUBLIC_REQUEST'}});
 });}
test('SY01 and SY02 keep the public design official contact and actual publication-bound download without accounts',async({page})=>{const s=state();await routes(page,s);await page.goto(web);await expect(page.getByRole('heading',{name:'Trường công khai từ API',exact:true})).toBeVisible();await expect(page.getByText('12 Đường kiểm thử',{exact:true})).toBeVisible();await expect(page.getByText('Không cần tài khoản, không đăng nhập.',{exact:true})).toBeVisible();await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});await page.getByRole('link',{name:/Tin đã công bố từ API/}).click();await expect(page.getByRole('heading',{name:news.title,exact:true})).toBeVisible();await expect(page.getByText('Nội dung tiếng Việt giữ nguyên thiết kế',{exact:true})).toBeVisible();const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Tải về',exact:true}).click()]);expect(download.suggestedFilename()).toBe('Tài liệu công khai.pdf');expect(s.downloads).toEqual([root+`/announcements/${id(1)}/revisions/${id(2)}/files/${id(3)}`]);expect(s.unexpected).toEqual([]);});
test('SY01 mobile suspended school keeps contact and hides news without a login or pupil lookup',async({page})=>{await page.setViewportSize({width:390,height:844});const s=state();s.mode='suspended';await routes(page,s);await page.goto(web);await expect(page.getByText('Trường đang tạm dừng trên EduManage',{exact:true})).toBeVisible();await expect(page.getByText('official@example.invalid',{exact:true})).toBeVisible();await expect(page.getByText(news.title,{exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('SY01 outage has a visible retry and never substitutes an empty news directory',async({page})=>{const s=state();s.mode='outage';await routes(page,s);await page.goto(web);await expect(page.getByText('Chưa có tin công khai',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Thử lại',exact:true})).toBeVisible();s.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByRole('link',{name:/Tin đã công bố từ API/})).toBeVisible();expect(s.unexpected).toEqual([]);});
test('SY02 an already open publication refuses fresh downloads after withdrawal and shows the actual failure',async({page})=>{const s=state();await routes(page,s);await page.goto(web+`/announcements/${id(1)}`);await expect(page.getByRole('button',{name:'Tải về',exact:true})).toBeVisible();s.mode='withdrawn';await page.getByRole('button',{name:'Tải về',exact:true}).click();await expect(page.getByText('Chưa tải được tệp',{exact:true})).toBeVisible();expect(s.downloads).toHaveLength(1);await page.reload();await expect(page.getByRole('heading',{name:news.title,exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Tải về',exact:true})).toHaveCount(0);expect(s.unexpected).toEqual([]);});
