import {test,expect,type Page,type Route} from '@playwright/test';
const id=(n:number)=>`6d000000-0000-4000-8000-${String(n).padStart(12,'0')}`,schoolId=id(1),yearId=id(2),classId=id(3),memberId=id(8),root=`/api/v1/schools/${schoolId}/teacher`,web=`/teacher/${schoolId}/announcements`,at='2026-10-02T01:00:00Z',prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-teacher-announcements';
type State={mode:'ready'|'outage'|'conflict';read:Set<string>;posts:{sources:unknown[]}[];unexpected:string[]};
const state=():State=>({mode:'ready',read:new Set(),posts:[],unexpected:[]});
const source=(n:number)=>({id:id(n),rootId:id(n),yearId,classId,version:2,dataVersion:1,publicationId:id(n+20)});
const item=(n:number,s:State)=>({id:id(n),rootId:id(n),origin:'class',className:'6A API',title:`Thông báo giáo viên API ${n}`,summary:'Tóm tắt thực tế theo bản công bố',body:[{type:'p',text:'Nội dung công bố tiếng Việt cho giáo viên'}],scopeLabel:'Lớp tôi phụ trách',audienceLabel:'Gia đình học sinh',publishedAt:at,createdByName:null,attachments:[],source:source(n),read:s.read.has(id(n)),readAt:s.read.has(id(n))?at:null});
const reply=(r:Route,data:unknown)=>r.fulfill({status:200,json:{data,requestId:'teacher-announcement-browser'}});
async function routes(page:Page,s:State){await page.route('**/api/v1/**',async r=>{const path=new URL(r.request().url()).pathname;
 if(path==='/api/v1/me/context')return reply(r,{user:{id:id(9),version:1,displayName:'Giáo viên thông báo API',email:'teacher-ann@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'teacher-ann-browser-csrf',mode:'connected',serverNow:at,memberships:[{memberId,schoolId,schoolName:'Trường thông báo API',schoolSlug:'teacher-ann',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-02',department:null,schoolWorkspace:false,teacherWorkspace:true,duties:[{id:id(7),classId,className:'6A API',kind:'HOMEROOM',subjectId:null,subjectName:null,startsOn:'2026-09-01',endsOn:'2027-06-01'}],grants:[{id:id(7),version:1,roleId:id(6),roleCode:'HOMEROOM',roleLabel:'Chủ nhiệm',scopeType:'CLASS',classId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,assignmentStartsOn:'2026-09-01',assignmentEndsOn:'2027-06-01',actions:['teacher.self','announcement.read','school.read','class.read']}]}]});
 if(path==='/api/v1/me/notifications')return r.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'teacher-ann-notifications'}});
 if(path===`/api/v1/schools/${schoolId}/me/class-directory`)return r.fulfill({status:200,json:{data:[],page:{total:0,limit:100,hasMore:false,nextCursor:null},requestId:'teacher-ann-class-directory'}});
 if(path===root+'/announcement-feed'){if(s.mode==='outage')return r.fulfill({status:503,json:{code:'DEPENDENCY_UNAVAILABLE'}});return r.fulfill({status:200,json:{data:{schoolId,memberId,items:[item(4,s),item(5,s)]},page:{total:2,limit:100,hasMore:false,nextCursor:null},requestId:'teacher-ann-feed'}});}
 if(path===root+'/announcement-read'){const body=r.request().postDataJSON();s.posts.push(body);if(s.mode==='conflict')return r.fulfill({status:409,json:{code:'STALE_SOURCE'}});for(const expected of body.sources)s.read.add(expected.id);return reply(r,{schoolId,memberId,items:body.sources.map((expected:ReturnType<typeof source>)=>({source:expected,receiptId:id(Number(expected.id.slice(-12))+40),readAt:at}))});}
 s.unexpected.push(path);return r.fulfill({status:503,json:{code:'UNEXPECTED_TEACHER_ANNOUNCEMENT_REQUEST'}});
 });}
test('TE05 opens published content and shows read confirmation only after one exact publication acknowledgement',async({page})=>{const s=state();await routes(page,s);await page.goto(web);await expect(page.getByText('Thông báo (2 chưa đọc)',{exact:true})).toBeVisible();await page.getByRole('button').filter({hasText:'Thông báo giáo viên API 4'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByText('Nội dung công bố tiếng Việt cho giáo viên')).toBeVisible();await expect(dialog.getByText('Đã đọc',{exact:true})).toBeVisible();expect(s.posts).toEqual([{sources:[source(4)]}]);await expect(dialog.getByText('Người đăng:')).toHaveCount(0);await page.screenshot({path:`qa/backend/${prefix}-desktop.png`,fullPage:true});await dialog.getByLabel('Đóng',{exact:true}).click();await page.reload();await expect(page.getByText('Thông báo (1 chưa đọc)',{exact:true})).toBeVisible();expect(s.unexpected).toEqual([]);});
test('TE05 mobile bulk read sends one atomic command for displayed sources and fits the existing layout',async({page})=>{await page.setViewportSize({width:390,height:844});const s=state();await routes(page,s);await page.goto(web);await page.getByRole('button',{name:'Đánh dấu tất cả đã đọc',exact:true}).click();await expect(page.getByText('Thông báo (0 chưa đọc)',{exact:true})).toBeVisible();expect(s.posts).toEqual([{sources:[source(4),source(5)]}]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`qa/backend/${prefix}-mobile.png`,fullPage:true});expect(s.unexpected).toEqual([]);});
test('TE05 source conflict preserves unread state and gives a visible retry without a false success badge',async({page})=>{const s=state();s.mode='conflict';await routes(page,s);await page.goto(web);await page.getByRole('button').filter({hasText:'Thông báo giáo viên API 4'}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByText('Chưa xác nhận đã đọc',{exact:true})).toBeVisible();await expect(dialog.getByText('Đã đọc',{exact:true})).toHaveCount(0);await expect(dialog.getByText('Chưa đọc',{exact:true})).toBeVisible();s.mode='ready';await dialog.getByRole('button',{name:'Đánh dấu đã đọc',exact:true}).click();await expect(dialog.getByText('Đã đọc',{exact:true})).toBeVisible();expect(s.unexpected).toEqual([]);});
test('TE05 an API outage exposes retry and never becomes an empty success list',async({page})=>{const s=state();s.mode='outage';await routes(page,s);await page.goto(web);await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByText('Chưa có thông báo',{exact:true})).toHaveCount(0);s.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByText('Thông báo (2 chưa đọc)',{exact:true})).toBeVisible();expect(s.unexpected).toEqual([]);});
