import {expect,test,type Page,type Route} from '@playwright/test';
const schoolId='69000000-0000-4000-8000-000000000001',yearId='69000000-0000-4000-8000-000000000002',homeId='69000000-0000-4000-8000-000000000003',subjectId='69000000-0000-4000-8000-000000000004',endedId='69000000-0000-4000-8000-000000000005',userId='69000000-0000-4000-8000-000000000006',memberId='69000000-0000-4000-8000-000000000007';
const prefix=process.env.EDU_NATIVE_QA_PREFIX??'b6-teacher-classes',directory=`/api/v1/schools/${schoolId}/me/class-directory`,web=`/teacher/${schoolId}/classes`;
const card=(id:string,name:string,kind:'HOMEROOM'|'SUBJECT',live=true)=>({id,schoolId,yearId,name,yearLabel:'2026–2027',status:'ACTIVE',today:'2026-10-01',referenceDate:'2026-10-01',live,motto:null,studentCount:live?2:null,roomLabel:null,homeroomName:live?'Chủ nhiệm công tác API':null,assignments:[{id,kind,subjectName:kind==='SUBJECT'?'Toán':null,startsOn:'2026-09-01',endsOn:'2027-06-01',live,status:live?'ACTIVE':'REVOKED'}],actions:live?(kind==='HOMEROOM'?['class.read','student.read','attendance.record','schedule.read']:['class.read','student.read','schedule.read']):[],nextLesson:live&&kind==='SUBJECT'?{date:'2026-10-02',startsAtLocal:'08:30',endsAtLocal:'09:15',periodNumber:null,subjectName:'Toán'}:null});
const reply=(route:Route,data:unknown)=>route.fulfill({status:200,json:{data,requestId:'teacher-classes-controlled-browser'}});
type State={mode:'ready'|'denied'|'outage'|'malformed';unexpected:string[];queries:string[]};
async function routes(page:Page,state:State){await page.route('**/api/v1/**',async route=>{
 const url=new URL(route.request().url()),path=url.pathname;
 if(path==='/api/v1/me/context')return reply(route,{user:{id:userId,version:1,displayName:'Giáo viên thẻ lớp API',email:'teacher-card@example.invalid',status:'ACTIVE'},platformActions:[],csrfToken:'teacher-card-csrf',mode:'connected',serverNow:'2026-10-01T01:00:00Z',memberships:[{memberId,schoolId,schoolName:'Trường thẻ lớp API',schoolSlug:'teacher-card',schoolShortName:'API',schoolStatus:'ACTIVE',status:'ACTIVE',timezone:'Asia/Ho_Chi_Minh',today:'2026-10-01',department:null,schoolWorkspace:false,teacherWorkspace:true,duties:[{id:homeId,classId:homeId,className:'6A API',kind:'HOMEROOM',subjectId:null,subjectName:null,startsOn:'2026-09-01',endsOn:'2027-06-01'}],grants:[{id:homeId,version:1,roleId:homeId,roleCode:'HOMEROOM',roleLabel:'Chủ nhiệm',scopeType:'CLASS',classId:homeId,validFrom:'2026-09-01T00:00:00Z',validUntil:null,assignmentStartsOn:'2026-09-01',assignmentEndsOn:'2027-06-01',actions:['teacher.self','school.read','class.read','student.read','schedule.read','attendance.record']}]}]});
 if(path==='/api/v1/me/notifications')return route.fulfill({status:200,json:{data:[],page:{total:0,limit:25,hasMore:false,nextCursor:null},requestId:'teacher-card-empty-notifications'}});
 if(path===directory){state.queries.push(url.search);if(state.mode==='denied'||state.mode==='outage')return route.fulfill({status:state.mode==='denied'?403:503,json:{code:state.mode==='denied'?'FORBIDDEN':'DEPENDENCY_UNAVAILABLE',requestId:'teacher-card-error'}});const rows=[card(homeId,'6A API','HOMEROOM'),card(subjectId,'6B API','SUBJECT')];if(url.searchParams.get('includeEnded')==='true')rows.push(card(endedId,'6C lịch sử','SUBJECT',false));if(state.mode==='malformed')Object.assign(rows[0],{studentId:userId});return route.fulfill({status:200,json:{data:rows,page:{total:rows.length,limit:100,hasMore:false,nextCursor:null},requestId:'teacher-card-directory'}});}
 state.unexpected.push(path);return route.fulfill({status:503,json:{code:'UNEXPECTED_TEACHER_CARD_OPERATION',requestId:'teacher-card-unexpected'}});
 });}
const ready=():State=>({mode:'ready',unexpected:[],queries:[]});
test('TE02 preserves class cards and buttons for exact homeroom/subject rights; ended history has no current panels',async({page})=>{
 const state=ready();await routes(page,state);await page.goto(web);await expect(page.getByRole('heading',{name:'Lớp học của tôi',exact:true})).toBeVisible();
 const home=page.locator('article').filter({has:page.getByRole('heading',{name:'Lớp 6A API',exact:true})}),subject=page.locator('article').filter({has:page.getByRole('heading',{name:'Lớp 6B API',exact:true})});await expect(home.getByRole('link',{name:'Điểm danh',exact:true})).toBeVisible();await expect(subject.getByRole('link',{name:'Điểm danh',exact:true})).toHaveCount(0);await expect(subject).toContainText('Toán – Tiết học (08:30)');await expect(subject).toContainText('Chưa phân phòng');await expect(subject.getByRole('link',{name:'Mở lớp',exact:true})).toHaveAttribute('href',`/classroom/${schoolId}/${yearId}/${subjectId}`);await page.screenshot({path:`qa/backend/${prefix}-teacher-classes-desktop.png`,fullPage:true});
 await page.getByRole('switch',{name:'Hiện cả phân công đã kết thúc'}).click();const ended=page.locator('article').filter({has:page.getByRole('heading',{name:'Lớp 6C lịch sử',exact:true})});await expect(ended).toBeVisible();await expect(ended).toContainText('Không còn quyền xem');await expect(ended.getByRole('link')).toHaveCount(0);await expect(ended).not.toContainText('2 học sinh');expect(state.queries.some(q=>q.includes('includeEnded=true'))).toBe(true);expect(state.unexpected).toEqual([]);
});
test('TE02 fits mobile class cards without inventing a period or leaking ended class navigation',async({page})=>{
 await page.setViewportSize({width:390,height:844});const state=ready();await routes(page,state);await page.goto(web);await expect(page.getByRole('heading',{name:'Lớp 6B API',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.locator('article').filter({hasText:'Lớp 6B API'})).not.toContainText('Tiết 1');await page.screenshot({path:`qa/backend/${prefix}-teacher-classes-mobile.png`,fullPage:true});expect(state.unexpected).toEqual([]);
});
test('TE02 shows permission loss and malformed responses as errors rather than a successful empty class list',async({page})=>{
 const state=ready();state.mode='denied';await routes(page,state);await page.goto(web);await expect(page.getByText('Bạn không có quyền xem mục này',{exact:true})).toBeVisible();await expect(page.getByText('Chưa có lớp được phân công',{exact:true})).toHaveCount(0);await expect(page.locator('article')).toHaveCount(0);state.mode='malformed';await page.reload();await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.locator('article')).toHaveCount(0);expect(state.unexpected).toEqual([]);
});
test('TE02 exposes an API outage and retry recovers actual cards under the same current staff identity',async({page})=>{
 const state=ready();state.mode='outage';await routes(page,state);await page.goto(web);await expect(page.getByText('Không tải được dữ liệu',{exact:true})).toBeVisible();await expect(page.getByText('Chưa có lớp được phân công',{exact:true})).toHaveCount(0);state.mode='ready';await page.getByRole('button',{name:'Thử lại',exact:true}).click();await expect(page.getByRole('heading',{name:'Lớp 6A API',exact:true})).toBeVisible();expect(state.unexpected).toEqual([]);
});
