import type { Resource } from '../../database/resources';

// Parameters: school, currently effective grants, year, reference date, user,
// member, base classes (NULL means all), whether this is a current active year.
export function allows(action:string,classExpression:string,subjectExpression?:string){
  return `EXISTS(SELECT 1 FROM jsonb_to_recordset($2::jsonb) AS g(scope_type text,class_id uuid,subject_id uuid,actions text[])
    WHERE '${action}'=ANY(g.actions) AND (g.scope_type='SCHOOL' OR (g.class_id=${classExpression} AND (g.scope_type='CLASS'${subjectExpression?subjectExpression==='*'?" OR g.scope_type='SUBJECT'":` OR (g.scope_type='SUBJECT' AND g.subject_id=${subjectExpression})`:''}))))`;
}
export const requestContext=`request AS (SELECT $1::uuid AS school,$2::jsonb AS grants,$3::uuid AS year,$4::date AS date,$5::uuid AS user_id,$6::uuid AS member,$7::uuid[] AS classes,$8::boolean AS live)`;
export const baseClasses=`SELECT c.* FROM app.classes c WHERE c.school_id=$1 AND c.year_id=$3::uuid AND ($7::uuid[] IS NULL OR c.id=ANY($7::uuid[]))`;
const live=`$8::boolean AND c.status='ACTIVE'`;
const schoolDay=`($4::date::timestamp AT TIME ZONE (SELECT timezone FROM platform.schools WHERE id=$1))`;
const noHoliday=`extract(isodow FROM $4::date)<>7 AND NOT EXISTS(SELECT 1 FROM app.calendar_events h WHERE h.school_id=c.school_id AND h.year_id=c.year_id AND (h.class_id IS NULL OR h.class_id=c.id) AND h.kind='HOLIDAY' AND h.status='PUBLISHED' AND h.starts_on<=$4::date AND h.ends_on>$4::date)`;
const columns=(id:string,kind:string,title:string,targetType:string,targetId:string,detail:string,status:string,tone:string,due:string='NULL::timestamptz',extra:string='NULL::uuid AS lesson_id')=>`${id} AS id,c.school_id,c.year_id,c.id AS class_id,c.name AS class_name,'${kind}' AS kind,${title} AS title,'${targetType}' AS target_kind,${targetId} AS target_id,${detail} AS detail,'${status}' AS status,'${tone}' AS tone,${due} AS due_at,${extra}`;
export const taskResource:Resource={table:`(WITH ${requestContext},base AS (${baseClasses})
  SELECT ${columns("'attendance:'||c.id::text",'attendance',"'Điểm danh buổi sáng — '||c.name",'attendance','c.id',"'Chưa có buổi điểm danh của lớp'",'Chưa điểm danh','danger',`${schoolDay}+interval '7 hours'`)} FROM base c
   WHERE ${live} AND ${noHoliday} AND ${allows('attendance.record','c.id')} AND EXISTS(SELECT 1 FROM app.enrollments e WHERE e.school_id=c.school_id AND e.class_id=c.id AND e.status<>'CANCELLED' AND e.starts_on<=$4::date AND (e.ends_on IS NULL OR e.ends_on>$4::date))
    AND NOT EXISTS(SELECT 1 FROM app.attendance_sessions s WHERE s.school_id=c.school_id AND s.class_id=c.id AND s.session_date=$4::date AND s.granularity='DAILY' AND s.slot_key IN ('morning','daily'))
  UNION ALL SELECT ${columns("'attendance-mark:'||s.id::text",'attendance',"'Hoàn tất điểm danh — '||c.name",'attendance','s.id',"'Còn học sinh chưa được ghi trạng thái'",'Chưa hoàn tất','warning',`${schoolDay}+interval '7 hours'`)} FROM base c JOIN app.attendance_sessions s ON s.school_id=c.school_id AND s.class_id=c.id
   WHERE ${live} AND ${allows('attendance.record','c.id')} AND s.session_date=$4::date AND s.granularity='DAILY' AND s.status='OPEN' AND EXISTS(SELECT 1 FROM app.attendance_records r WHERE r.school_id=s.school_id AND r.session_id=s.id AND r.status='UNMARKED')
  UNION ALL SELECT ${columns("'attendance-publish:'||s.id::text",'attendance',"'Công bố chuyên cần — '||c.name",'attendance','s.id',"'Nguồn đã ghi đủ, bản hiện tại chưa được công bố'",'Chưa công bố','warning',`${schoolDay}+interval '17 hours'`)} FROM base c JOIN app.attendance_sessions s ON s.school_id=c.school_id AND s.class_id=c.id
   WHERE ${live} AND ${allows('attendance.publish','c.id')} AND s.session_date=$4::date AND EXISTS(SELECT 1 FROM app.attendance_records r WHERE r.school_id=s.school_id AND r.session_id=s.id)
    AND NOT EXISTS(SELECT 1 FROM app.attendance_records r WHERE r.school_id=s.school_id AND r.session_id=s.id AND r.status='UNMARKED')
    AND NOT EXISTS(SELECT 1 FROM app.publication_revisions p WHERE p.school_id=s.school_id AND p.attendance_session_id=s.id AND p.status='PUBLISHED' AND p.source_version=s.data_version)
  UNION ALL SELECT ${columns("'lesson-attendance:'||l.id::text",'attendance',"'Điểm danh tiết '||coalesce(l.period_number::text,'')||' — '||c.name",'lesson','l.id',"'Tiết giảng dạy của chính bạn chưa có buổi điểm danh'",'Chưa điểm danh','neutral','l.starts_at','l.id AS lesson_id')} FROM base c JOIN app.lesson_occurrences l ON l.school_id=c.school_id AND l.class_id=c.id
   WHERE ${live} AND l.member_id=$6::uuid AND l.status='SCHEDULED' AND l.starts_at>=${schoolDay} AND l.starts_at<${schoolDay}+interval '1 day'
    AND ${allows('attendance.record','c.id','l.subject_id')} AND NOT EXISTS(SELECT 1 FROM app.attendance_sessions s WHERE s.school_id=l.school_id AND s.lesson_id=l.id)
  UNION ALL SELECT ${columns("'conduct-review:'||p.id::text",'conduct',"'Rà soát thi đua tuần '||w.week_number::text||' — '||c.name",'conduct-period','p.id',"'Có ghi nhận đang chờ rà soát'",'Chờ rà soát','warning','p.input_deadline')} FROM base c JOIN app.conduct_periods p ON p.school_id=c.school_id AND p.class_id=c.id JOIN app.school_weeks w ON w.school_id=p.school_id AND w.id=p.week_id
   WHERE ${live} AND ${allows('conduct.review','c.id')} AND p.status<>'LOCKED' AND EXISTS(SELECT 1 FROM app.conduct_records r WHERE r.school_id=p.school_id AND r.period_id=p.id AND r.status='DRAFT')
  UNION ALL SELECT ${columns("'conduct-lock:'||p.id::text",'conduct',"'Chốt thi đua tuần '||w.week_number::text||' — '||c.name",'conduct-period','p.id',"'Kỳ đã đến hạn, cần kiểm tra trước khi chốt'",'Đến hạn','danger','p.input_deadline')} FROM base c JOIN app.conduct_periods p ON p.school_id=c.school_id AND p.class_id=c.id JOIN app.school_weeks w ON w.school_id=p.school_id AND w.id=p.week_id
   WHERE ${live} AND ${allows('conduct.lock','c.id')} AND p.status<>'LOCKED' AND p.input_deadline<now()
  UNION ALL SELECT ${columns("'evidence:'||a.id::text",'evidence',"'Duyệt minh chứng — '||c.name",'activity','a.id',"a.title",'Chờ duyệt','info','a.due_at')} FROM base c JOIN app.activities a ON a.school_id=c.school_id AND a.class_id=c.id
   WHERE ${live} AND ${allows('evidence.review','c.id')} AND a.status='ASSIGNED' AND EXISTS(SELECT 1 FROM app.activity_participants p JOIN app.evidence e ON e.school_id=p.school_id AND e.participant_id=p.id WHERE p.school_id=a.school_id AND p.activity_id=a.id AND p.cancelled_at IS NULL AND e.status='SUBMITTED')
  UNION ALL SELECT ${columns("'supplement:'||a.id::text",'evidence',"'Theo dõi minh chứng cần bổ sung — '||c.name",'activity','a.id',"a.title",'Cần bổ sung','neutral','a.due_at')} FROM base c JOIN app.activities a ON a.school_id=c.school_id AND a.class_id=c.id
   WHERE ${live} AND ${allows('evidence.review','c.id')} AND a.status='ASSIGNED' AND EXISTS(SELECT 1 FROM app.activity_participants p WHERE p.school_id=a.school_id AND p.activity_id=a.id AND p.cancelled_at IS NULL AND p.status='NEEDS_REVISION')
  UNION ALL SELECT ${columns("'announcement:'||a.id::text",'announcement',"'Thông báo nháp — '||c.name",'announcement','a.id',"a.title",'Bản nháp','neutral')} FROM base c JOIN app.announcements a ON a.school_id=c.school_id AND a.class_id=c.id
   WHERE ${live} AND ${allows('announcement.manage','c.id')} AND a.status='DRAFT' AND a.discarded_at IS NULL
  UNION ALL SELECT ${columns("'adjustment:'||a.id::text",'conduct',"'Điều chỉnh sau chốt — '||c.name",'adjustment','a.id',"'Đề nghị cần được kiểm tra và duyệt'",'Chờ duyệt','warning')} FROM base c JOIN app.conduct_periods p ON p.school_id=c.school_id AND p.class_id=c.id JOIN app.adjustment_requests a ON a.school_id=p.school_id AND a.period_id=p.id
   WHERE ${live} AND ${allows('conduct.adjust.approve','c.id')} AND a.status='SUBMITTED'
  UNION ALL SELECT ${columns("'adjustment-publish:'||a.id::text",'conduct',"'Công bố bản điều chỉnh — '||c.name",'adjustment','a.id',"'Đề nghị đã duyệt, cần áp dụng và công bố lại'",'Đã duyệt','warning')} FROM base c JOIN app.conduct_periods p ON p.school_id=c.school_id AND p.class_id=c.id JOIN app.adjustment_requests a ON a.school_id=p.school_id AND a.period_id=p.id
   WHERE ${live} AND ${allows('conduct.adjust.approve','c.id')} AND ${allows('conduct.publish','c.id')} AND a.status='APPROVED'
  UNION ALL SELECT ${columns("'group:'||c.id::text",'groups',"'Xếp tổ cho học sinh — '||c.name",'groups','c.id',"'Có học sinh chưa được xếp tổ tại ngày tham chiếu'",'Chưa phân tổ','neutral')} FROM base c
   WHERE ${live} AND ${allows('group.manage','c.id')} AND EXISTS(SELECT 1 FROM app.enrollments e WHERE e.school_id=c.school_id AND e.class_id=c.id AND e.status<>'CANCELLED' AND e.starts_on<=$4::date AND (e.ends_on IS NULL OR e.ends_on>$4::date)
    AND NOT EXISTS(SELECT 1 FROM app.group_memberships gm WHERE gm.school_id=e.school_id AND gm.enrollment_id=e.id AND gm.cancelled_at IS NULL AND gm.starts_on<=$4::date AND (gm.ends_on IS NULL OR gm.ends_on>$4::date))))`,fields:{id:'id',schoolId:'school_id',yearId:'year_id',classId:'class_id',className:'class_name',kind:'kind',title:'title',targetType:'target_kind',targetId:'target_id',detail:'detail',status:'status',tone:'tone',dueAt:'due_at',lessonId:'lesson_id'},writeFields:[],search:['title','detail','class_name'],filters:{kind:'kind',classId:'class_id'}};
