import {dto,resource} from '../../database/resources';
import {one,iso,type Row,type Transaction} from '../../database/database';
import {schoolClassOverview} from './school-class-overview';
import type {ViewContext} from './dashboards.service';

/** School-wide totals have their own current permission; school.read never lends it. */
export async function schoolOverview(tx:Transaction,ctx:ViewContext){
  const {schoolId,year,referenceDate,grants}=ctx,yearId=year?.id??null;
  const has=(action:string)=>grants.some(g=>g.role_code!=='SUPPORT_READ'&&g.scope_type==='SCHOOL'&&g.actions.includes(action));
  const base=`/school/${schoolId}`,previous=year?await one<Row>(tx,'SELECT * FROM app.academic_years WHERE school_id=$1 AND ends_on<=$2 AND id<>$3 ORDER BY ends_on DESC,id DESC LIMIT 1',[schoolId,year.starts_on,year.id]):undefined;
  const scalar=async(sql:string,parameters:unknown[])=>Number((await one<{n:number|string}>(tx,sql,parameters))!.n);
  const classData=has('class.read')?await schoolClassOverview(tx,ctx):null,stats=classData?.stats;
  const activeClasses=stats?.active??null,draftClasses=stats?.draft??null;
  const studentCount=async(id:unknown,date:unknown)=>scalar(`SELECT count(DISTINCT e.student_id)::int AS n FROM app.enrollments e JOIN app.classes c ON c.school_id=e.school_id AND c.id=e.class_id AND c.year_id=e.year_id WHERE e.school_id=$1 AND e.year_id=$2 AND c.status IN ('ACTIVE','ARCHIVED') AND e.status<>'CANCELLED' AND e.starts_on<=$3 AND (e.ends_on IS NULL OR e.ends_on>$3)`,[schoolId,id,date]);
  const students=has('student.read')?await studentCount(yearId,referenceDate):null;
  // The previous year's final day is exclusive in storage and inclusive in the view.
  const previousStudentCount=has('student.read')&&previous?await scalar(`SELECT count(DISTINCT e.student_id)::int AS n FROM app.enrollments e JOIN app.classes c ON c.school_id=e.school_id AND c.id=e.class_id AND c.year_id=e.year_id WHERE e.school_id=$1 AND e.year_id=$2 AND c.status IN ('ACTIVE','ARCHIVED') AND e.status<>'CANCELLED' AND e.starts_on<$3::date AND (e.ends_on IS NULL OR e.ends_on>=$3::date)`,[schoolId,previous.id,previous.ends_on]):null;
  const prevClasses=has('class.read')&&previous?await scalar('SELECT count(*)::int AS n FROM app.classes WHERE school_id=$1 AND year_id=$2',[schoolId,previous.id]):null;
  const staffActive=has('member.read')?await scalar("SELECT count(*)::int AS n FROM app.memberships m JOIN identity.users u ON u.id=m.user_id AND u.status='ACTIVE' WHERE m.school_id=$1 AND m.status='ACTIVE' AND m.ended_at IS NULL",[schoolId]):null;
  let linksActive:number|null=null,linksOpened:number|null=null;
  if(has('parent_access.manage')){const row=(await one<{active:number;opened:number}>(tx,`SELECT count(*)::int AS active,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM app.parent_access_events e WHERE e.school_id=l.school_id AND e.access_link_id=l.id AND e.event_kind IN ('EXCHANGED','READ')))::int AS opened FROM app.parent_access_links l JOIN app.guardian_relationships g ON g.school_id=l.school_id AND g.id=l.relationship_id AND g.student_id=l.student_id WHERE l.school_id=$1 AND l.year_id=$2 AND l.revoked_at IS NULL AND l.expires_at>now() AND g.status='VERIFIED' AND g.can_receive_info AND g.revoked_at IS NULL`,[schoolId,yearId]))!;linksActive=row.active;linksOpened=row.opened;}
  const configuration=has('year.read')&&year?(await one<{ready:boolean}>(tx,`SELECT EXISTS(SELECT 1 FROM app.terms t JOIN app.school_weeks w ON w.school_id=t.school_id AND w.term_id=t.id WHERE t.school_id=$1 AND t.year_id=$2) AS ready`,[schoolId,yearId]))!.ready:has('year.read')?false:null;
  const rules=has('rules.read')?(await one<{ready:boolean}>(tx,`SELECT EXISTS(SELECT 1 FROM app.class_rule_periods p JOIN app.classes c ON c.school_id=p.school_id AND c.id=p.class_id JOIN app.rule_sets r ON r.school_id=p.school_id AND r.id=p.rule_set_id AND r.status='ISSUED' WHERE p.school_id=$1 AND c.year_id=$2 AND p.starts_on<=$3 AND (p.ends_on IS NULL OR p.ends_on>$3)) AS ready`,[schoolId,yearId,referenceDate]))!.ready:null;
  const familyAnnouncement=has('announcement.read')?(await one<{ready:boolean}>(tx,`SELECT EXISTS(SELECT 1 FROM app.announcements a JOIN app.publication_revisions p ON p.school_id=a.school_id AND p.announcement_id=a.id AND p.status='PUBLISHED' WHERE a.school_id=$1 AND a.year_id=$2 AND a.class_id IS NULL AND a.audience IN ('FAMILIES','ALL')) AS ready`,[schoolId,yearId]))!.ready:null;
  const step=(key:string,label:string,done:boolean|null,detail:string,href:string)=>({key,label,done,detail:done===null?'Không có quyền xem hạng mục':detail,href:base+href});
  const setup=[step('year','Cấu hình năm học, học kỳ, tuần',configuration,year?String(year.name):'Chưa tạo','/academic-years'),step('classes','Tạo danh sách lớp học',stats?stats.total>0:null,`${stats?.total} lớp`,'/classes'),step('homeroom','Phân công giáo viên chủ nhiệm',stats?stats.live>0&&stats.noHomeroom===0:null,stats?.noHomeroom?`Còn ${stats.noHomeroom} lớp`:stats?.live?'Đủ':'Chưa có lớp chưa lưu trữ','/assignments'),step('students','Nhập danh sách học sinh',has('student.read')&&stats?stats.active>0&&stats.noStudents===0:null,stats?.noStudents?`Còn ${stats.noStudents} lớp`:stats?.active?'Đủ':'Chưa có lớp đang hoạt động','/imports'),step('timetable','Thiết lập thời khóa biểu',stats?stats.active>0&&stats.noTimetable===0:null,stats?.noTimetable?`Còn ${stats.noTimetable} lớp`:stats?.active?'Đủ các lớp đang hoạt động':'Chưa có lớp đang hoạt động','/timetable'),step('rules','Ban hành nội quy thi đua',rules,rules?'Đã áp dụng bản ban hành':'Chưa áp dụng bản ban hành','/conduct-rules'),step('announce','Công bố thông báo đầu năm đến gia đình',familyAnnouncement,familyAnnouncement?'Đã công bố':'Chưa công bố','/announcements'),step('activate','Kích hoạt tất cả lớp',stats?stats.total>0&&stats.draft===0:null,stats?.draft?`${stats.draft} lớp còn nháp`:stats?.total?'Hoàn tất':'Chưa tạo lớp','/classes')];
  const classesNeedingAction=classData?.preview??null,classesNeedingActionTotal=classData?.total??null;
  const actionable=has('student.transfer')||has('member.manage')||has('conduct.adjust.approve')||has('support.approve')||has('assignment.read')&&!!stats;
  const todayItems:Record<string,unknown>[]|null=actionable?[]:null;
  const item=async(action:string,key:string,label:string,sql:string,href:string,tone:string,parameters:unknown[])=>{if(!has(action))return;const count=await scalar(sql,parameters);if(count)todayItems!.push({key,label:`${count} ${label}`,detail:'Cần kiểm tra và xử lý trong phạm vi được cấp.',href:base+href,tone});};
  await item('student.transfer','tr','yêu cầu chuyển lớp chờ duyệt',"SELECT count(*)::int AS n FROM app.transfer_requests t JOIN app.enrollments e ON e.school_id=t.school_id AND e.id=t.from_enrollment_id WHERE t.school_id=$1 AND e.year_id=$2 AND t.status='SUBMITTED'",'/transfers','warning',[schoolId,yearId]);
  await item('member.manage','inv','lời mời giáo viên chưa phản hồi',"SELECT count(*)::int AS n FROM app.staff_invitations WHERE school_id=$1 AND status='PENDING' AND expires_at>now()",'/teachers','info',[schoolId]);
  await item('conduct.adjust.approve','adj','đề nghị điều chỉnh sau chốt',"SELECT count(*)::int AS n FROM app.adjustment_requests a JOIN app.conduct_periods p ON p.school_id=a.school_id AND p.id=a.period_id JOIN app.classes c ON c.school_id=p.school_id AND c.id=p.class_id WHERE a.school_id=$1 AND c.year_id=$2 AND a.status='SUBMITTED'",'/publications','warning',[schoolId,yearId]);
  await item('support.approve','sg','đề nghị quyền hỗ trợ',"SELECT count(*)::int AS n FROM platform.support_access WHERE school_id=$1 AND status='REQUESTED' AND valid_until>now()",'/support','info',[schoolId]);
  if(has('assignment.read')&&stats?.noHomeroom)todayItems!.push({key:'hr',label:`${stats.noHomeroom} lớp chưa có giáo viên chủ nhiệm`,detail:'Kiểm tra các lớp cần phân công trong Ma trận phân công.',href:base+'/assignments',tone:'danger'});
  const announcements=has('announcement.read')?(await tx.query<Row>(`SELECT a.id,a.title,a.summary,a.status,a.created_at,a.scheduled_at,p.published_at FROM app.announcements a LEFT JOIN LATERAL(SELECT published_at FROM app.publication_revisions p WHERE p.school_id=a.school_id AND p.announcement_id=a.id AND p.status='PUBLISHED' ORDER BY published_at DESC,id DESC LIMIT 1) p ON true WHERE a.school_id=$1 AND a.year_id=$2 AND a.class_id IS NULL AND a.discarded_at IS NULL AND (a.status='SCHEDULED' OR (a.status='PUBLISHED' AND p.published_at IS NOT NULL)) AND NOT EXISTS(SELECT 1 FROM app.announcements newer WHERE newer.school_id=a.school_id AND newer.root_id=a.root_id AND newer.discarded_at IS NULL AND newer.status IN ('SCHEDULED','PUBLISHED') AND (newer.created_at,newer.id)>(a.created_at,a.id)) ORDER BY coalesce(a.scheduled_at,p.published_at,a.created_at) DESC,a.id DESC LIMIT 4`,[schoolId,yearId])).rows.map(a=>({id:a.id,title:a.title,summary:a.summary,status:a.status,createdAt:iso(a.created_at as Date),scheduledAt:a.scheduled_at?iso(a.scheduled_at as Date):null,publishedAt:a.published_at?iso(a.published_at as Date):null})):null;
  return {year:year?dto(resource('year'),year):null,prevYear:previous?dto(resource('year'),previous):null,kpi:{activeClasses,draftClasses,prevClasses,staffActive,students,prevStudents:previousStudentCount,linksActive,linksOpened},setup,classesNeedingAction,classesNeedingActionTotal,todayItems,announcements};
}
