import {Database,one,iso,type Row,type Transaction} from '../../database/database';
import {Permissions,grantAllows} from '../../common/permissions';
import {Commands,canonical} from '../../common/commands';
import {Problem,notFound,validation} from '../../common/problem';
import {resource,getResource,listResource} from '../../database/resources';
import type {RequestContext,Result} from '../../api.router';
import type {AnnouncementsService} from './announcements.service';
import {announcementHtmlToBlocks,blocksToAnnouncementHtml,type AnnouncementBlock} from './announcement-blocks';
type Target={kind:'PUBLIC'|'SCHOOL'|'GRADE'|'CLASS'|'STUDENT'|'STAFF';id?:string};
const r={table:'app.announcements',fields:{id:'id',version:'version',createdAt:'created_at',updatedAt:'updated_at',yearId:'year_id',title:'title',status:'status'},writeFields:[],search:['title','summary'],filters:{status:'status',yearId:'year_id'}};
function scoped(c:RequestContext,classId?:string,id?:string){return {...c,params:{...c.params,...(classId?{classId}:{}),...(id?{announcementId:id}:{})}};}
function native(c:RequestContext,id:string,permission:string,body:Record<string,unknown>={},sourceId?:string){return {...c,operation:{...c.operation,id,permission},body,params:{...c.params,...(sourceId?{announcementId:sourceId}:{})}};}
function bounded<T>(rows:T[],limit:number,code='ANNOUNCEMENT_WORKSPACE_LIMIT'){if(rows.length>limit)throw new Problem(422,code);return rows;}
async function access(tx:Transaction,policy:Permissions,c:RequestContext,classId?:string,yearId?:string){
 const schoolId=c.params.schoolId!,a=await policy.require(tx,c.principal!,'announcement.read',{schoolId,classId,yearId,allowSubject:true});
 const can=(action:string)=>a.grants.some(g=>grantAllows(g,action,{schoolId,classId,yearId},a.today));
 return {...a,schoolId,can};
}
async function publication(tx:Transaction,schoolId:string,rootId:unknown){return one<Row>(tx,"SELECT p.id,p.published_at,p.version,p.announcement_id FROM app.publication_revisions p JOIN app.announcements a ON a.school_id=p.school_id AND a.id=p.announcement_id WHERE a.school_id=$1 AND a.root_id=$2 AND p.status='PUBLISHED'",[schoolId,rootId]);}
function source(row:Row,pub?:Row){return {id:row.id,rootId:row.root_id,yearId:row.year_id,classId:row.class_id??null,version:Number(row.version),dataVersion:Number(row.data_version),publicationId:pub?.id??null};}
function targets(scope:Row,isPublic=false):Target[]{
 const kind=String(scope.type).toUpperCase();if(kind==='SCHOOL')return [{kind:'SCHOOL'},...(isPublic?[{kind:'PUBLIC' as const}]:[])];
 const key=kind==='GRADE'?'gradeIds':kind==='CLASS'?'classIds':'studentIds',ids=scope[key];if(!['GRADE','CLASS','STUDENT'].includes(kind)||!Array.isArray(ids)||!ids.length||new Set(ids).size!==ids.length)validation('scope','Chọn đối tượng nhận thông báo');return ids.map(id=>({kind:kind as Target['kind'],id:String(id)}));
}
async function audienceEstimate(tx:Transaction,ctx:Awaited<ReturnType<typeof access>>,yearId:string,selection:Target[],audience:string,classId?:string){
 const parent=audience!=='STAFF',staff=audience!=='FAMILIES',json=JSON.stringify(selection),scope=classId?`AND e.class_id=$5`:'',values=classId?[ctx.schoolId,yearId,ctx.today,json,classId]:[ctx.schoolId,yearId,ctx.today,json];
 const result=await one<Row>(tx,`WITH chosen AS(SELECT DISTINCT e.student_id FROM app.enrollments e JOIN app.classes cl ON cl.school_id=e.school_id AND cl.id=e.class_id WHERE e.school_id=$1 AND e.year_id=$2 AND e.status<>'CANCELLED' AND e.starts_on<=$3 AND (e.ends_on IS NULL OR e.ends_on>$3) AND cl.status='ACTIVE' ${scope}
  AND EXISTS(SELECT 1 FROM jsonb_to_recordset($4::jsonb) AS t(kind text,id uuid) WHERE t.kind IN ('SCHOOL','PUBLIC') OR t.kind='GRADE' AND t.id=cl.grade_level_id OR t.kind='CLASS' AND t.id=e.class_id OR t.kind='STUDENT' AND t.id=e.student_id))
  SELECT (SELECT count(*)::int FROM chosen) AS students,(SELECT count(*)::int FROM app.parent_access_links p JOIN chosen ch ON ch.student_id=p.student_id JOIN app.guardian_relationships g ON g.school_id=p.school_id AND g.id=p.relationship_id AND g.student_id=p.student_id WHERE p.school_id=$1 AND p.year_id=$2 AND p.revoked_at IS NULL AND p.expires_at>now() AND 'announcements'=ANY(p.allowed_sections) AND g.revoked_at IS NULL AND g.can_receive_info AND g.status='VERIFIED') AS links`,values);
 const seeLinks=ctx.can('parent_access.manage')||ctx.can('parent_access.issue');
 const members=staff?(await one<{n:number}>(tx,`SELECT count(DISTINCT m.id)::int AS n FROM app.memberships m JOIN identity.users u ON u.id=m.user_id AND u.status='ACTIVE' WHERE m.school_id=$1 AND m.status='ACTIVE' AND m.ended_at IS NULL AND (
  EXISTS(SELECT 1 FROM jsonb_to_recordset($4::jsonb) AS t(kind text,id uuid) WHERE t.kind IN ('SCHOOL','PUBLIC') OR t.kind='STAFF' AND t.id=m.id) OR EXISTS(
   SELECT 1 FROM app.teaching_assignments a JOIN app.classes cl ON cl.school_id=a.school_id AND cl.id=a.class_id JOIN app.role_grants g ON g.school_id=a.school_id AND g.id=a.role_grant_id JOIN app.roles r ON r.school_id=g.school_id AND r.id=g.role_id AND r.status='ACTIVE' WHERE a.school_id=m.school_id AND a.member_id=m.id AND cl.year_id=$2 AND a.revoked_at IS NULL AND a.starts_on<=$3 AND (a.ends_on IS NULL OR a.ends_on>$3) AND g.revoked_at IS NULL AND g.valid_from<=now() AND (g.valid_until IS NULL OR g.valid_until>now())
   AND EXISTS(SELECT 1 FROM jsonb_to_recordset($4::jsonb) AS t(kind text,id uuid) WHERE t.kind='CLASS' AND t.id=a.class_id OR t.kind='GRADE' AND t.id=cl.grade_level_id OR t.kind='STUDENT' AND a.kind='HOMEROOM' AND EXISTS(SELECT 1 FROM app.enrollments e WHERE e.school_id=a.school_id AND e.class_id=a.class_id AND e.student_id=t.id AND e.year_id=$2 AND e.status<>'CANCELLED' AND e.starts_on<=$3 AND (e.ends_on IS NULL OR e.ends_on>$3)))))`,[ctx.schoolId,yearId,ctx.today,json]))!.n:0;
 return {students:parent?Number(result!.students):0,activeLinks:parent&&seeLinks?Number(result!.links):null,staff:members};
}
async function project(tx:Transaction,policy:Permissions,c:RequestContext,service:AnnouncementsService,row:Row,read:Awaited<ReturnType<AnnouncementsService['readPredicate']>>){
 // The canonical predicate already proved this row readable (including school publications visible through a class grant).
 const grants=await policy.collection(tx,c.principal!,'announcement.read',c.params.schoolId!,true),ctx={...grants,schoolId:c.params.schoolId!,can:(action:string)=>grants.grants.some(g=>grantAllows(g,action,{schoolId:c.params.schoolId!,classId:row.class_id as string|undefined,yearId:String(row.year_id)},grants.today))};
 const view=await service.readView(tx,row,read),pub=await publication(tx,ctx.schoolId,row.root_id),year=await getResource(tx,resource('year'),ctx.schoolId,String(row.year_id)),cls=row.class_id?await getResource(tx,resource('class'),ctx.schoolId,String(row.class_id)):undefined;
 const selected=view.targets as Target[],kinds=[...new Set(selected.filter(t=>t.kind!=='PUBLIC').map(t=>t.kind))],representable=kinds.length===1&&['SCHOOL','GRADE','CLASS','STUDENT'].includes(kinds[0]!);
 const kind=representable?kinds[0]!:'MIXED',selection=kind==='MIXED'?{type:'mixed',targets:selected}:kind==='SCHOOL'?{type:'school'}:{type:kind.toLowerCase(),[kind==='GRADE'?'gradeIds':kind==='CLASS'?'classIds':'studentIds']:selected.filter(t=>t.kind===kind).map(t=>t.id!)};
 const canManage=ctx.can('announcement.manage'),readOnly=year.status==='ARCHIVED'||cls?.status==='ARCHIVED',canEdit=canManage&&!readOnly&&representable,canPublish=ctx.can('announcement.publish')&&!readOnly;
 let labels:string[]=[];if(kind==='CLASS')labels=(await tx.query<{name:string}>('SELECT name FROM app.classes WHERE school_id=$1 AND id=ANY($2::uuid[]) ORDER BY name COLLATE app.vi_names,id',[ctx.schoolId,selected.filter(t=>t.kind==='CLASS').map(t=>t.id)])).rows.map(r=>r.name);
 if(kind==='GRADE')labels=(await tx.query<{name:string}>('SELECT name FROM app.grade_levels WHERE school_id=$1 AND id=ANY($2::uuid[]) ORDER BY name COLLATE app.vi_names,id',[ctx.schoolId,selected.filter(t=>t.kind==='GRADE').map(t=>t.id)])).rows.map(r=>r.name);
 if(kind==='STUDENT'&&ctx.can('student.read'))labels=(await tx.query<{full_name:string}>('SELECT full_name FROM app.students WHERE school_id=$1 AND id=ANY($2::uuid[]) ORDER BY full_name COLLATE app.vi_names,id',[ctx.schoolId,selected.filter(t=>t.kind==='STUDENT').map(t=>t.id)])).rows.map(r=>r.full_name);
 const author=await one<Row>(tx,'SELECT work_display_name FROM app.memberships WHERE school_id=$1 AND user_id=$2',[ctx.schoolId,row.created_by]);
 const history=canManage?bounded((await tx.query<Row>(`SELECT e.id,e.created_at,e.action,e.reason,e.redacted_after,m.work_display_name FROM app.audit_events e JOIN app.announcements a ON a.school_id=e.school_id AND a.id=e.target_id LEFT JOIN app.memberships m ON m.school_id=e.school_id AND m.user_id=e.actor_user_id WHERE e.school_id=$1 AND e.target_type='announcement' AND a.root_id=$2 ORDER BY e.created_at,e.id LIMIT 2001`,[ctx.schoolId,row.root_id])).rows,2000):null;
 const files=bounded((await tx.query<Row>("SELECT f.id,f.version,f.original_name,f.content_type,f.byte_size,f.status FROM app.file_links l JOIN app.files f ON f.school_id=l.school_id AND f.id=l.file_id WHERE l.school_id=$1 AND l.announcement_id=$2 AND f.status='READY' AND (f.expires_at IS NULL OR f.expires_at>now()) ORDER BY l.id LIMIT 101",[ctx.schoolId,row.id])).rows,100);
 const withdrawn=history?.filter(h=>(h.redacted_after as Row).status==='WITHDRAWN').at(-1);
 return {schoolId:ctx.schoolId,id:row.id,rootId:row.root_id,yearId:row.year_id,yearVersion:Number(year.version),classVersion:cls?Number(cls.version):null,origin:row.class_id?'class':'school',originClassId:row.class_id??null,className:cls?.name??null,title:row.title,summary:row.summary,body:announcementHtmlToBlocks(String(row.sanitized_html)),audience:String(row.audience).toLowerCase(),scope:selection,scopeLabel:kind==='MIXED'?selected.map(t=>({PUBLIC:'Công khai',SCHOOL:'Toàn trường',GRADE:'Khối được chỉ định',CLASS:'Lớp được chỉ định',STUDENT:'Học sinh được chỉ định',STAFF:'Nhân sự được chỉ định'})[t.kind]).filter((v,i,a)=>a.indexOf(v)===i).join(' · '):kind==='SCHOOL'?'Toàn trường':kind==='STUDENT'?labels.length?`Riêng: ${labels.join(', ')}`:`Riêng: ${selected.filter(t=>t.kind==='STUDENT').length} học sinh`:`${kind==='CLASS'?'Lớp ':'Khối '}${labels.join(', ')}`,audienceLabel:row.audience==='STAFF'?'Nội bộ nhân sự':row.audience==='FAMILIES'?'Gia đình học sinh':'Nhân sự và gia đình',isPublic:selected.some(t=>t.kind==='PUBLIC'),status:String(row.status).toLowerCase(),createdAt:iso(row.created_at as Date),updatedAt:iso(row.updated_at as Date),createdByName:author?.work_display_name??null,scheduledAt:row.scheduled_at?iso(row.scheduled_at as Date):null,publishedAt:pub&&pub.announcement_id===row.id?iso(pub.published_at as Date):null,withdrawnAt:withdrawn?iso(withdrawn.created_at as Date):null,withdrawReason:withdrawn?.reason??null,internalNote:canManage?row.internal_note??null:null,version:Number(row.version),source:source(row,pub),canEdit,canPublish,canViewInternal:canManage,canWithdraw:canPublish&&['PUBLISHED','SCHEDULED'].includes(String(row.status)),canDelete:canEdit&&row.status==='DRAFT',readOnly,scheduleState:view.scheduleState??null,scheduleErrorCode:view.scheduleErrorCode??null,estimate:canManage?await audienceEstimate(tx,ctx,String(row.year_id),selected,String(row.audience),row.class_id as string|undefined):null,attachmentIds:files.map(f=>f.id),attachments:files.map(f=>({id:f.id,version:f.version,name:f.original_name,mime:f.content_type,size:Number(f.byte_size),canDownload:ctx.can('file.read')})),historyView:history?.map(h=>({id:h.id,at:iso(h.created_at as Date),action:(h.redacted_after as Row).discarded?'Xóa bản nháp':(h.redacted_after as Row).status==='PUBLISHED'?'Công bố thông báo':(h.redacted_after as Row).status==='WITHDRAWN'?'Thu hồi thông báo':(h.redacted_after as Row).status==='SCHEDULED'?'Đặt lịch công bố':'Lưu bản nháp',byName:h.work_display_name??null,reason:h.reason??null}))??null};
}
export async function announcementWorkspace(db:Database,policy:Permissions,service:AnnouncementsService,c:RequestContext):Promise<Result>{return db.transaction(async tx=>{
 const schoolId=c.params.schoolId!,isCompose=c.operation.id==='getAnnouncementComposeWorkspace',isEstimate=c.operation.id==='estimateAnnouncementAudience',classId=isEstimate?(c.body.classId??undefined) as string|undefined:c.params.classId??c.query.classId,yearId=isEstimate?String(c.body.yearId):c.params.yearId??c.query.yearId,ctx=await access(tx,policy,c,classId,yearId);
 if(isCompose||isEstimate){
  const selectedClassId=isEstimate?c.body.classId as string|undefined:classId,chosenYearId=isEstimate?String(c.body.yearId):yearId;
  await policy.require(tx,c.principal!,'announcement.manage',{schoolId,classId:selectedClassId,yearId:chosenYearId});
  const cls=selectedClassId?await getResource(tx,resource('class'),schoolId,selectedClassId):undefined;
  const year=cls?await getResource(tx,resource('year'),schoolId,String(cls.year_id)):chosenYearId?await getResource(tx,resource('year'),schoolId,chosenYearId):await one<Row>(tx,"SELECT * FROM app.academic_years WHERE school_id=$1 AND status='ACTIVE' AND starts_on<=$2 AND ends_on>$2 ORDER BY starts_on DESC,id LIMIT 1",[schoolId,ctx.today]);if(!year)throw new Problem(409,'ACTIVE_YEAR_UNAVAILABLE');if(chosenYearId&&year.id!==chosenYearId)notFound();
  const scopeCtx=await access(tx,policy,c,selectedClassId,String(year.id));
  if(isEstimate){const selection=targets(c.body.scope as Row,c.body.isPublic===true),audience=String(c.body.audience).toUpperCase();await service.validateWorkspaceTargets(tx,scoped(c,selectedClassId),String(year.id),selectedClassId,selection,audience,ctx.today);return {data:{schoolId,yearId:year.id,classId:selectedClassId??null,scope:c.body.scope,audience:String(c.body.audience),isPublic:c.body.isPublic,counts:await audienceEstimate(tx,scopeCtx,String(year.id),selection,audience,selectedClassId)}};}
  const grades=cls?[]:bounded((await tx.query<Row>("SELECT id,name FROM app.grade_levels WHERE school_id=$1 AND status='ACTIVE' ORDER BY name COLLATE app.vi_names,id LIMIT 101",[schoolId])).rows,100),classes=bounded((await tx.query<Row>(`SELECT id,name,grade_level_id FROM app.classes WHERE school_id=$1 AND year_id=$2 AND status='ACTIVE'${cls?' AND id=$3':''} ORDER BY name COLLATE app.vi_names,id LIMIT 501`,cls?[schoolId,year.id,cls.id]:[schoolId,year.id])).rows,500);
  const students=cls&&scopeCtx.can('student.read')?bounded((await tx.query<Row>("SELECT s.id,s.full_name,s.student_code FROM app.enrollments e JOIN app.students s ON s.school_id=e.school_id AND s.id=e.student_id WHERE e.school_id=$1 AND e.class_id=$2 AND e.year_id=$3 AND e.status<>'CANCELLED' AND e.starts_on<=$4 AND (e.ends_on IS NULL OR e.ends_on>$4) ORDER BY s.full_name COLLATE app.vi_names,s.id LIMIT 5001",[schoolId,cls.id,year.id,ctx.today])).rows,5000):[];
  const files=scopeCtx.can('file.read')?await service.workspaceFiles(tx,scoped(c,selectedClassId),selectedClassId):[];
  const school=(await one<Row>(tx,'SELECT timezone FROM platform.schools WHERE id=$1',[schoolId]))!;
  return {data:{schoolId,yearId:year.id,classId:cls?.id??null,timezone:school.timezone,today:ctx.today,serverNow:new Date().toISOString(),yearVersion:Number(year.version),classVersion:cls?Number(cls.version):null,readOnly:year.status==='ARCHIVED'||cls?.status==='ARCHIVED',canPublish:scopeCtx.can('announcement.publish'),canSelectStudents:scopeCtx.can('student.read'),grades:grades.map(g=>({id:g.id,name:g.name})),classes:classes.map(cl=>({id:cl.id,name:cl.name,gradeId:cl.grade_level_id})),students:students.map(s=>({id:s.id,fullName:s.full_name,code:s.student_code})),files}};
 }
 const bound=scoped(c,classId),read=await service.readPredicate(tx,{...bound,operation:{...c.operation,id:classId?'listClassAnnouncements':'listSchoolAnnouncements'}});
 if(yearId)read.predicate={sql:`(${read.predicate.sql}) AND t.year_id=$${read.predicate.values.length+1}`,values:[...read.predicate.values,yearId]};
 if(c.operation.id==='getAnnouncementWorkspaceDetail'){
  const predicate=read.predicate,values=[schoolId,c.params.announcementId,...predicate.values],sql=predicate.sql.replace(/\$(\d+)/g,(_,n)=>'$'+(Number(n)+2));const row=await one<Row>(tx,`SELECT t.* FROM app.announcements t WHERE t.school_id=$1 AND t.id=$2 AND (${sql})`,values);if(!row)notFound();if(classId&&row.class_id!==classId||yearId&&row.year_id!==yearId)notFound();return {data:await project(tx,policy,bound,service,row,read)};
 }
 let predicate=read.predicate;if(c.query.origin)predicate={sql:`(${predicate.sql}) AND t.class_id IS ${c.query.origin==='class'?'NOT ':''}NULL`,values:predicate.values};
 const result=await listResource(tx,r,schoolId,{...c.query,...(c.query.status?{status:c.query.status.toUpperCase()}:{}),limit:c.query.limit??'25',sort:'updatedAt',dir:'desc'},predicate,c.principal!.userId);
 const projected=[];for(const row of result.data){const actual=await one<Row>(tx,'SELECT * FROM app.announcements WHERE school_id=$1 AND id=$2',[schoolId,row.id]);projected.push(await project(tx,policy,bound,service,actual!,read));}
 const countRows=(await tx.query<Row>(`SELECT t.status,count(*)::int AS n FROM app.announcements t WHERE t.school_id=$1 AND (${read.predicate.sql.replace(/\$(\d+)/g,(_,n)=>'$'+(Number(n)+1))}) GROUP BY t.status`,[schoolId,...read.predicate.values])).rows,counts=Object.fromEntries(['DRAFT','SCHEDULED','PUBLISHED','WITHDRAWN'].map(status=>[status.toLowerCase(),Number(countRows.find(r=>r.status===status)?.n??0)]));
 return {data:{schoolId,yearId:yearId??null,classId:classId??null,today:ctx.today,items:projected,counts,canCompose:ctx.can('announcement.manage')},page:result.page};
 },{schoolId:c.params.schoolId,userId:c.principal!.userId,readOnly:true});}

export async function announcementWorkspaceCommand(db:Database,policy:Permissions,commands:Commands,service:AnnouncementsService,c:RequestContext){
 const authorize=async(tx:Transaction)=>{const expected=c.body.source as Row|null,row=expected?await one<Row>(tx,'SELECT * FROM app.announcements WHERE school_id=$1 AND id=$2 AND discarded_at IS NULL',[c.params.schoolId,expected.id]):undefined;if(expected&&!row)notFound();const classId=(row?.class_id??c.body.classId) as string|undefined,yearId=String(row?.year_id??c.body.yearId),ctx=await access(tx,policy,c,classId,yearId);await policy.require(tx,c.principal!,['withdrawAnnouncementWorkspace','publishAnnouncementWorkspace'].includes(c.operation.id)?'announcement.publish':'announcement.manage',{schoolId:ctx.schoolId,classId,yearId});if(c.operation.id==='saveAnnouncementWorkspace'&&c.body.action!=='draft')await policy.require(tx,c.principal!,'announcement.publish',{schoolId:ctx.schoolId,classId,yearId});return {row,classId,yearId,ctx};};
 return commands.execute(c,authorize,async tx=>{
  const {row,classId,yearId,ctx}=await authorize(tx),pub=row?await publication(tx,ctx.schoolId,row.root_id):undefined;if(row&&canonical(c.body.source)!==canonical(source(row,pub)))throw new Problem(409,'ANNOUNCEMENT_SOURCE_CHANGED');
  if(row&&['saveAnnouncementWorkspace','publishAnnouncementWorkspace'].includes(c.operation.id)&&await one(tx,'SELECT id FROM app.announcements WHERE school_id=$1 AND root_id=$2 AND discarded_at IS NULL AND (created_at,id)>(SELECT a.created_at,a.id FROM app.announcements a WHERE a.school_id=$1 AND a.id=$3) LIMIT 1',[ctx.schoolId,row.root_id,row.id]))throw new Problem(409,'ANNOUNCEMENT_SOURCE_CHANGED');
  const cls=classId?await getResource(tx,resource('class'),ctx.schoolId,classId):undefined,year=await getResource(tx,resource('year'),ctx.schoolId,yearId);if(year.status==='ARCHIVED'||cls?.status==='ARCHIVED')throw new Problem(409,'YEAR_ARCHIVED');
  let request=scoped(c,classId);const prefix=classId?'Class':'School';
  if(c.operation.id==='publishAnnouncementWorkspace'){
   if(!row)notFound();await service.applyInTransaction(tx,native(request,`publish${prefix}Announcement`,'announcement.publish',{expectedSourceVersion:row.data_version,expectedPublicationId:pub?.id??null},String(row.id)));const current=(await one<Row>(tx,'SELECT * FROM app.announcements WHERE school_id=$1 AND id=$2',[ctx.schoolId,row.id]))!;return {data:{id:current.id,rootId:current.root_id,status:'published',source:source(current,await publication(tx,ctx.schoolId,current.root_id))}};
  }
  if(c.operation.id!=='saveAnnouncementWorkspace'){
   if(!row)notFound();const id=c.operation.id==='discardAnnouncementWorkspace'?`update${prefix}Announcement`:`withdraw${prefix}Announcement`,body=c.operation.id==='discardAnnouncementWorkspace'?{expectedVersion:row.version,discard:true}:{expectedVersion:row.version,reason:c.body.reason};await service.applyInTransaction(tx,native(request,id,c.operation.id==='discardAnnouncementWorkspace'?'announcement.manage':'announcement.publish',body,String(row.id)));return {data:{id:row.id,rootId:row.root_id,status:c.operation.id==='discardAnnouncementWorkspace'?'discarded':'withdrawn',source:null}};
  }
  if(c.body.yearId!==yearId||(c.body.classId??null)!==(classId??null))validation('source','Nguồn thông báo không khớp lớp/năm');if(c.body.expectedYearVersion!==year.version||c.body.expectedClassVersion!==(cls?.version??null))throw new Problem(409,'VERSION_CONFLICT');
  const title=String(c.body.title).trim(),summary=String(c.body.summary).trim();if(title.length<5)validation('title','Tiêu đề tối thiểu 5 ký tự');if(summary.length<10)validation('summary','Tóm tắt tối thiểu 10 ký tự');
  const selection=targets(c.body.scope as Row,c.body.isPublic===true),audience=String(c.body.audience).toUpperCase();if(classId&&audience!=='FAMILIES')validation('audience','Thông báo lớp gửi gia đình học sinh');
  const body={yearId,title,summary,sanitizedHtml:blocksToAnnouncementHtml(c.body.body as AnnouncementBlock[]),targets:selection,audience,fileIds:c.body.attachmentIds,internalNote:c.body.internalNote??'',...(row?{expectedVersion:row.version}:{})};
  const saved=await service.applyInTransaction(tx,native(request,`${row?'update':'create'}${prefix}Announcement`,'announcement.manage',body,row?String(row.id):undefined));let current=await one<Row>(tx,'SELECT * FROM app.announcements WHERE school_id=$1 AND id=$2',[ctx.schoolId,(saved.data as Row).id]);
  request=scoped(request,classId,String(current!.id));if(c.body.action==='publish')await service.applyInTransaction(tx,native(request,`publish${prefix}Announcement`,'announcement.publish',{expectedSourceVersion:current!.data_version,expectedPublicationId:pub?.id??null},String(current!.id)));
  if(c.body.action==='schedule')await service.applyInTransaction(tx,native(request,`schedule${prefix}Announcement`,'announcement.publish',{expectedVersion:current!.version,scheduledAt:c.body.scheduledAt},String(current!.id)));
  current=await one<Row>(tx,'SELECT * FROM app.announcements WHERE school_id=$1 AND id=$2',[ctx.schoolId,current!.id]);return {data:{id:current!.id,rootId:current!.root_id,status:String(current!.status).toLowerCase(),source:source(current!,await publication(tx,ctx.schoolId,current!.root_id))}};
 });
}
