/** Connected application facade. Legacy modules contribute compile-time interfaces only. */
import {apiRepository} from './connected/facade';
import {connectedSessionRepo} from './connected/session';
import {connectedPlatformRepo} from './connected/platform';
import {connectedSchoolRepo} from './connected/school';
import {connectedStaffRepo} from './connected/staff';
import {connectedSupportRepo} from './connected/support';

import {connectedPlatformExtraRepo} from './connected/platform';
import {connectedAuthRepo} from './connected/auth';

export const sessionRepo=apiRepository<typeof import('./session').sessionRepo,typeof connectedSessionRepo>(connectedSessionRepo);
export const platformRepo=apiRepository<typeof import('./platform').platformRepo,typeof connectedPlatformRepo>(connectedPlatformRepo);
export const schoolRepo=apiRepository<typeof import('./school').schoolRepo,typeof connectedSchoolRepo>(connectedSchoolRepo);
export const staffRepo=apiRepository<typeof import('./staff').staffRepo,typeof connectedStaffRepo>(connectedStaffRepo);
export const studentsRepo=apiRepository<typeof import('./students').studentsRepo,object>({});
export const supportRepo=apiRepository<typeof import('./support').supportRepo,typeof connectedSupportRepo>(connectedSupportRepo);
export const platformExtraRepo=apiRepository<typeof import('./platform-extra').platformExtraRepo,typeof connectedPlatformExtraRepo>(connectedPlatformExtraRepo);
export const authDemoRepo=apiRepository<typeof import('./platform-extra').authDemoRepo,typeof connectedAuthRepo>(connectedAuthRepo);
export const studentsExtraRepo=apiRepository<typeof import('./students-extra').studentsExtraRepo,object>({});
export const classroomRepo=apiRepository<typeof import('./classroom').classroomRepo,object>({});
export const attendanceRepo=apiRepository<typeof import('./attendance').attendanceRepo,object>({});
export const conductRepo=apiRepository<typeof import('./conduct').conductRepo,object>({});
export const activitiesRepo=apiRepository<typeof import('./activities').activitiesRepo,object>({});
export const announcementsRepo=apiRepository<typeof import('./announcements').announcementsRepo,object>({});
export const reportsRepo=apiRepository<typeof import('./reports').reportsRepo,object>({});
export const parentRepo=apiRepository<typeof import('./parent').parentRepo,object>({});
export const searchRepo=apiRepository<typeof import('./search').searchRepo,object>({});
export const teacherExtraRepo=apiRepository<typeof import('./teacher-extra').teacherExtraRepo,object>({});
export const schoolOpsRepo=apiRepository<typeof import('./school-ops-extra').schoolOpsRepo,object>({});
export const schoolOrgRepo=apiRepository<typeof import('./school-org-extra').schoolOrgRepo,object>({});
export const parentExtraRepo=apiRepository<typeof import('./parent-extra').parentExtraRepo,object>({});
export const activitiesExtraRepo=apiRepository<typeof import('./activities-extra').activitiesExtraRepo,object>({});
export {accessStatus,UPLOAD_LIMITS,SCHOOL_REPORTS,CLASS_REPORTS,SUPPORT_SCOPE_LABEL,PASSWORD_RULES,passwordErrors} from './connected/statics';
export type {ReportData} from './reports';
export type {ParentKey} from './parent';
export type {SearchHit} from './search';
export {RepoError,isRepoError,errorMessage,type RepoErrorCode} from './errors';
export type {Ctx,ListQuery,Page} from './core';
export {makeConnectedCtx as makeCtx} from '../api/context';
export {unavailableBlob as getBlob} from './connected/statics';
export type {ServiceState} from './platform-extra';
export type {ImportKind,ImportKindInfo} from './students-extra';
