/** Connected application facade. Legacy modules contribute compile-time interfaces only. */
import {apiRepository} from './connected/facade';
import {connectedSessionRepo} from './connected/session';
import {connectedPlatformRepo} from './connected/platform';
import {connectedSchoolRepo} from './connected/school';
import {connectedStaffRepo} from './connected/staff';
import {connectedSupportRepo} from './connected/support';
import {connectedStudentsRepo} from './connected/students';
import {connectedStudentsExtraRepo} from './connected/students-extra';
import {connectedAttendanceRepo} from './connected/attendance';
import {connectedConductRepo,connectedConductStatics} from './connected/conduct';
import {connectedConductWorkspaceRepo} from './connected/conduct-workspace';
import {connectedConductAdjustmentsRepo} from './connected/conduct-adjustments';
import {connectedConductSchoolRepo} from './connected/conduct-school';
import {connectedAnnouncementsRepo} from './connected/announcements';
import {connectedPublicAnnouncementsRepo} from './connected/public-announcements';
import {connectedSchoolOpsRepo} from './connected/school-ops';
import {connectedClassroomRepo,connectedTeacherExtraRepo} from './connected/classroom';
import {connectedTeacherWorkspaceRepo} from './connected/teacher-workspace';
import {connectedScheduleClassroomRepo,connectedScheduleSchoolOpsRepo} from './connected/schedule';
import {connectedActivitiesRepo,connectedActivitiesExtraRepo} from './connected/activities';
import {connectedReportsRepo,connectedClassReportCatalogRepo,connectedStudentExportRepo} from './connected/reports';
import {connectedTransfersRepo} from './connected/transfers';
import {connectedImportsRepo} from './connected/imports';
import {connectedSearchRepo} from './connected/search';
import {connectedParentRepo,connectedParentExtraRepo,type ParentRepositoryInterface} from './connected/parent';

import {connectedPlatformExtraRepo} from './connected/platform';
import {connectedAuthRepo} from './connected/auth';
import {connectedPublicSystemRepo} from './connected/public-system';

export const sessionRepo=apiRepository<typeof import('./session').sessionRepo,typeof connectedSessionRepo>(connectedSessionRepo);
export const platformRepo=apiRepository<typeof import('./platform').platformRepo,typeof connectedPlatformRepo>(connectedPlatformRepo);
export const schoolRepo=apiRepository<typeof import('./school').schoolRepo,typeof connectedSchoolRepo>(connectedSchoolRepo);
export const staffRepo=apiRepository<typeof import('./staff').staffRepo,typeof connectedStaffRepo>(connectedStaffRepo);
export const studentsRepo=apiRepository<typeof import('./students').studentsRepo,typeof connectedStudentsRepo & typeof connectedImportsRepo & Omit<typeof connectedTransfersRepo,'studentOptions'>>({...connectedStudentsRepo,...connectedImportsRepo,...connectedTransfersRepo});
export const supportRepo=apiRepository<typeof import('./support').supportRepo,typeof connectedSupportRepo>(connectedSupportRepo);
export const platformExtraRepo=apiRepository<typeof import('./platform-extra').platformExtraRepo,typeof connectedPlatformExtraRepo>(connectedPlatformExtraRepo);
export const authDemoRepo=apiRepository<typeof import('./platform-extra').authDemoRepo,typeof connectedAuthRepo & typeof connectedPublicSystemRepo>({...connectedAuthRepo,...connectedPublicSystemRepo});
export const studentsExtraRepo=apiRepository<typeof import('./students-extra').studentsExtraRepo,typeof connectedStudentsExtraRepo & typeof connectedStudentExportRepo & Pick<typeof connectedImportsRepo,'importKinds'> & Pick<typeof connectedTransfersRepo,'studentOptions'>>({...connectedStudentsExtraRepo,...connectedStudentExportRepo,importKinds:connectedImportsRepo.importKinds,studentOptions:connectedTransfersRepo.studentOptions});
export const classroomRepo=apiRepository<typeof import('./classroom').classroomRepo,typeof connectedClassroomRepo & typeof connectedTeacherWorkspaceRepo & typeof connectedScheduleClassroomRepo>({...connectedClassroomRepo,...connectedTeacherWorkspaceRepo,...connectedScheduleClassroomRepo});
export const attendanceRepo=apiRepository<typeof import('./attendance').attendanceRepo,typeof connectedAttendanceRepo>(connectedAttendanceRepo);
export const conductRepo=apiRepository<typeof import('./conduct').conductRepo,typeof connectedConductRepo & typeof connectedConductStatics & typeof connectedConductWorkspaceRepo & typeof connectedConductAdjustmentsRepo & typeof connectedConductSchoolRepo>({...connectedConductRepo,...connectedConductStatics,...connectedConductWorkspaceRepo,...connectedConductAdjustmentsRepo,...connectedConductSchoolRepo});
export const activitiesRepo=apiRepository<typeof import('./activities').activitiesRepo,typeof connectedActivitiesRepo>(connectedActivitiesRepo);
export const announcementsRepo=apiRepository<typeof import('./announcements').announcementsRepo,typeof connectedAnnouncementsRepo & typeof connectedPublicAnnouncementsRepo>({...connectedAnnouncementsRepo,...connectedPublicAnnouncementsRepo});
export const reportsRepo=apiRepository<typeof import('./reports').reportsRepo,typeof connectedReportsRepo>(connectedReportsRepo);
export const parentRepo=apiRepository<ParentRepositoryInterface,typeof connectedParentRepo>(connectedParentRepo);
export const searchRepo=apiRepository<typeof import('./search').searchRepo,typeof connectedSearchRepo>(connectedSearchRepo);
export const teacherExtraRepo=apiRepository<typeof import('./teacher-extra').teacherExtraRepo,typeof connectedTeacherExtraRepo>(connectedTeacherExtraRepo);
export const schoolOpsRepo=apiRepository<typeof import('./school-ops-extra').schoolOpsRepo,typeof connectedSchoolOpsRepo & typeof connectedScheduleSchoolOpsRepo>({...connectedSchoolOpsRepo,...connectedScheduleSchoolOpsRepo});
export const schoolOrgRepo=apiRepository<typeof import('./school-org-extra').schoolOrgRepo,object>({});
export const parentExtraRepo=apiRepository<{grantedYear:typeof connectedParentExtraRepo.grantedYear},typeof connectedParentExtraRepo>(connectedParentExtraRepo);
export const activitiesExtraRepo=apiRepository<typeof import('./activities-extra').activitiesExtraRepo,typeof connectedActivitiesExtraRepo & typeof connectedClassReportCatalogRepo>({...connectedActivitiesExtraRepo,...connectedClassReportCatalogRepo});
export {accessStatus,UPLOAD_LIMITS,SCHOOL_REPORTS,CLASS_REPORTS,SUPPORT_SCOPE_LABEL,PASSWORD_RULES,passwordErrors} from './connected/statics';
export type {ReportData} from './reports';
export type {ParentKey} from './connected/parent';
export type {SearchHit} from './search';
export {RepoError,isRepoError,errorMessage,type RepoErrorCode} from './errors';
export type {Ctx,ListQuery,Page} from './core';
export {makeConnectedCtx as makeCtx} from '../api/context';
export {getOwnedBlob as getBlob} from '../api/owned-blobs';
export type {ServiceState} from './platform-extra';
export type {ImportKind,ImportKindInfo} from './students-extra';
