"use client";
import {useMemo,useState} from 'react';
import {permissionPresets} from '@/lib/api/generated';
import {TextField,Checkbox} from '@/components/ui/form';
import {Button} from '@/components/ui/button';

export interface PermissionEntry {action:string;key:string;label:string;group:string;allowedScopes:readonly string[];canGrant:boolean}
export const SCOPE_LABEL:Record<string,string>={SCHOOL:'Trường',CLASS:'Lớp',SUBJECT:'Môn'};
export function PermissionEditor({catalog,selected,onChange,disabled,preferredScope='CLASS'}:{catalog:PermissionEntry[];selected:Set<string>;onChange:(value:Set<string>)=>void;disabled:boolean;preferredScope?:string}){
 const [search,setSearch]=useState('');
 const groups=useMemo(()=>{const found=catalog.filter(p=>`${p.label} ${p.group} ${p.action}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))),result=new Map<string,PermissionEntry[]>();for(const p of found)result.set(p.group,[...(result.get(p.group)??[]),p]);return [...result];},[catalog,search]);
 const selectGroup=(items:PermissionEntry[],enabled:boolean)=>{const next=new Set(selected);for(const p of items)for(const scope of p.allowedScopes){const key=p.action+'|'+scope;if(!enabled)next.delete(key);else if(p.canGrant&&scope===(p.allowedScopes.includes(preferredScope)?preferredScope:'SCHOOL'))next.add(key);}onChange(next);};
 return <div className="space-y-4"><p className="text-sm">{new Set([...selected].map(k=>k.split('|')[0])).size}/{catalog.length} quyền đang bật</p><TextField label="Tìm quyền..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="flex flex-wrap gap-2" role="group" aria-label="Preset quyền giáo viên">{permissionPresets.map(p=><Button key={p.id} size="sm" disabled={disabled} onClick={()=>onChange(new Set(p.permissions.flatMap(item=>catalog.find(c=>c.action===item.action&&c.canGrant)?item.scopes.map(s=>item.action+'|'+s):[])))}>{p.label}</Button>)}</div>{groups.map(([group,items])=><fieldset key={group} className="rounded-xl border border-line p-4"><legend className="px-1 text-[14px] font-bold">{group}</legend><div className="mb-3 flex flex-wrap gap-2"><Button size="sm" disabled={disabled} onClick={()=>selectGroup(items,true)} aria-label={`Chọn tất cả nhóm ${group}`}>Chọn tất cả nhóm</Button><Button size="sm" disabled={disabled} onClick={()=>selectGroup(items,false)} aria-label={`Bỏ tất cả nhóm ${group}`}>Bỏ tất cả nhóm</Button></div><div className="grid gap-2.5 sm:grid-cols-2">{items.map(p=><div key={p.action} data-permission-action={p.action} className="rounded-lg border border-line p-2.5"><p className="mb-1.5 text-[13px] font-semibold">{p.label}</p><div className="flex flex-wrap gap-2">{p.allowedScopes.map(scope=>{const key=p.action+'|'+scope,checked=selected.has(key);return <Checkbox key={scope} label={SCOPE_LABEL[scope]} checked={checked} disabled={disabled||!checked&&!p.canGrant} description={!p.canGrant?'Bạn không thể cấp quyền này':undefined} onChange={on=>{const next=new Set(selected);if(on)next.add(key);else next.delete(key);onChange(next);}}/>;})}</div></div>)}</div></fieldset>)}{!groups.length&&<p>Không có quyền khớp từ khóa.</p>}</div>;
}
