"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {useQueryClient} from '@tanstack/react-query';
import {staffRepo} from '@/lib/repositories';
import {useCommand,useRepo} from '@/lib/query/hooks';
import {refreshFormOptions} from '@/lib/query/form-options';
import {Modal} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {TextField,TextArea,SelectField,RadioGroup} from '@/components/ui/form';
import {Callout} from '@/components/ui/card';
import {PickerState} from '@/features/forms/picker-state';
import type {ApiSchemas} from '@/lib/api/generated';

export function CloneProfileDialog({schoolId,roleId,name,onClose}:{schoolId:string;roleId:string;name:string;onClose:()=>void}){
 const router=useRouter(),client=useQueryClient(),[code,setCode]=useState(''),[label,setLabel]=useState(name+' — tùy chỉnh'),[reason,setReason]=useState(''),[error,setError]=useState('');
 const cmd=useCommand((ctx)=>staffRepo.cloneRole(ctx,schoolId,roleId,{code:code.trim(),label:label.trim(),reason:reason.trim()}),{success:'Đã sao chép mẫu quyền',onError:e=>setError(e.message)});
 return <Modal open onOpenChange={v=>{if(!v)onClose();}} title="Sao chép & tùy chỉnh" busy={cmd.pending} footer={<><Button onClick={onClose} disabled={cmd.pending}>Hủy</Button><Button variant="primary" loading={cmd.pending} onClick={async()=>{const value=await cmd.run();if(value){await refreshFormOptions(client,schoolId);router.push(`/school/${schoolId}/roles/${value.id}`);onClose();}}}>Sao chép</Button></>}><div className="space-y-4"><Callout tone="info">Bản sao giữ nguyên từng quyền và phạm vi. Bạn có thể chỉnh bản sao; mẫu gốc được giữ nguyên.</Callout><TextField label="Mã mẫu tùy chỉnh" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} helper="3–64 ký tự: chữ in hoa, số, dấu gạch dưới" required/><TextField label="Tên mẫu quyền" value={label} onChange={e=>setLabel(e.target.value)} required/><TextArea label="Lý do thay đổi" value={reason} onChange={e=>setReason(e.target.value)} required/>{error&&<p role="alert" className="error-text">{error}</p>}</div></Modal>;
}
export function AssignmentProfileDialog({schoolId,assignment,onClose}:{schoolId:string;assignment:{id:string;version:number;roleId:string;kind:'HOMEROOM'|'SUBJECT';className:string;startsOn:string;endsOn:string|null};onClose:()=>void}){
 const client=useQueryClient(),q=useRepo(['teacher-permission-profiles',schoolId],ctx=>staffRepo.permissionProfiles(ctx,schoolId)),[roleId,setRole]=useState(assignment.roleId),[reason,setReason]=useState(''),[review,setReview]=useState<ApiSchemas['AssignmentProfilePreview']>(),[error,setError]=useState('');
 const input={expectedVersion:assignment.version,roleId,reason:reason.trim()},scope=assignment.kind==='HOMEROOM'?'CLASS':'SUBJECT';
 const preview=useCommand(ctx=>staffRepo.previewProfile(ctx,schoolId,assignment.id,input),{success:false,onError:e=>setError(e.message)}),save=useCommand(ctx=>staffRepo.changeProfile(ctx,schoolId,assignment.id,input),{success:'Đã đổi mẫu quyền phân công — quyền mới được áp dụng ở lần đọc/ghi kế tiếp',onError:e=>setError(e.message)});
 return <Modal open onOpenChange={v=>{if(!v)onClose();}} title={`Đổi mẫu quyền — ${assignment.className}`} busy={preview.pending||save.pending} footer={<><Button onClick={onClose} disabled={preview.pending||save.pending}>Hủy</Button><Button variant="primary" loading={preview.pending||save.pending} disabled={roleId===assignment.roleId||!q.data||reason.trim().length<5} onClick={async()=>{if(!review){setReview(await preview.run());return;}const v=await save.run();if(v){await refreshFormOptions(client,schoolId);onClose();}}}>{review?'Xác nhận đổi mẫu quyền':'Xem thay đổi trước / sau'}</Button></>}><div className="space-y-4"><PickerState query={q}/><SelectField label="Mẫu quyền phân công" value={roleId} onChange={e=>{setRole(e.target.value);setReview(undefined);}} options={(q.data?.roles??[]).filter(r=>r.code!=='SCHOOL_ADMIN'&&r.permissions.some(p=>p.scopes.includes(scope))).map(r=>({value:r.id!,label:r.label}))}/><TextArea label="Lý do thay đổi" required value={reason} onChange={e=>{setReason(e.target.value);setReview(undefined);}} helper="Tối thiểu 5 ký tự. Lý do được lưu trong nhật ký."/><p>Phạm vi: {assignment.className} · {assignment.startsOn} đến trước {assignment.endsOn??'khi thu hồi'}</p>{review&&<Callout tone="warning" title={`Sẽ thêm ${review.added.length} quyền · bỏ ${review.removed.length} quyền`}><PermissionDiff added={review.added} removed={review.removed} catalog={q.data?.catalog??[]}/></Callout>}{error&&<p role="alert" className="error-text">{error}</p>}</div></Modal>;
}
export function DefaultProfileDialog({schoolId,roleId,name,kind,onClose}:{schoolId:string;roleId:string;name:string;kind:'HOMEROOM'|'SUBJECT';onClose:()=>void}){
 const client=useQueryClient(),q=useRepo(['teacher-permission-profiles',schoolId],ctx=>staffRepo.permissionProfiles(ctx,schoolId)),[apply,setApply]=useState('new'),[reason,setReason]=useState(''),[review,setReview]=useState<ApiSchemas['DefaultTeacherProfilePreview']>(),[error,setError]=useState('');
 const input={expectedVersion:q.data?.version??0,kind,roleId,applyCurrent:apply==='current',reason:reason.trim()};
 const preview=useCommand(ctx=>staffRepo.previewDefaultProfile(ctx,schoolId,input),{success:false,onError:e=>setError(e.message)}),save=useCommand(ctx=>staffRepo.setDefaultProfile(ctx,schoolId,input),{success:'Đã đặt mẫu quyền mặc định',onError:e=>setError(e.message)});
 return <Modal open onOpenChange={v=>{if(!v)onClose();}} title={`Đặt mặc định ${kind==='HOMEROOM'?'GVCN':'GVBM'}`} busy={preview.pending||save.pending} footer={<><Button onClick={onClose} disabled={preview.pending||save.pending}>Hủy</Button><Button variant="primary" loading={preview.pending||save.pending} disabled={!q.data||reason.trim().length<5} onClick={async()=>{if(!review){setReview(await preview.run());return;}if(await save.run()){await refreshFormOptions(client,schoolId);onClose();}}}>{review?'Xác nhận áp dụng':'Xem số phân công bị ảnh hưởng'}</Button></>}><div className="space-y-4"><PickerState query={q}/><p>Mẫu quyền: <strong>{name}</strong></p><RadioGroup label="Áp dụng" value={apply} onChange={v=>{setApply(v);setReview(undefined);}} options={[{value:'new',label:'Chỉ áp dụng cho phân công mới'},{value:'current',label:'Áp dụng cho các phân công đang có hiệu lực'}]}/><TextArea label="Lý do thay đổi" required value={reason} onChange={e=>{setReason(e.target.value);setReview(undefined);}}/>{review&&<Callout tone="warning">{review.affected} phân công đang có hiệu lực sẽ đổi mẫu quyền. Các phân công mới dùng {name}. Giữ nguyên giáo viên, lớp/môn và ngày phân công.</Callout>}{error&&<p role="alert" className="error-text">{error}</p>}</div></Modal>;
}
function PermissionDiff({added,removed,catalog}:{added:string[];removed:string[];catalog:{action:string;label:string}[]}){return <ul>{[...added.map(action=>({action,label:'Thêm'})),...removed.map(action=>({action,label:'Bỏ'}))].map(p=><li key={p.label+p.action}>{p.label}: {catalog.find(a=>a.action===p.action)?.label??'Quyền khác'}</li>)}</ul>;}
