import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import type {ApiSchemas} from '@/lib/api/generated';
import type {Ctx} from '@/lib/repositories/core';
import {authenticationChanged,authorizationChanged,captureStaffAccess,setStaffCsrf} from '@/lib/api/client';
import {connectedClassroomRepo,connectedTeacherExtraRepo} from '@/lib/repositories/connected/classroom';
import {nativeClassRoster,nativeClassTransferOptions} from '@/lib/repositories/connected/classroom-roster';
const schoolId='7a000000-0000-4000-8000-000000000001',yearId='7a000000-0000-4000-8000-000000000002',classId='7a000000-0000-4000-8000-000000000003',studentId='7a000000-0000-4000-8000-000000000004',enrollmentId='7a000000-0000-4000-8000-000000000005',groupId='7a000000-0000-4000-8000-000000000006',targetId='7a000000-0000-4000-8000-000000000007';
const roster=():ApiSchemas['ClassRosterWorkspace']=>({schoolId,yearId,classId,today:'2026-10-01',referenceDate:'2026-10-01',classVersion:3,readOnly:false,seeGuardians:true,seeLinks:true,canAdd:false,canTransfer:true,canGroups:true,canReadGroups:true,canSeating:false,groups:[{id:groupId,name:'Tổ API'}],total:2,rows:[{id:studentId,studentCode:'API001',fullName:'Học sinh roster API',gender:null,enrollmentId,enrollmentVersion:5,startsOn:'2026-09-01',ordinal:2,groupId,groupName:'Tổ API',positions:['Lớp trưởng'],transferredIn:true,currentEnrollment:true,guardian:{name:'Giám hộ riêng API',relation:'Mẹ',verification:'VERIFIED'},linkStatus:'opened'}],leftRecently:[{id:targetId,enrollmentId:targetId,fullName:'Học sinh đã rời API',studentCode:'API002',endsOn:'2026-09-30',reason:null}],linkSummary:{total:2,withLink:1,opened:1}});
const choices=():ApiSchemas['ClassTransferOptions']=>({schoolId,yearId,classId,today:'2026-10-01',referenceDate:'2026-10-01',startsOn:'2026-09-01',endsOn:'2027-06-01',students:[{id:studentId,fullName:'Học sinh roster API',studentCode:'API001',enrollmentId,enrollmentVersion:5,startsOn:'2026-09-01',endsOn:null}],targets:[{id:targetId,name:'Lớp nhận API',size:8,capacity:null}]});
const ctx=():Ctx=>({actor:{kind:'staff',userId:targetId},today:'2026-10-01',now:'2026-10-01T01:00:00Z',staffOwner:captureStaffAccess()});
const response=(data:unknown)=>new Response(JSON.stringify({data,requestId:'roster-unit'}),{headers:{'Content-Type':'application/json'}});
beforeEach(()=>{authenticationChanged();setStaffCsrf('roster-unit-csrf');});afterEach(()=>vi.unstubAllGlobals());
it('maps actual filtered roster ordinals nullable gender and independently denied historical family and organization panels',()=>{
 const v=roster(),r=nativeClassRoster(v,schoolId,yearId,classId);expect(r.total).toBe(2);expect(r.rows[0]).toMatchObject({code:'API001',enrollmentVersion:5,ordinal:2,gender:null,link:'opened'});expect(r.leftRecently[0]).toMatchObject({endDate:'2026-09-30',reason:undefined});
 const hidden={...v,seeGuardians:false,seeLinks:false,canGroups:false,canReadGroups:false,canTransfer:false,linkSummary:null,rows:[{...v.rows[0],guardian:null,linkStatus:null}]};expect(nativeClassRoster(hidden,schoolId,yearId,classId).rows[0].guardian).toBeUndefined();
 const historical={...v,rows:[{...v.rows[0],currentEnrollment:false,guardian:null,linkStatus:null}]};expect(nativeClassRoster(historical,schoolId,yearId,classId).rows[0].link).toBeUndefined();
});
it('rejects private foreign duplicate contradictory or incomplete roster sources and mismatched group or history identifiers',()=>{
 const v=roster();for(const bad of [{...v,phone:'PRIVATE'},{...v,yearId:targetId},{...v,seeGuardians:false},{...v,seeLinks:false},{...v,canReadGroups:false},{...v,readOnly:true},{...v,rows:[...v.rows,...v.rows]},{...v,total:0},{...v,rows:[{...v.rows[0],groupName:'Không khớp'}]},{...v,rows:[{...v.rows[0],guardian:{...v.rows[0].guardian,phone:'PRIVATE'}}]},{...v,rows:[{...v.rows[0],currentEnrollment:false}]},{...v,leftRecently:[{...v.leftRecently[0],endsOn:'2026-10-02'}]},{...v,linkSummary:{total:1,withLink:1,opened:2}}])expect(()=>nativeClassRoster(bad as ApiSchemas['ClassRosterWorkspace'],schoolId,yearId,classId)).toThrow();
});
it('requests only the exact class purpose with server filters and never converts an outage or denied source into an empty roster',async()=>{
 const requests:URL[]=[];vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{requests.push(new URL(String(input),'http://localhost'));return response(roster());}));const r=await connectedClassroomRepo.roster(ctx(),schoolId,yearId,classId,{q:'Đặng %_',groupId:'none'});expect(r.rows).toHaveLength(1);expect(requests).toHaveLength(1);expect(requests[0].pathname).toContain(`/academic-years/${yearId}/classes/${classId}/roster-workspace`);expect(requests[0].searchParams.get('q')).toBe('Đặng %_');expect(requests[0].searchParams.get('groupId')).toBe('none');
 vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({status:503,code:'DATABASE_UNAVAILABLE',requestId:'roster-unit'}),{status:503,headers:{'Content-Type':'application/problem+json'}})));await expect(connectedClassroomRepo.roster(ctx(),schoolId,yearId,classId)).rejects.toThrow();
});
it('validates dated transfer sources without target pupil directories invented capacities or foreign class choices',()=>{
 const v=choices();expect(nativeClassTransferOptions(v,schoolId,yearId,classId).targets[0].capacity).toBeNull();for(const bad of [{...v,classId:targetId},{...v,referenceDate:'2026-09-30'},{...v,targets:[{...v.targets[0],id:classId}]},{...v,students:[{...v.students[0],enrollmentVersion:0}]},{...v,targets:[...v.targets,...v.targets]},{...v,students:[{...v.students[0],guardianPhone:'PRIVATE'}]}])expect(()=>nativeClassTransferOptions(bad as ApiSchemas['ClassTransferOptions'],schoolId,yearId,classId)).toThrow();expect(()=>nativeClassTransferOptions(v,schoolId,yearId,classId,'2026-10-02')).toThrow();
});
it('sends one concrete request with displayed enrollment version and requires a matching submitted receipt without applying a transfer',async()=>{
 const received:Record<string,unknown>[]=[];vi.stubGlobal('fetch',vi.fn(async(_url:RequestInfo|URL,options?:RequestInit)=>{const body=JSON.parse(String(options?.body));received.push(body);return response({id:targetId,version:1,createdAt:'2026-10-01T01:00:00Z',updatedAt:'2026-10-01T01:00:00Z',studentId,fromEnrollmentId:enrollmentId,toClassId:targetId,effectiveOn:'2026-10-02',reason:body.reason,status:'SUBMITTED'});}));
 await connectedClassroomRepo.requestTransfer(ctx(),schoolId,{studentId,enrollmentId,expectedEnrollmentVersion:5,kind:'transfer',toClassId:targetId,effectiveDate:'2026-10-02',reason:'Đề nghị chuyển lớp thật'});expect(received).toEqual([{studentId,fromEnrollmentId:enrollmentId,expectedEnrollmentVersion:5,toClassId:targetId,effectiveOn:'2026-10-02',reason:'Đề nghị chuyển lớp thật'}]);
});
it('binds transfer choices and pending responses to current authorization and rejects a contradictory successful receipt',async()=>{
 let resolve!:(r:Response)=>void;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(done=>{resolve=done;})));const request=connectedTeacherExtraRepo.transferTargets(ctx(),schoolId,yearId,classId);await vi.waitFor(()=>expect(resolve).toBeTypeOf('function'));authorizationChanged();resolve(response(choices()));await expect(request).rejects.toThrow();
 vi.stubGlobal('fetch',vi.fn(async()=>response({id:targetId,version:1,createdAt:'2026-10-01T01:00:00Z',updatedAt:'2026-10-01T01:00:00Z',studentId,fromEnrollmentId:enrollmentId,toClassId:null,effectiveOn:'2026-10-02',reason:'Đề nghị chuyển lớp thật',status:'APPLIED'})));await expect(connectedClassroomRepo.requestTransfer(ctx(),schoolId,{studentId,enrollmentId,expectedEnrollmentVersion:5,kind:'transfer',toClassId:targetId,effectiveDate:'2026-10-02',reason:'Đề nghị chuyển lớp thật'})).rejects.toThrow();
});
