import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {connectedParentRepo as repo} from '@/lib/repositories/connected/parent';
import {nativeParentConduct,nativeParentConductDirectory} from '@/lib/repositories/connected/parent-conduct';
import {nativeParentContext} from '@/lib/repositories/connected/parent-context';
import {beginParentExchange,clearParentSession,readParentView} from '@/lib/api/parent-session';
import {authenticationChanged,authorizationChanged,captureStaffAccess} from '@/lib/api/client';
import type {ApiSchemas} from '@/lib/api/generated';
import type {Ctx} from '@/lib/repositories/core';
const slug='parent-conduct-unit',viewId='6f000000-0000-4000-8000-000000000001',id='6f000000-0000-4000-8000-000000000002',other='6f000000-0000-4000-8000-000000000003',schoolId='6f000000-0000-4000-8000-000000000004',accessId='6f000000-0000-4000-8000-000000000005',at='2026-10-01T01:00:00Z';
const context=():ApiSchemas['ParentContext']=>({viewId,school:{name:'Trường API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con API',classLabel:'Lớp hiện tại khác bản công bố',schoolYearLabel:'2026–2027'},allowedSections:['conduct'],allowDownload:false,csrfToken:'conduct-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const conduct=():ApiSchemas['ParentSharedConduct']=>({periodId:id,periodLabel:'Tuần nguồn 5',revision:2,basePoints:'80.10',bonusPoints:'0.20',penaltyPoints:'-1.25',finalPoints:'79.05',classification:'Xếp loại nguồn',lines:[{label:'Ghi nhận công khai',delta:'-1.25',occurredAt:'2026-09-29T17:30:00Z',reason:'Lý do được chia sẻ',date:'2026-09-30'}],publishedAt:at,adjusted:true,weekNumber:5,startsOn:'2026-09-28',endsOn:'2026-10-05',classLabel:'Lớp lúc công bố',ruleSetName:'Quy chế lúc công bố',ruleSetRevision:3,minimumPoints:'0.00',maximumPoints:'100.00',timezone:'Asia/Ho_Chi_Minh',history:[{revision:1,publishedAt:'2026-09-30T01:00:00Z',total:'80.30',classification:'Xếp loại nguồn',current:false},{revision:2,publishedAt:at,total:'79.05',classification:'Xếp loại nguồn',current:true}]});
const response=(data:unknown)=>new Response(JSON.stringify({data,requestId:'conduct-unit'}),{headers:{'Content-Type':'application/json'}}),display=()=>nativeParentContext(context(),slug).display,adopt=(value=viewId)=>beginParentExchange().adopt(slug,value,'conduct-csrf');
beforeEach(()=>{clearParentSession();authenticationChanged();});afterEach(()=>{clearParentSession();vi.unstubAllGlobals();});
describe('Native parent published conduct and private revision history',()=>{
 it('keeps exact official decimal totals, pinned labels, local dates and real current history without recomputing a clamped score',()=>{
  const value=nativeParentConduct(conduct(),display());expect(value).toMatchObject({periodId:id,periodLabel:'Tuần nguồn 5',base:'80.10',plus:'0.20',minus:'-1.25',total:'79.05',className:'Lớp lúc công bố',ruleSetName:'Quy chế lúc công bố',ruleSetVersionNo:3,startDate:'2026-09-28',endDate:'2026-10-04',adjusted:true});expect(value.items[0]).toEqual({label:'Ghi nhận công khai',points:'-1.25',date:'2026-09-30',reason:'Lý do được chia sẻ'});const clamped={...conduct(),bonusPoints:'30.00',penaltyPoints:'0.00',finalPoints:'100.00',history:conduct().history.map(h=>h.current?{...h,total:'100.00'}:h)};expect(nativeParentConduct(clamped,display()).total).toBe('100.00');expect(JSON.stringify(value)).not.toMatch(/studentId|enrollmentId|internalNote|staffSnapshot|ruleSetId|rank|csrf|viewId/);
 });
 it('keeps absent historical metadata and nullable classifications explicit without using the current class or an invented rule version',()=>{
  const value={...conduct(),weekNumber:null,startsOn:null,endsOn:null,classLabel:null,ruleSetName:null,ruleSetRevision:null,minimumPoints:null,maximumPoints:null,classification:null,history:conduct().history.map(h=>h.current?{...h,classification:null}:h)};expect(nativeParentConduct(value,display())).toMatchObject({weekIndex:null,startDate:null,endDate:null,className:null,ruleSetName:null,ruleSetVersionNo:null,minimum:null,maximum:null,grade:null,total:'79.05'});
 });
 it('rejects wrong periods, private fields, contradictory dates, signs/bounds and missing conduct authority',()=>{
  for(const value of [{...conduct(),periodId:other},{...conduct(),rank:1},{...conduct(),basePoints:80.1},{...conduct(),bonusPoints:'-0.20'},{...conduct(),penaltyPoints:'1.25'},{...conduct(),maximumPoints:'70.00'},{...conduct(),startsOn:'2026-08-01'},{...conduct(),endsOn:null},{...conduct(),timezone:'Invalid/Timezone'},{...conduct(),lines:[{...conduct().lines[0],date:'2026-09-29'}]},{...conduct(),lines:[{...conduct().lines[0],internalNote:'private'}]}])expect(()=>nativeParentConduct(value as ApiSchemas['ParentSharedConduct'],display(),id)).toThrow();expect(()=>nativeParentConduct(conduct(),{...display(),modules:['documents']})).toThrow();
 });
 it('rejects empty, duplicate, foreign or inconsistent current history instead of synthesizing another revision',()=>{
  for(const history of [[],[...conduct().history,conduct().history[0]],conduct().history.map(h=>({...h,current:false})),conduct().history.map(h=>({...h,current:true})),conduct().history.map(h=>h.current?{...h,total:'0.00'}:h),conduct().history.map(h=>h.current?{...h,studentId:other}:h)])expect(()=>nativeParentConduct({...conduct(),history} as ApiSchemas['ParentSharedConduct'],display())).toThrow();
 });
 it('retains a complete bounded directory and rejects duplicates, hidden private root data or oversized results',()=>{
  expect(nativeParentConductDirectory({items:Array.from({length:123},(_,n)=>({...conduct(),periodId:`6f000000-0000-4000-8000-${String(n+100).padStart(12,'0')}`}))},display())).toHaveLength(123);for(const value of [{items:[conduct(),conduct()]},{items:Array.from({length:1001},conduct)},{items:[],students:[other]}])expect(()=>nativeParentConductDirectory(value as ApiSchemas['ParentSharedConductDirectory'],display())).toThrow();
 });
 it('reads list and detail purposes with the exact current parent view and no overview or staff publication fallback',async()=>{
  adopt();const fetcher=vi.fn(async(url:string)=>response(url.endsWith('/context')?context():url.includes('/'+id+'/')?conduct():{items:[conduct()]}));vi.stubGlobal('fetch',fetcher);expect(await repo.conductList({viewId},slug)).toHaveLength(1);expect((await repo.conductDetail({viewId},slug,id)).total).toBe('79.05');const calls=fetcher.mock.calls as unknown as Array<[string,RequestInit]>;expect(calls.map(([url])=>url)).toEqual([`/api/v1/parent/${slug}/context`,`/api/v1/parent/${slug}/conduct/published`,`/api/v1/parent/${slug}/context`,`/api/v1/parent/${slug}/conduct/${id}/published`]);for(const [,opts]of calls)expect((opts.headers as Record<string,string>)['X-Parent-View']).toBe(viewId);
 });
 it('keeps server failures as errors and clears only its current terminally denied session',async()=>{
  adopt();vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/context')?response(context()):new Response(JSON.stringify({code:'DATABASE_UNAVAILABLE'}),{status:503})));await expect(repo.conductList({viewId},slug)).rejects.toBeDefined();expect(readParentView(slug)).toBe(viewId);vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/context')?response(context()):new Response(JSON.stringify({code:'PARENT_ACCESS_INVALID'}),{status:401})));await expect(repo.conductDetail({viewId},slug,id)).rejects.toBeDefined();expect(readParentView(slug)).toBeNull();
 });
 it('an older conduct receipt or denial cannot expose content or clear a newly adopted child',async()=>{
  for(const status of [200,401]){adopt();let resolve:(r:Response)=>void=()=>{},started=()=>{};const ready=new Promise<void>(r=>{started=r;});vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/context')?response(context()):new Promise<Response>(r=>{resolve=r;started();})));const pending=repo.conductList({viewId},slug);await ready;adopt(other);resolve(status===200?response({items:[conduct()]}):new Response(JSON.stringify({code:'PARENT_ACCESS_INVALID'}),{status}));await expect(pending).rejects.toMatchObject({code:'CONFLICT'});expect(readParentView(slug)).toBe(other);}
 });
 it('staff preview reads the same safe serializer with independent authority and cannot adopt the public parent view',async()=>{
  adopt();const ctx:Ctx={actor:{kind:'staff',userId:other},today:'2026-10-05',now:at,staffOwner:captureStaffAccess()},key={preview:{ctx,schoolId,accessId}},fetcher=vi.fn(async(url:string)=>response(url.endsWith('/preview')?{context:context()}:url.includes('/'+id+'/')?conduct():{items:[conduct()]}));vi.stubGlobal('fetch',fetcher);expect(await repo.conductList(key,slug)).toHaveLength(1);expect((await repo.conductDetail(key,slug,id)).className).toBe('Lớp lúc công bố');expect(fetcher.mock.calls.filter(([url])=>!url.endsWith('/preview')).map(([url])=>url)).toEqual([`/api/v1/schools/${schoolId}/parent-access/${accessId}/preview/conduct/published`,`/api/v1/schools/${schoolId}/parent-access/${accessId}/preview/conduct/${id}/published`]);expect(readParentView(slug)).toBe(viewId);authorizationChanged();await expect(repo.conductList(key,slug)).rejects.toMatchObject({code:'FORBIDDEN'});expect(fetcher).toHaveBeenCalledTimes(4);
 });
});
