import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import type {ApiSchemas} from '@/lib/api/generated';
import type {Ctx} from '@/lib/repositories/core';
import {authenticationChanged,authorizationChanged,captureStaffAccess,setStaffCsrf} from '@/lib/api/client';
import {connectedClassroomRepo} from '@/lib/repositories/connected/classroom';
import {nativeDutyWorkspace} from '@/lib/repositories/connected/classroom-duties';
const schoolId='78000000-0000-4000-8000-000000000001',yearId='78000000-0000-4000-8000-000000000002',classId='78000000-0000-4000-8000-000000000003',studentId='78000000-0000-4000-8000-000000000004',otherId='78000000-0000-4000-8000-000000000005',enrollmentId='78000000-0000-4000-8000-000000000006',otherEnrollment='78000000-0000-4000-8000-000000000007',groupId='78000000-0000-4000-8000-000000000008',groupPlanId='78000000-0000-4000-8000-000000000009',scheduleId='78000000-0000-4000-8000-000000000010',publicationId='78000000-0000-4000-8000-000000000011';
const workspace=():ApiSchemas['ClassDutyWorkspace']=>({schoolId,yearId,classId,today:'2026-10-01',monday:'2026-09-28',referenceDate:'2026-10-02',startsOn:'2026-09-01',endsOn:'2027-06-01',readOnly:false,canEdit:true,canPublish:true,canPreview:true,publicationId:null,students:[{id:studentId,enrollmentId,fullName:'Học sinh trực API'},{id:otherId,enrollmentId:otherEnrollment,fullName:'Bạn khác nguồn API'}],groups:[{id:groupId,name:'Tổ trực nguồn API',studentIds:[studentId,otherId]}],previewStudents:[{id:studentId,fullName:'Học sinh trực API'},{id:otherId,fullName:'Bạn khác nguồn API'}],preview:[],tasks:[{id:groupPlanId,scheduleId,version:2,dataVersion:4,date:'2026-10-02',task:'Chọn một thành viên trực',assignmentIds:[],groupPlanId,groupId,groupName:'Tổ trực nguồn API',studentIds:[studentId],studentNames:['Học sinh trực API'],unavailableTargets:0,status:'DRAFT',canEdit:true}]});
const ctx=():Ctx=>({actor:{kind:'staff',userId:publicationId},today:'2026-10-01',now:'2026-10-01T01:00:00Z',staffOwner:captureStaffAccess()});
const response=(data:unknown)=>new Response(JSON.stringify({data,requestId:'class-duty-unit'}),{headers:{'Content-Type':'application/json'}});
beforeEach(()=>{authenticationChanged();setStaffCsrf('class-duty-unit-csrf');});afterEach(()=>vi.unstubAllGlobals());
describe('Native duty board source and concrete command receipts',()=>{
 it('keeps selected group targets displayed versions independent denied preview and actual Sunday or clipped school weeks',()=>{
  let v=workspace(),d=nativeDutyWorkspace(v,schoolId,yearId,classId);expect(d.days.flatMap(x=>x.duties)[0].studentIds).toEqual([studentId]);expect(d.groups[0].members).toHaveLength(2);expect(d.days[4].duties[0].source).toMatchObject({expectedVersion:2,expectedDataVersion:4,assignmentIds:[],groupPlanId});
  v={...v,canPublish:false,canPreview:false,preview:null,previewStudents:[]};expect(nativeDutyWorkspace(v,schoolId,yearId,classId).preview).toEqual([]);v.tasks[0].date='2026-10-04';expect(nativeDutyWorkspace(v,schoolId,yearId,classId).days).toHaveLength(7);
  v=workspace();v.monday='2026-08-31';v.referenceDate='2026-09-01';v.tasks=[];d=nativeDutyWorkspace(v,schoolId,yearId,classId);expect(d.days[0].date).toBe('2026-09-01');expect(d.canPrevious).toBe(false);
 });
 it('rejects private fields foreign or duplicate scope malformed targets contradictory capability and unrelated preview pupils',()=>{
  const v=workspace();for(const bad of [{...v,guardianPhone:'PRIVATE'},{...v,yearId:schoolId},{...v,classId:otherId},{...v,preview:null},{...v,canEdit:false},{...v,readOnly:true},{...v,monday:'2026-09-29'},{...v,students:[...v.students,v.students[0]]},{...v,tasks:[{...v.tasks[0],studentNames:[]}]},{...v,tasks:[{...v.tasks[0],date:'2026-10-08'}]},{...v,tasks:[{...v.tasks[0],userId:otherId}]},{...v,publicationId,preview:[{studentId:scheduleId,date:'2026-10-02',task:'Không thuộc nguồn',status:'ASSIGNED',publishedAt:'2026-10-01T00:00:00Z'}]}])expect(()=>nativeDutyWorkspace(bad as ApiSchemas['ClassDutyWorkspace'],schoolId,yearId,classId)).toThrow();
  const withdrawn={...v,tasks:[{...v.tasks[0],status:'WITHDRAWN' as const}]};expect(nativeDutyWorkspace(withdrawn,schoolId,yearId,classId).days[4].duties[0].status).toBe('withdrawn');
 });
 it('posts one atomic save with original displayed versions and publication pointer without a fresh source overwrite',async()=>{
  const d=nativeDutyWorkspace(workspace(),schoolId,yearId,classId),source=d.days[4].duties[0].source,fetcher=vi.fn(async()=>response({sourceId:scheduleId,status:'PUBLISHED'}));vi.stubGlobal('fetch',fetcher);
  const r=await connectedClassroomRepo.saveDuty(ctx(),schoolId,classId,{yearId,source,date:'2026-10-03',task:'Chuyển ngày trực',studentIds:[studentId],groupId,publish:true,expectedPublicationId:publicationId});expect(r.status).toBe('published');expect(fetcher).toHaveBeenCalledTimes(1);const calls=fetcher.mock.calls as unknown as Array<[string,RequestInit]>;expect(calls[0][0]).toContain(`/academic-years/${yearId}/classes/${classId}/duty-tasks`);expect(JSON.parse(String(calls[0][1].body))).toEqual({source,date:'2026-10-03',task:'Chuyển ngày trực',studentIds:[studentId],groupId,publish:true,expectedPublicationId:publicationId});
 });
 it('removes the exact displayed task and stops stale ownership before a write',async()=>{
  const source=nativeDutyWorkspace(workspace(),schoolId,yearId,classId).days[4].duties[0].source,fetcher=vi.fn(async()=>response({sourceId:null,status:'REMOVED'}));vi.stubGlobal('fetch',fetcher);expect(await connectedClassroomRepo.deleteDuty(ctx(),schoolId,classId,{yearId,source,expectedPublicationId:publicationId})).toBe(true);expect(fetcher).toHaveBeenCalledTimes(1);const calls=fetcher.mock.calls as unknown as Array<[string,RequestInit]>;expect(JSON.parse(String(calls[0][1].body))).toEqual({source,expectedPublicationId:publicationId});
  const old=ctx();authorizationChanged();await expect(connectedClassroomRepo.deleteDuty(old,schoolId,classId,{yearId,source,expectedPublicationId:publicationId})).rejects.toMatchObject({code:'FORBIDDEN'});expect(fetcher).toHaveBeenCalledTimes(1);
 });
 it('does not turn an outage denial or wrong requested date into an empty successful board',async()=>{
  const fetcher=vi.fn(async()=>response(workspace()));vi.stubGlobal('fetch',fetcher);await connectedClassroomRepo.dutyChoices(ctx(),schoolId,yearId,classId,'2026-10-02');expect((fetcher.mock.calls as unknown as Array<[string]>)[0][0]).toContain('onDate=2026-10-02');await expect(connectedClassroomRepo.dutyChoices(ctx(),schoolId,yearId,classId,'2026-10-03')).rejects.toMatchObject({code:'READ_ERROR'});
  vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({code:'RESOURCE_NOT_FOUND',requestId:'duty-denied'}),{status:404,headers:{'Content-Type':'application/json'}})));await expect(connectedClassroomRepo.duties(ctx(),schoolId,yearId,classId)).rejects.toMatchObject({code:'NOT_FOUND'});
  vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({code:'DEPENDENCY_UNAVAILABLE',requestId:'duty-outage'}),{status:503,headers:{'Content-Type':'application/json'}})));await expect(connectedClassroomRepo.duties(ctx(),schoolId,yearId,classId)).rejects.toMatchObject({code:'READ_ERROR'});
 });
 it('rejects a replaced owner receipt and a private or contradictory command result',async()=>{
  let finish:(r:Response)=>void=()=>{},started=()=>{};const waiting=new Promise<void>(r=>{started=r;});vi.stubGlobal('fetch',vi.fn(async()=>new Promise<Response>(r=>{finish=r;started();})));const input={yearId,date:'2026-10-02',task:'Việc thật theo API',studentIds:[studentId],publish:false,expectedPublicationId:null};const pending=connectedClassroomRepo.saveDuty(ctx(),schoolId,classId,input);await waiting;authorizationChanged();finish(response({sourceId:scheduleId,status:'DRAFT'}));await expect(pending).rejects.toMatchObject({code:'FORBIDDEN'});
  for(const bad of [{sourceId:scheduleId,status:'PUBLISHED'},{sourceId:scheduleId,status:'DRAFT',userId:studentId}]){vi.stubGlobal('fetch',vi.fn(async()=>response(bad)));await expect(connectedClassroomRepo.saveDuty(ctx(),schoolId,classId,input)).rejects.toMatchObject({code:'READ_ERROR'});}
 });
});
