import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {connectedParentRepo as repo} from '@/lib/repositories/connected/parent';
import {nativeParentActivity,nativeParentAnnouncement,nativeParentActivities,nativeParentAnnouncements} from '@/lib/repositories/connected/parent-shared';
import {safeParentHtml} from '@/lib/repositories/connected/safe-parent-html';
import {nativeParentContext} from '@/lib/repositories/connected/parent-context';
import {beginParentExchange,clearParentSession,readParentView} from '@/lib/api/parent-session';
import {authenticationChanged,authorizationChanged,captureStaffAccess} from '@/lib/api/client';
import type {ApiSchemas} from '@/lib/api/generated';
import type {Ctx} from '@/lib/repositories/core';
const slug='parent-shared-unit',viewId='6d000000-0000-4000-8000-000000000001',id='6d000000-0000-4000-8000-000000000002',other='6d000000-0000-4000-8000-000000000003',schoolId='6d000000-0000-4000-8000-000000000004',accessId='6d000000-0000-4000-8000-000000000005';
const context=():ApiSchemas['ParentContext']=>({viewId,school:{name:'Trường API',slug,publicContactPhone:null,shortName:null,motto:null,publicContactEmail:null,publicAddress:null},student:{displayName:'Con API',classLabel:'6A',schoolYearLabel:'2026–2027'},allowedSections:['activities','announcements','documents'],allowDownload:false,csrfToken:'shared-csrf',expiresAt:'2026-10-05T08:00:00Z',today:'2026-10-05',year:{label:'2026–2027',startsOn:'2026-09-01',endsOn:'2027-06-01'},relationshipLabel:'Mẹ',linkExpiresAt:'2026-11-01T00:00:00Z',lastPublishedAt:null});
const document=():ApiSchemas['ParentDocumentEntry']=>({id:other,title:'Minh chứng đã chia sẻ',contentType:'image/png',byteSize:10,publishedAt:'2026-10-01T01:00:00Z',viewAllowed:true,downloadAllowed:false});
const activity=():ApiSchemas['ParentSharedActivity']=>({id,title:'Hoạt động công bố',description:'Nội dung riêng',dueAt:'2026-10-03T17:30:00Z',studentStatus:'EXCUSED',publicReviewNote:'Được miễn đã xác minh',documents:[document()],publishedAt:'2026-10-01T01:00:00Z',activityStatus:'ASSIGNED',illustration:'stem',updatedAt:'2026-10-01T00:00:00Z',timezone:'Asia/Ho_Chi_Minh',dueOn:'2026-10-04'});
const html='<h2>Đã công bố</h2><p><strong>Nội dung</strong> &amp; gia đình</p><ul><li>Mục thứ nhất</li></ul>';
const announcement=():ApiSchemas['ParentSharedAnnouncement']=>({id,title:'Thông báo công bố',summary:null,sanitizedHtml:html,publishedAt:'2026-10-01T01:00:00Z',senderLabel:'Lớp nguồn',documents:[document()],scopeKinds:['CLASS','STUDENT']});
const response=(data:unknown)=>new Response(JSON.stringify({data,requestId:'shared-unit'}),{headers:{'Content-Type':'application/json'}}),display=()=>nativeParentContext(context(),slug).display,adopt=(value=viewId)=>beginParentExchange().adopt(slug,value,'shared-csrf');
beforeEach(()=>{clearParentSession();authenticationChanged();});afterEach(()=>{clearParentSession();vi.unstubAllGlobals();});
describe('Native parent pinned activities and announcements',()=>{
 it('keeps actual own status, school-local due date and nullable pinned metadata without inventing private source facts',()=>{
  const item=nativeParentActivity(activity(),display());expect(item).toMatchObject({id,dueDate:'2026-10-04',submission:'EXCUSED',status:'active',illustration:'stem',note:'Được miễn đã xác minh'});expect(item.evidence[0]).toMatchObject({viewAllowed:true,downloadAllowed:false});const nullable=nativeParentActivity({...activity(),description:null,publicReviewNote:null,activityStatus:null,illustration:null,updatedAt:null},display());expect(nullable).toMatchObject({description:null,note:null,status:null,illustration:null,updatedAt:null});expect(JSON.stringify(item)).not.toMatch(/studentId|classId|participantId|createdBy|source|viewId|csrf/);
 });
 it('rejects another activity, mismatched school dates, unknown status, private fields or borrowed document authority',()=>{
  for(const value of [{...activity(),id:other},{...activity(),studentStatus:'PUBLISHED'},{...activity(),activityStatus:'DRAFT'},{...activity(),dueOn:'2026-10-03'},{...activity(),timezone:'Unknown/Zone'},{...activity(),participantId:other},{...activity(),documents:[{...document(),downloadAllowed:true}]}])expect(()=>nativeParentActivity(value as ApiSchemas['ParentSharedActivity'],display(),id)).toThrow();expect(()=>nativeParentActivity(activity(),{...display(),modules:['activities']})).toThrow();expect(()=>nativeParentActivity({...activity(),documents:[]},{...display(),modules:['activities']})).not.toThrow();
 });
 it('preserves safe rich formatting and actual scope kinds without claiming exclusive family recipients',()=>{
  const item=nativeParentAnnouncement(announcement(),display());expect(item.bodyHtml).toBe(html);expect(item.scopeLabels).toEqual(['Theo lớp','Học sinh được chọn']);expect(item.summary).toBeNull();expect(item.from).toBe('Lớp nguồn');expect(JSON.stringify(item)).not.toMatch(/recipients|studentId|rootId|internalNote|staffSnapshot|objectKey/);
 });
 it('rejects active markup, URLs, attributes, unknown tags and malformed markup before HTML rendering',()=>{
  for(const unsafe of ['<p onclick="alert(1)">X</p>','<script>alert(1)</script>','<img src=x onerror=alert(1)>','<a href="javascript:alert(1)">X</a>','<svg><style>X</style></svg>','<!--x--><p>X</p>','<p>X</p><','<textarea>&lt;script&gt;X</textarea>','<p style="color:red">X</p>'])expect(()=>safeParentHtml(unsafe)).toThrow();expect(safeParentHtml('<p>&lt;img src=x onerror=alert(1)&gt;</p>')).toBe('<p>&lt;img src=x onerror=alert(1)&gt;</p>');expect(()=>safeParentHtml('x'.repeat(4001))).toThrow();expect(()=>nativeParentAnnouncement({...announcement(),sanitizedHtml:'<iframe src="https://track.invalid"></iframe>'},display())).toThrow();
 });
 it('rejects private announcement fields, unknown/duplicate audience kinds and duplicate or oversized directories',()=>{
  for(const value of [{...announcement(),targets:[other]},{...announcement(),scopeKinds:['STAFF']},{...announcement(),scopeKinds:['STUDENT','STUDENT']},{...announcement(),id:other}])expect(()=>nativeParentAnnouncement(value as ApiSchemas['ParentSharedAnnouncement'],display(),id)).toThrow();expect(()=>nativeParentActivities({items:[activity(),activity()]},display())).toThrow();expect(()=>nativeParentAnnouncements({items:[announcement(),announcement()]},display())).toThrow();expect(()=>nativeParentActivities({items:Array.from({length:1001},activity)},display())).toThrow();expect(()=>nativeParentAnnouncements({items:[],students:[other]} as never,display())).toThrow();expect(()=>nativeParentAnnouncements({items:[]},{...display(),modules:['activities']})).toThrow();expect(nativeParentActivities({items:Array.from({length:123},(_,n)=>({...activity(),id:`6d000000-0000-4000-8000-${String(n+100).padStart(12,'0')}`}))},display())).toHaveLength(123);
 });
 it('reads complete purpose-built directories and details with the exact parent view rather than the overview subset',async()=>{
  adopt();const fetcher=vi.fn(async(url:string)=>response(url.endsWith('/context')?context():url.includes('/activities/')?url.includes('/'+id+'/')?activity():{items:[activity()]}:url.includes('/'+id+'/')?announcement():{items:[announcement()]}));vi.stubGlobal('fetch',fetcher);
  expect(await repo.activities({viewId},slug)).toHaveLength(1);expect((await repo.activity({viewId},slug,id)).submission).toBe('EXCUSED');expect(await repo.announcements({viewId},slug)).toHaveLength(1);expect((await repo.announcement({viewId},slug,id)).bodyHtml).toBe(html);const calls=fetcher.mock.calls as unknown as Array<[string,RequestInit]>;expect(calls.filter(([url])=>!url.endsWith('/context')).map(([url])=>url)).toEqual([`/api/v1/parent/${slug}/activities/published`,`/api/v1/parent/${slug}/activities/${id}/published`,`/api/v1/parent/${slug}/announcements/published`,`/api/v1/parent/${slug}/announcements/${id}/published`]);for(const [,opts]of calls)expect((opts.headers as Record<string,string>)['X-Parent-View']).toBe(viewId);
 });
 it('API errors stay errors; current terminal denial clears its view and never returns a mock or empty success',async()=>{
  adopt();vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/context')?response(context()):new Response(JSON.stringify({code:'DATABASE_UNAVAILABLE',requestId:'shared-down'}),{status:503})));await expect(repo.activities({viewId},slug)).rejects.toBeDefined();expect(readParentView(slug)).toBe(viewId);vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/context')?response(context()):new Response(JSON.stringify({code:'PARENT_ACCESS_INVALID',requestId:'shared-revoked'}),{status:401})));await expect(repo.announcements({viewId},slug)).rejects.toBeDefined();expect(readParentView(slug)).toBeNull();
 });
 it('an older response or error cannot return content or clear a newly adopted child',async()=>{
  for(const status of [200,401]){adopt();let resolve:(r:Response)=>void=()=>{},started=()=>{};const ready=new Promise<void>(r=>{started=r;});vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/context')?response(context()):new Promise<Response>(r=>{resolve=r;started();})));const pending=repo.announcements({viewId},slug);await ready;adopt(other);resolve(status===200?response({items:[announcement()]}):new Response(JSON.stringify({code:'PARENT_ACCESS_INVALID'}),{status}));await expect(pending).rejects.toMatchObject({code:'CONFLICT'});expect(readParentView(slug)).toBe(other);}
 });
 it('all staff previews keep their independent paths and epoch, without adopting a parent cookie or view',async()=>{
  adopt();const ctx:Ctx={actor:{kind:'staff',userId:other},today:'2026-10-05',now:'2026-10-05T01:00:00Z',staffOwner:captureStaffAccess()},key={preview:{ctx,schoolId,accessId}},fetcher=vi.fn(async(url:string)=>response(url.endsWith('/preview')?{context:context()}:url.includes('/activities/')?url.includes('/'+id+'/')?activity():{items:[activity()]}:url.includes('/'+id+'/')?announcement():{items:[announcement()]}));vi.stubGlobal('fetch',fetcher);await repo.activities(key,slug);await repo.activity(key,slug,id);await repo.announcements(key,slug);await repo.announcement(key,slug,id);expect(fetcher.mock.calls.filter(([url])=>!url.endsWith('/preview')).map(([url])=>url)).toEqual(['activities/published',`activities/${id}/published`,'announcements/published',`announcements/${id}/published`].map(tail=>`/api/v1/schools/${schoolId}/parent-access/${accessId}/preview/${tail}`));expect(readParentView(slug)).toBe(viewId);authorizationChanged();await expect(repo.activities(key,slug)).rejects.toMatchObject({code:'FORBIDDEN'});expect(fetcher).toHaveBeenCalledTimes(8);
 });
});
