import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {connectedClassroomRepo} from '@/lib/repositories/connected/classroom';
import {nativeClassOverview} from '@/lib/repositories/connected/classroom-overview';
import {authenticationChanged,authorizationChanged,captureStaffAccess} from '@/lib/api/client';
import type {ApiSchemas} from '@/lib/api/generated';
import type {Ctx} from '@/lib/repositories/core';
const schoolId='73000000-0000-4000-8000-000000000001',yearId='73000000-0000-4000-8000-000000000002',classId='73000000-0000-4000-8000-000000000003',id='73000000-0000-4000-8000-000000000004';
const overview=():ApiSchemas['ClassWorkspaceOverview']=>({schoolId,yearId,classId,today:'2026-10-01',referenceDate:'2026-10-01',asOf:'2026-10-01T01:00:00Z',isCurrent:true,readOnly:false,permissions:{attendance:false,schedule:false,groups:false,activities:false},canRecordMorning:false,allowedTaskKinds:[],tasks:null,attendance:null,lessons:null,groups:null,activities:null,navigation:[]});
const full=():ApiSchemas['ClassWorkspaceOverview']=>({...overview(),permissions:{attendance:true,schedule:true,groups:true,activities:true},canRecordMorning:true,allowedTaskKinds:['attendance','groups'],tasks:[{kind:'attendance',count:2},{kind:'groups',count:1}],attendance:{calendarState:'WITHIN_YEAR',session:null,counts:{total:2,present:0,late:0,excused:0,unexcused:0,unmarked:2}},lessons:[{id,version:1,periodNumber:null,startsAtLocal:'08:00',endsAtLocal:'08:30',subjectName:'Môn thật',teacherName:null,roomName:null,status:'CANCELLED',changeReason:'Nghỉ theo lịch thực tế'}],groups:{items:[{id,name:'Tổ thật',size:1}],totalStudents:2,noGroup:1},activities:{items:[{id,version:1,title:'Hoạt động thật',dueAt:'2026-10-03T17:30:00Z',dueDate:'2026-10-04',total:2,done:1}],total:1,hasMore:false},navigation:['reports','attendance/weekly','conduct','timetable','groups','activities']});
const ctx=():Ctx=>({actor:{kind:'staff',userId:id},today:'2026-10-01',now:'2026-10-01T01:00:00Z',staffOwner:captureStaffAccess()});
const response=(data:unknown)=>new Response(JSON.stringify({data,requestId:'native-overview-unit'}),{headers:{'Content-Type':'application/json'}});
beforeEach(()=>authenticationChanged());afterEach(()=>vi.unstubAllGlobals());
describe('Native bounded class overview and independently authorized nullable sources',()=>{
 it('retains denied null panels and accepts truthful source versions nullable schedule metadata and actual local due date',()=>{expect(nativeClassOverview(overview(),schoolId,yearId,classId).tasks).toBeNull();const d=nativeClassOverview(full(),schoolId,yearId,classId);expect(d.attendance?.counts?.unmarked).toBe(2);expect(d.lessons?.[0].periodNumber).toBeNull();expect(d.activities?.items[0].dueDate).toBe('2026-10-04');});
 it('requests only the exact school year class purpose with a current staff receipt',async()=>{const fetch=vi.fn(async(input:RequestInfo|URL)=>response(String(input).includes('/workspace-overview')?overview():null));vi.stubGlobal('fetch',fetch);expect((await connectedClassroomRepo.overview(ctx(),schoolId,yearId,classId)).classId).toBe(classId);expect(String(fetch.mock.calls[0]?.[0])).toContain(`/schools/${schoolId}/academic-years/${yearId}/classes/${classId}/workspace-overview`);expect(fetch).toHaveBeenCalledTimes(1);});
 it('rejects foreign private and inconsistent permission counts source tasks and navigation rather than filtering or defaulting',()=>{
  const d=full();for(const bad of [{...d,schoolId:id},{...d,yearId:id},{...d,classId:id},{...d,students:[]},{...d,permissions:{...d.permissions,attendance:false}},{...d,attendance:{...d.attendance!,counts:{...d.attendance!.counts!,present:1}}},{...d,tasks:[{kind:'attendance',count:1}]},{...d,groups:{...d.groups!,noGroup:0}},{...d,navigation:['/parent/secret']},{...d,lessons:[{...d.lessons![0],memberId:id}]}])expect(()=>nativeClassOverview(bad as never,schoolId,yearId,classId)).toThrow();
 });
 it('rejects missing-session fabricated presence duplicate or oversized sources and incomplete activity previews',()=>{
  const d=full();for(const bad of [{...d,attendance:{...d.attendance!,counts:{total:2,present:2,late:0,excused:0,unexcused:0,unmarked:0}}},{...d,lessons:Array.from({length:101},()=>d.lessons![0])},{...d,groups:{...d.groups!,items:[d.groups!.items[0],d.groups!.items[0]]}},{...d,activities:{...d.activities!,total:8,hasMore:true}},{...d,activities:{...d.activities!,hasMore:true}},{...d,allowedTaskKinds:['attendance','attendance']},{...d,tasks:[{kind:'lesson-attendance',count:1}]}])expect(()=>nativeClassOverview(bad as never,schoolId,yearId,classId)).toThrow();
 });
 it('accepts actual holiday absence and archived sources while rejecting current tasks in an archived year',()=>{
  const d=overview();const holiday={...d,permissions:{...d.permissions,attendance:true},attendance:{calendarState:'HOLIDAY' as const,session:null,counts:null}};expect(nativeClassOverview(holiday,schoolId,yearId,classId).attendance?.counts).toBeNull();expect(()=>nativeClassOverview({...holiday,canRecordMorning:true},schoolId,yearId,classId)).toThrow();expect(nativeClassOverview({...d,isCurrent:false,readOnly:true},schoolId,yearId,classId).lessons).toBeNull();expect(()=>nativeClassOverview({...d,isCurrent:false,readOnly:true,allowedTaskKinds:['groups'],tasks:[]},schoolId,yearId,classId)).toThrow();
 });
 it('rejects delayed receipts after authority changes and propagates outages without borrowing cached mock facts',async()=>{
  let finish!:(value:Response)=>void;vi.stubGlobal('fetch',vi.fn(()=>new Promise<Response>(resolve=>{finish=resolve;})));const pending=connectedClassroomRepo.overview(ctx(),schoolId,yearId,classId);await vi.waitFor(()=>expect(finish).toBeTypeOf('function'));authorizationChanged();finish(response(overview()));await expect(pending).rejects.toMatchObject({code:'FORBIDDEN'});
  vi.stubGlobal('fetch',vi.fn(async()=>{throw new Error('offline');}));await expect(connectedClassroomRepo.overview(ctx(),schoolId,yearId,classId)).rejects.toMatchObject({code:'READ_ERROR'});
 });
});
