import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {nativeScheduleWorkspace,scheduleClashes,connectedScheduleClassroomRepo as repo} from '@/lib/repositories/connected/schedule';
import {authenticationChanged,captureStaffAccess,setStaffCsrf} from '@/lib/api/client';
import type {ApiSchemas} from '@/lib/api/generated';
import type {Ctx} from '@/lib/repositories/core';
const id=(n:number)=>`66000000-0000-4000-8000-${String(n).padStart(12,'0')}`,school=id(1),cls=id(2),year=id(3),week='2026-10-05';
const source={lessonId:id(4),lessonVersion:1,draftId:null,draftVersion:null};
const lesson=():ApiSchemas['ScheduleWorkspaceLesson']=>({id:id(4),version:1,classId:cls,yearId:year,className:'Lớp lịch thật',date:week,period:9,start:'09:05',end:'09:50',startsAt:week+'T02:05:00Z',endsAt:week+'T02:50:00Z',subjectId:id(5),subject:'Môn thật',color:'#64748b',teacherMembershipId:id(6),teacher:'Giáo viên công tác',teacherStatus:'active',roomId:id(7),room:'Phòng thật',cancelled:false,changed:null,source,canEdit:true});
const workspace=():ApiSchemas['ScheduleWorkspace']=>({schoolId:school,classId:cls,yearId:year,today:'2026-10-02',timezone:'Asia/Ho_Chi_Minh',weekStart:week,canManage:true,canEdit:true,canPublish:true,publicationId:null,lessons:[lesson()],changes:[],holidays:[],options:{classes:[{id:cls,name:'Lớp lịch thật',yearId:year,startsOn:'2026-09-01',endsOn:'2027-06-01',canEdit:true,canPublish:true}],subjects:[{id:id(5),name:'Môn thật',color:'#64748b'}],teachers:[{id:id(6),name:'Giáo viên công tác'}],rooms:[{id:id(7),name:'Phòng thật',capacity:10}]}});
const ctx=():Ctx=>({actor:{kind:'staff',userId:id(10)},today:'2026-10-02',now:'2026-10-02T01:00:00Z',staffOwner:captureStaffAccess()});
beforeEach(()=>{authenticationChanged();setStaffCsrf('test-schedule-csrf');});afterEach(()=>vi.unstubAllGlobals());
describe('Connected native school/class timetable',()=>{
 it('loads the draft picker through bounded native pagination with supported descending sort parameters',async()=>{
  const fetcher=vi.fn(async(url:string)=>new Response(JSON.stringify(url.includes('/timetables?')?{data:[],page:{limit:100,nextCursor:null,hasMore:false,total:0},requestId:'drafts-unit'}:{data:workspace(),requestId:'workspace-unit'}),{status:200}));vi.stubGlobal('fetch',fetcher);
  const d=await repo.timetableDrafts(ctx(),school,cls,week);expect(d.schedules).toEqual([]);expect(d.canPublish).toBe(true);
  expect(fetcher.mock.calls.map(([url])=>url)).toContain(`/api/v1/schools/${school}/classes/${cls}/timetables?sort=createdAt&dir=desc&limit=100`);
 });
 it('retains the actual period, clock time, school and authoritative displayed lesson version',async()=>{const fetcher=vi.fn(async(_url:string)=>new Response(JSON.stringify({data:workspace(),requestId:'schedule-unit'}),{status:200}));vi.stubGlobal('fetch',fetcher);const d=await repo.timetable(ctx(),school,year,cls,week);expect(d.days).toHaveLength(7);expect(d.days[0].lessons[0]).toMatchObject({period:9,start:'09:05',end:'09:50',source});expect(fetcher.mock.calls[0][0]).toBe(`/api/v1/schools/${school}/schedule-workspace?yearId=${year}&classId=${cls}&weekStart=${week}`);});
 it('rejects foreign schools, classes, years, slot dates and stale or incomplete native sources',()=>{const d=workspace();for(const bad of [{...d,schoolId:id(99)},{...d,classId:id(99)},{...d,yearId:id(99)},{...d,weekStart:'2026-10-06'},{...d,lessons:[{...lesson(),date:'2026-10-12'}]},{...d,lessons:[{...lesson(),classId:id(99)}]},{...d,lessons:[{...lesson(),source:{...source,lessonVersion:2}}]},{...d,lessons:[lesson(),lesson()]}])expect(()=>nativeScheduleWorkspace(bad as ApiSchemas['ScheduleWorkspace'],school,cls,year,week)).toThrow();});
 it('computes overlapping teacher and room conflicts from actual clock times and excludes cancelled sources',()=>{const a=lesson(),b={...a,id:id(11),classId:id(12),className:'Lớp khác',period:2,start:'09:20',end:'09:40',startsAt:week+'T02:20:00Z',endsAt:week+'T02:40:00Z'};expect(scheduleClashes([a,b])).toHaveLength(2);expect(scheduleClashes([a,{...b,cancelled:true}])).toEqual([]);expect(scheduleClashes([a,{...b,startsAt:a.endsAt,endsAt:week+'T03:20:00Z'}])).toEqual([]);});
 it('requires the displayed source before mutations and never replaces a missing source with a new server read',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(repo.saveLessonChange(ctx(),school,{classId:cls,date:week,period:9,kind:'cancel',reason:'Lý do đổi lịch thật',publish:false})).rejects.toMatchObject({code:'CONFLICT'});await expect(repo.publishLessonChange(ctx(),school,id(20))).rejects.toMatchObject({code:'CONFLICT'});expect(fetcher).not.toHaveBeenCalled();});
 it('sends stale-safe source and publication guards and propagates server errors without mock success',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({code:'STALE_SOURCE',status:409,requestId:'schedule-stale'}),{status:409}));vi.stubGlobal('fetch',fetcher);await expect(repo.saveLessonChange(ctx(),school,{classId:cls,date:week,period:9,kind:'cancel',reason:'Lý do đổi lịch thật',publish:true,source,expectedPublicationId:id(21)})).rejects.toMatchObject({code:'CONFLICT'});const options=(fetcher.mock.calls as unknown as [string,RequestInit][])[0][1],body=JSON.parse(options.body as string);expect(body.source).toEqual(source);expect(body.expectedPublicationId).toBe(id(21));expect(fetcher).toHaveBeenCalledTimes(1);});
});
