import {describe,it,expect} from 'vitest';
import {parsePaste,mappedRows,previewPaste} from '../../src/features/students/paste-parser';
describe('student clipboard input',()=>{
 it('keeps full Vietnamese names, trims blank rows and never generates codes',()=>{const t=parsePaste(' Nguyễn Văn An \n\nTrần Thị Bình\r\nLê Minh Cường');expect(mappedRows(t)).toEqual([{fullName:'Nguyễn Văn An'},{fullName:'Trần Thị Bình'},{fullName:'Lê Minh Cường'}]);expect(t.needsMapping).toBe(false);});
 it('detects Excel and Google Sheets aliases with accents and normalizes dates/gender',()=>{const t=parsePaste('Mã HS\tHỌ VÀ TÊN\tNgày sinh\tGiới tính\n11A5001\tNguyễn Văn An\t01/02/2010\tNam\n11A5002\tTrần Thị Bình\t03/04/2010\tNữ');expect(t.needsMapping).toBe(false);const p=previewPaste(mappedRows(t),'2026-10-06');expect(p.map(r=>r.errors)).toEqual([[],[]]);expect(p[1]!.values.dateOfBirth).toBe('2010-04-03');expect(p[1]!.values.gender).toBe('Nữ');});
 it('requires explicit mapping for uncertain multi-column data',()=>{const t=parsePaste('11A5001\tNguyễn Văn An\n11A5002\tTrần Thị Bình');expect(t.needsMapping).toBe(true);expect(t.rows).toHaveLength(2);});
 it('CSV fallback only accepts clear column structure, preserving commas in names',()=>{expect(mappedRows(parsePaste('Nguyễn Văn An, Jr.\nTrần Thị Bình, Sr.'))[0]!.fullName).toBe('Nguyễn Văn An, Jr.');const t=parsePaste('Code,Full name,DOB\nA1,"Nguyễn Văn An, Jr.",2010-02-01');expect(mappedRows(t)[0]!.fullName).toBe('Nguyễn Văn An, Jr.');});
 it('rejects size/count limits and malformed columns',()=>{expect(()=>parsePaste('An\n'.repeat(501))).toThrow('500');expect(()=>parsePaste('á'.repeat(110000))).toThrow('200 KB');expect(()=>parsePaste('An\tA\nBình')).toThrow('Số cột');});
 it('warns on names without merging, marks duplicate codes and invalid dates/gender',()=>{const p=previewPaste([{fullName:'Nguyễn Văn An',studentCode:'A1'},{fullName:'Nguyen Van An',studentCode:'A1'},{fullName:'',dateOfBirth:'31/02/2010',gender:'??'}],'2026-10-06');expect(p).toHaveLength(3);expect(p[0]!.warnings).toHaveLength(1);expect(p[0]!.errors).toContain('MÃ TRÙNG / SAI');expect(p[2]!.errors).toEqual(['THIẾU TÊN','NGÀY SINH SAI','GIỚI TÍNH SAI']);});
});
