import {describe,it,expect} from 'vitest';
import {parseTimetableSheet,resolveTimetableRows} from '@/lib/domain/timetable-import';
import {decodeTimetableWorkbook} from '@/lib/domain/timetable-workbook';
import * as XLSX from 'xlsx';
describe('spreadsheet timetable import',()=>{
 it('detects merged weekdays, class headers, date and morning/afternoon blocks',()=>{const p=parseTimetableSheet({name:'Sheet 1',rows:[['THỜI KHÓA BIỂU SỐ 6'],['BUỔI SÁNG'],['Thực hiện từ ngày 05 tháng 10 năm 2026'],['THỨ','TIẾT','11A5 (Ánh)','11A6\n(Bắc)'],['2','1','TO – Giang','TI-Bắc'],['','2','VA—May',''],['BUỔI CHIỀU'],['THỨ','TIẾT','11A5 (Ánh)'],['3','1','HO - LongH']]});expect(p.mode).toBe('MATRIX');expect(p.effectiveDate).toBe('2026-10-05');expect(p.rows).toHaveLength(4);expect(p.rows[2]).toMatchObject({weekday:1,period:2,subjectAlias:'VA',teacherAlias:'May',classLabel:'11A5'});expect(p.rows[3]?.session).toBe('afternoon');});
 it('handles normalized Vietnamese columns and manual fallback',()=>{const p=parseTimetableSheet({name:'CSV',rows:[['Lớp','Thứ','Tiết','Môn','Giáo viên','Phòng'],['10A1','2','1','Toán','Cô Ánh','A1']]});expect(p.mode).toBe('NORMALIZED');expect(p.rows[0]).toMatchObject({classLabel:'10A1',weekday:1,roomAlias:'A1'});const manual=parseTimetableSheet({name:'S',rows:[['a','b','c','d','e'],['10A1','3','2','VA','Bắc']]},{headerRow:0,classColumn:0,dayColumn:1,periodColumn:2,subjectColumn:3,teacherColumn:4,roomColumn:5});expect(manual.rows[0]?.weekday).toBe(2);});
 it('requires explicit mappings/time and catches duplicate periods before commands',()=>{const p=parseTimetableSheet({name:'S',rows:[['THỨ','TIẾT','11A5'],['2','1','TO - Giang'],['','1','TO - Giang']]});const options={classes:[{id:'c',name:'11A5'}],subjects:[{id:'s',name:'Toán'}],teachers:[{id:'t',name:'Nguyễn Giang'}],rooms:[]};const config={version:0,aliases:{subjects:{to:'s'},teachers:{giang:'t'}},periodTimes:{}};expect(resolveTimetableRows(p.rows,options,config)[0]?.status).toBe('PERIOD_TIME_MISSING');config.periodTimes={'unspecified:1':{start:'07:00',end:'07:45'}};expect(resolveTimetableRows(p.rows,options,config).map(r=>r.status)).toEqual(['MATCHED','CONFLICT']);});
 it('does not approximate class/teacher aliases or create unknown resources',()=>{const p=parseTimetableSheet({name:'S',rows:[['THỨ','TIẾT','11A5'],['2','1','TO - Giang']]});const rows=resolveTimetableRows(p.rows,{classes:[{id:'c',name:'11A6'}],subjects:[],teachers:[],rooms:[]},{version:0,aliases:{subjects:{},teachers:{}},periodTimes:{}});expect(rows[0]?.status).toBe('CLASS_NEEDS_MAPPING');});
 it('requires mapping or explicit ignore for special periods',()=>{const p=parseTimetableSheet({name:'S',rows:[['THỨ','TIẾT','11A5'],['2','1','SHDC'],['','2','Sinh hoạt']]});const options={classes:[{id:'c',name:'11A5'}],subjects:[],teachers:[],rooms:[]},config={version:0,aliases:{subjects:{},teachers:{}},periodTimes:{}};expect(resolveTimetableRows(p.rows,options,config).map(r=>r.status)).toEqual(['SPECIAL_NEEDS_MAPPING','SPECIAL_NEEDS_MAPPING']);expect(resolveTimetableRows(p.rows.map(r=>({...r,ignored:true})),options,config).every(r=>r.status==='IGNORED')).toBe(true);});
 it('accepts ISO weekdays and English day names without carrying an invalid day',()=>{const p=parseTimetableSheet({name:'English',rows:[['Class','Weekday','Period','Subject','Teacher'],['10A1','1','1','Toán','Ánh'],['10A1','Wednesday','2','Văn','Bắc'],['10A1','bad day','3','Văn','Bắc']]});expect(p.rows.map(r=>r.weekday)).toEqual([1,3]);});
 for(const bookType of ['xlsx','xls','xlsm','csv','ods'] as const)it(`reads ${bookType} and keeps Vietnamese values`,()=>{
  const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['THỨ','TIẾT','11A5 (Ánh)'],['2','1','TO - Cô Ánh']]),'TKB');
  const buffer=XLSX.write(book,{bookType,type:'array'}) as ArrayBuffer,p=parseTimetableSheet(decodeTimetableWorkbook(buffer)[0]!);expect(p.rows[0]).toMatchObject({classLabel:'11A5',subjectAlias:'TO',teacherAlias:'Cô Ánh',weekday:1});
 });
 it('rejects oversized input before workbook decoding',()=>expect(()=>decodeTimetableWorkbook(new ArrayBuffer(5*1024*1024+1))).toThrow('5 MB'));
});
